/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.gestiones.documentacion;

import com.licensis.notaire.dto.DtoTramite;
import com.licensis.notaire.gui.Principal;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanca
 */
public class NomenclaturaCatastral extends javax.swing.JInternalFrame
{

    private static JMenuItem ventanaNomenclaturas = new JMenuItem("Ventana Nomenclaturas Catastrales");
    private static NomenclaturaCatastral instancia = null;

    /**
     * Creates new form NomenclaturaCatastral
     */
    public NomenclaturaCatastral()
    {
        initComponents();
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
    }

    public static NomenclaturaCatastral getInstancia()
    {
        if (instancia == null)
        {
            instancia = new NomenclaturaCatastral();
        }

        return instancia;
    }

    public static JMenuItem getVentanaNomenclaturas()
    {
        return ventanaNomenclaturas;
    }

    public static void setVentanaNomenclaturas(JMenuItem ventanaNomenclaturas)
    {
        NomenclaturaCatastral.ventanaNomenclaturas = ventanaNomenclaturas;
    }

    public void limpiarJtable()
    {
        int i = ((DefaultTableModel) grillasNomenclaturas.getModel()).getRowCount() - 1;

        while (((DefaultTableModel) grillasNomenclaturas.getModel()).getRowCount() > 0)
        {
            ((DefaultTableModel) grillasNomenclaturas.getModel()).removeRow(i);

        }

    }

    public void cargarGrilla(List<DtoTramite> dtoListaTramites)
    {

        DtoTramite dtoTramite = null;
        this.limpiarJtable();
        int cont = 0;

        if (!dtoListaTramites.isEmpty())
        {

            for (int i = 0; i < dtoListaTramites.size(); i++)
            {
                dtoTramite = dtoListaTramites.get(i);
                if (dtoTramite.getInmueble() != null)
                {
                    cont++;

                    Object[] datos =
                    {
                        dtoTramite.getTipoDeTramite().getNombre(),
                        dtoTramite.getInmueble().getTipoInmueble(),
                        dtoTramite.getInmueble().getDomicilio(),
                        dtoTramite.getInmueble().getNomenclaturaCatastral(),
                        dtoTramite.getInmueble().getValuacionFiscal(),
                        dtoTramite.getInmueble().getObservaciones(),
                    };

                    ((DefaultTableModel) grillasNomenclaturas.getModel()).addRow(datos);
                }
            }
        }
        if (cont > 0)
        {
            IngresarDocumento.getInstancia().botonNomenclaturas.setEnabled(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        grillasNomenclaturas = new javax.swing.JTable();
        botonCerrar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Nomenclaturas Catastrales");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Nomenclaturas");

        grillasNomenclaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Tramite", "Tipo Inmueble", "Domicilio", "Nomenclatura", "Valuacion Fiscal", "Observaciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(grillasNomenclaturas);

        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar.png"))); // NOI18N
        botonCerrar.setText("Cerrar");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        Principal.removeVentanaActivas(ventanaNomenclaturas);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrar;
    private javax.swing.JTable grillasNomenclaturas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
