/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.gestiones.gestion;

import com.licensis.notaire.dto.DtoEstadoDeGestion;
import com.licensis.notaire.dto.DtoGestionDeEscritura;
import com.licensis.notaire.dto.DtoPersona;
import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.gui.gestiones.escrituras.PrepararEscritura;
import com.licensis.notaire.negocio.ControllerNegocio;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JMenuItem;

/**
 *
 * @author matias
 */
public class ListaGestionesCliente extends javax.swing.JInternalFrame
{

    private static JMenuItem ventanaListaGestionesCliente = new JMenuItem("Ventana Lista Gestiones Cliente");
    private String formularioInvocador = new String();
    private DtoPersona cliente;
    private List<DtoGestionDeEscritura> gestionesCliente = new ArrayList<>();

    /**
     * Creates new form ListaGestionesCliente
     */
    public ListaGestionesCliente()
    {
        initComponents();
        this.setSize(1100, 600);
    }

    private void salir()
    {
        this.dispose();
    }

    public static JMenuItem getVentanaListaGestionesCliente()
    {
        return ventanaListaGestionesCliente;
    }

    public String getFormularioInvocador()
    {
        return formularioInvocador;
    }

    public void setFormularioInvocador(String formularioInvocador)
    {
        this.formularioInvocador = formularioInvocador;
    }

    public DtoPersona getCliente()
    {
        return cliente;
    }

//    public void setCliente(DtoPersona cliente) {
//        this.cliente = cliente;
//
//        List<DtoGestionDeEscritura> listaGestionesCliente = ControllerNegocio.getInstancia().obtenerListaGestionesCliente(cliente);
//
//        this.cargarGrillaGestiones(listaGestionesCliente);
//
//    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelListaGestionesCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonSeleccionar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grillaGestionesCliente = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Lista Gestiones Cliente");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Lista Gestiones Cliente");

        botonSeleccionar.setText("Seleccionar");
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        grillaGestionesCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de Gestión", "Encabezado", "Fecha Inicio", "Estado", "Número Bibliorato", "Observaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grillaGestionesCliente);

        javax.swing.GroupLayout panelListaGestionesClienteLayout = new javax.swing.GroupLayout(panelListaGestionesCliente);
        panelListaGestionesCliente.setLayout(panelListaGestionesClienteLayout);
        panelListaGestionesClienteLayout.setHorizontalGroup(
            panelListaGestionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaGestionesClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelListaGestionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelListaGestionesClienteLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListaGestionesClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelListaGestionesClienteLayout.setVerticalGroup(
            panelListaGestionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaGestionesClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelListaGestionesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(botonSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelListaGestionesCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelListaGestionesCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonSeleccionarActionPerformed
    {//GEN-HEADEREND:event_botonSeleccionarActionPerformed

        switch (this.getFormularioInvocador())
        {
            case ConstantesGui.MODIFICAR_GESTION:
            {
                int filaSeleccionada = grillaGestionesCliente.getSelectedRow();

                for (Iterator<DtoGestionDeEscritura> it = gestionesCliente.iterator(); it.hasNext();)
                {
                    DtoGestionDeEscritura dtoGestionDeEscritura = it.next();

                    if (dtoGestionDeEscritura.getNumero() == (int) grillaGestionesCliente.getModel().getValueAt(filaSeleccionada, 0))
                    {
                        ModificarGestion formModificarGestion = (ModificarGestion) Principal.getInstancia().obtenerFormularioActivo(ConstantesGui.MODIFICAR_GESTION);
                        formModificarGestion.cargarDatosGestion(dtoGestionDeEscritura);
                    }
                }
                salir();
                break;
            }
            //  Tambien se incluye: ConsultarEstadoGestion
            //  Tambien se incluye: VerHistorialGestion
            case ConstantesGui.DETALLE_GESTION:
            {
                Principal.cargarFormulario(DetalleGestion.getInstancia());
                Principal.setVentanasActivas(DetalleGestion.getVentanaDetalleGestion());
                break;
            }
            case ConstantesGui.PREPARAR_ESCRITURA:
            {
                int filaSeleccionada = grillaGestionesCliente.getSelectedRow();

                for (Iterator<DtoGestionDeEscritura> it = gestionesCliente.iterator(); it.hasNext();)
                {
                    DtoGestionDeEscritura dtoGestionDeEscritura = it.next();

                    if (dtoGestionDeEscritura.getNumero() == (int) grillaGestionesCliente.getModel().getValueAt(filaSeleccionada, 0))
                    {
                        PrepararEscritura prepararEscrituraForm = new PrepararEscritura();
                        prepararEscrituraForm.cargarFormulario(dtoGestionDeEscritura);

                        Principal.cargarFormulario(prepararEscrituraForm);
                        salir();
                    }
                }
                break;
            }
            default:
            {
                salir();
            }
        }
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    public void cargarGrillaGestiones(List<DtoGestionDeEscritura> listaDtoGestiones)
    {
        gestionesCliente = listaDtoGestiones;
        for (Iterator<DtoGestionDeEscritura> it = listaDtoGestiones.iterator(); it.hasNext();)
        {
            DtoGestionDeEscritura dtoGestionDeEscritura = it.next();

            DtoEstadoDeGestion estadoActual = ControllerNegocio.getInstancia().obtenerEstadoActualDeGestion(dtoGestionDeEscritura);

            Object[] datos =
            {
                dtoGestionDeEscritura.getNumero(),
                dtoGestionDeEscritura.getEncabezado(),
                dtoGestionDeEscritura.getFechaInicio(),
                estadoActual.getNombre(),
                dtoGestionDeEscritura.getObservaciones()
            };

        }

    }

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
        salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        Principal.removeVentanaActivas(ventanaListaGestionesCliente);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JTable grillaGestionesCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelListaGestionesCliente;
    // End of variables declaration//GEN-END:variables
}
