info:
  name: Delete second role
  type: http
  seq: 6
  description: |-
      Teardown for 01a.
      Traceability: CU76
http:
  method: DELETE
  url: "{{base_url}}/api/v1/roles/{{roles_second_id}}"
  headers:
    - name: Content-Type
      value: application/json
    - name: Authorization
      value: "Bearer {{token}}"
runtime:
  scripts:
    - type: tests
      code: |-
          test("Status 204", function () { expect(res.getStatus()).to.equal(204); });
