/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.gestiones.testimonios;

import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.gui.gestiones.escrituras.BuscarEscritura;
import javax.swing.JMenuItem;

/**
 *
 * @author matias
 */
public class Testimonios extends javax.swing.JInternalFrame
{

    private static Testimonios instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem submenuTestimonios = new JMenuItem("Sub-modulo Testimonios");

    /**
     * Creates new form Testimonios
     */
    private Testimonios() {
        initComponents();
    }

    public static Testimonios getInstancia() {
        if (instancia == null)
        {
            instancia = new Testimonios();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);

        }
        return instancia;
    }

    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario) {
        Testimonios.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getSubmenuTestimonios() {
        return submenuTestimonios;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonGenerarTestimonio = new javax.swing.JButton();
        botonVerificarTestimonio = new javax.swing.JButton();
        botonRetirarTestimonio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Sub-modulo Testimonios");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonGenerarTestimonio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/testimonios/generarTestimonio.png"))); // NOI18N
        botonGenerarTestimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarTestimonioActionPerformed(evt);
            }
        });

        botonVerificarTestimonio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/testimonios/verificarTestimonio.png"))); // NOI18N
        botonVerificarTestimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerificarTestimonioActionPerformed(evt);
            }
        });

        botonRetirarTestimonio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/testimonios/retirarTestimonio.png"))); // NOI18N
        botonRetirarTestimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRetirarTestimonioActionPerformed(evt);
            }
        });

        jLabel1.setText("Registrar Testimonio");

        jLabel2.setText("Verificar Testimonio");

        jLabel3.setText("Retirar Testimonio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGenerarTestimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonVerificarTestimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonRetirarTestimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonRetirarTestimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerificarTestimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGenerarTestimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(597, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(submenuTestimonios);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonGenerarTestimonioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonGenerarTestimonioActionPerformed
    {//GEN-HEADEREND:event_botonGenerarTestimonioActionPerformed
        BuscarEscritura buscarEscrituraForm = new BuscarEscritura();
        buscarEscrituraForm.setFormularioInvocador(ConstantesGui.GENERAR_TESTIMONIO);
        buscarEscrituraForm.cargarFormulario();
        
        Principal.cargarFormulario(buscarEscrituraForm);
        Principal.setVentanasActivas(BuscarEscritura.getVentanaBuscarEscritura());
    }//GEN-LAST:event_botonGenerarTestimonioActionPerformed

    private void botonVerificarTestimonioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonVerificarTestimonioActionPerformed
    {//GEN-HEADEREND:event_botonVerificarTestimonioActionPerformed
        BuscarEscritura buscarEscrituraForm = new BuscarEscritura();
        buscarEscrituraForm.setFormularioInvocador(ConstantesGui.VERIFICAR_TESTIMONIO);
        buscarEscrituraForm.cargarFormulario();
        Principal.cargarFormulario(buscarEscrituraForm);
        Principal.setVentanasActivas(BuscarEscritura.getVentanaBuscarEscritura());
    }//GEN-LAST:event_botonVerificarTestimonioActionPerformed

    private void botonRetirarTestimonioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonRetirarTestimonioActionPerformed
    {//GEN-HEADEREND:event_botonRetirarTestimonioActionPerformed
        BuscarEscritura buscarEscrituraForm = new BuscarEscritura();
        buscarEscrituraForm.setFormularioInvocador(ConstantesGui.RETIRAR_TESTIMONIO);
        buscarEscrituraForm.cargarFormulario();
        Principal.cargarFormulario(buscarEscrituraForm);
        Principal.setVentanasActivas(BuscarEscritura.getVentanaBuscarEscritura());
    }//GEN-LAST:event_botonRetirarTestimonioActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGenerarTestimonio;
    private javax.swing.JButton botonRetirarTestimonio;
    private javax.swing.JButton botonVerificarTestimonio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
