/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.conceptos;

import com.licensis.notaire.dto.DtoConcepto;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.negocio.ControllerNegocio;
import com.licensis.notaire.servicios.AdministradorValidaciones;
import com.licensis.notaire.gui.util.AdministradorValidacionesGui;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Tefi
 */
public class IngresarConcepto extends javax.swing.JInternalFrame {

    private static JMenuItem ventanaIngresarConceptos = new JMenuItem("Ventana Ingresar Conceptos");
    private ControllerNegocio miControllerNegocio = null;

    /**
     * Creates new form IngresarConcepto
     */
    public IngresarConcepto() {
        initComponents();
        this.limpiarFormulario();
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        miControllerNegocio = ControllerNegocio.getInstancia();
    }

    private void salir() {
        this.dispose();
    }

    public static JMenuItem getVentanaIngresarConceptos() {
        return ventanaIngresarConceptos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIngresarConcepto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNombreConcepto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoValorConcepto = new javax.swing.JTextField();
        selectorPorcentaje = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        labelAdvertencia = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        checkBoxFijo = new javax.swing.JCheckBox();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Ingresar Conceptos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }

            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Ingresar Concepto");

        campoNombreConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreConceptoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Valor:");

        jLabel4.setText("Porcentaje:");

        campoValorConcepto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoValorConceptoKeyPressed(evt);
            }

            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoValorConceptoKeyReleased(evt);
            }
        });

        selectorPorcentaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectorPorcentajeMouseClicked(evt);
            }
        });
        selectorPorcentaje.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                selectorPorcentajeStateChanged(evt);
            }
        });
        selectorPorcentaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                selectorPorcentajeKeyPressed(evt);
            }

            public void keyReleased(java.awt.event.KeyEvent evt) {
                selectorPorcentajeKeyReleased(evt);
            }
        });

        jLabel5.setText("%");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        labelAdvertencia.setForeground(new java.awt.Color(239, 8, 8));

        jLabel6.setText("Valor fijo:");

        javax.swing.GroupLayout panelIngresarConceptoLayout = new javax.swing.GroupLayout(panelIngresarConcepto);
        panelIngresarConcepto.setLayout(panelIngresarConceptoLayout);
        panelIngresarConceptoLayout.setHorizontalGroup(
                panelIngresarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelIngresarConceptoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelIngresarConceptoLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                panelIngresarConceptoLayout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(botonAceptar,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(botonCancelar,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelIngresarConceptoLayout.createSequentialGroup()
                                                .addGroup(panelIngresarConceptoLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addGroup(panelIngresarConceptoLayout.createSequentialGroup()
                                                                .addGroup(panelIngresarConceptoLayout
                                                                        .createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel6))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(panelIngresarConceptoLayout
                                                                        .createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(checkBoxFijo)
                                                                        .addGroup(panelIngresarConceptoLayout
                                                                                .createSequentialGroup()
                                                                                .addComponent(selectorPorcentaje,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        54,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel5))
                                                                        .addGroup(panelIngresarConceptoLayout
                                                                                .createSequentialGroup()
                                                                                .addGroup(panelIngresarConceptoLayout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                        .addComponent(
                                                                                                campoNombreConcepto)
                                                                                        .addComponent(
                                                                                                campoValorConcepto,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                176,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(labelAdvertencia,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        250,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(0, 0, Short.MAX_VALUE)))));
        panelIngresarConceptoLayout.setVerticalGroup(
                panelIngresarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelIngresarConceptoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(panelIngresarConceptoLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(campoNombreConcepto, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelIngresarConceptoLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(campoValorConcepto, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelIngresarConceptoLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(selectorPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(panelIngresarConceptoLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(checkBoxFijo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134,
                                        Short.MAX_VALUE)
                                .addGroup(panelIngresarConceptoLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelIngresarConcepto, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelIngresarConcepto, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreConceptoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campoNombreConceptoActionPerformed
    }// GEN-LAST:event_campoNombreConceptoActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)// GEN-FIRST:event_formInternalFrameClosed
    {// GEN-HEADEREND:event_formInternalFrameClosed
        Principal.removeVentanaActivas(ventanaIngresarConceptos);
        Principal.eliminarFormulario(this);
    }// GEN-LAST:event_formInternalFrameClosed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_botonAceptarActionPerformed
    {// GEN-HEADEREND:event_botonAceptarActionPerformed

        String msj = AdministradorValidacionesGui.getInstancia().validarIngresarConcepto(this);

        if (msj == "") {
            try {
                DtoConcepto miDtoConcepto = new DtoConcepto();

                miDtoConcepto.setNombre(this.campoNombreConcepto.getText());

                if ("".equals(this.campoValorConcepto.getText())) {
                    miDtoConcepto.setValor(new Float(0.0));
                } else {
                    miDtoConcepto.setValor(Float.valueOf(this.campoValorConcepto.getText()));
                }

                miDtoConcepto.setHabilitado(true);

                if (checkBoxFijo.isSelected()) {
                    miDtoConcepto.setFijo(true);
                    miDtoConcepto.setPorcentaje(0);
                } else {
                    miDtoConcepto.setFijo(false);
                    miDtoConcepto.setPorcentaje(Integer.valueOf(this.selectorPorcentaje.getValue().toString()));
                }

                if (miControllerNegocio.darAltaConcepto(miDtoConcepto) == Boolean.TRUE) {
                    JOptionPane.showMessageDialog(this, "Se ha ingresado un concepto correctamente");
                    this.limpiarFormulario();
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Alguno de los campos contiene datos incorectos", "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, msj);
        }

    }// GEN-LAST:event_botonAceptarActionPerformed

    public void limpiarFormulario() {
        this.campoNombreConcepto.setText("");
        this.campoValorConcepto.setText("");
        this.selectorPorcentaje.setValue(0);
        this.checkBoxFijo.setSelected(false);
    }

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_botonCancelarActionPerformed
    {// GEN-HEADEREND:event_botonCancelarActionPerformed
        salir();
    }// GEN-LAST:event_botonCancelarActionPerformed

    private void campoValorConceptoKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_campoValorConceptoKeyReleased

        String valor = this.campoValorConcepto.getText();

        if (AdministradorValidaciones.getInstancia().validarNumeroFloat(valor)) {
            Float numeroFloat = Float.parseFloat(valor);
            if (numeroFloat < 0) {
                labelAdvertencia.setText("El valor no puede ser negativo.");
                this.campoValorConcepto.setText("");
            } else {
                labelAdvertencia.setText("");
            }
        }

    }// GEN-LAST:event_campoValorConceptoKeyReleased

    private void campoValorConceptoKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_campoValorConceptoKeyPressed
    }// GEN-LAST:event_campoValorConceptoKeyPressed

    private void selectorPorcentajeKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_selectorPorcentajeKeyReleased
    }// GEN-LAST:event_selectorPorcentajeKeyReleased

    private void selectorPorcentajeMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_selectorPorcentajeMouseClicked
    }// GEN-LAST:event_selectorPorcentajeMouseClicked

    private void selectorPorcentajeKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_selectorPorcentajeKeyPressed
    }// GEN-LAST:event_selectorPorcentajeKeyPressed

    private void selectorPorcentajeStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_selectorPorcentajeStateChanged
        int valor = this.selectorPorcentaje.getValue().hashCode();
        if (valor < 0) {
            this.selectorPorcentaje.setValue(0);
        }
    }// GEN-LAST:event_selectorPorcentajeStateChanged
     // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    public javax.swing.JTextField campoNombreConcepto;
    public javax.swing.JTextField campoValorConcepto;
    private javax.swing.JCheckBox checkBoxFijo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelAdvertencia;
    private javax.swing.JPanel panelIngresarConcepto;
    public javax.swing.JSpinner selectorPorcentaje;
    // End of variables declaration//GEN-END:variables
}
