/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.gestiones.documentacion;

import com.licensis.notaire.gui.Principal;
import javax.swing.JMenuItem;
import com.licensis.notaire.gui.gestiones.documentacion.Documentacion;

/**
 *
 * @author matias
 */
public class Documentacion extends javax.swing.JInternalFrame
{

    private static Documentacion instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem submenuDocumentacion = new JMenuItem("Sub-modulo Documentacion");

    /**
     * Creates new form Documentacion
     */
    private Documentacion() {
        initComponents();
    }

    public static Documentacion getInstancia() {
        if (instancia == null)
        {
            instancia = new Documentacion();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);

        }
        return instancia;
    }

    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario) {
        Documentacion.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getSubmenuDocumentacion() {
        return submenuDocumentacion;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonIngresarDocumentosEntidadesExternas = new javax.swing.JButton();
        botonConsultarDeudas = new javax.swing.JButton();
        botonListarDocumentos = new javax.swing.JButton();
        botonReingresarDocumentos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botonConsultarVencimientos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        botonRegistrarEntregaDocumentos = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Sub-modulo Documentacion");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel7.setText("<HTML>Registrar <BR>Documentacion<BR>Entidades Externas</HTML>");

        jLabel6.setText("<HTML>Registrar Ingreso <BR>Documentacion<BR>Cliente</HTML>");

        botonIngresarDocumentosEntidadesExternas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/gestiones/documentacion/ingresarDocumentos.png"))); // NOI18N
        botonIngresarDocumentosEntidadesExternas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarDocumentosEntidadesExternasActionPerformed(evt);
            }
        });

        botonConsultarDeudas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/gestiones/documentacion/consultarDeudas.png"))); // NOI18N
        botonConsultarDeudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarDeudasActionPerformed(evt);
            }
        });

        botonListarDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/gestiones/documentacion/listarDocumentos.png"))); // NOI18N
        botonListarDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarDocumentosActionPerformed(evt);
            }
        });

        botonReingresarDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/gestiones/documentacion/reingresarDocumentos.png"))); // NOI18N
        botonReingresarDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReingresarDocumentosActionPerformed(evt);
            }
        });

        jLabel4.setText("<HTML>Consultar<BR>Vencimientos</HTML>");

        jLabel2.setText("<HTML>Consultar-Registrar<BR>Deudas Documentacion<BR>Cliente</HTML>");

        jLabel1.setText("Listar Documentos");

        botonConsultarVencimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/gestiones/documentacion/consultarVencimientos.png"))); // NOI18N
        botonConsultarVencimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarVencimientosActionPerformed(evt);
            }
        });

        jLabel5.setText("<HTML>Reingresar Documentos<BR>Entidades Externas</HTML>");

        botonRegistrarEntregaDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/gestiones/documentacion/entregaDocumentacion.png"))); // NOI18N
        botonRegistrarEntregaDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarEntregaDocumentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonListarDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(botonRegistrarEntregaDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonConsultarDeudas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(botonConsultarVencimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonIngresarDocumentosEntidadesExternas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(botonReingresarDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(61, 274, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonConsultarDeudas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonListarDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))))
                    .addComponent(botonConsultarVencimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonIngresarDocumentosEntidadesExternas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonRegistrarEntregaDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonReingresarDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(submenuDocumentacion);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonListarDocumentosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonListarDocumentosActionPerformed
    {//GEN-HEADEREND:event_botonListarDocumentosActionPerformed
        Principal.cargarFormulario(new ListarDocumentos());
        Principal.setVentanasActivas(ListarDocumentos.getVentanaListarDocumentos());
    }//GEN-LAST:event_botonListarDocumentosActionPerformed

    private void botonConsultarDeudasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonConsultarDeudasActionPerformed
    {//GEN-HEADEREND:event_botonConsultarDeudasActionPerformed

        ConsultarDeudasDocumentos.getInstancia().limpiarForm();
        Principal.cargarFormulario(ConsultarDeudasDocumentos.getInstancia());
        Principal.setVentanasActivas(ConsultarDeudasDocumentos.getVentanaConsultarDeudasDocumento());        
    }//GEN-LAST:event_botonConsultarDeudasActionPerformed

    private void botonConsultarVencimientosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonConsultarVencimientosActionPerformed
    {//GEN-HEADEREND:event_botonConsultarVencimientosActionPerformed

        ConsultarVencimientosDocumentos form = new ConsultarVencimientosDocumentos();
        form.cargarListaDocumentosConVencimiento();
        Principal.cargarFormulario(form);
        Principal.setVentanasActivas(ConsultarVencimientosDocumentos.getVentanaConsultarVencimientosDocumento());
    }//GEN-LAST:event_botonConsultarVencimientosActionPerformed

    private void botonRegistrarEntregaDocumentosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonRegistrarEntregaDocumentosActionPerformed
    {//GEN-HEADEREND:event_botonRegistrarEntregaDocumentosActionPerformed
        RegistrarEntregaDocumentos formEntregaDocumentos = RegistrarEntregaDocumentos.getInstancia();
        formEntregaDocumentos.limpiarFormulario();

        Principal.cargarFormulario(formEntregaDocumentos);
        Principal.setVentanasActivas(RegistrarEntregaDocumentos.getVentanaRegistrarEntregaDocumentos());
    }//GEN-LAST:event_botonRegistrarEntregaDocumentosActionPerformed

    private void botonIngresarDocumentosEntidadesExternasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonIngresarDocumentosEntidadesExternasActionPerformed
    {//GEN-HEADEREND:event_botonIngresarDocumentosEntidadesExternasActionPerformed
        IngresarDocumento.getInstancia().limpiarFormulario();
        Principal.cargarFormulario(IngresarDocumento.getInstancia());
        Principal.setVentanasActivas(IngresarDocumento.getVentanaIngresarDocumento());
    }//GEN-LAST:event_botonIngresarDocumentosEntidadesExternasActionPerformed

    private void botonReingresarDocumentosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonReingresarDocumentosActionPerformed
    {//GEN-HEADEREND:event_botonReingresarDocumentosActionPerformed
        Principal.cargarFormulario(ReingresarDocumentos.getInstancia());
        ReingresarDocumentos.getInstancia().limpiarForm();
        Principal.setVentanasActivas(ReingresarDocumentos.getVentanaReingresarDocumento());

    }//GEN-LAST:event_botonReingresarDocumentosActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultarDeudas;
    private javax.swing.JButton botonConsultarVencimientos;
    private javax.swing.JButton botonIngresarDocumentosEntidadesExternas;
    private javax.swing.JButton botonListarDocumentos;
    private javax.swing.JButton botonRegistrarEntregaDocumentos;
    private javax.swing.JButton botonReingresarDocumentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
