/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.gestiones.documentacion;

import com.licensis.notaire.dto.DtoPlantillaTramite;
import com.licensis.notaire.dto.DtoTipoDeTramite;
import com.licensis.notaire.gui.Principal;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.licensis.notaire.negocio.ControllerNegocio;
import com.licensis.notaire.servicios.AdministradorReportes;

/**
 *
 * @author matias
 */
public class ListarDocumentos extends javax.swing.JInternalFrame
{

    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem ventanaListarDocumentos = new JMenuItem("Ventana Listar Documentos");
    private ControllerNegocio miController = null;
    private List<DtoTipoDeTramite> listaTiposDeTramites = new ArrayList<>();
    private DtoTipoDeTramite dtoTipoDeTramiteSeleccionado = null;

    /**
     * Creates new form ListarDocumentacion
     */
    public ListarDocumentos() {
        initComponents();
        this.estadoFormulario = Boolean.TRUE;
        miController = ControllerNegocio.getInstancia();
        this.setSize(900,600);
        this.cargarListaTramites();
    }

    private void salir() {
        this.dispose();
    }

    public static JMenuItem getVentanaListarDocumentos() {
        return ventanaListarDocumentos;
    }

    public void cargarListaTramites() {
        listaTiposDeTramites = miController.buscarTiposDeTramiteHabilitados();

        if (!listaTiposDeTramites.isEmpty())
        {
            for (Iterator<DtoTipoDeTramite> it = listaTiposDeTramites.iterator(); it.hasNext();)
            {
                DtoTipoDeTramite dtoTipoDeTramite = it.next();
                this.comboTipoTramites.addItem(dtoTipoDeTramite.getNombre());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No existen tipo de tramites registrados.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            this.salir();
        }
    }

    public void cargarPlantillaTipoTramite(DtoTipoDeTramite tipoDeTramite) {
        List<DtoPlantillaTramite> listaPlantillaTramites = miController.obtenerPlantillasTramite(tipoDeTramite);

        if (!listaPlantillaTramites.isEmpty())
        {
            for (Iterator<DtoPlantillaTramite> it = listaPlantillaTramites.iterator(); it.hasNext();)
            {
                DtoPlantillaTramite dtoPlantillaTramite = it.next();
                Object[] datos =
                {
                    dtoPlantillaTramite.getTiposDeDocumento().getNombre(),
                    dtoPlantillaTramite.getTiposDeDocumento().isVence(),
                    dtoPlantillaTramite.getTiposDeDocumento().getDiasVencimiento(),
                    dtoPlantillaTramite.getTiposDeDocumento().getQuienEntrega()
                };

                ((DefaultTableModel) this.grillaDocumentosTramite.getModel()).addRow(datos);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "El tipo de tramite seleccionado no posee documentos asociados", "Error", JOptionPane.ERROR_MESSAGE);
            this.salir();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelListarDocumentos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonImprimir = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grillaDocumentosTramite = new javax.swing.JTable();
        comboTipoTramites = new javax.swing.JComboBox();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Listar Documentos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Listar Documentos");

        botonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/impresora.png"))); // NOI18N
        botonImprimir.setText("Imprimir");
        botonImprimir.setIconTextGap(10);
        botonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImprimirActionPerformed(evt);
            }
        });

        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/cerrar.png"))); // NOI18N
        botonCerrar.setText("Cerrar");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de Trámite:");

        grillaDocumentosTramite.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo de Documento", "Vence", "Dias de Validéz", "A presentar Por:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grillaDocumentosTramite);

        comboTipoTramites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoTramitesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelListarDocumentosLayout = new javax.swing.GroupLayout(panelListarDocumentos);
        panelListarDocumentos.setLayout(panelListarDocumentosLayout);
        panelListarDocumentosLayout.setHorizontalGroup(
            panelListarDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListarDocumentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelListarDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelListarDocumentosLayout.createSequentialGroup()
                        .addGroup(panelListarDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListarDocumentosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelListarDocumentosLayout.createSequentialGroup()
                                .addGroup(panelListarDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(panelListarDocumentosLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboTipoTramites, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 242, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panelListarDocumentosLayout.setVerticalGroup(
            panelListarDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListarDocumentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelListarDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboTipoTramites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelListarDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelListarDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelListarDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonImprimirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonImprimirActionPerformed
    {//GEN-HEADEREND:event_botonImprimirActionPerformed
        if (this.dtoTipoDeTramiteSeleccionado != null)
        {
            List<DtoTipoDeTramite> listaTramites = new ArrayList<DtoTipoDeTramite>();
            listaTramites.add(dtoTipoDeTramiteSeleccionado);

            AdministradorReportes reportes = AdministradorReportes.getInstancia();
            reportes.generarReporteListaDocumentos(listaTramites);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningun tipo de tramite.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        salir();
    }//GEN-LAST:event_botonImprimirActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCerrarActionPerformed
    {//GEN-HEADEREND:event_botonCerrarActionPerformed
        salir();
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        this.estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(ventanaListarDocumentos);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    public void limpiarGrilla() {
        int i = ((DefaultTableModel) this.grillaDocumentosTramite.getModel()).getRowCount() - 1;

        while (((DefaultTableModel) this.grillaDocumentosTramite.getModel()).getRowCount() > 0)
        {
            ((DefaultTableModel) this.grillaDocumentosTramite.getModel()).removeRow(i);
            i--;
        }
    }

    private void comboTipoTramitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoTramitesActionPerformed

        this.limpiarGrilla();

        String tramiteSeleccionado = this.comboTipoTramites.getSelectedItem().toString();
        DtoTipoDeTramite dtoTipoDeTramiteSeleccionado = null;

        if (!tramiteSeleccionado.isEmpty() || tramiteSeleccionado != null)
        {

            for (Iterator<DtoTipoDeTramite> it = listaTiposDeTramites.iterator(); it.hasNext();)
            {

                DtoTipoDeTramite dtoTipoDeTramite = it.next();

                if (dtoTipoDeTramite.getNombre().contains(tramiteSeleccionado))
                {
                    dtoTipoDeTramiteSeleccionado = dtoTipoDeTramite;
                    break;
                }
            }

        }
        else
        {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun tipo de tramite", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

        this.cargarPlantillaTipoTramite(dtoTipoDeTramiteSeleccionado);
        this.dtoTipoDeTramiteSeleccionado = dtoTipoDeTramiteSeleccionado;

    }//GEN-LAST:event_comboTipoTramitesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonImprimir;
    private javax.swing.JComboBox comboTipoTramites;
    private javax.swing.JTable grillaDocumentosTramite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelListarDocumentos;
    // End of variables declaration//GEN-END:variables
}
