// =============================================================================
// Jenkinsfile — Notaire CI Pipeline
// =============================================================================
// Builds, tests, and publishes code coverage for the Notaire project using the
// Coverage Plugin (https://github.com/jenkinsci/coverage-plugin) as a modern
// replacement for the legacy JaCoCo Jenkins plugin.
//
// Requires: Maven 3.9, JDK 21, Docker
// =============================================================================

pipeline {
    agent any

    tools {
        maven 'Maven 3.9'
        jdk 'JDK21'
    }

    options {
        timestamps()
        ansiColor('xterm')
        buildDiscarder(
            logRotator(numToKeepStr: '20', daysToKeepStr: '30', artifactNumToKeepStr: '5')
        )
        skipDefaultCheckout()
    }

    environment {
        // -----------------------------------------------------------------------
        // Coverage report paths (generated by the Maven JaCoCo plugin at compile
        // time; the Jenkins Coverage Plugin parses these XML reports to display
        // trend charts, quality gates, and per-file coverage in the UI).
        // -----------------------------------------------------------------------
        JACOCO_XML_REPORT  = '**/target/site/jacoco/jacoco.xml'
        JACOCO_CSV_REPORT  = '**/target/site/jacoco/jacoco.csv'
        JUNIT_REPORTS      = '**/target/surefire-reports/*.xml'

        // -----------------------------------------------------------------------
        // Coverage quality gates enforced by the Coverage Plugin.
        // These mirror the 80 % LINE / BRANCH thresholds in pom.xml.
        // -----------------------------------------------------------------------
        COVERAGE_LINE_MIN   = '80.0'
        COVERAGE_BRANCH_MIN = '80.0'
    }

    stages {

        // -----------------------------------------------------------------------
        // CHECKOUT
        // -----------------------------------------------------------------------
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        // -----------------------------------------------------------------------
        // BUILD & TEST
        // -----------------------------------------------------------------------
        stage('Build & Test') {
            steps {
                sh 'mvn clean install -pl backend-api -am -DskipTests=false'
            }
            post {
                always {
                    // Publish JUnit/Surefire XML reports so the test-results trend
                    // is available in the Jenkins UI.
                    junit allowEmptyResults: true, testResults: "${JUNIT_REPORTS}"
                }
            }
        }

        // -----------------------------------------------------------------------
        // COVERAGE ANALYSIS  (Coverage Plugin)
        // -----------------------------------------------------------------------
        // Parse JaCoCo XML reports generated by `mvn jacoco:report` and publish
        // them through the Jenkins Coverage Plugin.  This provides:
        //   • per-build coverage trend charts
        //   • file-level coverage annotations
        //   • quality gates (the build is marked UNSTABLE when a threshold drops
        //     below the configured minimum).
        // -----------------------------------------------------------------------
        stage('Coverage Analysis') {
            when {
                expression { fileExists(env.JACOCO_XML_REPORT) }
            }
            steps {
                publishCoverage adapters: [
                    jacocoAdapter(
                        path: env.JACOCO_XML_REPORT
                    )
                ]
            }
        }

        // -----------------------------------------------------------------------
        // PACKAGE
        // -----------------------------------------------------------------------
        stage('Package') {
            steps {
                sh 'mvn package -pl backend-api -am -DskipTests'
            }
            post {
                success {
                    archiveArtifacts artifacts: 'backend-api/target/*.jar',
                                    fingerprint: true,
                                    allowEmpty: false
                }
            }
        }

        // -----------------------------------------------------------------------
        // DOCKER BUILD
        // -----------------------------------------------------------------------
        stage('Docker Build') {
            steps {
                script {
                    docker.build(
                        "notaire-backend:latest",
                        "-f backend-api/Dockerfile ."
                    )
                }
            }
        }
    }

    post {
        always {
            // Clean up workspace after build.
            cleanWs()
        }
        failure {
            echo "Pipeline FAILED — ${env.BUILD_URL}"
        }
        unstable {
            echo "Pipeline UNSTABLE (threshold breach?) — ${env.BUILD_URL}"
        }
    }
}
