/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.gestiones.escrituras;

import com.licensis.notaire.dto.DtoEscritura;
import com.licensis.notaire.dto.DtoPersona;
import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.api.client.RestMapper;
import com.licensis.notaire.servicios.AdministradorJpa;
import com.licensis.notaire.servicios.GenericRestClient;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author matias
 */
public class BuscarEscritura extends javax.swing.JInternalFrame
{

    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem ventanaBuscarEscritura = new JMenuItem("Ventana Buscar Escritura");
    private List<DtoEscritura> escriturasEncontradas = new ArrayList<>();
    private GenericRestClient escrituraClient = AdministradorJpa.getInstancia().getEscrituraJpa();
    private GenericRestClient personaClient = AdministradorJpa.getInstancia().getPersonaJpa();
    private String formularioInvocador;
    private Boolean cargada = true;
    private ListaEscrituras listaEscriturasForm;

    /**
     * Creates new form BuscarEscritura
     */
    public BuscarEscritura()
    {
        initComponents();
        estadoFormulario = Boolean.TRUE;
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        grupoBotones.add(radioButtonBuscarPorEscribano);
        grupoBotones.add(radioButtonPorNumeroEscritura);
        radioButtonBuscarPorEscribano.setSelected(true);
        this.cargarFormulario();
    }

    public void setFormularioInvocador(String formularioInvocador)
    {
        this.formularioInvocador = formularioInvocador;
    }

    private void salir()
    {
        this.dispose();
    }

    public static JMenuItem getVentanaBuscarEscritura()
    {
        return ventanaBuscarEscritura;
    }

    public void cargarFormulario()
    {
        this.limpiarFormulario();

        try
        {
            List<com.licensis.notaire.dto.GenericDto> escribanos = escrituraClient.findAllByPath("escribanos-disponibles");
            if (escribanos != null && !escribanos.isEmpty())
            {
                for (com.licensis.notaire.dto.GenericDto dto : escribanos)
                {
                    Integer registro = dto.getInt("registroEscribano");
                    if (registro != null)
                    {
                        this.comboNumeroRegistro.addItem(registro);
                    }
                }
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error al cargar escribanos: " + e.getMessage());
        }
    }

    public void limpiarFormulario()
    {
        this.comboNumeroRegistro.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        panelBuscarEscritura = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        radioButtonBuscarPorEscribano = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        comboNumeroRegistro = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        campoNumeroEscritura = new javax.swing.JTextField();
        radioButtonPorNumeroEscritura = new javax.swing.JRadioButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Buscar Escritura");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Buscar Escritura");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        radioButtonBuscarPorEscribano.setText("Busca por Escribano:");

        jLabel6.setText("Número Registro:");

        comboNumeroRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboNumeroRegistroMouseClicked(evt);
            }
        });
        comboNumeroRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNumeroRegistroActionPerformed(evt);
            }
        });

        jLabel7.setText("Número Escritura:");

        campoNumeroEscritura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNumeroEscrituraMouseClicked(evt);
            }
        });

        radioButtonPorNumeroEscritura.setText("Buscar por número de escritura");

        javax.swing.GroupLayout panelBuscarEscrituraLayout = new javax.swing.GroupLayout(panelBuscarEscritura);
        panelBuscarEscritura.setLayout(panelBuscarEscrituraLayout);
        panelBuscarEscrituraLayout.setHorizontalGroup(
            panelBuscarEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarEscrituraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarEscrituraLayout.createSequentialGroup()
                        .addGap(0, 255, Short.MAX_VALUE)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBuscarEscrituraLayout.createSequentialGroup()
                        .addGroup(panelBuscarEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioButtonPorNumeroEscritura)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(radioButtonBuscarPorEscribano)
                            .addGroup(panelBuscarEscrituraLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(panelBuscarEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelBuscarEscrituraLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboNumeroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelBuscarEscrituraLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoNumeroEscritura, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBuscarEscrituraLayout.setVerticalGroup(
            panelBuscarEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarEscrituraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelBuscarEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarEscrituraLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelBuscarEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(comboNumeroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(radioButtonBuscarPorEscribano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonPorNumeroEscritura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBuscarEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoNumeroEscritura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(panelBuscarEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBuscarEscritura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBuscarEscritura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAceptarActionPerformed
    {//GEN-HEADEREND:event_botonAceptarActionPerformed
        listaEscriturasForm = new ListaEscrituras();
        cargada = false;

        switch (formularioInvocador)
        {
            case ConstantesGui.MODIFICAR_ESCRITURA:
            {
                listaEscriturasForm.setFormularioInvocador(ConstantesGui.MODIFICAR_ESCRITURA);
                cargarOpcionEscrituras();

                break;
            }
            case ConstantesGui.GENERAR_TESTIMONIO:
            {
                listaEscriturasForm.setFormularioInvocador(ConstantesGui.GENERAR_TESTIMONIO);
                cargarOpcionEscriturasFirmadas();

                break;
            }
            case ConstantesGui.VERIFICAR_TESTIMONIO:
            {
                listaEscriturasForm.setFormularioInvocador(ConstantesGui.VERIFICAR_TESTIMONIO);
                cargarOpcionEscriturasFirmadasInscriptas();
                break;
            }
            case ConstantesGui.INGRESAR_PARA_INSCRIPCION:
            {
                listaEscriturasForm.setFormularioInvocador(ConstantesGui.INGRESAR_PARA_INSCRIPCION);
                cargarOpcionEscriturasFirmadasSeInscriben();
                if (!cargada)
                {
                    JOptionPane.showMessageDialog(this, "No hay testimonios generados de las escrituras para ingresar a inscribir.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                }
                break;
            }
            case ConstantesGui.REGISTRAR_REINGRESO:
            {
                listaEscriturasForm.setFormularioInvocador(ConstantesGui.REGISTRAR_REINGRESO);
                cargarOpcionEscriturasFirmadasSeInscriben();
                if (!cargada)
                {
                    JOptionPane.showMessageDialog(this, "No hay testimonios para reingresar.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                }
                break;
            }
            case ConstantesGui.REGISTRAR_INSCRIPCION:
            {
                listaEscriturasForm.setFormularioInvocador(ConstantesGui.REGISTRAR_INSCRIPCION);
                cargarOpcionEscriturasFirmadasSeInscriben();
                if (!cargada)
                {
                    JOptionPane.showMessageDialog(this, "No hay testimonios para inscribir.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                }
                break;
            }
            case ConstantesGui.RETIRAR_TESTIMONIO:
            {
                listaEscriturasForm.setFormularioInvocador(ConstantesGui.RETIRAR_TESTIMONIO);
                cargarOpcionEscriturasFirmadasInscriptas();
                break;
            }
            case ConstantesGui.BUSCAR_ESCRITURA:
            {
                listaEscriturasForm.setFormularioInvocador(ConstantesGui.BUSCAR_ESCRITURA);
                cargarOpcionEscrituras();
                break;
            }
        }

        if (cargada)
        {
            Principal.cargarFormulario(listaEscriturasForm);
            Principal.setVentanasActivas(ListaEscrituras.getVentanaListaEscritura());
        }

        this.salir();

    }//GEN-LAST:event_botonAceptarActionPerformed

    private void cargarOpcionEscrituras()
    {

        if (radioButtonBuscarPorEscribano.isSelected())
        {
            Integer registro = (Integer) comboNumeroRegistro.getSelectedItem();
            escriturasEncontradas = buscarEscriturasPorRegistro(registro);

            if (escriturasEncontradas != null && !escriturasEncontradas.isEmpty())
            {
                listaEscriturasForm.limpiarGrilla();
                cargada = listaEscriturasForm.cargarGrilla(escriturasEncontradas);
            } else
            {
                JOptionPane.showMessageDialog(this, "No existen escrituras asociadas al Escribano indicado.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        } else if (radioButtonPorNumeroEscritura.isSelected())
        {
            try
            {
                int numero = Integer.parseInt(campoNumeroEscritura.getText());
                List<com.licensis.notaire.dto.GenericDto> results = escrituraClient.findAllByPath("buscar?numero=" + numero);
                escriturasEncontradas = new ArrayList<>();
                for (com.licensis.notaire.dto.GenericDto raw : results)
                {
                    DtoEscritura esc = new DtoEscritura();
                    esc.setIdEscritura(raw.getInt("idEscritura"));
                    esc.setNumero(raw.getInt("numero") != null ? raw.getInt("numero") : 0);
                    Object fechaObj = raw.get("fechaEscrituracion");
                    if (fechaObj instanceof Number fechaNum)
                    {
                        esc.setFechaEscrituracion(new java.util.Date(fechaNum.longValue()));
                    }
                    esc.setEstado(raw.getString("estado"));
                    escriturasEncontradas.add(esc);
                }
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error al buscar escritura: " + e.getMessage());
            }

            if (escriturasEncontradas != null && !escriturasEncontradas.isEmpty())
            {
                listaEscriturasForm.limpiarGrilla();
                cargada = listaEscriturasForm.cargarGrilla(escriturasEncontradas);
            } else
            {
                JOptionPane.showMessageDialog(this, "No existen escrituras con el numero indicado.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    private void cargarOpcionEscriturasFirmadas()
    {

        if (radioButtonBuscarPorEscribano.isSelected())
        {
            Integer registro = (Integer) comboNumeroRegistro.getSelectedItem();
            escriturasEncontradas = buscarEscriturasPorRegistro(registro);
        } else if (radioButtonPorNumeroEscritura.isSelected())
        {
            try
            {
                int numero = Integer.parseInt(campoNumeroEscritura.getText());
                List<com.licensis.notaire.dto.GenericDto> results = escrituraClient.findAllByPath("buscar?numero=" + numero);
                escriturasEncontradas = new ArrayList<>();
                for (com.licensis.notaire.dto.GenericDto raw : results)
                {
                    DtoEscritura esc = new DtoEscritura();
                    esc.setIdEscritura(raw.getInt("idEscritura"));
                    esc.setNumero(raw.getInt("numero") != null ? raw.getInt("numero") : 0);
                    escriturasEncontradas.add(esc);
                }
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
            }
        }

        if (escriturasEncontradas != null && !escriturasEncontradas.isEmpty())
        {
            listaEscriturasForm.limpiarGrilla();
            cargada = listaEscriturasForm.cargarGrilla(escriturasEncontradas);
        } else
        {
            JOptionPane.showMessageDialog(this, "No existen escrituras firmadas asociadas al Escribano indicado.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }

        listaEscriturasForm.labelTituloEscrituras.setText("Lista Escrituras Firmadas");
    }

    private void cargarOpcionEscriturasFirmadasSeInscriben()
    {

        List<DtoEscritura> escrituras = new ArrayList<>();

        if (radioButtonBuscarPorEscribano.isSelected())
        {
            Integer registro = (Integer) comboNumeroRegistro.getSelectedItem();
            escriturasEncontradas = buscarEscriturasPorRegistro(registro);

            if (escriturasEncontradas != null && !escriturasEncontradas.isEmpty())
            {
                for (Iterator<DtoEscritura> it = escriturasEncontradas.iterator(); it.hasNext();)
                {
                    DtoEscritura dtoEscritura = it.next();
                    escrituras.add(dtoEscritura);
                }

                if (!escrituras.isEmpty())
                {
                    listaEscriturasForm.limpiarGrilla();
                    cargada = listaEscriturasForm.cargarGrilla(escrituras);
                } else
                {
                    JOptionPane.showMessageDialog(this, "No hay testimonios disponibles para ingresar a inscribir.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);

                }
            } else
            {
                JOptionPane.showMessageDialog(this, "No existen escrituras para inscribir asociadas al Escribano indicado.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        } else if (radioButtonPorNumeroEscritura.isSelected())
        {
            try
            {
                int numero = Integer.parseInt(campoNumeroEscritura.getText());
                List<com.licensis.notaire.dto.GenericDto> results = escrituraClient.findAllByPath("buscar?numero=" + numero);
                escriturasEncontradas = new ArrayList<>();
                for (com.licensis.notaire.dto.GenericDto raw : results)
                {
                    DtoEscritura esc = new DtoEscritura();
                    esc.setIdEscritura(raw.getInt("idEscritura"));
                    esc.setNumero(raw.getInt("numero") != null ? raw.getInt("numero") : 0);
                    escriturasEncontradas.add(esc);
                }
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
            }

            if (escriturasEncontradas != null && !escriturasEncontradas.isEmpty())
            {
                for (Iterator<DtoEscritura> it = escriturasEncontradas.iterator(); it.hasNext();)
                {
                    DtoEscritura dtoEscritura = it.next();
                    escrituras.add(dtoEscritura);
                }

                if (!escrituras.isEmpty())
                {
                    listaEscriturasForm.limpiarGrilla();
                    cargada = listaEscriturasForm.cargarGrilla(escrituras);
                } else
                {
                    JOptionPane.showMessageDialog(this, "No hay testimonios disponibles para ingresar a inscribir.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                }
            } else
            {
                JOptionPane.showMessageDialog(this, "No existen escrituras para inscribir con el numero indicado.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        }

        listaEscriturasForm.labelTituloEscrituras.setText("Lista Escrituras Firmadas Para Inscripcion");
    }

    private void cargarOpcionEscriturasFirmadasInscriptas()
    {

        if (radioButtonBuscarPorEscribano.isSelected())
        {
            Integer registro = (Integer) comboNumeroRegistro.getSelectedItem();
            escriturasEncontradas = buscarEscriturasPorRegistro(registro);

            if (escriturasEncontradas != null && !escriturasEncontradas.isEmpty())
            {
                listaEscriturasForm.limpiarGrilla();
                cargada = listaEscriturasForm.cargarGrilla(escriturasEncontradas);
            } else
            {
                JOptionPane.showMessageDialog(this, "No existen escrituras firmadas o inscriptas asociadas al Escribano indicado.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        } else if (radioButtonPorNumeroEscritura.isSelected())
        {
            try
            {
                int numero = Integer.parseInt(campoNumeroEscritura.getText());
                List<com.licensis.notaire.dto.GenericDto> results = escrituraClient.findAllByPath("buscar?numero=" + numero);
                escriturasEncontradas = new ArrayList<>();
                for (com.licensis.notaire.dto.GenericDto raw : results)
                {
                    DtoEscritura esc = new DtoEscritura();
                    esc.setIdEscritura(raw.getInt("idEscritura"));
                    esc.setNumero(raw.getInt("numero") != null ? raw.getInt("numero") : 0);
                    escriturasEncontradas.add(esc);
                }
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
            }

            if (escriturasEncontradas != null && !escriturasEncontradas.isEmpty())
            {
                listaEscriturasForm.limpiarGrilla();
                cargada = listaEscriturasForm.cargarGrilla(escriturasEncontradas);
            } else
            {
                JOptionPane.showMessageDialog(this, "No existen escrituras  firmadas o inscriptas con el numero indicado.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        }
        listaEscriturasForm.labelTituloEscrituras.setText("Lista Escrituras Firmadas e Inscriptas");
    }

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
        this.salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(ventanaBuscarEscritura);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void comboNumeroRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboNumeroRegistroMouseClicked
        // TODO add your handling code here:
        radioButtonBuscarPorEscribano.setSelected(true);
        radioButtonPorNumeroEscritura.setSelected(false);
    }//GEN-LAST:event_comboNumeroRegistroMouseClicked

    private void campoNumeroEscrituraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNumeroEscrituraMouseClicked
        // TODO add your handling code here:
        radioButtonBuscarPorEscribano.setSelected(false);
        radioButtonPorNumeroEscritura.setSelected(true);
    }//GEN-LAST:event_campoNumeroEscrituraMouseClicked

    private void comboNumeroRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNumeroRegistroActionPerformed
        radioButtonBuscarPorEscribano.setSelected(true);
        radioButtonPorNumeroEscritura.setSelected(false);
    }//GEN-LAST:event_comboNumeroRegistroActionPerformed

    private List<DtoEscritura> buscarEscriturasPorRegistro(Integer registroEscribano)
    {
        List<DtoEscritura> result = new ArrayList<>();
        try
        {
            List<com.licensis.notaire.dto.GenericDto> todasEscrituras = escrituraClient.findAll();
            for (com.licensis.notaire.dto.GenericDto raw : todasEscrituras)
            {
                DtoEscritura esc = new DtoEscritura();
                esc.setIdEscritura(raw.getInt("idEscritura"));
                esc.setNumero(raw.getInt("numero") != null ? raw.getInt("numero") : 0);
                Object fechaObj = raw.get("fechaEscrituracion");
                if (fechaObj instanceof Number fechaNum)
                {
                    esc.setFechaEscrituracion(new java.util.Date(fechaNum.longValue()));
                }
                esc.setEstado(raw.getString("estado"));
                esc.setMatriculaInscripcion(raw.getString("matriculaInscripcion"));
                result.add(esc);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error al buscar escrituras: " + e.getMessage());
        }
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoNumeroEscritura;
    private javax.swing.JComboBox comboNumeroRegistro;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelBuscarEscritura;
    private javax.swing.JRadioButton radioButtonBuscarPorEscribano;
    private javax.swing.JRadioButton radioButtonPorNumeroEscritura;
    // End of variables declaration//GEN-END:variables
}
