/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.documentos;

import com.licensis.notaire.dto.GenericDto;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.servicios.AdministradorJpa;
import com.licensis.notaire.servicios.GenericRestClient;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Tefi
 */
public class EliminarDocumento extends javax.swing.JInternalFrame
{

    private static JMenuItem ventanaEliminarTipoDocumento = new JMenuItem("Ventana Eliminar Tipo de Documento");
    private List<GenericDto> misDocumentos = null;
    private GenericRestClient tipoDocumentoClient = null;
    private GenericDto miDocumentoSeleccionado = null;

    /**
     * Creates new form EliminarDocumento
     */
    public EliminarDocumento()
    {
        initComponents();
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        tipoDocumentoClient = AdministradorJpa.getInstancia().getTipoDeDocumentoJpa();
        inicializarFormulario();
    }

    private void salir()
    {
        this.dispose();
    }

    public static JMenuItem getVentanaEliminarDocumento()
    {
        return ventanaEliminarTipoDocumento;
    }

    private void inicializarFormulario()
    {
        misDocumentos = null;
        miDocumentoSeleccionado = null;
        
        try
        {
            misDocumentos = tipoDocumentoClient.findAll();

            if (misDocumentos != null && !misDocumentos.isEmpty())
            {
                DefaultListModel lista = new DefaultListModel();

                for (Iterator<GenericDto> it = misDocumentos.iterator(); it.hasNext();)
                {
                    GenericDto miDto = it.next();
                    String nombre = miDto.getString("nombre");
                    if (nombre != null)
                    {
                        lista.addElement(nombre);
                    }
                }

                this.listaTiposDocumentosDisponibles.setModel(lista);

            campoNombre.setEnabled(false);
            campoDiasVencimiento.setEnabled(false);
            campoEntrega.setEnabled(false);
            checkBoxVence.setEnabled(false);
            botonAceptar.setEnabled(false);

                campoNombre.setText("");
                campoDiasVencimiento.setText("");
                campoEntrega.setText("");
                checkBoxVence.setSelected(false);
            } else
            {
                JOptionPane.showMessageDialog(this, "No existen Tipos de Documento para eliminar.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                salir();
            }
        }
        catch (IOException ex)
        {
            JOptionPane.showMessageDialog(this, "Error al cargar documentos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(EliminarDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEliminarDocumento = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaTiposDocumentosDisponibles = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonSeleccionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoDiasVencimiento = new javax.swing.JTextField();
        campoEntrega = new javax.swing.JTextField();
        checkBoxVence = new javax.swing.JCheckBox();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Eliminar Tipo de Documento");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        listaTiposDocumentosDisponibles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(listaTiposDocumentosDisponibles);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Eliminar Tipo de Documento");

        jLabel6.setText("Lista de Tipos de Documentos Disponibles:");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/aceptar.png"))); // NOI18N
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Tipo de Documento:");

        jLabel3.setText("Vence:");

        jLabel4.setText("Días Vencimiento:");

        jLabel5.setText("Hace entrega:");

        campoNombre.setEditable(false);

        campoDiasVencimiento.setEditable(false);

        campoEntrega.setEditable(false);

        javax.swing.GroupLayout panelEliminarDocumentoLayout = new javax.swing.GroupLayout(panelEliminarDocumento);
        panelEliminarDocumento.setLayout(panelEliminarDocumentoLayout);
        panelEliminarDocumentoLayout.setHorizontalGroup(
            panelEliminarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarDocumentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEliminarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEliminarDocumentoLayout.createSequentialGroup()
                        .addGroup(panelEliminarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarDocumentoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelEliminarDocumentoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelEliminarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkBoxVence)
                                    .addGroup(panelEliminarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(campoDiasVencimiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                        .addComponent(campoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campoEntrega)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panelEliminarDocumentoLayout.createSequentialGroup()
                        .addGroup(panelEliminarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelEliminarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 78, Short.MAX_VALUE))))
        );
        panelEliminarDocumentoLayout.setVerticalGroup(
            panelEliminarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarDocumentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(panelEliminarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEliminarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(checkBoxVence))
                .addGap(18, 18, 18)
                .addGroup(panelEliminarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoDiasVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEliminarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panelEliminarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEliminarDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEliminarDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAceptarActionPerformed
    {//GEN-HEADEREND:event_botonAceptarActionPerformed
        int opcion;

        Integer nroSelecion = this.listaTiposDocumentosDisponibles.getSelectedIndex();
        if (nroSelecion != -1)
        {

            opcion = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desa eliminar el documento?", "ELIMINACION", JOptionPane.YES_NO_OPTION);

            if (opcion == JOptionPane.YES_OPTION)
            {

                String seleccionado = this.listaTiposDocumentosDisponibles.getSelectedValue().toString();

                for (Iterator<GenericDto> it = misDocumentos.iterator(); it.hasNext();)
                {
                    GenericDto miDto = it.next();

                    if (seleccionado.equals(miDto.getString("nombre")))
                    {
                        try
                        {
                            Integer idTipoDocumento = miDto.getInt("idTipoDocumento");
                            
                            if (idTipoDocumento != null)
                            {
                                tipoDocumentoClient.remove(idTipoDocumento);
                                JOptionPane.showMessageDialog(this, "Se ha eliminado el documento seleccionado.", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
                                inicializarFormulario();
                            } else
                            {
                                JOptionPane.showMessageDialog(this, "Error: No se pudo obtener el ID del documento", "ERROR", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                        catch (IOException ex)
                        {
                            JOptionPane.showMessageDialog(this, "Error al comunicarse con el servidor: " + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                            Logger.getLogger(EliminarDocumento.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        finally
                        {
                            DefaultListModel lista = new DefaultListModel();
                            listaTiposDocumentosDisponibles.setModel(lista);
                            botonAceptar.setEnabled(false);
                            this.listaTiposDocumentosDisponibles.updateUI();
                            this.inicializarFormulario();
                        }
                    }
                }
            }
        } else
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Documento");
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
        salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        Principal.removeVentanaActivas(ventanaEliminarTipoDocumento);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed

        Integer nroSelecion = this.listaTiposDocumentosDisponibles.getSelectedIndex();
        if (nroSelecion != -1)
        {

            String seleccionado = this.listaTiposDocumentosDisponibles.getSelectedValue().toString();

            for (Iterator<GenericDto> it = misDocumentos.iterator(); it.hasNext();)
            {
                GenericDto miDto = it.next();

                if (seleccionado.equals(miDto.getString("nombre")))
                {
                    campoNombre.setEnabled(true);
                    campoDiasVencimiento.setEnabled(true);
                    campoEntrega.setEnabled(true);
                    botonAceptar.setEnabled(true);

                    campoNombre.setText(miDto.getString("nombre"));
                    campoEntrega.setText(miDto.getString("quienEntrega"));

                    Boolean vence = miDto.getBoolean("vence");
                    if (vence != null && vence)
                    {
                        checkBoxVence.setSelected(true);

                        Integer diasVencimiento = miDto.getInt("diasVencimiento");
                        if (diasVencimiento != null)
                        {
                            campoDiasVencimiento.setText(diasVencimiento.toString());
                        }
                    }
                }
            }
        } else
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de Documento", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_botonSeleccionarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JTextField campoDiasVencimiento;
    private javax.swing.JTextField campoEntrega;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JCheckBox checkBoxVence;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listaTiposDocumentosDisponibles;
    private javax.swing.JPanel panelEliminarDocumento;
    // End of variables declaration//GEN-END:variables
}
