package com.licensis.notaire.dto;
// Generated 19/04/2012 16:59:26 by Hibernate Tools 3.2.1.GA

import com.licensis.notaire.dto.interfaces.DtoValido;

/**
 * DtoIdentificacion generated by hbm2java
 */
public class DtoIdentificacion implements DtoValido
{

    private DtoTipoIdentificacion tiposIdentificacion;
    private DtoPersona personas;
    private int numero;

    public DtoIdentificacion()
    {
    }

    public DtoTipoIdentificacion getTiposIdentificacion()
    {
        return this.tiposIdentificacion;
    }

    public void setTiposIdentificacion(DtoTipoIdentificacion tiposIdentificacion)
    {
        this.tiposIdentificacion = tiposIdentificacion;
    }

    public DtoPersona getPersonas()
    {
        return this.personas;
    }

    public void setPersonas(DtoPersona personas)
    {
        this.personas = personas;
    }

    public int getNumero()
    {
        return this.numero;
    }

    public void setNumero(int numero)
    {
        this.numero = numero;
    }

    @Override
    public Boolean isValido()
    {
        //  TODO: implementar.
        return true;
    }
}
