/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.conceptos;

import com.licensis.notaire.dto.GenericDto;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.servicios.AdministradorJpa;
import com.licensis.notaire.servicios.GenericRestClient;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Tefi
 */
public class EliminarConcepto extends javax.swing.JInternalFrame
{

    private static JMenuItem ventanaEliminarConceptos = new JMenuItem("Ventana Eliminar Conceptos");
    private GenericRestClient conceptoClient = null;
    private List<GenericDto> miListaConceptos = null;
    private GenericDto dtoConceptoSeleccionado = null;
    private String nombreConceptoSeleccionado = null;

    /**
     * Creates new form EliminarConcepto
     */
    public EliminarConcepto()
    {
        initComponents();
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        conceptoClient = AdministradorJpa.getInstancia().getConceptoJpa();
        this.cargarListaConceptos();
    }

    private void salir()
    {
        this.dispose();
    }

    public static JMenuItem getVentanaEliminarConceptos()
    {
        return ventanaEliminarConceptos;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEliminarConcepto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaConceptosDisponibles = new javax.swing.JList();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonSeleccionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoValor = new javax.swing.JTextField();
        campoPorcentaje = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        checkBoxFijo = new javax.swing.JCheckBox();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Eliminar Conceptos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Eliminar Concepto");

        jLabel6.setText("Lista de Conceptos Disponibles:");

        jScrollPane3.setViewportView(listaConceptosDisponibles);

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/aceptar.png"))); // NOI18N
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Concepto:");

        jLabel3.setText("Valor:");

        jLabel4.setText("Porcentaje:");

        campoNombre.setEditable(false);

        campoValor.setEditable(false);
        campoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorActionPerformed(evt);
            }
        });

        campoPorcentaje.setEditable(false);

        jLabel5.setText("Valor fijo:");

        checkBoxFijo.setEnabled(false);

        javax.swing.GroupLayout panelEliminarConceptoLayout = new javax.swing.GroupLayout(panelEliminarConcepto);
        panelEliminarConcepto.setLayout(panelEliminarConceptoLayout);
        panelEliminarConceptoLayout.setHorizontalGroup(
            panelEliminarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarConceptoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEliminarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarConceptoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEliminarConceptoLayout.createSequentialGroup()
                        .addGroup(panelEliminarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelEliminarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelEliminarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)))
                            .addGroup(panelEliminarConceptoLayout.createSequentialGroup()
                                .addGroup(panelEliminarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(panelEliminarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkBoxFijo)
                                    .addGroup(panelEliminarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campoNombre)
                                        .addComponent(campoValor)
                                        .addComponent(campoPorcentaje)))))
                        .addGap(0, 167, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelEliminarConceptoLayout.setVerticalGroup(
            panelEliminarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarConceptoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(panelEliminarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEliminarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEliminarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEliminarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(checkBoxFijo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEliminarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEliminarConcepto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEliminarConcepto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAceptarActionPerformed
    {//GEN-HEADEREND:event_botonAceptarActionPerformed
        if (!nombreConceptoSeleccionado.isEmpty())
        {
            for (Iterator<GenericDto> it = miListaConceptos.iterator(); it.hasNext();)
            {
                GenericDto dtoConcepto = it.next();

                if (nombreConceptoSeleccionado.equals(dtoConcepto.getString("nombre")))
                {
                    try
                    {
                        dtoConceptoSeleccionado = dtoConcepto;
                        Integer idConcepto = dtoConceptoSeleccionado.getInt("idConcepto");
                        
                        if (idConcepto != null)
                        {
                            conceptoClient.remove(idConcepto);
                            JOptionPane.showMessageDialog(this, "Se ha eliminado un concepto correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                            this.cargarListaConceptos();
                        } else
                        {
                            JOptionPane.showMessageDialog(this, "Error: No se pudo obtener el ID del concepto", "Error", JOptionPane.ERROR_MESSAGE);
                        }

                    }
                    catch (IOException ex)
                    {
                        JOptionPane.showMessageDialog(this, "Error al comunicarse con el servidor: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                        Logger.getLogger(EliminarConcepto.class.getName()).log(Level.SEVERE, null, ex);
                        this.cargarListaConceptos();
                    }
                    finally
                    {
                        DefaultListModel newModel = new DefaultListModel();
                        listaConceptosDisponibles.setModel(newModel);
                        cargarListaConceptos();
                        break;
                    }
                }
            }

        } else
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Concepto", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
        salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        Principal.removeVentanaActivas(ventanaEliminarConceptos);
        Principal.eliminarFormulario(this);

    }//GEN-LAST:event_formInternalFrameClosed

    private void campoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorActionPerformed

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed
        // TODO add your handling code here:
        int opcion;

        Integer nroSelecion = this.listaConceptosDisponibles.getSelectedIndex();
        if (nroSelecion != -1)
        {

            nombreConceptoSeleccionado = this.listaConceptosDisponibles.getSelectedValue().toString();

            if (!nombreConceptoSeleccionado.isEmpty())
            {
                for (Iterator<GenericDto> it = miListaConceptos.iterator(); it.hasNext();)
                {
                    GenericDto dtoConcepto = it.next();

                    if (nombreConceptoSeleccionado.equals(dtoConcepto.getString("nombre")))
                    {
                        campoNombre.setEnabled(true);
                        campoPorcentaje.setEnabled(true);
                        campoValor.setEnabled(true);
                        botonAceptar.setEnabled(true);

                        campoNombre.setText(dtoConcepto.getString("nombre"));
                        Integer porcentaje = dtoConcepto.getInt("porcentaje");
                        if (porcentaje != null)
                        {
                            campoPorcentaje.setText(porcentaje.toString());
                        }
                        Float valor = dtoConcepto.getFloat("valor");
                        if (valor != null)
                        {
                            campoValor.setText(valor.toString());
                        }

                        Boolean fijo = dtoConcepto.getBoolean("fijo");
                        if (fijo != null && fijo)
                        {
                            checkBoxFijo.setSelected(true);
                        } else
                        {
                            checkBoxFijo.setSelected(false);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    private void cargarListaConceptos()
    {
        //  obtengo la lista de conceptos disponibles.
        miListaConceptos = null;
        dtoConceptoSeleccionado = null;
        nombreConceptoSeleccionado = null;
        campoNombre.setEnabled(false);
        campoPorcentaje.setEnabled(false);
        campoValor.setEnabled(false);
        botonAceptar.setEnabled(false);
        miListaConceptos = new ArrayList<>();

        try
        {
            miListaConceptos = conceptoClient.findAll();

            //  si la lista no esta vacia, la cargo en la grilla de conceptos disponibles.
            if (miListaConceptos != null && !miListaConceptos.isEmpty())
            {
                DefaultListModel lista = new DefaultListModel();

                for (Iterator<GenericDto> it = miListaConceptos.iterator(); it.hasNext();)
                {
                    GenericDto dtoConcepto = it.next();
                    String nombre = dtoConcepto.getString("nombre");
                    if (nombre != null)
                    {
                        lista.addElement(nombre);
                    }
                }

                this.listaConceptosDisponibles.setModel(lista);

            } else
            {
                JOptionPane.showMessageDialog(this, "No existen Conceptos para eliminar.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                salir();
            }
        }
        catch (IOException ex)
        {
            JOptionPane.showMessageDialog(this, "Error al cargar conceptos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(EliminarConcepto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPorcentaje;
    private javax.swing.JTextField campoValor;
    private javax.swing.JCheckBox checkBoxFijo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listaConceptosDisponibles;
    private javax.swing.JPanel panelEliminarConcepto;
    // End of variables declaration//GEN-END:variables
}
