/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.gestiones.gestion;

import com.licensis.notaire.dto.DtoPersona;
import com.licensis.notaire.dto.DtoTipoIdentificacion;
import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.gui.clientes.BuscarGestionesCliente;
import com.licensis.notaire.gui.clientes.ListarPersonas;
import java.util.ArrayList;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import com.licensis.notaire.negocio.ControllerNegocio;

/**
 *
 * @author matias
 */
public class BuscarGestion extends javax.swing.JInternalFrame
{

    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem ventanaBuscarGestion = new JMenuItem("Ventana Buscar Gestion");
    private String formularioInvocador = new String();
    private String tipoBusqueda;
    private Boolean flag = false; //Sirve para saber cuando hay que cerrar el form de busqueda

    public String getTipoBusqueda() {
        return tipoBusqueda;
    }

    public void setTipoBusqueda(String tipoBusqueda) {
        this.tipoBusqueda = tipoBusqueda;
    }

    /**
     * Creates new form BuscarGestion
     */
    public BuscarGestion() {
        initComponents();
        grupo_botones.add(buscarTipoIdentificacion);
        grupo_botones.add(buscarNombreApellido);
        estadoFormulario = Boolean.TRUE;
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        this.cargarCombo();


    }

    private void salir() {
        this.dispose();
    }

    public static JMenuItem getVentanaBuscarGestion() {
        return ventanaBuscarGestion;
    }

    public void cargarCombo() {
        ArrayList<DtoTipoIdentificacion> listaDtoIdentificaciones = ControllerNegocio.getInstancia().listarTiposIdentificacion();

        for (int i = 0; i < listaDtoIdentificaciones.size(); i++)
        {
            String nombre = listaDtoIdentificaciones.get(i).getNombre();
            this.comboTipoIdentificacion.addItem(nombre);
        }
    }

    public String getFormularioInvocador() {
        return formularioInvocador;
    }

    public void setFormularioInvocador(String formularioInvocador) {
        this.formularioInvocador = formularioInvocador;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_botones = new javax.swing.ButtonGroup();
        panelBuscarGestion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        buscarNombreApellido = new javax.swing.JRadioButton();
        campoNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        campoApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNumeroIdentificacion = new javax.swing.JTextField();
        buscarTipoIdentificacion = new javax.swing.JRadioButton();
        comboTipoIdentificacion = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Buscar Gestion");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Buscar Gestión");

        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.setIconTextGap(10);
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar.png"))); // NOI18N
        botonCancelar.setText("Cerrar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        buscarNombreApellido.setSelected(true);
        buscarNombreApellido.setText("Buscar por Nombre y Apellido:");
        buscarNombreApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNombreApellidoActionPerformed(evt);
            }
        });

        campoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNombreMouseClicked(evt);
            }
        });

        campoApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoApellidoMouseClicked(evt);
            }
        });

        jLabel4.setText("Tipo Ident.:");

        jLabel5.setText("Número Ident.:");

        jLabel2.setText("Nombre:");

        campoNumeroIdentificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNumeroIdentificacionMouseClicked(evt);
            }
        });

        buscarTipoIdentificacion.setText("Buscar por Tipo y Número de Identificación:");
        buscarTipoIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTipoIdentificacionActionPerformed(evt);
            }
        });

        comboTipoIdentificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboTipoIdentificacionMouseClicked(evt);
            }
        });

        jLabel3.setText("Apellido");

        javax.swing.GroupLayout panelBuscarGestionLayout = new javax.swing.GroupLayout(panelBuscarGestion);
        panelBuscarGestion.setLayout(panelBuscarGestionLayout);
        panelBuscarGestionLayout.setHorizontalGroup(
            panelBuscarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarGestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarGestionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBuscarGestionLayout.createSequentialGroup()
                        .addGroup(panelBuscarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(panelBuscarGestionLayout.createSequentialGroup()
                                .addGroup(panelBuscarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(51, 51, 51)
                                .addGroup(panelBuscarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoApellido)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelBuscarGestionLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(32, 32, 32)
                                .addComponent(comboTipoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBuscarGestionLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNumeroIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buscarNombreApellido)
                            .addComponent(buscarTipoIdentificacion)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 274, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBuscarGestionLayout.setVerticalGroup(
            panelBuscarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarGestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(buscarNombreApellido)
                .addGap(18, 18, 18)
                .addGroup(panelBuscarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(panelBuscarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarTipoIdentificacion)
                .addGap(18, 18, 18)
                .addGroup(panelBuscarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboTipoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBuscarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoNumeroIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(panelBuscarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBuscarGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBuscarGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonBuscarActionPerformed
    {//GEN-HEADEREND:event_botonBuscarActionPerformed
        DtoPersona miDtoPersona = new DtoPersona();
        DtoTipoIdentificacion miDtoIdentificacion = new DtoTipoIdentificacion();

        if (buscarNombreApellido.isSelected() && (!campoNombre.getText().isEmpty() || !campoApellido.getText().isEmpty()))
        {

            ArrayList<DtoPersona> miListaDtoPersonasEncontradas = new ArrayList<>();

            //Set datos de busqueda Nombre y apellido, por aproximacion
            miDtoPersona.setNombre(campoNombre.getText());
            miDtoPersona.setApellido(campoApellido.getText());

            //Busco todas las personas con gestioon que tengan alguna coincidencia ya sea por Nombre o Apellido
            miListaDtoPersonasEncontradas = ControllerNegocio.getInstancia().buscarPersonaNombreApellidoConGestion(miDtoPersona);

            if (!miListaDtoPersonasEncontradas.isEmpty())
            {
                switch (this.tipoBusqueda)
                {
                    case ConstantesGui.VER_GESTIONES:
                    {
                        ListarPersonas.getInstancia().limpiarJtable();
                        this.flag = ListarPersonas.getInstancia().cargarGrillaClientes(miListaDtoPersonasEncontradas, ConstantesGui.VER_GESTIONES);
                        Principal.cargarFormulario(ListarPersonas.getInstancia());
                        Principal.setVentanasActivas(ListarPersonas.getVentanaListadoPersonas());
                        this.salir();
                        break;
                    }
                    case ConstantesGui.MODIFICAR_GESTION:
                    {
                        ListarPersonas.getInstancia().limpiarJtable();
                        this.flag = ListarPersonas.getInstancia().cargarGrillaClientes(miListaDtoPersonasEncontradas, ConstantesGui.MODIFICAR_GESTION);
                        Principal.cargarFormulario(ListarPersonas.getInstancia());
                        Principal.setVentanasActivas(ListarPersonas.getVentanaListadoPersonas());
                        this.salir();
                        break;
                    }
                    case ConstantesGui.DOCUMENTACION_INGRESO:
                    {
                        ListarPersonas.getInstancia().limpiarJtable();
                        this.flag = ListarPersonas.getInstancia().cargarGrillaClientes(miListaDtoPersonasEncontradas, ConstantesGui.DOCUMENTACION_INGRESO);
                        Principal.cargarFormulario(ListarPersonas.getInstancia());
                        Principal.setVentanasActivas(ListarPersonas.getVentanaListadoPersonas());
                        this.salir();
                        break;
                    }
                    case ConstantesGui.PREPARAR_ESCRITURA:
                    {
                        ListarPersonas.getInstancia().limpiarJtable();
                        this.flag = ListarPersonas.getInstancia().cargarGrillaClientes(miListaDtoPersonasEncontradas, ConstantesGui.PREPARAR_ESCRITURA);
                        Principal.cargarFormulario(ListarPersonas.getInstancia());
                        Principal.setVentanasActivas(ListarPersonas.getVentanaListadoPersonas());
                        this.salir();
                        break;
                    }
                    case ConstantesGui.VER_HISTORIAL_GESTION:
                    {
                        ListarPersonas.getInstancia().limpiarJtable();
                        this.flag = ListarPersonas.getInstancia().cargarGrillaClientes(miListaDtoPersonasEncontradas, ConstantesGui.VER_HISTORIAL_GESTION);
                        Principal.cargarFormulario(ListarPersonas.getInstancia());
                        Principal.setVentanasActivas(ListarPersonas.getVentanaListadoPersonas());
                        this.salir();
                        break;
                    }
                    case ConstantesGui.DOCUMENTACION_DEUDA:
                    {
                        ListarPersonas.getInstancia().limpiarJtable();
                        this.flag = ListarPersonas.getInstancia().cargarGrillaClientes(miListaDtoPersonasEncontradas, ConstantesGui.DOCUMENTACION_DEUDA);
                        Principal.cargarFormulario(ListarPersonas.getInstancia());
                        Principal.setVentanasActivas(ListarPersonas.getVentanaListadoPersonas());
                        this.salir();
                        break;
                    }
                    case ConstantesGui.DOCUMENTACION_ENTIDAD_EXTERNA:
                    {
                        ListarPersonas.getInstancia().limpiarJtable();
                        this.flag = ListarPersonas.getInstancia().cargarGrillaClientes(miListaDtoPersonasEncontradas, ConstantesGui.DOCUMENTACION_ENTIDAD_EXTERNA);
                        Principal.cargarFormulario(ListarPersonas.getInstancia());
                        Principal.setVentanasActivas(ListarPersonas.getVentanaListadoPersonas());
                        this.salir();
                        break;
                    }
                    case ConstantesGui.DOCUMENTACION_REINGRESO:
                    {
                        ListarPersonas.getInstancia().limpiarJtable();
                        this.flag = ListarPersonas.getInstancia().cargarGrillaClientes(miListaDtoPersonasEncontradas, ConstantesGui.DOCUMENTACION_REINGRESO);
                        Principal.cargarFormulario(ListarPersonas.getInstancia());
                        Principal.setVentanasActivas(ListarPersonas.getVentanaListadoPersonas());
                        this.salir();
                        break;
                    }
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "No hay gestion, asociada con la busqueda", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

            }
        }
        else if (buscarTipoIdentificacion.isSelected() && !campoNumeroIdentificacion.getText().isEmpty())
        {
            //Set dato de busqueda 
            miDtoIdentificacion.setNombre(comboTipoIdentificacion.getSelectedItem().toString());
            miDtoPersona.setDtoTipoIdentificacion(miDtoIdentificacion);
            miDtoPersona.setNumeroIdentificacion(campoNumeroIdentificacion.getText());
            miDtoPersona.getDtoTipoIdentificacion().setIdTipoIdentificacion(ControllerNegocio.getInstancia().asociarFkTipoIdentificacion(miDtoPersona));

            //Busco la persona por Tipo y Numero de documento con gestion
            DtoPersona personaEncontrada = ControllerNegocio.getInstancia().buscarPersonaTipoNumeroIdentificacionConGestion(miDtoPersona);

            if (personaEncontrada != null)
            {
                switch (tipoBusqueda)
                {

                    case ConstantesGui.VER_GESTIONES:
                    {
                        BuscarGestionesCliente.getInstancia().cargarGrillaGestionesCliente(personaEncontrada, ConstantesGui.VER_GESTIONES);
                        this.salir();
                        break;
                    }
                    case ConstantesGui.MODIFICAR_GESTION:
                    {
                        BuscarGestionesCliente.getInstancia().cargarGrillaGestionesCliente(personaEncontrada, ConstantesGui.MODIFICAR_GESTION);
                        this.salir();
                        break;
                    }
                    case ConstantesGui.DOCUMENTACION_INGRESO:
                    {
                        BuscarGestionesCliente.getInstancia().cargarGrillaGestionesCliente(personaEncontrada, ConstantesGui.DOCUMENTACION_INGRESO);
                        this.salir();
                        break;
                    }
                    case ConstantesGui.PREPARAR_ESCRITURA:
                    {
                        BuscarGestionesCliente.getInstancia().cargarGrillaGestionesCliente(personaEncontrada, ConstantesGui.PREPARAR_ESCRITURA);
                        this.salir();
                        break;
                    }
                    case ConstantesGui.VER_HISTORIAL_GESTION:
                    {
                        BuscarGestionesCliente.getInstancia().cargarGrillaGestionesCliente(personaEncontrada, ConstantesGui.VER_HISTORIAL_GESTION);
                        this.salir();
                        break;
                    }
                    case ConstantesGui.DOCUMENTACION_DEUDA:
                    {
                        BuscarGestionesCliente.getInstancia().cargarGrillaGestionesCliente(personaEncontrada, ConstantesGui.DOCUMENTACION_DEUDA);
                        this.salir();
                        break;
                    }
                    case ConstantesGui.DOCUMENTACION_ENTIDAD_EXTERNA:
                    {
                        BuscarGestionesCliente.getInstancia().cargarGrillaGestionesCliente(personaEncontrada, ConstantesGui.DOCUMENTACION_ENTIDAD_EXTERNA);
                        this.salir();
                        break;
                    }
                    case ConstantesGui.DOCUMENTACION_REINGRESO:
                    {
                        BuscarGestionesCliente.getInstancia().cargarGrillaGestionesCliente(personaEncontrada, ConstantesGui.DOCUMENTACION_REINGRESO);
                        this.salir();
                        break;
                    }
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "La persona no esta Registrada o No posee Gestion alguna asociada", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Complete los datos de busqueda", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        if (flag)
        { //Si es verdadera significa que se cargo la persona deseada, cierro busqueda
            this.salir();
        }

        this.limpiarFormulario();
        this.toFront();

    }//GEN-LAST:event_botonBuscarActionPerformed

    public void limpiarFormulario() {

        campoNombre.setText("");
        campoApellido.setText("");
        campoNumeroIdentificacion.setText("");
        buscarNombreApellido.setSelected(true);
    }
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
     
        this.dispose();
        Principal.removeVentanaActivas(ventanaBuscarGestion);
        Principal.eliminarFormulario(this);
        this.salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(ventanaBuscarGestion);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void buscarNombreApellidoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscarNombreApellidoActionPerformed
    {//GEN-HEADEREND:event_buscarNombreApellidoActionPerformed
        buscarNombreApellido.setSelected(true);
        buscarTipoIdentificacion.setSelected(false);
    }//GEN-LAST:event_buscarNombreApellidoActionPerformed

    private void buscarTipoIdentificacionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscarTipoIdentificacionActionPerformed
    {//GEN-HEADEREND:event_buscarTipoIdentificacionActionPerformed
        buscarNombreApellido.setSelected(false);
        buscarTipoIdentificacion.setSelected(true);
    }//GEN-LAST:event_buscarTipoIdentificacionActionPerformed

    private void campoNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNombreMouseClicked
        this.buscarNombreApellido.setSelected(true);
    }//GEN-LAST:event_campoNombreMouseClicked

    private void campoApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoApellidoMouseClicked
        this.buscarNombreApellido.setSelected(true);
    }//GEN-LAST:event_campoApellidoMouseClicked

    private void comboTipoIdentificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTipoIdentificacionMouseClicked
        this.buscarTipoIdentificacion.setSelected(true);
    }//GEN-LAST:event_comboTipoIdentificacionMouseClicked

    private void campoNumeroIdentificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNumeroIdentificacionMouseClicked
        this.buscarTipoIdentificacion.setSelected(true);
    }//GEN-LAST:event_campoNumeroIdentificacionMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JRadioButton buscarNombreApellido;
    private javax.swing.JRadioButton buscarTipoIdentificacion;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoNumeroIdentificacion;
    private javax.swing.JComboBox comboTipoIdentificacion;
    private javax.swing.ButtonGroup grupo_botones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelBuscarGestion;
    // End of variables declaration//GEN-END:variables
}
