/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.gestiones.gestion;

import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.gui.clientes.BuscarGestionesCliente;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author matias
 */
public class Gestion extends javax.swing.JInternalFrame
{

    private static Gestion instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem submenuGestion = new JMenuItem("Sub-modulo Gestion");

    /**
     * Creates new form Gestion
     */
    private Gestion() {
        initComponents();
    }

    public static Gestion getInstancia() {
        if (instancia == null)
        {
            instancia = new Gestion();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);

        }
        return instancia;
    }

    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario) {
        Gestion.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getSubmenuGestion() {
        return submenuGestion;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonIniciarGestion = new javax.swing.JButton();
        botonVerHistorialGestion = new javax.swing.JButton();
        botonBuscarGestion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonArchivarGestion = new javax.swing.JButton();
        botonModificarGestion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Sub-modulo Gestion");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonIniciarGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/gestion/iniciarGestion.png"))); // NOI18N
        botonIniciarGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarGestionActionPerformed(evt);
            }
        });

        botonVerHistorialGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/gestion/verHistorial.png"))); // NOI18N
        botonVerHistorialGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerHistorialGestionActionPerformed(evt);
            }
        });

        botonBuscarGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/gestion/buscarGestion.png"))); // NOI18N
        botonBuscarGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarGestionActionPerformed(evt);
            }
        });

        jLabel1.setText("Iniciar Gestión");

        jLabel3.setText("Ver Historial");

        jLabel4.setText("Buscar Gestión");

        botonArchivarGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/gestion/archivarGestion.png"))); // NOI18N
        botonArchivarGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArchivarGestionActionPerformed(evt);
            }
        });

        botonModificarGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/gestion/modificarGestion.png"))); // NOI18N
        botonModificarGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarGestionActionPerformed(evt);
            }
        });

        jLabel6.setText("Modificar Gestión");

        jLabel7.setText("Archivar Gestión");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonIniciarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(botonModificarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(botonBuscarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonVerHistorialGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(botonArchivarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonVerHistorialGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonIniciarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)))
                    .addComponent(botonModificarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonBuscarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonArchivarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarGestionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonBuscarGestionActionPerformed
    {//GEN-HEADEREND:event_botonBuscarGestionActionPerformed
        BuscarGestionesCliente formBuscarGestionesCliente = BuscarGestionesCliente.getInstancia();
        
        formBuscarGestionesCliente.labelTitulo.setText(ConstantesGui.VER_GESTIONES);        
        formBuscarGestionesCliente.desactivarGrilla();
        formBuscarGestionesCliente.mostrarBotonBuscar();
        
        Principal.cargarFormulario(formBuscarGestionesCliente);
        Principal.setVentanasActivas(BuscarGestion.getVentanaBuscarGestion());
    }//GEN-LAST:event_botonBuscarGestionActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(submenuGestion);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonIniciarGestionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonIniciarGestionActionPerformed
    {//GEN-HEADEREND:event_botonIniciarGestionActionPerformed
        Principal.cargarFormulario(new IniciarGestion());
        Principal.setVentanasActivas(IniciarGestion.getVentanaIniciarGestion());        
    }//GEN-LAST:event_botonIniciarGestionActionPerformed

    private void botonVerHistorialGestionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonVerHistorialGestionActionPerformed
    {//GEN-HEADEREND:event_botonVerHistorialGestionActionPerformed
        Principal.cargarFormulario(new VerHistorialGestion());
        Principal.setVentanasActivas(VerHistorialGestion.getVentanaVerHistorialGestion());
    }//GEN-LAST:event_botonVerHistorialGestionActionPerformed

    private void botonArchivarGestionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonArchivarGestionActionPerformed
    {//GEN-HEADEREND:event_botonArchivarGestionActionPerformed
        ArchivarGestion formArchivarGestion = ArchivarGestion.getInstancia();

        boolean flag = formArchivarGestion.cargarGrillaGestiones();
        if (!flag)
        {
            JOptionPane.showMessageDialog(this, "No hay gestion para ser archivadas");
        }
        else
        {
            Principal.cargarFormulario(formArchivarGestion);
            Principal.setVentanasActivas(ArchivarGestion.getVentanaArchivarGestion());
        }


    }//GEN-LAST:event_botonArchivarGestionActionPerformed

    private void botonModificarGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarGestionActionPerformed

        ModificarGestion formModificarGestion = new ModificarGestion();
        Principal.cargarFormulario(formModificarGestion);
        Principal.setVentanasActivas(ModificarGestion.getVentanaModificarGestion());
    }//GEN-LAST:event_botonModificarGestionActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonArchivarGestion;
    private javax.swing.JButton botonBuscarGestion;
    private javax.swing.JButton botonIniciarGestion;
    private javax.swing.JButton botonModificarGestion;
    private javax.swing.JButton botonVerHistorialGestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
