/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.gestiones.gestion;

import com.licensis.notaire.dto.DtoEstadoDeGestion;
import com.licensis.notaire.dto.DtoGestionDeEscritura;
import com.licensis.notaire.dto.DtoPersona;
import com.licensis.notaire.dto.DtoPresupuesto;
import com.licensis.notaire.dto.DtoTipoDeTramite;
import com.licensis.notaire.dto.DtoTramite;
import com.licensis.notaire.dto.DtoUsuario;
import com.licensis.notaire.dto.interfaces.DtoValido;
import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.gui.clientes.BuscarCliente;
import com.licensis.notaire.gui.presupuestos.BuscarPresupuesto;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.licensis.notaire.negocio.ConstantesNegocio;
import com.licensis.notaire.negocio.ControllerNegocio;
import com.licensis.notaire.servicios.AdministradorReportes;
import com.licensis.notaire.servicios.AdministradorSesion;

/**
 *
 * @author matias
 */
public class IniciarGestion extends javax.swing.JInternalFrame
{

    private static final long serialVersionUID = 1L;
    private static JMenuItem ventanaIniciarGestion = new JMenuItem("Ventana Iniciar Gestion");
    private static Boolean estadoFormulario = Boolean.FALSE;
    private List<DtoPresupuesto> listaDtoPresupuestosSeleccionados = new ArrayList<>();
    private DtoPersona dtoCliente = null;
    private List<DtoPersona> listaDtoEscribanos = new ArrayList<>();
    private List<DtoPersona> listaClientesAsociados = new ArrayList<>();
    private ControllerNegocio miController = ControllerNegocio.getInstancia();
    private DtoEstadoDeGestion estadoInicial;

    /**
     * Creates new form IniciarGestion
     */
    public IniciarGestion() {
        initComponents();
        IniciarGestion.setEstadoFormulario(Boolean.TRUE);
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioGrandeVertical);
        this.cargarRegistrosEscribanos();
        this.cargarUltimaGestionSugerida();
        this.cargarEstadoGestionInicial();
    }

    private void salir() {
        this.dispose();
    }

    public static JMenuItem getVentanaIniciarGestion() {
        return ventanaIniciarGestion;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        panelIniciarGestion = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoFechaInicio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboEscribanoACargo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        grillaClientesAsociados = new javax.swing.JTable();
        botonQuitarCliente = new javax.swing.JButton();
        botonAsociarCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        campoEncabezado = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        campoObservaciones = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        comboNumeroGestion = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        grillaPresupuestos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        botonBuscarPresupuesto = new javax.swing.JButton();
        labelNombreCliente = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Iniciar Gestion");
        setToolTipText("Iniciar Gestión");
        setAutoscrolls(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panelIniciarGestion.setAutoscrolls(true);
        panelIniciarGestion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha de Inicio:");

        campoFechaInicio.setEditable(false);

        jLabel4.setText("Escribano a cargo:");

        jLabel7.setText("Asociar Clientes:");

        grillaClientesAsociados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Cliente"
            }
        ));
        jScrollPane3.setViewportView(grillaClientesAsociados);

        botonQuitarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/borrar.png"))); // NOI18N
        botonQuitarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarClienteActionPerformed(evt);
            }
        });

        botonAsociarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar.png"))); // NOI18N
        botonAsociarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsociarClienteActionPerformed(evt);
            }
        });

        jLabel6.setText("Encabezado:");

        campoEncabezado.setColumns(20);
        campoEncabezado.setLineWrap(true);
        campoEncabezado.setRows(5);
        jScrollPane4.setViewportView(campoEncabezado);

        jLabel8.setText("Observaciones:");

        campoObservaciones.setColumns(20);
        campoObservaciones.setLineWrap(true);
        campoObservaciones.setRows(5);
        jScrollPane5.setViewportView(campoObservaciones);

        jLabel9.setText("Número de Gestión");

        comboNumeroGestion.setEditable(true);

        grillaPresupuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número Presupuesto", "Nombre Trámite", "Total Presupuesto", "Seleccionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grillaPresupuestos);

        jLabel2.setText("Buscar Presupuesto:");

        botonBuscarPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        botonBuscarPresupuesto.setText("Buscar");
        botonBuscarPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarPresupuestoActionPerformed(evt);
            }
        });

        labelNombreCliente.setText("...");
        labelNombreCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Cliente:");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Iniciar Gestión");

        javax.swing.GroupLayout panelIniciarGestionLayout = new javax.swing.GroupLayout(panelIniciarGestion);
        panelIniciarGestion.setLayout(panelIniciarGestionLayout);
        panelIniciarGestionLayout.setHorizontalGroup(
            panelIniciarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIniciarGestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIniciarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIniciarGestionLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(botonBuscarPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIniciarGestionLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIniciarGestionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelIniciarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIniciarGestionLayout.createSequentialGroup()
                                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIniciarGestionLayout.createSequentialGroup()
                                .addComponent(botonAsociarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonQuitarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addGroup(panelIniciarGestionLayout.createSequentialGroup()
                        .addGroup(panelIniciarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboNumeroGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelIniciarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboEscribanoACargo, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelIniciarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(campoFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelIniciarGestionLayout.setVerticalGroup(
            panelIniciarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIniciarGestionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIniciarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscarPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(labelNombreCliente))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelIniciarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboNumeroGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelIniciarGestionLayout.createSequentialGroup()
                        .addGroup(panelIniciarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboEscribanoACargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIniciarGestionLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIniciarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIniciarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIniciarGestionLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(botonAsociarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonQuitarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelIniciarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane6.setViewportView(panelIniciarGestion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        setEstadoFormulario(Boolean.FALSE);
        Principal.removeVentanaActivas(ventanaIniciarGestion);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonBuscarPresupuestoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonBuscarPresupuestoActionPerformed
    {//GEN-HEADEREND:event_botonBuscarPresupuestoActionPerformed
        BuscarPresupuesto miForm = new BuscarPresupuesto();
        miForm.setFormularioInvocador(ConstantesGui.INICIAR_GESTION);
        Principal.cargarFormulario(miForm);
        Principal.setVentanasActivas(BuscarPresupuesto.getVentanaBuscarPresupuesto());
    }//GEN-LAST:event_botonBuscarPresupuestoActionPerformed

    private void botonAsociarClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAsociarClienteActionPerformed
    {//GEN-HEADEREND:event_botonAsociarClienteActionPerformed
        BuscarCliente miform = new BuscarCliente();
        BuscarCliente.setTipoBusqueda(ConstantesGui.INICIAR_GESTION);
        Principal.cargarFormulario(miform);
        Principal.setVentanasActivas(BuscarCliente.getVentanaBuscarCliente());
    }//GEN-LAST:event_botonAsociarClienteActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAceptarActionPerformed
    {//GEN-HEADEREND:event_botonAceptarActionPerformed

        // creo un DTO para la nueva gestion.
        DtoGestionDeEscritura nuevaGestion = new DtoGestionDeEscritura();

        try
        {
            nuevaGestion.setNumero(Integer.valueOf(this.comboNumeroGestion.getSelectedItem().toString()));
            nuevaGestion.setClienteReferencia(this.getDtoCliente());
            nuevaGestion.setEncabezado(this.campoEncabezado.getText());
            nuevaGestion.setFechaInicio(Calendar.getInstance().getTime());
            nuevaGestion.setObservaciones(this.campoObservaciones.getText());
            nuevaGestion.setPersonaEscribano(this.obtenerEscribanoSeleccionado());

            if (!this.getListaClientesAsociados().isEmpty())
            {
                nuevaGestion.setListaClientesInvolucrados(this.getListaClientesAsociados());
            }
            else
            {
                nuevaGestion.setListaClientesInvolucrados(new ArrayList<DtoPersona>());
            }

            nuevaGestion.setEstado(this.estadoInicial);

            // creamos una lista con los tramites involucrados.
            List<DtoTramite> listaTramites = new ArrayList<>();

            for (Iterator<DtoPresupuesto> it = this.obtenerListaPresupuestosSeleccionados().iterator(); it.hasNext();)
            {
                DtoPresupuesto dtoPresupuesto = it.next();
                //  hago las referencias cruzadas: tramite-presupuesto
                DtoTramite unTramite = dtoPresupuesto.getTramite();
                unTramite.setPresupuesto(dtoPresupuesto);
                listaTramites.add(unTramite);
            }

            nuevaGestion.setListaTramitesAsociados(listaTramites);

            if (nuevaGestion.isValido())
            {
                DtoGestionDeEscritura gestion = this.getMiController().iniciarGestionDeEscritura(nuevaGestion);

                if (gestion.getIdGestion() == DtoValido.ID_DTO_INICIALIZADO)
                {
                    JOptionPane.showMessageDialog(this, "Error, no se ha podido iniciar la gestion.", "Error al inicia gestion", JOptionPane.ERROR_MESSAGE);
                }
                else if (gestion.getIdGestion() == DtoValido.VERSION_INICIAL)
                {
                    JOptionPane.showMessageDialog(this, "Error, el numero de gestion indicado ya existe..", "Error al inicia gestion", JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Se ha iniciado la gestion Nro.: " + gestion.getNumero());

                    //  Ahora imprimimos las listas de documentos necesarios para cada tramite de la gestion.

                    List<DtoTipoDeTramite> listaTiposTramites = new ArrayList<DtoTipoDeTramite>();

                    AdministradorReportes reportes = AdministradorReportes.getInstancia();


                    for (Iterator<DtoTramite> it = listaTramites.iterator(); it.hasNext();)
                    {
                        DtoTramite dtoTramite = it.next();
                        listaTiposTramites.add(dtoTramite.getTipoDeTramite());
                    }

                    reportes.generarReporteListaDocumentos(listaTiposTramites);

                    salir();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Algunos de los campos indicados no es valido!", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        }
        catch (NullPointerException e)
        {
            JOptionPane.showMessageDialog(this, "Numero de Gestion no valido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Numero de gestion no valido!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
        this.salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonQuitarClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonQuitarClienteActionPerformed
    {//GEN-HEADEREND:event_botonQuitarClienteActionPerformed
        DefaultTableModel grilla = (DefaultTableModel) this.grillaClientesAsociados.getModel();

        int i = this.grillaClientesAsociados.getSelectedRow();
        if (i != ConstantesGui.ERROR)
        {
            this.getListaClientesAsociados().remove(i);
            grilla.removeRow(i);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun cliente", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonQuitarClienteActionPerformed

    public void setPresupuestoSeleccionado(DtoPresupuesto presupuestoSeleccionado) {
        this.getListaDtoPresupuestosSeleccionados().add(presupuestoSeleccionado);
    }

    public void cargarGrillaTramitesPresupuesto() {
        if (this.getListaDtoPresupuestosSeleccionados().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "No se han seleccionado presupuestos", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            this.setDtoCliente(this.getListaDtoPresupuestosSeleccionados().get(0).getPersona());

            this.labelNombreCliente.setText(this.getDtoCliente().getNombre() + " " + this.getDtoCliente().getApellido());

            for (Iterator<DtoPresupuesto> it = this.getListaDtoPresupuestosSeleccionados().iterator(); it.hasNext();)
            {
                DtoPresupuesto dtoPresupuesto = it.next();

                DtoTramite dtoTramite = dtoPresupuesto.getTramite();
                Object[] datos =
                {
                    dtoPresupuesto.getIdPresupuesto(),
                    dtoTramite.getTipoDeTramite().getNombre(),
                    dtoPresupuesto.getTotal(),
                    false
                };
                ((DefaultTableModel) grillaPresupuestos.getModel()).addRow(datos);

            }

            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            Date fechaActual = Calendar.getInstance().getTime();
            String fecha = format.format(fechaActual);
            this.campoFechaInicio.setText(fecha);
        }
    }

    public void cargarRegistrosEscribanos() {

        this.setListaDtoEscribanos(this.miController.obtenerListaEscribanosDisponibles());

        //  Verifico si el usuario loguado es un escribano, y en tal caso, es el escribano por defualt
        //  para el combo.
        DtoUsuario usuariologuado = AdministradorSesion.getInstancia().getSesionUsuario().getDto();

        if (usuariologuado.getPersonas().getRegistroEscribano() != null)
        {
            this.comboEscribanoACargo.addItem(usuariologuado.getPersonas().getRegistroEscribano() + " - "
                    + usuariologuado.getPersonas().getNombre() + " "
                    + usuariologuado.getPersonas().getApellido());
        }

        if (!this.getListaDtoEscribanos().isEmpty())
        {
            for (Iterator<DtoPersona> it = this.getListaDtoEscribanos().iterator(); it.hasNext();)
            {
                DtoPersona dtoPersona = it.next();

                this.comboEscribanoACargo.addItem(dtoPersona.getRegistroEscribano() + " - "
                        + dtoPersona.getApellido() + " "
                        + dtoPersona.getNombre());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No existen escribanos registrados", "Error", JOptionPane.ERROR_MESSAGE);
            this.salir();
        }

    }

    public void cargarUltimaGestionSugerida() {

        this.comboNumeroGestion.addItem(new String(""));
        DtoGestionDeEscritura dtoProximaGestion = miController.obtenerProximaGestionDeEscritura();

        int proximoNumeroGestion = dtoProximaGestion.getNumero();

        if (proximoNumeroGestion == ConstantesGui.SIN_REGISTRO)
        {
            this.comboNumeroGestion.addItem(new Integer(1));
        }
        else
        {

            this.comboNumeroGestion.addItem(++proximoNumeroGestion);
        }
    }

    public void cargarEstadoGestionInicial() {
        List<DtoEstadoDeGestion> listaEstados = miController.obtenerListaEstadosDeGestionDisponibles();

        for (Iterator<DtoEstadoDeGestion> it = listaEstados.iterator(); it.hasNext();)
        {
            DtoEstadoDeGestion dtoEstadoDeGestion = it.next();

            if (dtoEstadoDeGestion.getNombre().contains(ConstantesNegocio.ESTADO_DE_GESTION_INICIAL))
            {
                this.estadoInicial = dtoEstadoDeGestion;
                this.estadoInicial.setNombre(ConstantesNegocio.ESTADO_DE_GESTION_INICIAL);
                this.estadoInicial.setObservaciones(ConstantesNegocio.ESTADO_DE_GESTION_INICIAL);
                break;
            }
        }

        if (this.estadoInicial == null)
        {
            JOptionPane.showMessageDialog(this, "El estado de gestion: INICIAL no ha sido registrado", "Error", JOptionPane.ERROR_MESSAGE);
            this.salir();
        }
    }

    public boolean agregarClienteGestion(DtoPersona nuevoCliente) {
        boolean registrado = false;
        for (Iterator<DtoPersona> it = this.getListaClientesAsociados().iterator(); it.hasNext();)
        {
            DtoPersona dtoPersona = it.next();

            if (nuevoCliente.getIdPersona().intValue() == dtoPersona.getIdPersona().intValue())
            {
                // El cliente ya se encuentra registrado en la lista de cliente, por lo tanto, 
                // no se puede volver a cargar.
                registrado = true;
                break;
            }
        }

        if ((this.getDtoCliente().getIdPersona().intValue() == nuevoCliente.getIdPersona().intValue()))
        {
            registrado = true;
        }

        if (registrado == true)
        {
            JOptionPane.showMessageDialog(this, "El cliente ya se encuentra en la lista de clientes", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            this.getListaClientesAsociados().add(nuevoCliente);
            Object[] datos =
            {
                nuevoCliente.getApellido() + " "
                + nuevoCliente.getNombre()
            };
            ((DefaultTableModel) this.grillaClientesAsociados.getModel()).addRow(datos);
        }
        return registrado;
    }

    public List<DtoPersona> getListaDtoEscribanos() {
        return listaDtoEscribanos;
    }

    public void setListaDtoEscribanos(List<DtoPersona> listaDtoEscribanos) {
        this.listaDtoEscribanos.addAll(listaDtoEscribanos);
    }

    public List<DtoPresupuesto> obtenerListaPresupuestosSeleccionados() {
        List<DtoPresupuesto> listaPresupuestos = new ArrayList<>();

        DefaultTableModel miGrilla = (DefaultTableModel) this.grillaPresupuestos.getModel();
        int cantidadFilas = this.getListaDtoPresupuestosSeleccionados().size();

        for (int i = 0; i < cantidadFilas; i++)
        {
            boolean seleccionado = (boolean) miGrilla.getValueAt(i, 3);

            if (seleccionado == true)
            {
                for (Iterator<DtoPresupuesto> it = this.listaDtoPresupuestosSeleccionados.iterator(); it.hasNext();)
                {
                    DtoPresupuesto dtoPresupuesto = it.next();

                    if (dtoPresupuesto.getIdPresupuesto() == Integer.parseInt(miGrilla.getValueAt(i, 0).toString()))
                    {
                        listaPresupuestos.add(dtoPresupuesto);
                    }
                }
            }
        }

        return listaPresupuestos;
    }

    public DtoPersona obtenerEscribanoSeleccionado() {
        DtoPersona escribanoSeleccionado = new DtoPersona();

        try
        {
            String escribano = this.comboEscribanoACargo.getSelectedItem().toString();

            for (Iterator<DtoPersona> it = this.getListaDtoEscribanos().iterator(); it.hasNext();)
            {
                DtoPersona unEscribano = it.next();

                if (escribano.contains(unEscribano.getRegistroEscribano().toString()))
                {
                    return unEscribano;
                }
            }
        }
        catch (NullPointerException e)
        {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun escribano", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return escribanoSeleccionado;
    }

    public DtoPersona getDtoCliente() {
        return dtoCliente;
    }

    public void setDtoCliente(DtoPersona dtoCliente) {
        this.dtoCliente = dtoCliente;
    }

    public List<DtoPresupuesto> getListaDtoPresupuestosSeleccionados() {
        return listaDtoPresupuestosSeleccionados;
    }

    public void setListaDtoPresupuestosSeleccionados(List<DtoPresupuesto> listaDtoPresupuestosSeleccionados) {
        this.listaDtoPresupuestosSeleccionados.addAll(listaDtoPresupuestosSeleccionados);
    }

    public List<DtoPersona> getListaClientesAsociados() {
        return listaClientesAsociados;
    }

    public void setListaClientesAsociados(List<DtoPersona> listaClientesAsociados) {
        this.listaClientesAsociados.addAll(listaClientesAsociados);
    }

    public ControllerNegocio getMiController() {
        return miController;
    }

    public void setMiController(ControllerNegocio miController) {
        this.miController = miController;
    }

    /**
     * @return the estadoFormulario
     */
    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    /**
     * @param aEstadoFormulario the estadoFormulario to set
     */
    public static void setEstadoFormulario(Boolean aEstadoFormulario) {
        estadoFormulario = aEstadoFormulario;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAsociarCliente;
    private javax.swing.JButton botonBuscarPresupuesto;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonQuitarCliente;
    private javax.swing.JTextArea campoEncabezado;
    private javax.swing.JTextField campoFechaInicio;
    private javax.swing.JTextArea campoObservaciones;
    private javax.swing.JComboBox comboEscribanoACargo;
    private javax.swing.JComboBox comboNumeroGestion;
    private javax.swing.JTable grillaClientesAsociados;
    private javax.swing.JTable grillaPresupuestos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelNombreCliente;
    private javax.swing.JPanel panelIniciarGestion;
    // End of variables declaration//GEN-END:variables
}
