/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.gestiones.gestion;

import com.licensis.notaire.dto.DtoGestionDeEscritura;
import com.licensis.notaire.dto.DtoPersona;
import com.licensis.notaire.dto.DtoPresupuesto;
import com.licensis.notaire.dto.DtoTramite;
import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.gui.clientes.BuscarCliente;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.licensis.notaire.jpa.exceptions.ClassModifiedException;
import com.licensis.notaire.negocio.ConstantesNegocio;
import com.licensis.notaire.negocio.ControllerNegocio;

/**
 *
 * @author User
 */
public class ModificarGestion extends javax.swing.JInternalFrame
{

    private static final long serialVersionUID = 1L;
    private static JMenuItem ventanaModificarGestion = new JMenuItem("Ventana Modificar Gestion");
    private DtoPersona dtoCliente = null;
    private List<DtoPersona> listaClientesEliminados = new ArrayList<>();
    private List<DtoPersona> listaClientesAgregados = new ArrayList<>();
    private DtoGestionDeEscritura dtoGestionSeleccionada;
    private List<DtoPersona> listaClientesAsociados = new ArrayList<>();
    private List<DtoTramite> listaTramitesAsociados = new ArrayList<>();
    private ControllerNegocio miController = ControllerNegocio.getInstancia();

    /**
     * Creates new form ModificarGestion
     */
    public ModificarGestion() {
        initComponents();
        this.setTitle("Ventana Modificar Gestion");
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioGrandeVertical);
        this.setMinimumSize(new Dimension(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical));
    }

    public static JMenuItem getVentanaModificarGestion() {
        return ventanaModificarGestion;
    }

    private void salir() {
        this.dispose();
    }

    public List<DtoPersona> getListaClientesAsociados() {
        return listaClientesAsociados;
    }

    public void setListaClientesAsociados(List<DtoPersona> listaClientesAsociados) {
        this.listaClientesAsociados = listaClientesAsociados;
    }

    public List<DtoTramite> getListaTramitesAsociados() {
        return listaTramitesAsociados;
    }

    public void setListaTramitesAsociados(List<DtoTramite> listaTramitesAsociados) {
        this.listaTramitesAsociados = listaTramitesAsociados;
    }

    public void agregarClienteGestion(DtoPersona nuevoCliente) {
        this.listaClientesAgregados.add(nuevoCliente);
        Object[] datos =
        {
            nuevoCliente.getApellido() + " "
            + nuevoCliente.getNombre()
        };
        ((DefaultTableModel) this.grillaClientesAsociados.getModel()).addRow(datos);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        panelModificarGestion = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoFechaInicio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboEscribanoACargo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        grillaClientesAsociados = new javax.swing.JTable();
        botonQuitarCliente = new javax.swing.JButton();
        botonAsociarCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        campoEncabezado = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        campoObservaciones = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grillaPresupuestos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        buscarGestion = new javax.swing.JButton();
        labelNombreCliente = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoNumeroGestion = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Modificar Gestion");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panelModificarGestion.setAutoscrolls(true);
        panelModificarGestion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha de Inicio:");

        campoFechaInicio.setEditable(false);

        jLabel4.setText("Escribano a cargo:");

        jLabel7.setText("Asociar Clientes:");

        grillaClientesAsociados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Cliente"
            }
        ));
        jScrollPane3.setViewportView(grillaClientesAsociados);

        botonQuitarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/borrar.png"))); // NOI18N
        botonQuitarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarClienteActionPerformed(evt);
            }
        });

        botonAsociarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/agregar.png"))); // NOI18N
        botonAsociarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsociarClienteActionPerformed(evt);
            }
        });

        jLabel6.setText("Encabezado:");

        campoEncabezado.setColumns(20);
        campoEncabezado.setRows(5);
        jScrollPane4.setViewportView(campoEncabezado);

        jLabel8.setText("Observaciones:");

        campoObservaciones.setColumns(20);
        campoObservaciones.setRows(5);
        jScrollPane5.setViewportView(campoObservaciones);

        jLabel9.setText("Número de Gestión");

        grillaPresupuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número Presupuesto", "Nombre Trámite", "Total Presupuesto", "Seleccionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grillaPresupuestos);

        jLabel2.setText("Buscar Gestión");

        buscarGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/buscar.png"))); // NOI18N
        buscarGestion.setText("Buscar");
        buscarGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarGestionActionPerformed(evt);
            }
        });

        labelNombreCliente.setText("...");
        labelNombreCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Cliente:");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Modificar Gestión");

        campoNumeroGestion.setEditable(false);
        campoNumeroGestion.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        campoNumeroGestion.setEnabled(false);

        javax.swing.GroupLayout panelModificarGestionLayout = new javax.swing.GroupLayout(panelModificarGestion);
        panelModificarGestion.setLayout(panelModificarGestionLayout);
        panelModificarGestionLayout.setHorizontalGroup(
            panelModificarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarGestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarGestionLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(buscarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelModificarGestionLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarGestionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelModificarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarGestionLayout.createSequentialGroup()
                                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarGestionLayout.createSequentialGroup()
                                .addComponent(botonAsociarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonQuitarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addGroup(panelModificarGestionLayout.createSequentialGroup()
                        .addGroup(panelModificarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNumeroGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(panelModificarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboEscribanoACargo, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelModificarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(campoFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelModificarGestionLayout.setVerticalGroup(
            panelModificarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarGestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(labelNombreCliente))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelModificarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelModificarGestionLayout.createSequentialGroup()
                        .addGroup(panelModificarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelModificarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboEscribanoACargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNumeroGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelModificarGestionLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelModificarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarGestionLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(botonAsociarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonQuitarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelModificarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane6.setViewportView(panelModificarGestion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarDatosGestion(DtoGestionDeEscritura dtoGestion) {

        if (dtoGestion.isValido())
        {

            this.dtoGestionSeleccionada = dtoGestion;

            this.labelNombreCliente.setText(dtoGestion.getClienteReferencia().getNombre() + ", " + dtoGestion.getClienteReferencia().getApellido());
            this.campoNumeroGestion.setText(String.valueOf(dtoGestion.getNumero()));
            this.comboEscribanoACargo.addItem(dtoGestion.getPersonaEscribano().getNombre() + ", " + dtoGestion.getPersonaEscribano().getApellido());

            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            Date fechaActual = dtoGestion.getFechaInicio();
            String fecha = format.format(fechaActual);
            this.campoFechaInicio.setText(fecha);
            this.campoEncabezado.setText(dtoGestion.getEncabezado());
            this.campoObservaciones.setText(dtoGestion.getObservaciones());


            for (Iterator<DtoTramite> itTramites = dtoGestion.getListaTramitesAsociados().iterator(); itTramites.hasNext();)
            {
                DtoTramite dtoTramite = itTramites.next();

                dtoTramite = miController.buscarTramite(dtoTramite);

                DtoPresupuesto dtoPresupuesto = miController.buscarPresupuestoPorNumero(dtoTramite.getPresupuesto());

                dtoTramite.setPresupuesto(dtoPresupuesto);

                Object[] datos =
                {
                    dtoTramite.getPresupuesto().getIdPresupuesto(),
                    dtoTramite.getTipoDeTramite().getNombre(),
                    dtoTramite.getPresupuesto().getTotal(),
                    true
                };

                ((DefaultTableModel) this.grillaPresupuestos.getModel()).addRow(datos);

                this.getListaTramitesAsociados().add(dtoTramite);
            }

            this.grillaPresupuestos.setEnabled(false);

            for (Iterator<DtoPersona> itClientes = dtoGestion.getListaClientesInvolucrados().iterator(); itClientes.hasNext();)
            {
                DtoPersona dtoPersona = itClientes.next();

                if ((dtoPersona.getNombre().contains(dtoGestion.getClienteReferencia().getNombre()))
                        && (dtoPersona.getApellido().contains(dtoGestion.getClienteReferencia().getApellido())))
                {
                    // se pasa de largo, por que el cliente de referencia no debe estar en la lista de clientes asociados.                    
                }
                else
                {
                    Object[] datos =
                    {
                        dtoPersona.getNombre() + ", " + dtoPersona.getApellido()
                    };

                    ((DefaultTableModel) this.grillaClientesAsociados.getModel()).addRow(datos);

                    this.getListaClientesAsociados().add(dtoPersona);
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "La gestion seleccionada no es valida.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        Principal.removeVentanaActivas(ventanaModificarGestion);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
        salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonQuitarClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonQuitarClienteActionPerformed
    {//GEN-HEADEREND:event_botonQuitarClienteActionPerformed
        DefaultTableModel grilla = (DefaultTableModel) this.grillaClientesAsociados.getModel();

        try
        {
            int i = this.grillaClientesAsociados.getSelectedRow();

            // eliminamos de la lista
            DefaultTableModel modelo = ((DefaultTableModel) this.grillaClientesAsociados.getModel());
            String nombre = (String) modelo.getValueAt(i, 0);

            for (Iterator<DtoPersona> it = this.getListaClientesAsociados().iterator(); it.hasNext();)
            {
                DtoPersona dtoPersona = it.next();

                String nombreLista = dtoPersona.getNombre() + ", " + dtoPersona.getApellido();

                if (nombreLista.contains(nombre))
                {
                    this.getListaClientesAsociados().remove(dtoPersona);

                    this.listaClientesEliminados.add(dtoPersona);

                    break;
                }
            }
            // eliminamos de la grilla
            grilla.removeRow(i);
        }
        catch (NullPointerException | ArrayIndexOutOfBoundsException ex)
        {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun cliente", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonQuitarClienteActionPerformed

    private void botonAsociarClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAsociarClienteActionPerformed
    {//GEN-HEADEREND:event_botonAsociarClienteActionPerformed
        BuscarCliente miform = new BuscarCliente();
        BuscarCliente.setTipoBusqueda(ConstantesGui.MODIFICAR_GESTION_AGREGAR_CLIENTE);
        Principal.cargarFormulario(miform);
        Principal.setVentanasActivas(BuscarCliente.getVentanaBuscarCliente());
    }//GEN-LAST:event_botonAsociarClienteActionPerformed

    private void buscarGestionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscarGestionActionPerformed
    {//GEN-HEADEREND:event_buscarGestionActionPerformed
        BuscarGestion formBuscarGestion = new BuscarGestion();

        formBuscarGestion.setFormularioInvocador(ConstantesGui.MODIFICAR_GESTION);
        formBuscarGestion.setTipoBusqueda(ConstantesGui.MODIFICAR_GESTION);

        Principal.cargarFormulario(formBuscarGestion);
        Principal.setVentanasActivas(BuscarGestion.getVentanaBuscarGestion());
    }//GEN-LAST:event_buscarGestionActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAceptarActionPerformed
    {//GEN-HEADEREND:event_botonAceptarActionPerformed

        dtoGestionSeleccionada.setEncabezado(campoEncabezado.getText());
        dtoGestionSeleccionada.setObservaciones(campoObservaciones.getText());

        if (dtoGestionSeleccionada.isValido())
        {
            try
            {
                DtoGestionDeEscritura gestion = miController.modificarGestionDeEscritura(dtoGestionSeleccionada, this.listaClientesAgregados, this.listaClientesEliminados);
                if (gestion.getIdGestion() != ConstantesNegocio.ID_OBJETO_NO_VALIDO)
                {
                    JOptionPane.showMessageDialog(this, "Se ha modificado correctamente la gestion: " + dtoGestionSeleccionada.getNumero(), "Informacion", JOptionPane.INFORMATION_MESSAGE);
                    this.salir();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Error al intentar modificar la gestion indicada", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch (ClassModifiedException ex)
            {
                JOptionPane.showMessageDialog(this, "Alguien ha modificado la gestion indicada!", "Advertencia", JOptionPane.WARNING_MESSAGE);
                this.salir();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Alguno de los campo de gestion no es valido", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_botonAceptarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAsociarCliente;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonQuitarCliente;
    private javax.swing.JButton buscarGestion;
    private javax.swing.JTextArea campoEncabezado;
    private javax.swing.JTextField campoFechaInicio;
    private javax.swing.JTextField campoNumeroGestion;
    private javax.swing.JTextArea campoObservaciones;
    private javax.swing.JComboBox comboEscribanoACargo;
    private javax.swing.JTable grillaClientesAsociados;
    private javax.swing.JTable grillaPresupuestos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelNombreCliente;
    private javax.swing.JPanel panelModificarGestion;
    // End of variables declaration//GEN-END:variables
}
