/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.gestiones.gestion;

import com.licensis.notaire.dto.DtoGestionDeEscritura;
import com.licensis.notaire.dto.DtoHistorial;
import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import java.util.Iterator;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.licensis.notaire.negocio.ControllerNegocio;
import com.licensis.notaire.servicios.AdministradorReportes;

/**
 *
 * @author matias
 */
public class VerHistorialGestion extends javax.swing.JInternalFrame
{

    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem ventanaVerHistorialGestion = new JMenuItem("Ventana Ver Historial Gestion");
    private ControllerNegocio miController;
    private DtoGestionDeEscritura gestionSeleccionada;

    /**
     * Creates new form VerHistorialGestion
     */
    public VerHistorialGestion() {
        initComponents();
        estadoFormulario = Boolean.TRUE;
        this.setSize(Principal.tamanioGrandeHorizontal, Principal.tamanioNormalVertical);
        miController = ControllerNegocio.getInstancia();
        grillaGestionesCliente.setAutoCreateRowSorter(true);
    }

    public static JMenuItem getVentanaVerHistorialGestion() {
        return ventanaVerHistorialGestion;
    }

    private void salir() {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        panelVerHistorialGestion = new javax.swing.JPanel();
        botonCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonBuscarGestion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grillaGestionesCliente = new javax.swing.JTable();
        botonImprimirReporte = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Ver Historial Gestion");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/cerrar.png"))); // NOI18N
        botonCerrar.setText("Cerrar");
        botonCerrar.setIconTextGap(8);
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Ver Historial de Gestión");

        botonBuscarGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/buscar.png"))); // NOI18N
        botonBuscarGestion.setText("Buscar");
        botonBuscarGestion.setIconTextGap(10);
        botonBuscarGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarGestionActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar Gestión");

        labelCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Nombre Cliente:");

        grillaGestionesCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de Gestión", "Encabezado", "Estado", "Fecha Cambio", "Número Archivo", "Número Bibliorato", "Observaciones"
            }
        ));
        jScrollPane1.setViewportView(grillaGestionesCliente);

        botonImprimirReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/impresora.png"))); // NOI18N
        botonImprimirReporte.setText("Imprimir");
        botonImprimirReporte.setIconTextGap(8);
        botonImprimirReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImprimirReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVerHistorialGestionLayout = new javax.swing.GroupLayout(panelVerHistorialGestion);
        panelVerHistorialGestion.setLayout(panelVerHistorialGestionLayout);
        panelVerHistorialGestionLayout.setHorizontalGroup(
            panelVerHistorialGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerHistorialGestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVerHistorialGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVerHistorialGestionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonImprimirReporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCerrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                    .addGroup(panelVerHistorialGestionLayout.createSequentialGroup()
                        .addGroup(panelVerHistorialGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(panelVerHistorialGestionLayout.createSequentialGroup()
                                .addGroup(panelVerHistorialGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(29, 29, 29)
                                .addGroup(panelVerHistorialGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonBuscarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelVerHistorialGestionLayout.setVerticalGroup(
            panelVerHistorialGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVerHistorialGestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelVerHistorialGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(botonBuscarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelVerHistorialGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelVerHistorialGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonImprimirReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(panelVerHistorialGestion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCerrarActionPerformed
    {//GEN-HEADEREND:event_botonCerrarActionPerformed
        salir();
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(ventanaVerHistorialGestion);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonBuscarGestionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonBuscarGestionActionPerformed
    {//GEN-HEADEREND:event_botonBuscarGestionActionPerformed

        BuscarGestion formBuscarGestion = new BuscarGestion();
        formBuscarGestion.setFormularioInvocador(ConstantesGui.VER_HISTORIAL_GESTION);
        formBuscarGestion.setTipoBusqueda(ConstantesGui.VER_HISTORIAL_GESTION);

        Principal.cargarFormulario(formBuscarGestion);
        Principal.setVentanasActivas(BuscarGestion.getVentanaBuscarGestion());
    }//GEN-LAST:event_botonBuscarGestionActionPerformed

    private void botonImprimirReporteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonImprimirReporteActionPerformed
    {//GEN-HEADEREND:event_botonImprimirReporteActionPerformed
        if (gestionSeleccionada != null)
        {
            AdministradorReportes reportes = AdministradorReportes.getInstancia();
            reportes.generarReporteHistorialGestion(gestionSeleccionada);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ninguna gestion.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonImprimirReporteActionPerformed

    public void cargarGestion(DtoGestionDeEscritura gestion) {
        this.gestionSeleccionada = gestion;

        this.labelCliente.setText(gestion.getClienteReferencia().getNombre() + ", " + gestion.getClienteReferencia().getApellido());

        for (Iterator<DtoHistorial> itHistorial = gestion.getRegistroHistorial().iterator(); itHistorial.hasNext();)
        {
            DtoHistorial dtoHistorial = itHistorial.next();

            Object[] datos =
            {
                gestion.getNumero(),
                gestion.getEncabezado(),
                dtoHistorial.getEstadosDeGestion().getNombre(),
                dtoHistorial.getFecha(),
                gestion.getNumeroArchivo(),
                gestion.getNumeroBibliorato(),
                gestion.getObservaciones()
            };
            ((DefaultTableModel) grillaGestionesCliente.getModel()).addRow(datos);
        }


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarGestion;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonImprimirReporte;
    private javax.swing.JTable grillaGestionesCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JPanel panelVerHistorialGestion;
    // End of variables declaration//GEN-END:variables
}
