/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.escribanos;

import com.licensis.notaire.dto.DtoSuplencia;
import com.licensis.notaire.dto.GenericDto;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.servicios.AdministradorJpa;
import com.licensis.notaire.servicios.AdministradorValidaciones;
import com.licensis.notaire.servicios.GenericRestClient;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matias
 */
public class ConsultarSuplencias extends javax.swing.JInternalFrame
{

    private static JMenuItem ventaraConsultarSuplencias = new JMenu("Ventana Consultar Suplencias");

    /**
     * Creates new form ConsultarSuplencias
     */
    public ConsultarSuplencias()
    {
        initComponents();
        suplenciaClient = AdministradorJpa.getInstancia().getSuplenciaJpa();
        personaClient = AdministradorJpa.getInstancia().getPersonaJpa();
        this.setSize(Principal.tamanioGrandeHorizontal, Principal.tamanioGrandeVertical);
        this.grillaSuplencias.setAutoCreateRowSorter(true);
    }

    public static JMenuItem getVentaraConsultarSuplencias()
    {
        return ventaraConsultarSuplencias;
    }

    public static void setVentaraConsultarSuplencias(JMenuItem ventaraConsultarSuplencias)
    {
        ConsultarSuplencias.ventaraConsultarSuplencias = ventaraConsultarSuplencias;
    }

    public void salir()
    {
        this.dispose();
    }

    public void limpiarGrilla()
    {
        int i = ((DefaultTableModel) grillaSuplencias.getModel()).getRowCount() - 1;

        while (((DefaultTableModel) grillaSuplencias.getModel()).getRowCount() > 0)
        {
            ((DefaultTableModel) grillaSuplencias.getModel()).removeRow(i);
            i--;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelConsultarSuplencias = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        selectorAnio = new com.toedter.calendar.JYearChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        grillaSuplencias = new javax.swing.JTable();
        botonCerrar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelTitulo.setText("Consultar Suplencias");

        jLabel1.setText("Indicar Periodo:");

        grillaSuplencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Suplantado", "Suplente", "Fecha Inicio", "Fecha Fin", "Observaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(grillaSuplencias);

        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar.png"))); // NOI18N
        botonCerrar.setText("Cerrar");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConsultarSuplenciasLayout = new javax.swing.GroupLayout(panelConsultarSuplencias);
        panelConsultarSuplencias.setLayout(panelConsultarSuplenciasLayout);
        panelConsultarSuplenciasLayout.setHorizontalGroup(
            panelConsultarSuplenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarSuplenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsultarSuplenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                    .addGroup(panelConsultarSuplenciasLayout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarSuplenciasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConsultarSuplenciasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(selectorAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelConsultarSuplenciasLayout.setVerticalGroup(
            panelConsultarSuplenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarSuplenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConsultarSuplenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultarSuplenciasLayout.createSequentialGroup()
                        .addGroup(panelConsultarSuplenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(selectorAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConsultarSuplenciasLayout.createSequentialGroup()
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(panelConsultarSuplencias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        this.salir();
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed

        this.limpiarGrilla();

        int anio = this.selectorAnio.getYear();

        Calendar fechaDesde = new GregorianCalendar(anio, 1, 1);
        Calendar fechaHasta = new GregorianCalendar(anio, 12, 31);

        if (AdministradorValidaciones.getInstancia().validarFechaAnioLimite(fechaHasta.getTime()))
        {

            Date fechaDesdeDate = fechaDesde.getTime();
            Date fechaHastaDate = fechaHasta.getTime();

            try
            {
                // Obtener todas las suplencias y filtrar por fecha
                List<GenericDto> todasLasSuplencias = suplenciaClient.findAll();
                List<GenericDto> suplenciasFiltradas = new java.util.ArrayList<>();
                
                // Filtrar por rango de fechas
                for (GenericDto suplencia : todasLasSuplencias)
                {
                    Date fechaInicio = (Date) suplencia.get("fechaInicio");
                    if (fechaInicio != null && fechaInicio.compareTo(fechaDesdeDate) >= 0 && fechaInicio.compareTo(fechaHastaDate) <= 0)
                    {
                        suplenciasFiltradas.add(suplencia);
                    }
                }

                if (!suplenciasFiltradas.isEmpty())
                {
                    // Obtener todas las personas para poder mostrar nombres
                    List<GenericDto> todasLasPersonas = personaClient.findAll();
                    java.util.Map<Integer, GenericDto> personasMap = new java.util.HashMap<>();
                    for (GenericDto persona : todasLasPersonas)
                    {
                        Integer id = persona.getInt("idPersona");
                        if (id != null)
                        {
                            personasMap.put(id, persona);
                        }
                    }
                    
                    for (Iterator<GenericDto> it = suplenciasFiltradas.iterator(); it.hasNext();)
                    {
                        GenericDto dtoSuplencia = it.next();

                        Integer idSuplantado = dtoSuplencia.getInt("fkIdSuplantado");
                        Integer idSuplente = dtoSuplencia.getInt("fkIdSuplente");
                        
                        String nombreSuplantado = "N/A";
                        String nombreSuplente = "N/A";
                        
                        if (idSuplantado != null && personasMap.containsKey(idSuplantado))
                        {
                            GenericDto personaSuplantado = personasMap.get(idSuplantado);
                            nombreSuplantado = personaSuplantado.getString("nombre") + ", " + personaSuplantado.getString("apellido");
                        }
                        if (idSuplente != null && personasMap.containsKey(idSuplente))
                        {
                            GenericDto personaSuplente = personasMap.get(idSuplente);
                            nombreSuplente = personaSuplente.getString("nombre") + ", " + personaSuplente.getString("apellido");
                        }

                        Date fechaInicio = (Date) dtoSuplencia.get("fechaInicio");
                        Date fechaFin = (Date) dtoSuplencia.get("fechaFin");
                        String observaciones = dtoSuplencia.getString("observaciones");

                        Object[] datos =
                        {
                            nombreSuplantado,
                            nombreSuplente,
                            fechaInicio != null ? fechaInicio.toString() : "",
                            fechaFin != null ? fechaFin.toString() : "",
                            observaciones != null ? observaciones : ""
                        };

                        ((DefaultTableModel) grillaSuplencias.getModel()).addRow(datos);
                    }
                } else
                {
                    JOptionPane.showMessageDialog(this, "No existen suplencias registradas para el periodo indicado,", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            }
            catch (IOException ex)
            {
                JOptionPane.showMessageDialog(this, "Error al cargar suplencias: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                logger.log(Level.SEVERE, "Error al consultar suplencias", ex);
            }
        } else
        {
            JOptionPane.showMessageDialog(this, "El año indicado no puede ser superior al año actual", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonBuscarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JTable grillaSuplencias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelConsultarSuplencias;
    private com.toedter.calendar.JYearChooser selectorAnio;
    // End of variables declaration//GEN-END:variables
}
