/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.gestiones.inscripciones;

import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.gui.gestiones.escrituras.BuscarEscritura;
import javax.swing.JMenuItem;

/**
 *
 * @author matias
 */
public class Inscripciones extends javax.swing.JInternalFrame
{

    private static Inscripciones instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem submenuInscripciones = new JMenuItem("Sub-modulo Inscripciones");

    /**
     * Creates new form Inscripciones
     */
    private Inscripciones() {
        initComponents();
    }

    public static Inscripciones getInstancia() {
        if (instancia == null)
        {
            instancia = new Inscripciones();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);

        }
        return instancia;
    }

    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario) {
        Inscripciones.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getSubmenuInscripciones() {
        return submenuInscripciones;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonIngresarParaInscribir = new javax.swing.JButton();
        botonRegistrarReingreso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonRegistrarInscripcion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Sub-modulo Inscripciones");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonIngresarParaInscribir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/inscripciones/ingresarInscribir.png"))); // NOI18N
        botonIngresarParaInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarParaInscribirActionPerformed(evt);
            }
        });

        botonRegistrarReingreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/inscripciones/registrarReingresoInscripcion.png"))); // NOI18N
        botonRegistrarReingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarReingresoActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("<HTML>Ingresar para <BR>Inscripción</HTML>");

        jLabel2.setText("Registrar Reingreso");

        botonRegistrarInscripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/inscripciones/registrarInscripcion.png"))); // NOI18N
        botonRegistrarInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarInscripcionActionPerformed(evt);
            }
        });

        jLabel3.setText("Registrar Inscripción");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonIngresarParaInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonRegistrarReingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(botonRegistrarInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonIngresarParaInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonRegistrarReingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonRegistrarInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addGap(94, 264, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(submenuInscripciones);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonIngresarParaInscribirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonIngresarParaInscribirActionPerformed
    {//GEN-HEADEREND:event_botonIngresarParaInscribirActionPerformed
        BuscarEscritura formBuscarEscritura = new BuscarEscritura();
        formBuscarEscritura.setFormularioInvocador(ConstantesGui.INGRESAR_PARA_INSCRIPCION);
        Principal.cargarFormulario(formBuscarEscritura);
        Principal.setVentanasActivas(BuscarEscritura.getVentanaBuscarEscritura());
    }//GEN-LAST:event_botonIngresarParaInscribirActionPerformed

    private void botonRegistrarReingresoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonRegistrarReingresoActionPerformed
    {//GEN-HEADEREND:event_botonRegistrarReingresoActionPerformed
        BuscarEscritura formBuscarEscritura = new BuscarEscritura();
        formBuscarEscritura.setFormularioInvocador(ConstantesGui.REGISTRAR_REINGRESO);
        Principal.cargarFormulario(formBuscarEscritura);
        Principal.setVentanasActivas(BuscarEscritura.getVentanaBuscarEscritura());
    }//GEN-LAST:event_botonRegistrarReingresoActionPerformed

    private void botonRegistrarInscripcionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonRegistrarInscripcionActionPerformed
    {//GEN-HEADEREND:event_botonRegistrarInscripcionActionPerformed
        BuscarEscritura formBuscarEscritura = new BuscarEscritura();
        formBuscarEscritura.setFormularioInvocador(ConstantesGui.REGISTRAR_INSCRIPCION);
        Principal.cargarFormulario(formBuscarEscritura);
        Principal.setVentanasActivas(BuscarEscritura.getVentanaBuscarEscritura());
    }//GEN-LAST:event_botonRegistrarInscripcionActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresarParaInscribir;
    private javax.swing.JButton botonRegistrarInscripcion;
    private javax.swing.JButton botonRegistrarReingreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
