package com.licensis.notaire.dto;
// Generated 19/04/2012 16:59:26 by Hibernate Tools 3.2.1.GA

import com.licensis.notaire.dto.interfaces.DtoValido;
import java.util.HashSet;
import java.util.Set;

/**
 * DtoTipoDeFolio generated by hbm2java
 */
public class DtoFolioType implements DtoValido {

    private Integer idFolioType;
    private String name;
    private String notes;
    private Set folios = new HashSet(0);
    private boolean enabled;
    private boolean isAuxiliary;
    private Integer version;

    public DtoFolioType() {
        this.version = 0;
    }

    public DtoFolioType(String name) {
        this.name = name;
    }

    public DtoFolioType(String name, String notes, Set folioses) {
        this.name = name;
        this.notes = notes;
        this.folios = folioses;
    }

    public Integer getIdFolioType() {
        return this.idFolioType;
    }

    public void setIdFolioType(Integer idFolioType) {
        this.idFolioType = idFolioType;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Set getFolios() {
        return this.folios;
    }

    public void setFolios(Set folios) {
        this.folios = folios;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public boolean isIsAuxiliary() {
        return isAuxiliary;
    }

    public void setIsAuxiliary(boolean isAuxiliary) {
        this.isAuxiliary = isAuxiliary;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Override
    public Boolean isValido() {
        return true;
    }
}
