/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.escribanos;

import com.licensis.notaire.dto.DtoPersona;
import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.gui.clientes.BuscarCliente;
import java.awt.Dimension;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import com.licensis.notaire.jpa.exceptions.ClassModifiedException;
import com.licensis.notaire.negocio.ControllerNegocio;

/**
 *
 * @author matias
 */
public class DarAltaEscribano extends javax.swing.JInternalFrame
{

    private static JMenuItem ventanaDarAltaEscribano = new JMenuItem("Ventana Dar de Alta Escribano");
    private DtoPersona dtoNuevoEscribano = null;

    /**
     * Creates new form DarAltaEscribano
     */
    public DarAltaEscribano() {
        initComponents();
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        this.setMinimumSize(new Dimension(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical));
    }

    public static JMenuItem getVentanaDarAltaEscribano() {
        return ventanaDarAltaEscribano;
    }

    private void salir() {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelDarAltaEscribano = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoApellido = new javax.swing.JTextField();
        comboTipoIdentificacion = new javax.swing.JComboBox();
        campoTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoNumeroIdentificacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        campoRegistroEscribano = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botonBuscarPersona = new javax.swing.JButton();
        labelBuscar = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Dar de Alta Escribano");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelTitulo.setText("Dar de Alta Escribano");

        campoEmail.setEnabled(false);

        jLabel6.setText("Teléfono:");

        campoNombre.setEnabled(false);

        jLabel7.setText("E-Mail:");

        jLabel3.setText("Apellido");

        jLabel2.setText("Nombre:");

        campoApellido.setEnabled(false);

        comboTipoIdentificacion.setEnabled(false);

        campoTelefono.setEnabled(false);

        jLabel4.setText("Tipo Ident.:");

        campoNumeroIdentificacion.setEnabled(false);

        jLabel5.setText("Número Ident.:");

        jLabel9.setText("Número de Registro de Escribano:");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonBuscarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/buscar.png"))); // NOI18N
        botonBuscarPersona.setText("Buscar");
        botonBuscarPersona.setIconTextGap(10);
        botonBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarPersonaActionPerformed(evt);
            }
        });

        labelBuscar.setText("Buscar Persona:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(botonBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBuscar)))
        );

        javax.swing.GroupLayout panelDarAltaEscribanoLayout = new javax.swing.GroupLayout(panelDarAltaEscribano);
        panelDarAltaEscribano.setLayout(panelDarAltaEscribanoLayout);
        panelDarAltaEscribanoLayout.setHorizontalGroup(
            panelDarAltaEscribanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDarAltaEscribanoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDarAltaEscribanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDarAltaEscribanoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDarAltaEscribanoLayout.createSequentialGroup()
                        .addGroup(panelDarAltaEscribanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelDarAltaEscribanoLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(campoRegistroEscribano))
                            .addGroup(panelDarAltaEscribanoLayout.createSequentialGroup()
                                .addGroup(panelDarAltaEscribanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(panelDarAltaEscribanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelDarAltaEscribanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(campoApellido)
                                        .addComponent(comboTipoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoTelefono)
                                        .addComponent(campoEmail)
                                        .addComponent(campoNumeroIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(labelTitulo)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE))
                        .addGap(0, 140, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDarAltaEscribanoLayout.setVerticalGroup(
            panelDarAltaEscribanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDarAltaEscribanoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDarAltaEscribanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDarAltaEscribanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelDarAltaEscribanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTipoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDarAltaEscribanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNumeroIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDarAltaEscribanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDarAltaEscribanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(panelDarAltaEscribanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoRegistroEscribano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(panelDarAltaEscribanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(panelDarAltaEscribano);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarPersonaActionPerformed
        BuscarCliente miform = BuscarCliente.getInstancia();
        miform.setTipoBusqueda(ConstantesGui.DAR_ALTA_ESCRIBANO);
        Principal.cargarFormulario(miform);
        Principal.setVentanasActivas(BuscarCliente.getVentanaBuscarCliente());
    }//GEN-LAST:event_botonBuscarPersonaActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        Principal.removeVentanaActivas(ventanaDarAltaEscribano);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAceptarActionPerformed
    {//GEN-HEADEREND:event_botonAceptarActionPerformed

        try
        {
            int registro = Integer.parseInt(campoRegistroEscribano.getText());

            dtoNuevoEscribano.setRegistroEscribano(registro);

            if (dtoNuevoEscribano.isValido())
            {
                try
                {
                    if (ControllerNegocio.getInstancia().darAltaEscribano(dtoNuevoEscribano) == Boolean.TRUE)
                    {
                        switch (labelTitulo.getText())
                        {
                            case ConstantesGui.DAR_ALTA_ESCRIBANO:
                            {
                                JOptionPane.showMessageDialog(this, "Se ha " + labelTitulo.getText() + ": " + dtoNuevoEscribano.getNombre());
                                this.salir();
                                break;
                            }
                            case ConstantesGui.MODIFICAR_ESCRIBANO:
                            {
                                JOptionPane.showMessageDialog(this, "Se ha " + labelTitulo.getText() + ": " + dtoNuevoEscribano.getNombre());
                                this.salir();
                                break;
                            }
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Error al intentar dar de alta un nuevo escribano", "Error", JOptionPane.ERROR_MESSAGE);
                        this.salir();
                    }
                }
                catch (ClassModifiedException ex)
                {
                    JOptionPane.showMessageDialog(this, "El persona que desea registrar como escribano ha sido modificado por otro usuario", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    this.salir();
                }

            }
            else
            {
                JOptionPane.showMessageDialog(this, "Alguno de los datos en pantalla es incorrecto", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "El valor de registro de escribano no es valido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
        this.salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    public void cargarEscribano(DtoPersona dtoPersonaEscribano, String tituloLabel) {
        this.labelTitulo.setText(tituloLabel);

        if (tituloLabel.contains(ConstantesGui.DAR_ALTA_ESCRIBANO))
        {
            this.labelBuscar.setVisible(true);
            this.botonBuscarPersona.setVisible(true);
        }
        else
        {
            this.labelBuscar.setVisible(false);
            this.botonBuscarPersona.setVisible(false);
        }
        
        if (dtoPersonaEscribano.isValido())
        {

            campoNombre.setText(dtoPersonaEscribano.getNombre());
            campoApellido.setText(dtoPersonaEscribano.getApellido());
            comboTipoIdentificacion.addItem(dtoPersonaEscribano.getDtoTipoIdentificacion().getNombre());
            campoNumeroIdentificacion.setText(dtoPersonaEscribano.getNumeroIdentificacion());
            campoTelefono.setText(dtoPersonaEscribano.getTelefono());
            campoEmail.setText(dtoPersonaEscribano.getEmail());

            if (this.labelTitulo.getText().contains(ConstantesGui.MODIFICAR_ESCRIBANO))
            {
                campoRegistroEscribano.setText(dtoPersonaEscribano.getRegistroEscribano().toString());
            }

            dtoNuevoEscribano = dtoPersonaEscribano;
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Los datos de la persona indicada no son validos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonBuscarPersona;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoNumeroIdentificacion;
    private javax.swing.JTextField campoRegistroEscribano;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JComboBox comboTipoIdentificacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelDarAltaEscribano;
    // End of variables declaration//GEN-END:variables
}
