/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.escribanos;

import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.gui.clientes.BuscarCliente;
import java.awt.Dimension;
import javax.swing.JMenuItem;

/**
 *
 * @author matias
 */
public class Escribanos extends javax.swing.JInternalFrame
{

    private static Escribanos instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem submenuEscribanos = new JMenuItem("Sub-Modulo Escribanos");

    /**
     * Creates new form Escribanos
     */
    private Escribanos() {
        initComponents();
    }

    public static Escribanos getInstancia() {
        if (instancia == null)
        {
            instancia = new Escribanos();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
            instancia.setMinimumSize(new Dimension(Principal.tamanioMinimoHorizontal, Principal.tamanioMinimoVertical));
        }
        return instancia;
    }

    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario) {
        Escribanos.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getSubmenuEscribanos() {
        return submenuEscribanos;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonDarAltaEscribano = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonRegistrarSuplencia = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botonModificarEscribano = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        botonConsultarSuplencias = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Sub-Modulo Escribanos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonDarAltaEscribano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/administracion/escribanos/altaEscribano.png"))); // NOI18N
        botonDarAltaEscribano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDarAltaEscribanoActionPerformed(evt);
            }
        });

        jLabel1.setText("Dar Alta Escribano");

        botonRegistrarSuplencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/administracion/escribanos/registrarSuplencia.png"))); // NOI18N
        botonRegistrarSuplencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarSuplenciaActionPerformed(evt);
            }
        });

        jLabel2.setText("Registrar Suplencia");

        botonModificarEscribano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/administracion/escribanos/modificarEscribano.png"))); // NOI18N
        botonModificarEscribano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarEscribanoActionPerformed(evt);
            }
        });

        jLabel3.setText("Modificar Escribano");

        botonConsultarSuplencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/administracion/escribanos/consultarSuplencias.png"))); // NOI18N
        botonConsultarSuplencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarSuplenciasActionPerformed(evt);
            }
        });

        jLabel4.setText("Consultar Suplencias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonDarAltaEscribano, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(botonModificarEscribano, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonRegistrarSuplencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(botonConsultarSuplencias, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonConsultarSuplencias, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonModificarEscribano, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addComponent(botonRegistrarSuplencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonDarAltaEscribano, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(315, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(submenuEscribanos);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonDarAltaEscribanoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonDarAltaEscribanoActionPerformed
    {//GEN-HEADEREND:event_botonDarAltaEscribanoActionPerformed

        BuscarCliente miform = BuscarCliente.getInstancia();
        miform.setTipoBusqueda(ConstantesGui.DAR_ALTA_ESCRIBANO);
        Principal.cargarFormulario(miform);
        Principal.setVentanasActivas(BuscarCliente.getVentanaBuscarCliente());
    }//GEN-LAST:event_botonDarAltaEscribanoActionPerformed

    private void botonRegistrarSuplenciaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonRegistrarSuplenciaActionPerformed
    {//GEN-HEADEREND:event_botonRegistrarSuplenciaActionPerformed
        Principal.cargarFormulario(new RegistrarSuplencia());
        Principal.setVentanasActivas(RegistrarSuplencia.getVentanaRegistrarSuplencia());
    }//GEN-LAST:event_botonRegistrarSuplenciaActionPerformed

    private void botonModificarEscribanoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonModificarEscribanoActionPerformed
    {//GEN-HEADEREND:event_botonModificarEscribanoActionPerformed
        BuscarCliente miForm = BuscarCliente.getInstancia();
        miForm.setTipoBusqueda(ConstantesGui.MODIFICAR_ESCRIBANO);
        Principal.cargarFormulario(miForm);
        Principal.setVentanasActivas(BuscarCliente.getVentanaBuscarCliente());
    }//GEN-LAST:event_botonModificarEscribanoActionPerformed

    private void botonConsultarSuplenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarSuplenciasActionPerformed
        Principal.cargarFormulario(new ConsultarSuplencias());
        Principal.setVentanasActivas(ConsultarSuplencias.getVentaraConsultarSuplencias());        
    }//GEN-LAST:event_botonConsultarSuplenciasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultarSuplencias;
    private javax.swing.JButton botonDarAltaEscribano;
    private javax.swing.JButton botonModificarEscribano;
    private javax.swing.JButton botonRegistrarSuplencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
