/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.escribanos;

import com.licensis.notaire.dto.DtoPersona;
import com.licensis.notaire.dto.DtoSuplencia;
import com.licensis.notaire.gui.Principal;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import com.licensis.notaire.negocio.ControllerNegocio;

/**
 *
 * @author matias
 */
public class RegistrarSuplencia extends javax.swing.JInternalFrame
{

    private static JMenuItem ventanaRegistrarSuplencia = new JMenuItem("Ventana Registrar Suplencia");
    private ControllerNegocio miControllerNegocio = null;
    private List<DtoPersona> miListaDtoEscribanos = null;
    private DtoPersona dtoEscribanoSuplantado = null;
    private DtoPersona dtoEscribanoSuplente = null;
    private int cantidadSelecciones = 0;
    private static final Integer CAMPO_ESCRIBANO_SUPLANTADO = 0;
    private static final Integer CAMPO_ESCRIBANO_SUPLENTE = 1;

    /**
     * Creates new form RegistrarSuplencia
     */
    public RegistrarSuplencia() {
        initComponents();
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        miControllerNegocio = ControllerNegocio.getInstancia();
        this.cargarGrilla();
        grillaEscribanosDisponibles.setAutoCreateRowSorter(true);

        this.labelMensajeSuplencia.setText("Favor seleccionar el Escribano Suplantado:");
    }

    private void salir() {
        this.dispose();
    }

    public static JMenuItem getVentanaRegistrarSuplencia() {
        return ventanaRegistrarSuplencia;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        panelRegistrarSuplencia = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grillaEscribanosDisponibles = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        botonSeleccionar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        selectorFechaDesde = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        selectorFechaHasta = new com.toedter.calendar.JDateChooser();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoObservaciones = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campoEscribanoSuplantado = new javax.swing.JTextField();
        campoEscribanoSuplente = new javax.swing.JTextField();
        labelMensajeSuplencia = new javax.swing.JLabel();
        botonDeseleccionar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Registrar Suplencia");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Registrar Suplencia");

        jLabel2.setText("Lista Escribanos Disponibles:");

        grillaEscribanosDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Número Registro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grillaEscribanosDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grillaEscribanosDisponiblesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grillaEscribanosDisponibles);

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel3.setText("Período Licencia:");

        botonSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/aceptar.png"))); // NOI18N
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        jLabel4.setText("Desde:");

        jLabel5.setText("Hasta (inclusive):");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        campoObservaciones.setColumns(20);
        campoObservaciones.setRows(5);
        jScrollPane2.setViewportView(campoObservaciones);

        jLabel7.setText("Observaciones:");

        jLabel8.setText("Escribano Suplantado:");

        jLabel9.setText("Escribano Suplente:");

        campoEscribanoSuplantado.setEditable(false);

        campoEscribanoSuplente.setEditable(false);

        labelMensajeSuplencia.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botonDeseleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/borrar.png"))); // NOI18N
        botonDeseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDeseleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegistrarSuplenciaLayout = new javax.swing.GroupLayout(panelRegistrarSuplencia);
        panelRegistrarSuplencia.setLayout(panelRegistrarSuplenciaLayout);
        panelRegistrarSuplenciaLayout.setHorizontalGroup(
            panelRegistrarSuplenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarSuplenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegistrarSuplenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrarSuplenciaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistrarSuplenciaLayout.createSequentialGroup()
                        .addGroup(panelRegistrarSuplenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRegistrarSuplenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelRegistrarSuplenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegistrarSuplenciaLayout.createSequentialGroup()
                                        .addGroup(panelRegistrarSuplenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel8)
                                            .addComponent(campoEscribanoSuplantado, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(jLabel4)
                                            .addComponent(selectorFechaDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelRegistrarSuplenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(selectorFechaHasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(campoEscribanoSuplente)
                                            .addGroup(panelRegistrarSuplenciaLayout.createSequentialGroup()
                                                .addGroup(panelRegistrarSuplenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel5))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelRegistrarSuplenciaLayout.createSequentialGroup()
                                    .addComponent(labelMensajeSuplencia, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonDeseleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 74, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRegistrarSuplenciaLayout.setVerticalGroup(
            panelRegistrarSuplenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarSuplenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistrarSuplenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMensajeSuplencia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDeseleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(panelRegistrarSuplenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrarSuplenciaLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoEscribanoSuplantado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrarSuplenciaLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoEscribanoSuplente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelRegistrarSuplenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrarSuplenciaLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectorFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistrarSuplenciaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectorFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(panelRegistrarSuplenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane3.setViewportView(panelRegistrarSuplencia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        Principal.removeVentanaActivas(RegistrarSuplencia.ventanaRegistrarSuplencia);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAceptarActionPerformed
    {//GEN-HEADEREND:event_botonAceptarActionPerformed

        Date fechaDesde = selectorFechaDesde.getDate();
        Date fechaHasta = selectorFechaHasta.getDate();

        DtoSuplencia nuevaSuplencia = new DtoSuplencia();
        nuevaSuplencia.setFechaInicio(fechaDesde);
        nuevaSuplencia.setFechaFin(fechaHasta);
        nuevaSuplencia.setObservaciones(campoObservaciones.getText());
        nuevaSuplencia.setPersonasByFkIdSuplente(dtoEscribanoSuplente);
        nuevaSuplencia.setPersonasByFkIdSuplantado(dtoEscribanoSuplantado);

        if (nuevaSuplencia.isValido())
        {
            if (miControllerNegocio.registrarSuplenciaEscribano(nuevaSuplencia) == Boolean.TRUE)
            {
                JOptionPane.showMessageDialog(this, "<HTML>Se ha registrado una suplencia de Escribano:"
                        + "<BR> " + dtoEscribanoSuplantado.getNombre() + " " + dtoEscribanoSuplantado.getApellido()
                        + " por " + dtoEscribanoSuplente.getNombre() + " " + dtoEscribanoSuplente.getApellido()
                        + "</HTML>");
                salir();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error al registrar suplencia", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Alguno de los datos ingresados no es valido", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
        salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonSeleccionarActionPerformed
    {//GEN-HEADEREND:event_botonSeleccionarActionPerformed

        if (this.cantidadSelecciones == CAMPO_ESCRIBANO_SUPLENTE)
        {
            this.labelMensajeSuplencia.setText("Favor seleccionar al escribano suplente:");
        }
        else if (this.cantidadSelecciones == CAMPO_ESCRIBANO_SUPLANTADO)
        {
            this.labelMensajeSuplencia.setText("Favor seleccionar el Escribano Suplantado:");
        }

        TableModel miGrilla = grillaEscribanosDisponibles.getModel();
        int filaGrilla = grillaEscribanosDisponibles.getSelectedRow();
        filaGrilla = grillaEscribanosDisponibles.convertRowIndexToModel(filaGrilla);

        try
        {
            int registroEscribano = (int) (grillaEscribanosDisponibles.getModel()).getValueAt(filaGrilla, 1);

            for (Iterator<DtoPersona> it = miListaDtoEscribanos.iterator(); it.hasNext();)
            {
                DtoPersona dtoEscribano = it.next();

                if (dtoEscribano.getRegistroEscribano() == registroEscribano)
                {

                    if (this.cantidadSelecciones == CAMPO_ESCRIBANO_SUPLANTADO)
                    {
                        this.campoEscribanoSuplantado.setText(dtoEscribano.getNombre()
                                + " "
                                + dtoEscribano.getApellido());
                        this.cantidadSelecciones = CAMPO_ESCRIBANO_SUPLENTE;
                        this.labelMensajeSuplencia.setText("Favor seleccionar el Escribano Suplente:");
                        this.dtoEscribanoSuplantado = dtoEscribano;
                    }
                    else
                    {
                        if (this.dtoEscribanoSuplantado.getRegistroEscribano() == dtoEscribano.getRegistroEscribano())
                        {
                            JOptionPane.showMessageDialog(this, "El escribano suplente y suplantado, son inguales. Favor seleccionar otro", "Advertencia", JOptionPane.WARNING_MESSAGE);
                        }
                        else
                        {
                            this.campoEscribanoSuplente.setText(dtoEscribano.getNombre()
                                    + " "
                                    + dtoEscribano.getApellido());
                            //  volvemos a cero.
                            this.cantidadSelecciones = CAMPO_ESCRIBANO_SUPLANTADO;
                            this.labelMensajeSuplencia.setText("");
                            this.dtoEscribanoSuplente = dtoEscribano;
                        }
                    }
                    break;
                }
            }


        }
        catch (ArrayIndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(this, "No ha seleccionado un elemento valido o la lista esta vacia", "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch (NumberFormatException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    private void botonDeseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDeseleccionarActionPerformed
        this.campoEscribanoSuplantado.setText("");
        this.campoEscribanoSuplente.setText("");
        this.selectorFechaDesde.cleanup();
        this.selectorFechaHasta.cleanup();
        this.campoObservaciones.setText("");
        this.cantidadSelecciones = CAMPO_ESCRIBANO_SUPLANTADO;
    }//GEN-LAST:event_botonDeseleccionarActionPerformed

    private void grillaEscribanosDisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grillaEscribanosDisponiblesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_grillaEscribanosDisponiblesMouseClicked

    public void cargarGrilla() {
        try
        {
            miListaDtoEscribanos = miControllerNegocio.obtenerListaEscribanosDisponibles();

            if (miListaDtoEscribanos.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "No hay escribanos registrados", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                for (Iterator<DtoPersona> it = miListaDtoEscribanos.iterator(); it.hasNext();)
                {
                    DtoPersona dtoEscribano = it.next();

                    Object[] datos =
                    {
                        dtoEscribano.getNombre() + " " + dtoEscribano.getApellido(),
                        dtoEscribano.getRegistroEscribano()
                    };

                    ((DefaultTableModel) grillaEscribanosDisponibles.getModel()).addRow(datos);
                }
            }
        }
        catch (NullPointerException e)
        {
            JOptionPane.showMessageDialog(this, "No existen escribanos registrados", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonDeseleccionar;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JTextField campoEscribanoSuplantado;
    private javax.swing.JTextField campoEscribanoSuplente;
    private javax.swing.JTextArea campoObservaciones;
    private javax.swing.JTable grillaEscribanosDisponibles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelMensajeSuplencia;
    private javax.swing.JPanel panelRegistrarSuplencia;
    private com.toedter.calendar.JDateChooser selectorFechaDesde;
    private com.toedter.calendar.JDateChooser selectorFechaHasta;
    // End of variables declaration//GEN-END:variables
}
