/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.usuarios;

import com.licensis.notaire.gui.Principal;
import java.awt.Dimension;
import javax.swing.JMenuItem;

/**
 *
 * @author matias
 */
public class Usuarios extends javax.swing.JInternalFrame
{

    private static Usuarios instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem submenuUsuarios = new JMenuItem("Sub-Modulo Usuarios");

    /**
     * Creates new form Usuarios
     */
    private Usuarios()
    {
        initComponents();
    }

    public static Usuarios getInstancia()
    {
        if (instancia == null)
        {
            instancia = new Usuarios();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
            instancia.setMinimumSize(new Dimension(Principal.tamanioMinimoHorizontal, Principal.tamanioMinimoVertical));
        }
        return instancia;
    }

    public static Boolean getEstadoFormulario()
    {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario)
    {
        Usuarios.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getSubmenuUsuarios()
    {
        return submenuUsuarios;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonDarAltaUsuario = new javax.swing.JButton();
        botonModificarUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonActividadesUsuario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Sub-Modulo Usuarios");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonDarAltaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/administracion/usuarios/altaUsuario.png"))); // NOI18N
        botonDarAltaUsuario.setToolTipText("Dar Alta Usuario");
        botonDarAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDarAltaUsuarioActionPerformed(evt);
            }
        });

        botonModificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/administracion/usuarios/modificarUsuario.png"))); // NOI18N
        botonModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Dar Alta Usuario");

        jLabel2.setText("Modificar Usuario");

        botonActividadesUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/administracion/usuarios/actividadesUsuario.png"))); // NOI18N
        botonActividadesUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActividadesUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Actividades de Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonDarAltaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(botonActividadesUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonActividadesUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonDarAltaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addContainerGap(299, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(submenuUsuarios);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonDarAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonDarAltaUsuarioActionPerformed
    {//GEN-HEADEREND:event_botonDarAltaUsuarioActionPerformed
        DarAltaUsuario formAltaUsuario = DarAltaUsuario.getInstancia();
        formAltaUsuario.limpiarFormulario();
        formAltaUsuario.desabilitarFormulario();
        Principal.cargarFormulario(formAltaUsuario);
        Principal.setVentanasActivas(DarAltaUsuario.getInstancia().getVentanaDarAltaUsuario());
    }//GEN-LAST:event_botonDarAltaUsuarioActionPerformed

    private void botonModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonModificarUsuarioActionPerformed
    {//GEN-HEADEREND:event_botonModificarUsuarioActionPerformed

        ModificarUsuario formModificarUsuario = ModificarUsuario.getInstancia();
        formModificarUsuario.limpiarFormulario();
        try
        {
            formModificarUsuario.cargarUsuariosDisponibles();
            formModificarUsuario.desabilitarFormulario();
        }
        catch (Exception ex)
        {
            System.out.println("Erxception  Usuarios - cargarUsuarioDispoibles() ");
        }
        Principal.cargarFormulario(formModificarUsuario);
        Principal.setVentanasActivas(ModificarUsuario.getInstancia().getVentanaModificarUsuario());
    }//GEN-LAST:event_botonModificarUsuarioActionPerformed

    private void botonActividadesUsuarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonActividadesUsuarioActionPerformed
    {//GEN-HEADEREND:event_botonActividadesUsuarioActionPerformed
        ActividadUsuario formActividadesUsuario = ActividadUsuario.getInstancia();
        formActividadesUsuario.limpiarFormulario();

        try
        {
            formActividadesUsuario.cargarUsuariosDisponibles();
        }
        catch (Exception ex)
        {
            System.out.println("Exception Usuarios - cargarUsuariosDisponibles");
        }
        Principal.cargarFormulario(formActividadesUsuario);
        Principal.setVentanasActivas(ActividadUsuario.getInstancia().getVentanaActividadUsuario());
    }//GEN-LAST:event_botonActividadesUsuarioActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActividadesUsuario;
    private javax.swing.JButton botonDarAltaUsuario;
    private javax.swing.JButton botonModificarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
