package com.licensis.notaire.dto;
// Generated 19/04/2012 16:59:26 by Hibernate Tools 3.2.1.GA

import com.licensis.notaire.dto.interfaces.DtoValido;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import com.licensis.notaire.servicios.AdministradorValidaciones;

/**
 * DtoPersona generated by hbm2java
 */
public class DtoPersona implements DtoValido
{

    private Integer idPersona;
    private String nombre;
    private String apellido;
    private String nacionalidad;
    private String cuit;
    private String sexo;
    private Date fechaNacimiento;
    private String estadoCivil;
    private Integer numeroNupcias;
    private String ocupacion;
    private String domicilio;
    private String telefono;
    private Integer registroEscribano;
    private boolean esCliente;
    private String numeroidentificacion;
    private String eMail;
    private DtoTipoIdentificacion dtoTipoIdentificacion = null;
    private Integer version;
    private ArrayList<DtoGestionDeEscritura> listDtoGestionDeEscriturasEscribano = new ArrayList<DtoGestionDeEscritura>();
    private ArrayList<DtoGestionDeEscritura> listaDtoGestionDeEscriturasPersona = new ArrayList<DtoGestionDeEscritura>();
    private ArrayList<DtoTramite> listaTramitesPersona = new ArrayList<DtoTramite>();
    /*
     * Quitar luego los que nos necesarios
     */
    private Set usuarioses = new HashSet(0);
    private Set copiases = new HashSet(0);
    private Set suplenciasesForFkIdSuplente = new HashSet(0);
    private Set suplenciasesForFkIdSuplantado = new HashSet(0);
    private Set presupuestoses = new HashSet(0);
    private Set identificacioneses = new HashSet(0);
    private Set folioses = new HashSet(0);    /*
     * -----------------------------------
     */


    public Integer getVersion()
    {
        return version;
    }

    public void setVersion(Integer version)
    {
        this.version = version;
    }

    public DtoPersona()
    {
    }

    public DtoPersona(String nombre, String apellido, boolean esCliente)
    {
        this.nombre = nombre;
        this.apellido = apellido;
        this.esCliente = esCliente;
    }

    public DtoPersona(String nombre, String apellido, String nacionalidad, String cuit, String sexo, Date fechaNacimiento, String estadoCivil, Integer numeroNupcias, String ocupacion, String domicilio, String telefono, Integer EMail, Integer registroEscribano, boolean esCliente, Set usuarioses, Set tramiteses, Set copiases, Set suplenciasesForFkIdSuplente, Set suplenciasesForFkIdSuplantado, Set presupuestoses, Set identificacioneses, Set folioses, Set gestionesDeEscriturases)
    {
        this.nombre = nombre;
        this.apellido = apellido;
        this.nacionalidad = nacionalidad;
        this.cuit = cuit;
        this.sexo = sexo;
        this.fechaNacimiento = fechaNacimiento;
        this.estadoCivil = estadoCivil;
        this.numeroNupcias = numeroNupcias;
        this.ocupacion = ocupacion;
        this.domicilio = domicilio;
        this.telefono = telefono;
        this.registroEscribano = registroEscribano;
        this.esCliente = esCliente;
        this.usuarioses = usuarioses;
        this.copiases = copiases;
        this.suplenciasesForFkIdSuplente = suplenciasesForFkIdSuplente;
        this.suplenciasesForFkIdSuplantado = suplenciasesForFkIdSuplantado;
        this.presupuestoses = presupuestoses;
        this.identificacioneses = identificacioneses;
        this.folioses = folioses;
    }

    public Integer getIdPersona()
    {
        return this.idPersona;
    }

    public void setIdPersona(Integer idPersona)
    {
        this.idPersona = idPersona;
    }

    public String getNombre()
    {
        return this.nombre;
    }

    public void setNombre(String nombre)
    {
        this.nombre = nombre;
    }

    public String getApellido()
    {
        return this.apellido;
    }

    public void setApellido(String apellido)
    {
        this.apellido = apellido;
    }

    public String getNacionalidad()
    {
        return this.nacionalidad;
    }

    public void setNacionalidad(String nacionalidad)
    {
        this.nacionalidad = nacionalidad;
    }

    public String getCuit()
    {
        return this.cuit;
    }

    public void setCuit(String cuit)
    {
        this.cuit = cuit;
    }

    public String getSexo()
    {
        return this.sexo;
    }

    public void setSexo(String sexo)
    {
        this.sexo = sexo;
    }

    public Date getFechaNacimiento()
    {
        return this.fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento)
    {
        this.fechaNacimiento = fechaNacimiento;
    }

    public String getEstadoCivil()
    {
        return this.estadoCivil;
    }

    public void setEstadoCivil(String estadoCivil)
    {
        this.estadoCivil = estadoCivil;
    }

    public Integer getNumeroNupcias()
    {
        return this.numeroNupcias;
    }

    public void setNumeroNupcias(Integer numeroNupcias)
    {
        this.numeroNupcias = numeroNupcias;
    }

    public String getOcupacion()
    {
        return this.ocupacion;
    }

    public void setOcupacion(String ocupacion)
    {
        this.ocupacion = ocupacion;
    }

    public String getDomicilio()
    {
        return this.domicilio;
    }

    public void setDomicilio(String domicilio)
    {
        this.domicilio = domicilio;
    }

    public String getTelefono()
    {
        return this.telefono;
    }

    public void setTelefono(String telefono)
    {
        this.telefono = telefono;
    }

    public Integer getRegistroEscribano()
    {
        return this.registroEscribano;
    }

    public void setRegistroEscribano(Integer registroEscribano)
    {
        this.registroEscribano = registroEscribano;
    }

    public boolean getEsCliente()
    {
        return this.esCliente;
    }

    public void setEsCliente(boolean esCliente)
    {
        this.esCliente = esCliente;
    }

    public Set getUsuarioses()
    {
        return this.usuarioses;
    }

    public void setUsuarioses(Set usuarioses)
    {
        this.usuarioses = usuarioses;
    }

    public Set getCopiases()
    {
        return this.copiases;
    }

    public void setCopiases(Set copiases)
    {
        this.copiases = copiases;
    }

    public Set getSuplenciasesForFkIdSuplente()
    {
        return this.suplenciasesForFkIdSuplente;
    }

    public void setSuplenciasesForFkIdSuplente(Set suplenciasesForFkIdSuplente)
    {
        this.suplenciasesForFkIdSuplente = suplenciasesForFkIdSuplente;
    }

    public Set getSuplenciasesForFkIdSuplantado()
    {
        return this.suplenciasesForFkIdSuplantado;
    }

    public void setSuplenciasesForFkIdSuplantado(Set suplenciasesForFkIdSuplantado)
    {
        this.suplenciasesForFkIdSuplantado = suplenciasesForFkIdSuplantado;
    }

    public Set getPresupuestoses()
    {
        return this.presupuestoses;
    }

    public void setPresupuestoses(Set presupuestoses)
    {
        this.presupuestoses = presupuestoses;
    }

    public Set getIdentificacioneses()
    {
        return this.identificacioneses;
    }

    public void setIdentificacioneses(Set identificacioneses)
    {
        this.identificacioneses = identificacioneses;
    }

    public Set getFolioses()
    {
        return this.folioses;
    }

    public void setFolioses(Set folioses)
    {
        this.folioses = folioses;
    }

    public void setNumeroIdentificacion(String numeroIdentificacion)
    {
        this.numeroidentificacion = numeroIdentificacion;
    }

    public String getNumeroIdentificacion()
    {
        return this.numeroidentificacion;
    }

    public void setEmail(String eMail)
    {
        this.eMail = eMail;
    }

    public String getEmail()
    {
        return this.eMail;
    }

    public DtoTipoIdentificacion getDtoTipoIdentificacion()
    {
        return dtoTipoIdentificacion;
    }

    public void setDtoTipoIdentificacion(DtoTipoIdentificacion dtoTipoIdentificacion)
    {
        this.dtoTipoIdentificacion = dtoTipoIdentificacion;
    }

    @Override
    public Boolean isValido()
    {
        Boolean resultado = Boolean.TRUE;

        if (this.getIdPersona() == ID_DTO_INICIALIZADO)
        {
            return false;
        }
        if ((this.getRegistroEscribano() != null)
                && (this.getRegistroEscribano() != 0))
        {
            if (!AdministradorValidaciones.getInstancia().validarCampoSoloNumerosEnteros(this.getRegistroEscribano().toString()))
            {
                return false;
            }
        }

        return resultado;
    }

    /*
     * Retorna las escrituras de un escribano, no la de la persona
     */
    public ArrayList<DtoGestionDeEscritura> getListDtoGestionDeEscriturasDeEscribano()
    {
        return listDtoGestionDeEscriturasEscribano;
    }

    public ArrayList<DtoTramite> getListaTramitesPersona()
    {
        return listaTramitesPersona;
    }

    public void setListaTramitesPersona(ArrayList<DtoTramite> listaTramitesPersona)
    {
        this.listaTramitesPersona = listaTramitesPersona;
    }

    public void setListDtoGestionDeEscriturasDeEscribano(ArrayList<DtoGestionDeEscritura> listDtoGestionDeEscrituras)
    {
        this.listDtoGestionDeEscriturasEscribano = listDtoGestionDeEscrituras;
    }

    public ArrayList<DtoGestionDeEscritura> getListaDtoGestionDeEscriturasPersona()
    {
        return listaDtoGestionDeEscriturasPersona;
    }

    public void setListaDtoGestionDeEscriturasPersona(ArrayList<DtoGestionDeEscritura> listaDtoGestionDeEscriturasPersona)
    {
        this.listaDtoGestionDeEscriturasPersona = listaDtoGestionDeEscriturasPersona;
    }
}
