package com.licensis.notaire.dto;
// Generated 19/04/2012 16:59:26 by Hibernate Tools 3.2.1.GA

import com.licensis.notaire.dto.interfaces.DtoValido;
import java.util.Date;

/**
 * DtoRegistroAuditoria generated by hbm2java
 */
public class DtoRegistroAuditoria implements DtoValido
{

    private Integer idRegistroAuditoria;
    private DtoUsuario usuarios;
    private String detalleOperacion;
    private Date fecha;
    private String modulo;

    public String getModulo()
    {
        return modulo;
    }

    public void setModulo(String modulo)
    {
        this.modulo = modulo;
    }

    public DtoRegistroAuditoria()
    {
    }

    public DtoRegistroAuditoria(DtoUsuario usuarios, String detalleOperacion, Date fecha)
    {
        this.usuarios = usuarios;
        this.detalleOperacion = detalleOperacion;
        this.fecha = fecha;
    }

    public Integer getIdRegistroAuditoria()
    {
        return this.idRegistroAuditoria;
    }

    public void setIdRegistroAuditoria(Integer idRegistroAuditoria)
    {
        this.idRegistroAuditoria = idRegistroAuditoria;
    }

    public DtoUsuario getUsuarios()
    {
        return this.usuarios;
    }

    public void setUsuarios(DtoUsuario usuarios)
    {
        this.usuarios = usuarios;
    }

    public String getDetalleOperacion()
    {
        return this.detalleOperacion;
    }

    public void setDetalleOperacion(String detalleOperacion)
    {
        this.detalleOperacion = detalleOperacion;
    }

    public Date getFecha()
    {
        return this.fecha;
    }

    public void setFecha(Date fecha)
    {
        this.fecha = fecha;
    }

    @Override
    public Boolean isValido()
    {
        //  TODO: implementar.
        return true;
    }
}
