/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.documentos;

import com.licensis.notaire.gui.Principal;
import java.awt.Dimension;
import javax.swing.JMenuItem;

/**
 *
 * @author matias
 */
public class Documentos extends javax.swing.JInternalFrame
{

    private static Documentos instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem submenuDocumentos = new JMenuItem("Sub-Modulo Documentos");

    /**
     * Creates new form Documentos
     */
    private Documentos() {
        initComponents();
    }

    public static Documentos getInstancia() {
        if (instancia == null)
        {
            instancia = new Documentos();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
            instancia.setMinimumSize(new Dimension(Principal.tamanioMinimoHorizontal, Principal.tamanioMinimoVertical));
        }
        return instancia;
    }

    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario) {
        Documentos.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getSubmenuDocumentos() {
        return submenuDocumentos;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonIngresarDocumento = new javax.swing.JButton();
        botonModificarDocumento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonEliminarDocumento = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Sub-Modulo Documentos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonIngresarDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/administracion/documentos/ingresarDocumento.png"))); // NOI18N
        botonIngresarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarDocumentoActionPerformed(evt);
            }
        });

        botonModificarDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/administracion/documentos/modificarDocumento.png"))); // NOI18N
        botonModificarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarDocumentoActionPerformed(evt);
            }
        });

        jLabel1.setText("<HTML>Ingresar Tipo<BR>de Documento</HTML>");

        jLabel2.setText("<HTML>Modificar Tipo<BR>de Documento</HTML>");

        botonEliminarDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/administracion/documentos/eliminarDocumento.png"))); // NOI18N
        botonEliminarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarDocumentoActionPerformed(evt);
            }
        });

        jLabel3.setText("<HTML>Eliminar Tipo<BR>de Documento</HTML>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonIngresarDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonModificarDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonEliminarDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonEliminarDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonModificarDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonIngresarDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(274, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(submenuDocumentos);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonIngresarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarDocumentoActionPerformed

        Principal.cargarFormulario(new IngresarDocumento());
        Principal.setVentanasActivas(IngresarDocumento.getVentanaIngresarDocumento());
    }//GEN-LAST:event_botonIngresarDocumentoActionPerformed

    private void botonModificarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarDocumentoActionPerformed

        Principal.cargarFormulario(new ModificarDocumento());
        Principal.setVentanasActivas(ModificarDocumento.getVentanaModificarDocumento());
    }//GEN-LAST:event_botonModificarDocumentoActionPerformed

    private void botonEliminarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarDocumentoActionPerformed

        Principal.cargarFormulario(new EliminarDocumento());
        Principal.setVentanasActivas(EliminarDocumento.getVentanaEliminarDocumento());

    }//GEN-LAST:event_botonEliminarDocumentoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarDocumento;
    private javax.swing.JButton botonIngresarDocumento;
    private javax.swing.JButton botonModificarDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
