/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.documentos;

import com.licensis.notaire.dto.DtoTipoDeDocumento;
import com.licensis.notaire.gui.Principal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import com.licensis.notaire.negocio.ControllerNegocio;
import com.licensis.notaire.servicios.AdministradorValidaciones;

/**
 *
 * @author Tefi
 */
public class IngresarDocumento extends javax.swing.JInternalFrame
{

    private static JMenuItem ventanaIngresarDocumento = new JMenuItem("Ventana Ingresar Documento");
    private ControllerNegocio miController = ControllerNegocio.getInstancia();

    /**
     * Creates new form IngresarDocumento
     */
    public IngresarDocumento()
    {
        initComponents();
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
    }

    private void salir()
    {
        this.dispose();
    }

    public static JMenuItem getVentanaIngresarDocumento()
    {
        return ventanaIngresarDocumento;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIngresarDocumento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        checkVenceDocumento = new javax.swing.JCheckBox();
        campoNombreDocumento = new javax.swing.JTextField();
        selectorDiasVencimiento = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        comboQuienEntrega = new javax.swing.JComboBox();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Ingresar Documento");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Ingresar Documento");

        jLabel2.setText("Nombre:");

        jLabel3.setText("¿Vence?:");

        jLabel4.setText("Días de validez:");

        checkVenceDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkVenceDocumentoMouseClicked(evt);
            }
        });
        checkVenceDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVenceDocumentoActionPerformed(evt);
            }
        });
        checkVenceDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkVenceDocumentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                checkVenceDocumentoKeyReleased(evt);
            }
        });

        campoNombreDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreDocumentoActionPerformed(evt);
            }
        });
        campoNombreDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoNombreDocumentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoNombreDocumentoKeyReleased(evt);
            }
        });

        selectorDiasVencimiento.setEnabled(false);
        selectorDiasVencimiento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                selectorDiasVencimientoStateChanged(evt);
            }
        });

        jLabel5.setText("¿Quién hace entrega?:");

        comboQuienEntrega.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente", "Entidad Externa" }));
        comboQuienEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboQuienEntregaActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIngresarDocumentoLayout = new javax.swing.GroupLayout(panelIngresarDocumento);
        panelIngresarDocumento.setLayout(panelIngresarDocumentoLayout);
        panelIngresarDocumentoLayout.setHorizontalGroup(
            panelIngresarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDocumentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngresarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresarDocumentoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIngresarDocumentoLayout.createSequentialGroup()
                        .addGroup(panelIngresarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(panelIngresarDocumentoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addComponent(comboQuienEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelIngresarDocumentoLayout.createSequentialGroup()
                                .addGroup(panelIngresarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGroup(panelIngresarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelIngresarDocumentoLayout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(checkVenceDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(selectorDiasVencimiento))
                                    .addGroup(panelIngresarDocumentoLayout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(campoNombreDocumento)))))
                        .addGap(0, 125, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelIngresarDocumentoLayout.setVerticalGroup(
            panelIngresarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarDocumentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelIngresarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombreDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelIngresarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectorDiasVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkVenceDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboQuienEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(panelIngresarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelIngresarDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelIngresarDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkVenceDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVenceDocumentoActionPerformed
    }//GEN-LAST:event_checkVenceDocumentoActionPerformed

    private void campoNombreDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreDocumentoActionPerformed
    }//GEN-LAST:event_campoNombreDocumentoActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed

        DtoTipoDeDocumento miDtoDocumento = new DtoTipoDeDocumento();

        /*
         * Controlo que todos los campos sean correcto
         */
        String msj = AdministradorValidaciones.getInstancia().validarIngresarDocumento(this);

        if (msj == "")
        {
            try
            {
                miDtoDocumento.setNombre(campoNombreDocumento.getText());

                if (checkVenceDocumento.isSelected() == true)
                {
                    miDtoDocumento.setVence(true);
                    miDtoDocumento.setDiasVencimiento((Integer) selectorDiasVencimiento.getValue());
                } else
                {
                    miDtoDocumento.setVence(false);
                }

                miDtoDocumento.setQuienEntrega(comboQuienEntrega.getSelectedItem().toString());
                miDtoDocumento.setHabilitado(true);

                Boolean seCreo = false;

                seCreo = miController.darAltaDocumento(miDtoDocumento);

                if (seCreo)
                {
                    JOptionPane.showMessageDialog(this, "Se ha ingresado el nuevo documento.", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
                    this.limpiarFormulario();
                } else
                {

                    JOptionPane.showMessageDialog(this, "<HTML>ERROR: No se ha ingresado el documento.<BR>El documento ya existe o se han insertado mal los campos.</HTML>", "ERROR", JOptionPane.ERROR_MESSAGE);
                }

            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Alguno de los campos es incorrecto.", "ERROR", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(IngresarDocumento.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else
        {
            JOptionPane.showMessageDialog(this, msj);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    public void limpiarFormulario()
    {
        this.campoNombreDocumento.setText("");
        this.checkVenceDocumento.setSelected(false);
        this.selectorDiasVencimiento.setValue(0);
        this.selectorDiasVencimiento.setEnabled(false);
        this.comboQuienEntrega.setSelectedIndex(0);

    }

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed

        salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        Principal.removeVentanaActivas(ventanaIngresarDocumento);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void campoNombreDocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreDocumentoKeyPressed
    }//GEN-LAST:event_campoNombreDocumentoKeyPressed

    private void checkVenceDocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checkVenceDocumentoKeyPressed
    }//GEN-LAST:event_checkVenceDocumentoKeyPressed

    private void checkVenceDocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checkVenceDocumentoKeyReleased
    }//GEN-LAST:event_checkVenceDocumentoKeyReleased

    private void checkVenceDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkVenceDocumentoMouseClicked
        if (checkVenceDocumento.isSelected())
        {
            this.selectorDiasVencimiento.setEnabled(true);
        } else
        {
            this.selectorDiasVencimiento.setEnabled(false);
        }
    }//GEN-LAST:event_checkVenceDocumentoMouseClicked

    private void comboQuienEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboQuienEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboQuienEntregaActionPerformed

    private void campoNombreDocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreDocumentoKeyReleased
    }//GEN-LAST:event_campoNombreDocumentoKeyReleased

    private void selectorDiasVencimientoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_selectorDiasVencimientoStateChanged
        int valor = this.selectorDiasVencimiento.getValue().hashCode();
        if (valor < 0)
        {
            this.selectorDiasVencimiento.setValue(0);
        }
    }//GEN-LAST:event_selectorDiasVencimientoStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    public javax.swing.JTextField campoNombreDocumento;
    public javax.swing.JCheckBox checkVenceDocumento;
    public javax.swing.JComboBox comboQuienEntrega;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelIngresarDocumento;
    public javax.swing.JSpinner selectorDiasVencimiento;
    // End of variables declaration//GEN-END:variables
}
