/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.documentos;

import com.licensis.notaire.dto.DtoFlag;
import com.licensis.notaire.dto.DtoTipoDeDocumento;
import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import com.licensis.notaire.jpa.exceptions.ClassEliminatedException;
import com.licensis.notaire.jpa.exceptions.ClassModifiedException;
import com.licensis.notaire.negocio.ControllerNegocio;
import com.licensis.notaire.servicios.AdministradorValidaciones;

/**
 *
 * @author Tefi
 */
public class ModificarDocumento extends javax.swing.JInternalFrame
{

    private static JMenuItem ventanaModificarDocumento = new JMenuItem("Ventana Modificar Documento");
    private ArrayList<DtoTipoDeDocumento> misDocumentos = null;
    private ControllerNegocio miController = ControllerNegocio.getInstancia();
    private DtoTipoDeDocumento miDocumentoSeleccionado = null;

    /**
     * Creates new form ModificarDocumento
     */
    public ModificarDocumento() {
        initComponents();
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        inicializarFormulario();
    }

    private void salir() {
        this.dispose();
    }

    public static JMenuItem getVentanaModificarDocumento() {
        return ventanaModificarDocumento;
    }

    private void inicializarFormulario() {

        this.limpiarFormulario();

        misDocumentos = miController.buscarTiposDeDocumentoDisponibles();

        if (misDocumentos != null && !misDocumentos.isEmpty())
        {
            DefaultListModel lista = new DefaultListModel();

            for (Iterator<DtoTipoDeDocumento> it = misDocumentos.iterator(); it.hasNext();)
            {
                DtoTipoDeDocumento miDto = it.next();

                lista.addElement(miDto.getNombre());
            }

            this.listaDocumentosDisponibles.setModel(lista);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No existen Tipos de Documento registrados.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            salir();
        }
    }

    private void limpiarFormulario() {
        miDocumentoSeleccionado = null;
        campoNombreDocumento.setText("");
        checkVenceDocumento.setSelected(false);
        selectorDiasVencimiento.setEnabled(false);
        selectorDiasVencimiento.setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelModificarDocumento = new javax.swing.JPanel();
        botonSeleccionar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaDocumentosDisponibles = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        comboQuienEntrega = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        checkVenceDocumento = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selectorDiasVencimiento = new javax.swing.JSpinner();
        campoNombreDocumento = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Modificar Documento");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/aceptar.png"))); // NOI18N
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        jLabel6.setText("Documentos:");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Modificar Documento");

        listaDocumentosDisponibles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(listaDocumentosDisponibles);

        comboQuienEntrega.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente", "Entidad Externa" }));
        comboQuienEntrega.setEnabled(false);

        jLabel5.setText("¿Quién hace entrega?:");

        checkVenceDocumento.setEnabled(false);
        checkVenceDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkVenceDocumentoMouseClicked(evt);
            }
        });
        checkVenceDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVenceDocumentoActionPerformed(evt);
            }
        });

        jLabel3.setText("¿Vence?:");

        jLabel4.setText("Días de validez:");

        jLabel2.setText("Nombre:");

        selectorDiasVencimiento.setEnabled(false);
        selectorDiasVencimiento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                selectorDiasVencimientoStateChanged(evt);
            }
        });

        campoNombreDocumento.setEditable(false);
        campoNombreDocumento.setBorder(null);
        campoNombreDocumento.setEnabled(false);
        campoNombreDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreDocumentoActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelModificarDocumentoLayout = new javax.swing.GroupLayout(panelModificarDocumento);
        panelModificarDocumento.setLayout(panelModificarDocumentoLayout);
        panelModificarDocumentoLayout.setHorizontalGroup(
            panelModificarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarDocumentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarDocumentoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(panelModificarDocumentoLayout.createSequentialGroup()
                        .addGroup(panelModificarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addGroup(panelModificarDocumentoLayout.createSequentialGroup()
                                .addGroup(panelModificarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelModificarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelModificarDocumentoLayout.createSequentialGroup()
                                        .addComponent(checkVenceDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(selectorDiasVencimiento))
                                    .addComponent(campoNombreDocumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboQuienEntrega, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(132, Short.MAX_VALUE))
                    .addGroup(panelModificarDocumentoLayout.createSequentialGroup()
                        .addGroup(panelModificarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 87, Short.MAX_VALUE))))
        );
        panelModificarDocumentoLayout.setVerticalGroup(
            panelModificarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarDocumentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombreDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelModificarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelModificarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(selectorDiasVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkVenceDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelModificarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboQuienEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(panelModificarDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModificarDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModificarDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkVenceDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVenceDocumentoActionPerformed
        if (!checkVenceDocumento.isSelected())
        {
            selectorDiasVencimiento.setEnabled(false);
        }
        else
        {
            selectorDiasVencimiento.setEnabled(true);
        }
    }//GEN-LAST:event_checkVenceDocumentoActionPerformed

    private void campoNombreDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreDocumentoActionPerformed
    }//GEN-LAST:event_campoNombreDocumentoActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed

        /*
         * Controlo que todos los campos sean correctos
         */
        String msj = AdministradorValidaciones.getInstancia().validarModificarDocumento(this);

        if (msj == "")
        {

            if (checkVenceDocumento.isSelected() == true)
            {
                miDocumentoSeleccionado.setVence(true);
                miDocumentoSeleccionado.setDiasVencimiento((Integer) selectorDiasVencimiento.getValue());
            }
            else
            {
                miDocumentoSeleccionado.setVence(false);
                miDocumentoSeleccionado.setDiasVencimiento(null);
            }

            miDocumentoSeleccionado.setQuienEntrega(comboQuienEntrega.getSelectedItem().toString());

            try
            {
                DtoFlag seModifico = miController.modificarTipoDeDocumento(miDocumentoSeleccionado);

                if (seModifico.getFlag())
                {
                    JOptionPane.showMessageDialog(this, "Se ha modificado el tipo de documento.", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
                    limpiarFormulario();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "<HTML>ERROR: No se ha modificado el tipo de documento.<BR>Se ha insertado mal alguno de los campos.</HTML>", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch (ClassModifiedException ex)
            {

                JOptionPane.showMessageDialog(this, "El Documento ha sido recientemente modificado por otro usuario.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                this.inicializarFormulario();

            }
            catch (ClassEliminatedException ex)
            {
                JOptionPane.showMessageDialog(this, "El Documento ha sido recientemente eliminado por otro usuario.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                this.inicializarFormulario();
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Error grave, Accion cancelada", "Error", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(ModificarDocumento.class.getName()).log(Level.SEVERE, null, ex);
                this.salir();
            }
            finally
            {
                listaDocumentosDisponibles.removeAll();
                inicializarFormulario();
            }

        }
        else
        {
            JOptionPane.showMessageDialog(this, msj);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed

        salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        Principal.removeVentanaActivas(ventanaModificarDocumento);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed

        checkVenceDocumento.setSelected(true);
        selectorDiasVencimiento.setEnabled(true);
        selectorDiasVencimiento.setValue(0);

        Integer nroSeleccionado = listaDocumentosDisponibles.getAnchorSelectionIndex();

        if (nroSeleccionado == ConstantesGui.ERROR)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de documento", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        else
        {

            String seleccionado = listaDocumentosDisponibles.getSelectedValue().toString();

            for (Iterator<DtoTipoDeDocumento> it = misDocumentos.iterator(); it.hasNext();)
            {
                DtoTipoDeDocumento miDto = it.next();

                this.activarCampos(miDto);

                if (miDto.getNombre().equals(seleccionado))
                {
                    campoNombreDocumento.setText(miDto.getNombre());

                    checkVenceDocumento.setSelected(miDto.isVence());

                    if (miDto.isVence())
                    {
                        selectorDiasVencimiento.setValue(miDto.getDiasVencimiento());
                    }

                    if (miDto.getQuienEntrega().equals("Cliente"))
                    {
                        comboQuienEntrega.setSelectedItem("Cliente");
                    }
                    else
                    {
                        comboQuienEntrega.setSelectedItem("Entidad Externa");
                    }

                    miDocumentoSeleccionado = miDto;

                    break;
                }
            }
        }


    }//GEN-LAST:event_botonSeleccionarActionPerformed

    public void activarCampos(DtoTipoDeDocumento miDto) {

        this.campoNombreDocumento.setEditable(true);
        this.comboQuienEntrega.setEnabled(true);
        this.selectorDiasVencimiento.setEnabled(true);
        this.checkVenceDocumento.setEnabled(true);

    }

    private void checkVenceDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkVenceDocumentoMouseClicked
        if (checkVenceDocumento.isSelected())
        {
            this.selectorDiasVencimiento.setEnabled(true);
        }
        else
        {
            this.selectorDiasVencimiento.setEnabled(false);
        }
    }//GEN-LAST:event_checkVenceDocumentoMouseClicked

    private void selectorDiasVencimientoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_selectorDiasVencimientoStateChanged
        int valor = this.selectorDiasVencimiento.getValue().hashCode();
        if (valor < 0)
        {
            this.selectorDiasVencimiento.setValue(0);
        }
    }//GEN-LAST:event_selectorDiasVencimientoStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonSeleccionar;
    public javax.swing.JTextField campoNombreDocumento;
    public javax.swing.JCheckBox checkVenceDocumento;
    public javax.swing.JComboBox comboQuienEntrega;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList listaDocumentosDisponibles;
    private javax.swing.JPanel panelModificarDocumento;
    public javax.swing.JSpinner selectorDiasVencimiento;
    // End of variables declaration//GEN-END:variables
}
