package com.licensis.notaire.dto;
// Generated 19/04/2012 16:59:26 by Hibernate Tools 3.2.1.GA

import com.licensis.notaire.dto.interfaces.DtoValido;
import java.util.Date;

/**
 * DtoDocumentoPresentado generated by hbm2java
 */
public class DtoDocumentoPresentado implements DtoValido
{

    private int version;
    private Integer idDocumentoPresentado;
    private DtoTramite fkTramite;
    private DtoTipoDeDocumento fkTipoDeDocumento;
    private String nombre;
    private Integer numeroCarton;
    private Date fechaIngreso;
    private Date fechaSalida;
    private boolean preparado;
    private boolean vence;
    private Date fechaVencimiento;
    private Integer diasVencimiento;
    private Float importeAPagar;
    private Date fechaPago;
    private boolean liberado;
    private Date fechaLiberado;
    private boolean observado;
    private String observaciones;
    private boolean reingresado;
    private String quienEntrega;
    private boolean entregado;

    public String getQuienEntrega() {
        return quienEntrega;
    }

    public void setQuienEntrega(String quienEntrega) {
        this.quienEntrega = quienEntrega;
    }

    public boolean isReingresado() {
        return reingresado;
    }

    public void setReingresado(boolean reingresado) {
        this.reingresado = reingresado;
    }
    
    public boolean isEntregado() {
        return entregado;
    }

    public void setEntregado(boolean entregado) {
        this.entregado = entregado;
    }

    public int getVersion() {
        return version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public DtoDocumentoPresentado() {
    }
/*
    public DtoDocumentoPresentado(DtoTramite tramites, String nombre, Date fechaIngreso, boolean preparado, boolean vence, boolean liberado, boolean observado) {
        this.fkTramite = tramites;
        this.nombre = nombre;
        this.fechaIngreso = fechaIngreso;
        this.preparado = preparado;
        this.vence = vence;
        this.liberado = liberado;
        this.observado = observado;
    }

    public DtoDocumentoPresentado(DtoTramite tramites, String nombre, Integer numeroCarton, Date fechaIngreso, Date fechaSalida, boolean preparado, boolean vence, Date fechaVencimiento, Integer diasVencimiento, Float importeAPagar, Date fechaPago, boolean liberado, Date fechaLiberado, boolean observado, String observaciones) {
        this.fkTramite = tramites;
        this.nombre = nombre;
        this.numeroCarton = numeroCarton;
        this.fechaIngreso = fechaIngreso;
        this.fechaSalida = fechaSalida;
        this.preparado = preparado;
        this.vence = vence;
        this.fechaVencimiento = fechaVencimiento;
        this.diasVencimiento = diasVencimiento;
        this.importeAPagar = importeAPagar;
        this.fechaPago = fechaPago;
        this.liberado = liberado;
        this.fechaLiberado = fechaLiberado;
        this.observado = observado;
        this.observaciones = observaciones;
    }*/

    public Integer getIdDocumentoPresentado() {
        return this.idDocumentoPresentado;
    }

    public void setIdDocumentoPresentado(Integer idDocumentoPresentado) {
        this.idDocumentoPresentado = idDocumentoPresentado;
    }

    public DtoTramite getFkTramite() {
        return this.fkTramite;
    }

    public void setFkTramite(DtoTramite tramites) {
        this.fkTramite = tramites;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Integer getNumeroCarton() {
        return this.numeroCarton;
    }

    public void setNumeroCarton(Integer numeroCarton) {
        this.numeroCarton = numeroCarton;
    }

    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }

    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    public Date getFechaSalida() {
        return this.fechaSalida;
    }

    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }

    public boolean isPreparado() {
        return this.preparado;
    }

    public void setPreparado(boolean preparado) {
        this.preparado = preparado;
    }

    public boolean isVence() {
        return this.vence;
    }

    public void setVence(boolean vence) {
        this.vence = vence;
    }

    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }

    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }

    public Integer getDiasVencimiento() {
        return this.diasVencimiento;
    }

    public void setDiasVencimiento(Integer diasVencimiento) {
        this.diasVencimiento = diasVencimiento;
    }

    public Float getImporteAPagar() {
        return this.importeAPagar;
    }

    public void setImporteApagar(Float importeAPagar) {
        this.importeAPagar = importeAPagar;
    }

    public Date getFechaPago() {
        return this.fechaPago;
    }

    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }

    public boolean isLiberado() {
        return this.liberado;
    }

    public void setLiberado(boolean liberado) {
        this.liberado = liberado;
    }

    public Date getFechaLiberado() {
        return this.fechaLiberado;
    }

    public void setFechaLiberado(Date fechaLiberado) {
        this.fechaLiberado = fechaLiberado;
    }

    public boolean isObservado() {
        return this.observado;
    }

    public void setObservado(boolean observado) {
        this.observado = observado;
    }

    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @Override
    public Boolean isValido() {
        //  TODO: Implementar
        return true;
    }
}