package com.licensis.notaire.dto;
// Generated 19/04/2012 16:59:26 by Hibernate Tools 3.2.1.GA

import com.licensis.notaire.dto.interfaces.DtoValido;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import com.licensis.notaire.negocio.ConstantesNegocio;

/**
 * DtoEscritura generated by hbm2java
 */
public class DtoEscritura implements DtoValido
{

    private Integer idEscritura;
    private int numero;
    private Date fechaEscrituracion;
    private String cuerpo;
    private String estado = ConstantesNegocio.ESCRITURA_SIN_FIRMAR;
    private String matriculaInscripcion;
    private Date fechaInscripcion;
    private String observaciones;
    private int version = 0;
    private List<DtoTestimonio> testimonios = new ArrayList<>();
    private List<DtoFolio> folios = new ArrayList<>();
    private List<DtoTramite> tramites = new ArrayList<>();

    public DtoEscritura() {
    }

    public DtoEscritura(int numero, Date fechaEscrituracion, String cuerpo, String estado) {
        this.numero = numero;
        this.fechaEscrituracion = fechaEscrituracion;
        this.cuerpo = cuerpo;
        this.estado = estado;
    }

    public DtoEscritura(int numero, Date fechaEscrituracion, String cuerpo, String estado, String matriculaInscripcion, Date fechaInscripcion, String observaciones, List<DtoTestimonio> dtoTestimonios, List<DtoFolio> dtoFolios, List<DtoTramite> dtoTramites) {
        this.numero = numero;
        this.fechaEscrituracion = fechaEscrituracion;
        this.cuerpo = cuerpo;
        this.estado = estado;
        this.matriculaInscripcion = matriculaInscripcion;
        this.fechaInscripcion = fechaInscripcion;
        this.observaciones = observaciones;
        this.testimonios = dtoTestimonios;
        this.folios = dtoFolios;
        this.tramites = dtoTramites;
    }

    public int getVersion() {
        return version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public String getCuerpo() {
        return cuerpo;
    }

    public void setCuerpo(String cuerpo) {
        this.cuerpo = cuerpo;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Date getFechaEscrituracion() {
        return fechaEscrituracion;
    }

    public void setFechaEscrituracion(Date fechaEscrituracion) {
        this.fechaEscrituracion = fechaEscrituracion;
    }

    public Date getFechaInscripcion() {
        return fechaInscripcion;
    }

    public void setFechaInscripcion(Date fechaInscripcion) {
        this.fechaInscripcion = fechaInscripcion;
    }

    public List<DtoFolio> getFolios() {
        return folios;
    }

    public void setFolios(List<DtoFolio> folios) {
        this.folios = folios;
    }

    public Integer getIdEscritura() {
        return idEscritura;
    }

    public void setIdEscritura(Integer idEscritura) {
        this.idEscritura = idEscritura;
    }

    public String getMatriculaInscripcion() {
        return matriculaInscripcion;
    }

    public void setMatriculaInscripcion(String matriculaInscripcion) {
        this.matriculaInscripcion = matriculaInscripcion;
    }

    public int getNumero() {
        return numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    public List<DtoTestimonio> getTestimonios() {
        return testimonios;
    }

    public void setTestimonios(List<DtoTestimonio> testimonios) {
        this.testimonios = testimonios;
    }

    public List<DtoTramite> getTramites() {
        return tramites;
    }

    public void setTramites(List<DtoTramite> tramites) {
        this.tramites = tramites;
    }

    @Override
    public Boolean isValido() {
        //  TODO: implementar.
        return true;
    }
}