package com.licensis.notaire.dto;
// Generated 19/04/2012 16:59:26 by Hibernate Tools 3.2.1.GA

import com.licensis.notaire.dto.interfaces.DtoValido;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import com.licensis.notaire.jpa.ConstantesPersistencia;
import com.licensis.notaire.servicios.AdministradorValidaciones;

/**
 * DtoFolio generated by hbm2java
 */
public class DtoFolio implements DtoValido
{

    private Integer idFolio;
    private DtoTipoDeFolio tiposDeFolio;
    private DtoEscritura escritura;
    private DtoPersona personaEscribano;
    private int numero;
    private int anio;
    private String estado;
    private String observaciones;
    private List<DtoCopia> copias = new ArrayList<>();
    private Integer version;

    public DtoFolio() {
        this.version = ConstantesPersistencia.VERSION_INICIAL;
    }

    public DtoFolio(DtoTipoDeFolio tiposDeFolio, DtoPersona personas, int numero, int anio, String estado) {
        this.tiposDeFolio = tiposDeFolio;
        this.personaEscribano = personas;
        this.numero = numero;
        this.anio = anio;
        this.estado = estado;
    }

    public DtoFolio(DtoTipoDeFolio tiposDeFolio, DtoEscritura escrituras, DtoPersona personas, int numero, int anio, String estado, String observaciones, List<DtoCopia> copias) {
        this.tiposDeFolio = tiposDeFolio;
        this.escritura = escrituras;
        this.personaEscribano = personas;
        this.numero = numero;
        this.anio = anio;
        this.estado = estado;
        this.observaciones = observaciones;
        this.copias = copias;
    }

    public Integer getIdFolio() {
        return this.idFolio;
    }

    public void setIdFolio(Integer idFolio) {
        this.idFolio = idFolio;
    }

    public DtoTipoDeFolio getTiposDeFolio() {
        return this.tiposDeFolio;
    }

    public void setTiposDeFolio(DtoTipoDeFolio tiposDeFolio) {
        this.tiposDeFolio = tiposDeFolio;
    }

    public DtoEscritura getEscritura() {
        return this.escritura;
    }

    public void setEscritura(DtoEscritura escrituras) {
        this.escritura = escrituras;
    }

    public DtoPersona getPersonaEscribano() {
        return this.personaEscribano;
    }

    public void setPersonaEscribano(DtoPersona personaEscribano) {
        this.personaEscribano = personaEscribano;
    }

    public int getNumero() {
        return this.numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    public int getAnio() {
        return this.anio;
    }

    public void setAnio(int anio) {
        this.anio = anio;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    public List<DtoCopia> getCopias() {
        return this.copias;
    }

    public void setCopias(List<DtoCopia> copias) {
        this.copias = copias;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Override
    public Boolean isValido() {
        boolean resultado = true;

        if (!AdministradorValidaciones.getInstancia().validarNumero(this.getNumero()))
        {
            return false;
        }
        return resultado;
    }
}
