package com.licensis.notaire.dto;
// Generated 19/04/2012 16:59:26 by Hibernate Tools 3.2.1.GA

import com.licensis.notaire.dto.interfaces.DtoValido;
import java.util.Date;

/**
 * DtoMovimientoTestimonio generated by hbm2java
 */
public class DtoMovimientoTestimonio implements DtoValido
{

    private Integer idMovimientoTestimonio;
    private DtoTestimonio testimonio;
    private Date fechaIngreso;
    private Date fechaSalida;
    private Date fechaInscripcion;
    private boolean inscripta;
    private int numeroCarton;
    private String observaciones;
    private int version = 0;

    public DtoMovimientoTestimonio() {
    }

    public int getVersion() {
        return version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public Integer getIdMovimientoTestimonio() {
        return this.idMovimientoTestimonio;
    }

    public void setIdMovimientoTestimonio(Integer idMovimientoTestimonio) {
        this.idMovimientoTestimonio = idMovimientoTestimonio;
    }

    public DtoTestimonio getTestimonio() {
        return this.testimonio;
    }

    public void setTestimonio(DtoTestimonio testimonios) {
        this.testimonio = testimonios;
    }

    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }

    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    public Date getFechaSalida() {
        return this.fechaSalida;
    }

    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }

    public Date getFechaInscripcion() {
        return this.fechaInscripcion;
    }

    public void setFechaInscripcion(Date fechaInscripcion) {
        this.fechaInscripcion = fechaInscripcion;
    }

    public boolean isInscripta() {
        return this.inscripta;
    }

    public void setInscripta(boolean inscripta) {
        this.inscripta = inscripta;
    }

    public int getNumeroCarton() {
        return this.numeroCarton;
    }

    public void setNumeroCarton(int numeroCarton) {
        this.numeroCarton = numeroCarton;
    }

    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @Override
    public Boolean isValido() {
        //  TODO: Implementar.
        return true;
    }
}
