package com.licensis.notaire.dto;
// Generated 19/04/2012 16:59:26 by Hibernate Tools 3.2.1.GA

import com.licensis.notaire.dto.interfaces.DtoValido;

/**
 * DtoPlantillaPresupuesto generated by hbm2java
 */
public class DtoPlantillaPresupuesto implements DtoValido
{

    private DtoConcepto conceptos;
    private DtoTipoDeTramite tiposDeTramite;
    private String observaciones;
    private Integer version = 0;

    public DtoPlantillaPresupuesto() {
    }

    public DtoConcepto getConceptos() {
        return this.conceptos;
    }

    public void setConceptos(DtoConcepto conceptos) {
        this.conceptos = conceptos;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public DtoTipoDeTramite getTiposDeTramite() {
        return this.tiposDeTramite;
    }

    public void setTiposDeTramite(DtoTipoDeTramite tiposDeTramite) {
        this.tiposDeTramite = tiposDeTramite;
    }

    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @Override
    public Boolean isValido() {
        //  TODO: implementar.
        return true;
    }
}
