package com.licensis.notaire.dto;
// Generated 19/04/2012 16:59:26 by Hibernate Tools 3.2.1.GA

import com.licensis.notaire.dto.interfaces.DtoValido;

/**
 * DtoPlantillaTramite generated by hbm2java
 */
public class DtoPlantillaTramite implements DtoValido
{

    private DtoTipoDeDocumento tiposDeDocumento;
    private DtoTipoDeTramite tiposDeTramite;
    private String observaciones;

    public DtoPlantillaTramite() {
    }

    public DtoTipoDeDocumento getTiposDeDocumento() {
        return this.tiposDeDocumento;
    }

    public void setTiposDeDocumento(DtoTipoDeDocumento tiposDeDocumento) {
        this.tiposDeDocumento = tiposDeDocumento;
    }

    public DtoTipoDeTramite getTiposDeTramite() {
        return this.tiposDeTramite;
    }

    public void setTiposDeTramite(DtoTipoDeTramite tiposDeTramite) {
        this.tiposDeTramite = tiposDeTramite;
    }

    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @Override
    public Boolean isValido() {
        //  TODO: implementar.
        return true;
    }
}
