package com.licensis.notaire.dto;
// Generated 19/04/2012 16:59:26 by Hibernate Tools 3.2.1.GA

import com.licensis.notaire.dto.interfaces.DtoValido;
import java.util.HashSet;
import java.util.Set;
import com.licensis.notaire.jpa.ConstantesPersistencia;
import com.licensis.notaire.servicios.AdministradorValidaciones;

/**
 * DtoTipoDeFolio generated by hbm2java
 */
public class DtoTipoDeFolio implements DtoValido
{

    private Integer idTipoFolio;
    private String nombre;
    private String observaciones;
    private Set folios = new HashSet(0);
    private boolean habilitado;
    private Integer version;

    public DtoTipoDeFolio() {
        this.version = ConstantesPersistencia.VERSION_INICIAL;
    }

    public DtoTipoDeFolio(String nombre) {
        this.nombre = nombre;
    }

    public DtoTipoDeFolio(String nombre, String observaciones, Set folioses) {
        this.nombre = nombre;
        this.observaciones = observaciones;
        this.folios = folioses;
    }

    public Integer getIdTipoFolio() {
        return this.idTipoFolio;
    }

    public void setIdTipoFolio(Integer idTipoFolio) {
        this.idTipoFolio = idTipoFolio;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    public Set getFolios() {
        return this.folios;
    }

    public void setFolios(Set folios) {
        this.folios = folios;
    }

    public boolean isHabilitado() {
        return habilitado;
    }

    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Override
    public Boolean isValido() {
        boolean resultado = true;

        if (!AdministradorValidaciones.getInstancia().validarCampoLetrasYNumeros(this.getNombre()))
        {
            return false;
        }

        return resultado;
    }
}
