/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.protocolo.folios;

import com.licensis.notaire.dto.DtoFolio;
import com.licensis.notaire.dto.DtoPersona;
import com.licensis.notaire.dto.DtoTipoDeFolio;
import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.licensis.notaire.jpa.exceptions.ClassEliminatedException;
import com.licensis.notaire.jpa.exceptions.ClassModifiedException;
import com.licensis.notaire.jpa.exceptions.NonexistentEntityException;
import com.licensis.notaire.jpa.exceptions.NonexistentJpaException;
import com.licensis.notaire.negocio.ConstantesNegocio;
import com.licensis.notaire.negocio.ControllerNegocio;

/**
 *
 * @author matias
 */
public class ModificarFolio extends javax.swing.JInternalFrame
{

    private static JMenuItem ventanaModificarFolio = new JMenuItem("Ventana Modificar Folio");
    private static Boolean estadoFormulario = Boolean.FALSE;
    private ControllerNegocio miController = null;
    private List<DtoPersona> milistaEscribanos = null;
    private List<DtoFolio> dtoListaFolios = null;
    private Integer folioSeleccionado = null;

    /**
     * Creates new form ModificarFolio
     */
    public ModificarFolio() {
        initComponents();
        estadoFormulario = Boolean.TRUE;
        this.setSize(Principal.tamanioGrandeHorizontal, Principal.tamanioNormalVertical);
        this.miController = ControllerNegocio.getInstancia();
        this.cargarRegistrosEscribanos();
        this.cargarEstadosFolios();
    }

    private void limpiarFormulario() {
        campoFoliosSeleccionado.setText("");
        campoObservaciones.setText("");
        comboEstadosFolio.setSelectedIndex(0);
    }

    private void salir() {
        this.dispose();
    }

    public static JMenuItem getVentanaModificarFolio() {
        return ventanaModificarFolio;
    }

    public void cargarRegistrosEscribanos() {
        try
        {
            milistaEscribanos = miController.obtenerListaEscribanosDisponibles();

            if (!milistaEscribanos.isEmpty())
            {
                for (Iterator<DtoPersona> it = milistaEscribanos.iterator(); it.hasNext();)
                {
                    DtoPersona dtoPersona = it.next();

                    this.comboRegistroEscribano.addItem(dtoPersona.getRegistroEscribano());
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "No existen escribanos registrados", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NullPointerException e)
        {
            JOptionPane.showMessageDialog(this, "No existen escribanos registrados", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public DtoPersona buscarEscribano(Integer registro) {
        for (Iterator<DtoPersona> it = milistaEscribanos.iterator(); it.hasNext();)
        {
            DtoPersona dtoPersona = it.next();

            if (dtoPersona.getRegistroEscribano().intValue() == registro.intValue())
            {
                return dtoPersona;
            }
        }
        return null;
    }

    public void cargarEstadosFolios() {
        this.comboEstadosFolio.addItem(ConstantesNegocio.ESTADO_FOLIO_NUEVOS);
        this.comboEstadosFolio.addItem(ConstantesNegocio.ESTADO_FOLIO_UTILIZADO);
        this.comboEstadosFolio.addItem(ConstantesNegocio.ESTADO_FOLIO_ERROSE);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        panelModificarFolio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        selectorAnio = new com.toedter.calendar.JYearChooser();
        comboRegistroEscribano = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        grillaDetalleFolios = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        comboEstadosFolio = new javax.swing.JComboBox();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campoFoliosSeleccionado = new javax.swing.JTextField();
        botonSeleccionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoObservaciones = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Modificar Folio");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Modificar Folio");

        jLabel3.setText("Registro Escribano:");

        jLabel6.setText("Año:");

        grillaDetalleFolios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de Folio", "Tipo", "Estado", "Observaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grillaDetalleFolios.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(grillaDetalleFolios);
        grillaDetalleFolios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel5.setText("Nuevo Estado de Folio:");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonBuscar.setForeground(new java.awt.Color(26, 83, 143));
        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Folios Seleccionado:");

        campoFoliosSeleccionado.setEditable(false);

        botonSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/aceptar.png"))); // NOI18N
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        campoObservaciones.setColumns(20);
        campoObservaciones.setRows(5);
        jScrollPane2.setViewportView(campoObservaciones);

        jLabel4.setText("Observaciones:");

        javax.swing.GroupLayout panelModificarFolioLayout = new javax.swing.GroupLayout(panelModificarFolio);
        panelModificarFolio.setLayout(panelModificarFolioLayout);
        panelModificarFolioLayout.setHorizontalGroup(
            panelModificarFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarFolioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                    .addGroup(panelModificarFolioLayout.createSequentialGroup()
                        .addGroup(panelModificarFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelModificarFolioLayout.createSequentialGroup()
                                .addGroup(panelModificarFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(30, 30, 30)
                                .addGroup(panelModificarFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelModificarFolioLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelModificarFolioLayout.createSequentialGroup()
                                        .addGroup(panelModificarFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jScrollPane2)
                                            .addGroup(panelModificarFolioLayout.createSequentialGroup()
                                                .addComponent(campoFoliosSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(comboEstadosFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelModificarFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelModificarFolioLayout.createSequentialGroup()
                                    .addGroup(panelModificarFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelModificarFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelModificarFolioLayout.createSequentialGroup()
                                            .addComponent(comboRegistroEscribano, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(panelModificarFolioLayout.createSequentialGroup()
                                            .addComponent(selectorAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabel1)))
                        .addContainerGap())))
        );
        panelModificarFolioLayout.setVerticalGroup(
            panelModificarFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarFolioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboRegistroEscribano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelModificarFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarFolioLayout.createSequentialGroup()
                        .addGroup(panelModificarFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(selectorAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelModificarFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelModificarFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(campoFoliosSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(comboEstadosFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelModificarFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelModificarFolioLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(panelModificarFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelModificarFolioLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelModificarFolioLayout.createSequentialGroup()
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jScrollPane3.setViewportView(panelModificarFolio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(ventanaModificarFolio);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAceptarActionPerformed
    {//GEN-HEADEREND:event_botonAceptarActionPerformed

        try
        {
            for (Iterator<DtoFolio> it = dtoListaFolios.iterator(); it.hasNext();)
            {
                DtoFolio dtoFolio = it.next();
                if (dtoFolio.getNumero() == this.folioSeleccionado)
                {
                    Integer registro = (Integer) this.comboRegistroEscribano.getSelectedItem();

                    DtoPersona escribano = this.buscarEscribano(registro);
                    
                    DtoTipoDeFolio miTipoDeFolio = miController.buscarTipoDeFolio(new DtoTipoDeFolio(ConstantesGui.FOLIO_PROTOCOLO_PRINCIPAL));
                    
                    dtoFolio.setTiposDeFolio(miTipoDeFolio);
                    dtoFolio.setAnio(this.selectorAnio.getYear());
                    dtoFolio.setPersonaEscribano(escribano);
                    dtoFolio.setEstado(this.comboEstadosFolio.getSelectedItem().toString());
                    dtoFolio.setObservaciones(this.campoObservaciones.getText());

                    if (miController.modificarFolio(dtoFolio))
                    {
                        JOptionPane.showMessageDialog(this, "Se ha modificar folios Correctamente");
                        salir();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "No se ha podido modificar el folio indicado", "Error al modificar folio", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
        catch (NonexistentEntityException ex)
        {
            Logger.getLogger(ModificarFolio.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (NonexistentJpaException ex)
        {
            Logger.getLogger(ModificarFolio.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (ClassModifiedException ex)
        {
            JOptionPane.showMessageDialog(this, "El folio que intenta modificar ha sido recientemente actualizado", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        catch (ClassEliminatedException ex)
        {
            JOptionPane.showMessageDialog(this, "El folio que intenta modificar ha sido recientemente eliminado", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        catch (NullPointerException e)
        {
            JOptionPane.showMessageDialog(this, "No existen folios registrados o no ha seleccionado ninguno", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
        salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonBuscarActionPerformed
    {//GEN-HEADEREND:event_botonBuscarActionPerformed
        try            
        {
            this.limpiarFormulario();
            this.limpiarGrilla();
            int registroEscribano = Integer.parseInt(this.comboRegistroEscribano.getSelectedItem().toString());
            int anio = selectorAnio.getYear();

            this.actualizarGrilla(registroEscribano, anio);
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Alguno de los datos indicados no es valido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonSeleccionarActionPerformed
    {//GEN-HEADEREND:event_botonSeleccionarActionPerformed
        this.limpiarFormulario();

        try
        {
            int filaSeleccionada = this.grillaDetalleFolios.getSelectedRow();

            try
            {
                Integer numeroFolio = (Integer) (grillaDetalleFolios.getModel()).getValueAt(filaSeleccionada, 0);
                String observaciones = (String) (grillaDetalleFolios.getModel()).getValueAt(filaSeleccionada, 3);
                this.folioSeleccionado = numeroFolio;
                campoFoliosSeleccionado.setText(numeroFolio.toString());
                campoObservaciones.setText(observaciones);
            }
            catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "Error format exception", "Error grave", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (ArrayIndexOutOfBoundsException ex)
        {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun elemento.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    public void limpiarGrilla() {
        int i = ((DefaultTableModel) grillaDetalleFolios.getModel()).getRowCount() - 1;

        while (((DefaultTableModel) grillaDetalleFolios.getModel()).getRowCount() > 0)
        {
            ((DefaultTableModel) grillaDetalleFolios.getModel()).removeRow(i);
            i--;
        }
    }

    public void actualizarGrilla(int registro, int anio) {
        DtoFolio parametros = new DtoFolio();
        parametros.setAnio(anio);
        DtoPersona escribano = new DtoPersona();
        escribano.setRegistroEscribano(registro);
        parametros.setPersonaEscribano(escribano);
        this.dtoListaFolios = miController.obtenerListaFolios(parametros);

        for (Iterator<DtoFolio> it = dtoListaFolios.iterator(); it.hasNext();)
        {
            DtoFolio dtoFolio = it.next();

            Object[] datos =
            {
                dtoFolio.getNumero(),
                dtoFolio.getTiposDeFolio().getNombre(),
                dtoFolio.getEstado(),
                dtoFolio.getObservaciones()
            };

            ((DefaultTableModel) grillaDetalleFolios.getModel()).addRow(datos);

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JTextField campoFoliosSeleccionado;
    private javax.swing.JTextArea campoObservaciones;
    private javax.swing.JComboBox comboEstadosFolio;
    private javax.swing.JComboBox comboRegistroEscribano;
    private javax.swing.JTable grillaDetalleFolios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelModificarFolio;
    private com.toedter.calendar.JYearChooser selectorAnio;
    // End of variables declaration//GEN-END:variables
}
