/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.clientes;

import com.licensis.notaire.dto.DtoPersona;
import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import com.licensis.notaire.jpa.exceptions.NonexistentJpaException;
import com.licensis.notaire.negocio.ControllerNegocio;

/**
 *
 * @author matias
 */
public class Clientes extends javax.swing.JInternalFrame {

    private static Clientes instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem menuClientes = new JMenuItem("Modulo Clientes");

    /**
     * Creates new form Clientes
     */
    private Clientes() {
        initComponents();
    }

    public static Clientes getInstancia() {
        if (instancia == null) {
            instancia = new Clientes();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        }
        return instancia;
    }

    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario) {
        Clientes.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getMenuClientes() {
        return menuClientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonDarAltaPersona = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonModificarPersona = new javax.swing.JButton();
        botonDarAltaCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonModificarCliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        botonBuscarCliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        botonBuscarGestionesCliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        botonPersonasClientes = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Modulo Clientes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }

            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonDarAltaPersona
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clientes/altaPersona.png"))); // NOI18N
        botonDarAltaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDarAltaPersonaActionPerformed(evt);
            }
        });

        jLabel1.setText("Dar Alta Persona");

        botonModificarPersona
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clientes/modificarPersona.png"))); // NOI18N
        botonModificarPersona.setToolTipText("Modificar Persona");
        botonModificarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarPersonaActionPerformed(evt);
            }
        });

        botonDarAltaCliente
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clientes/altaCliente.png"))); // NOI18N
        botonDarAltaCliente.setToolTipText("Dar Alta Cliente");
        botonDarAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDarAltaClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Modificar Persona");

        jLabel3.setText("Dar Alta Cliente");

        botonModificarCliente
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clientes/modificarCliente.png"))); // NOI18N
        botonModificarCliente.setToolTipText("Modificar Cliente");
        botonModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarClienteActionPerformed(evt);
            }
        });

        jLabel4.setText("Modificar Cliente");

        botonBuscarCliente
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clientes/buscarCliente.png"))); // NOI18N
        botonBuscarCliente.setToolTipText("Buscar Cliente");
        botonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarClienteActionPerformed(evt);
            }
        });

        jLabel5.setText("Buscar Cliente");

        botonBuscarGestionesCliente.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/iconos/clientes/buscarGestionesCliente.png"))); // NOI18N
        botonBuscarGestionesCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarGestionesClienteActionPerformed(evt);
            }
        });

        jLabel6.setText("Buscar Gestiones Cliente");

        botonPersonasClientes.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/iconos/clientes/buscarPersonasClientes.png"))); // NOI18N
        botonPersonasClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPersonasClientesActionPerformed(evt);
            }
        });

        jLabel7.setText("Personas/Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(botonBuscarCliente,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(botonPersonasClientes,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 118,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(botonBuscarGestionesCliente,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(botonDarAltaPersona,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botonModificarPersona,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botonDarAltaCliente,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botonModificarCliente,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(89, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botonDarAltaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(botonDarAltaPersona,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(botonModificarCliente,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(botonModificarPersona,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(botonBuscarGestionesCliente,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(botonPersonasClientes,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 116,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(botonBuscarCliente,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)))
                                .addContainerGap(211, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarGestionesClienteActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_botonBuscarGestionesClienteActionPerformed
    {// GEN-HEADEREND:event_botonBuscarGestionesClienteActionPerformed
        BuscarGestionesCliente formBuscarGestionesCliente = BuscarGestionesCliente.getInstancia();
        formBuscarGestionesCliente.labelTitulo.setText(ConstantesGui.VER_GESTIONES);
        formBuscarGestionesCliente.desactivarGrilla();
        formBuscarGestionesCliente.mostrarBotonBuscar();
        formBuscarGestionesCliente.mostrarLabelBuscar();

        Principal.cargarFormulario(formBuscarGestionesCliente);
        Principal.setVentanasActivas(BuscarGestionesCliente.getVentanaBuscarGestionesCliente());
    }// GEN-LAST:event_botonBuscarGestionesClienteActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)// GEN-FIRST:event_formInternalFrameClosed
    {// GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(menuClientes);
        Principal.eliminarFormulario(this);
    }// GEN-LAST:event_formInternalFrameClosed

    private void botonDarAltaPersonaActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_botonDarAltaPersonaActionPerformed
    {// GEN-HEADEREND:event_botonDarAltaPersonaActionPerformed
        DarAltaPersona formAltaPersona = DarAltaPersona.getInstancia();
        formAltaPersona.limpiarFormulario();
        Principal.cargarFormulario(formAltaPersona);
        Principal.setVentanasActivas(DarAltaPersona.getVentanaDarAltaPersona());
    }// GEN-LAST:event_botonDarAltaPersonaActionPerformed

    private void botonModificarPersonaActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_botonModificarPersonaActionPerformed
    {// GEN-HEADEREND:event_botonModificarPersonaActionPerformed
        AdministrarCliente formModificarPersona = AdministrarCliente.getInstancia();
        formModificarPersona.setTitle(ConstantesGui.VENTANA_PERSONA);
        formModificarPersona.limpiarFormulario();
        formModificarPersona.desactivarFormulario();
        formModificarPersona.cargarTipoFormulario(botonModificarPersona.getToolTipText());

        Principal.cargarFormulario(formModificarPersona);
        Principal.setVentanasActivas(AdministrarCliente.getInstancia().getVentanaActiva());
    }// GEN-LAST:event_botonModificarPersonaActionPerformed

    private void botonDarAltaClienteActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_botonDarAltaClienteActionPerformed
    {// GEN-HEADEREND:event_botonDarAltaClienteActionPerformed
        AdministrarCliente formAltaCliente = AdministrarCliente.getInstancia();
        formAltaCliente.setTitle(ConstantesGui.VENTANA_CLIENTE);

        formAltaCliente.cargarTipoFormulario(botonDarAltaCliente.getToolTipText());
        formAltaCliente.desactivarFormulario();
        formAltaCliente.limpiarFormulario();
        formAltaCliente.botonModoEdicion();
        Principal.cargarFormulario(formAltaCliente);
        Principal.setVentanasActivas(AdministrarCliente.getInstancia().getVentanaActiva());
    }// GEN-LAST:event_botonDarAltaClienteActionPerformed

    private void botonModificarClienteActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_botonModificarClienteActionPerformed
    {// GEN-HEADEREND:event_botonModificarClienteActionPerformed
        AdministrarCliente formModificarCliente = AdministrarCliente.getInstancia();
        formModificarCliente.setTitle(ConstantesGui.VENTANA_CLIENTE);
        formModificarCliente.cargarTipoFormulario(botonModificarCliente.getToolTipText());
        formModificarCliente.desactivarFormulario();
        formModificarCliente.limpiarFormulario();
        formModificarCliente.botonModoEdicion();

        Principal.cargarFormulario(formModificarCliente);
        Principal.setVentanasActivas(AdministrarCliente.getInstancia().getVentanaActiva());
    }// GEN-LAST:event_botonModificarClienteActionPerformed

    private void botonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_botonBuscarClienteActionPerformed
    {// GEN-HEADEREND:event_botonBuscarClienteActionPerformed
        AdministrarCliente formAltaCliente = AdministrarCliente.getInstancia();
        formAltaCliente.setTitle(ConstantesGui.VENTANA_CLIENTE);
        formAltaCliente.cargarTipoFormulario(botonBuscarCliente.getToolTipText());
        formAltaCliente.desactivarFormulario();
        formAltaCliente.limpiarFormulario();
        formAltaCliente.botonModoVista();
        Principal.cargarFormulario(formAltaCliente);
        Principal.setVentanasActivas(AdministrarCliente.getInstancia().getVentanaActiva());

    }// GEN-LAST:event_botonBuscarClienteActionPerformed

    private void botonPersonasClientesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonPersonasClientesActionPerformed
        try {
            ArrayList<DtoPersona> miLitaDtoPersonasClientes = new ArrayList<DtoPersona>();
            miLitaDtoPersonasClientes = ControllerNegocio.getInstancia().buscarPersonasClientes();
            ListarPersonas.getInstancia().limpiarJtable();
            Boolean flag = ListarPersonas.getInstancia().cargarGrillaPersonasClientes(miLitaDtoPersonasClientes,
                    ConstantesGui.BUSCAR_PERSONA_CLIENTE);
            ListarPersonas.getInstancia().labelTitulo.setText(ConstantesGui.BUSCAR_PERSONA_CLIENTE);

            Principal.setVentanasActivas(ListarPersonas.getInstancia().getVentanaActiva());

        } catch (Exception ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }// GEN-LAST:event_botonPersonasClientesActionPerformed
     // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JButton botonBuscarCliente;
    private javax.swing.JButton botonBuscarGestionesCliente;
    private javax.swing.JButton botonDarAltaCliente;
    private javax.swing.JButton botonDarAltaPersona;
    private javax.swing.JButton botonModificarCliente;
    private javax.swing.JButton botonModificarPersona;
    private javax.swing.JButton botonPersonasClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
