/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.clientes;

import com.licensis.notaire.dto.DtoPersona;
import com.licensis.notaire.dto.DtoTipoIdentificacion;
import com.licensis.notaire.gui.Principal;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import com.licensis.notaire.jpa.exceptions.NonexistentJpaException;
import com.licensis.notaire.negocio.ControllerNegocio;
import com.licensis.notaire.servicios.AdministradorValidaciones;

/**
 *
 * @author matias
 */
public class DarAltaPersona extends javax.swing.JInternalFrame {

    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem ventanaDarAltaPersona = new JMenuItem("Ventana Dar Alta Persona");
    private static DarAltaPersona instancia = null;
    private ControllerNegocio miController;

    /**
     * Creates new form DarAltaPersona
     */
    public DarAltaPersona() {
        initComponents();
        estadoFormulario = Boolean.TRUE;

        // this.setSize(Principal.tamanioNormalHorizontal,
        // Principal.tamanioNormalVertical);
        miController = ControllerNegocio.getInstancia();

        /*
         * Cargo el combo de Tipo de Identificacion
         */
        this.cargarCombo();
    }

    public static DarAltaPersona getInstancia() {
        if (instancia == null) {
            instancia = new DarAltaPersona();
        }
        return instancia;
    }

    private void salir() {
        this.dispose();
    }

    public void cargarCombo() {
        String nombre = null;
        ArrayList<DtoTipoIdentificacion> listaDtoIdentificaciones = new ArrayList<DtoTipoIdentificacion>();
        listaDtoIdentificaciones = miController.listarTiposIdentificacion();

        for (int i = 0; i < listaDtoIdentificaciones.size(); i++) {
            nombre = listaDtoIdentificaciones.get(i).getNombre();
            comboTipoIdentificacion.addItem(nombre);

        }

    }

    public void limpiarFormulario() {
        campoNombre.setText("");
        campoApellido.setText("");
        campoEmail.setText("");
        campoNumeroIdentificacion.setText("");
        campoTelefono.setText("");

    }

    public static JMenuItem getVentanaDarAltaPersona() {
        return ventanaDarAltaPersona;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDarAltaPersona = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        campoNumeroIdentificacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboTipoIdentificacion = new javax.swing.JComboBox();
        campoApellido = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoTelefono = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        advertencia = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Dar Alta Persona");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }

            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Dar de Alta Persona");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        campoNumeroIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroIdentificacionActionPerformed(evt);
            }
        });
        campoNumeroIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoNumeroIdentificacionKeyPressed(evt);
            }

            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoNumeroIdentificacionKeyReleased(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNumeroIdentificacionKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido");

        jLabel4.setText("Tipo Ident.:");

        jLabel5.setText("Número Ident.:");

        jLabel6.setText("Teléfono:");

        jLabel7.setText("Correo electrónico:");

        comboTipoIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoIdentificacionActionPerformed(evt);
            }
        });

        campoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoNombreKeyReleased(evt);
            }
        });

        advertencia.setFont(new java.awt.Font("Century Schoolbook L", 1, 12)); // NOI18N
        advertencia.setForeground(new java.awt.Color(238, 4, 4));

        javax.swing.GroupLayout panelDarAltaPersonaLayout = new javax.swing.GroupLayout(panelDarAltaPersona);
        panelDarAltaPersona.setLayout(panelDarAltaPersonaLayout);
        panelDarAltaPersonaLayout.setHorizontalGroup(
                panelDarAltaPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDarAltaPersonaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelDarAltaPersonaLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelDarAltaPersonaLayout.createSequentialGroup()
                                                .addGroup(panelDarAltaPersonaLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jLabel1)
                                                        .addGroup(panelDarAltaPersonaLayout.createSequentialGroup()
                                                                .addGroup(panelDarAltaPersonaLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(jLabel4,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                120, Short.MAX_VALUE)
                                                                        .addComponent(jLabel3,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(panelDarAltaPersonaLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(comboTipoIdentificacion,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                150,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(campoApellido,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                300,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(campoNombre,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                300,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(panelDarAltaPersonaLayout.createSequentialGroup()
                                                                .addGroup(panelDarAltaPersonaLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addGroup(panelDarAltaPersonaLayout
                                                                                .createSequentialGroup()
                                                                                .addComponent(jLabel7,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                                        .addGroup(panelDarAltaPersonaLayout
                                                                                .createSequentialGroup()
                                                                                .addGroup(panelDarAltaPersonaLayout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(jLabel6,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(jLabel5,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                                .addGap(6, 6, 6)))
                                                                .addGroup(panelDarAltaPersonaLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                        .addComponent(campoTelefono,
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(campoNumeroIdentificacion,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                300, Short.MAX_VALUE)
                                                                        .addComponent(campoEmail))))
                                                .addGap(4, 4, 4)
                                                .addComponent(advertencia, javax.swing.GroupLayout.DEFAULT_SIZE, 159,
                                                        Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDarAltaPersonaLayout
                                                .createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap()));
        panelDarAltaPersonaLayout.setVerticalGroup(
                panelDarAltaPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDarAltaPersonaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(9, 9, 9)
                                .addGroup(panelDarAltaPersonaLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelDarAltaPersonaLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelDarAltaPersonaLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(comboTipoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelDarAltaPersonaLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(campoNumeroIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(advertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelDarAltaPersonaLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelDarAltaPersonaLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36,
                                        Short.MAX_VALUE)
                                .addGroup(panelDarAltaPersonaLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelDarAltaPersona, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelDarAltaPersona, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)// GEN-FIRST:event_formInternalFrameClosed
    {// GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(ventanaDarAltaPersona);
        Principal.eliminarFormulario(this);
    }// GEN-LAST:event_formInternalFrameClosed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_botonAceptarActionPerformed
    {// GEN-HEADEREND:event_botonAceptarActionPerformed

        /*
         * Controlo que todos los campos que no contemplan null, esten completos
         */
        String msj = AdministradorValidaciones.getInstancia().validarDarAltaPersona(this);

        if (msj == "") {

            DtoPersona dtoPersona = new DtoPersona();

            DtoTipoIdentificacion dtoTipoIdentificacion = new com.licensis.notaire.dto.DtoTipoIdentificacion();

            dtoPersona.setNombre(campoNombre.getText());
            dtoPersona.setApellido(campoApellido.getText());
            dtoTipoIdentificacion.setNombre(comboTipoIdentificacion.getSelectedItem().toString());
            dtoPersona.setDtoTipoIdentificacion(dtoTipoIdentificacion);
            dtoPersona.setNumeroIdentificacion(campoNumeroIdentificacion.getText());
            dtoPersona.setTelefono(campoTelefono.getText());
            dtoPersona.setEmail(campoEmail.getText());
            dtoPersona.setEsCliente(false);

            // Set version del obejto inicial
            dtoPersona.setVersion(0);

            // Controlo que la persona no exista
            if (!miController.siExistePersona(dtoPersona)) {
                try {
                    // Se da de alta la persona
                    dtoPersona = miController.darAltaPersona(dtoPersona);
                    if (dtoPersona != null) {
                        JOptionPane.showMessageDialog(this,
                                "Fue dado de alta: " + dtoPersona.getNombre() + " " + dtoPersona.getApellido(),
                                "Informacion", JOptionPane.INFORMATION_MESSAGE);
                        this.limpiarFormulario();

                    } else {
                        JOptionPane.showMessageDialog(this, "La persona No pudo darse de alta", "Advertencia",
                                JOptionPane.WARNING_MESSAGE);
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error al comunicarse con el servidor: " + ex.getMessage(),
                            "Error", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(DarAltaPersona.class.getName()).log(Level.SEVERE, "Error al dar de alta persona",
                            ex);
                }

            } else {
                JOptionPane.showMessageDialog(this, "El numero de Documento, ya se encuetra registrado", "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
                this.limpiarFormulario();
            }
        } else {
            JOptionPane.showMessageDialog(this, msj, "ADEVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }

    }// GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_botonCancelarActionPerformed
    {// GEN-HEADEREND:event_botonCancelarActionPerformed
        salir();
        Principal.removeVentanaActivas(DarAltaPersona.getInstancia().getVentanaDarAltaPersona());
    }// GEN-LAST:event_botonCancelarActionPerformed

    private void campoNumeroIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campoNumeroIdentificacionActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_campoNumeroIdentificacionActionPerformed

    private void comboTipoIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboTipoIdentificacionActionPerformed
    }// GEN-LAST:event_comboTipoIdentificacionActionPerformed

    private void campoNombreKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_campoNombreKeyReleased
        // TODO add your handling code here:
    }// GEN-LAST:event_campoNombreKeyReleased

    private void campoNumeroIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_campoNumeroIdentificacionKeyTyped
    }// GEN-LAST:event_campoNumeroIdentificacionKeyTyped

    private void campoNumeroIdentificacionKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_campoNumeroIdentificacionKeyPressed
    }// GEN-LAST:event_campoNumeroIdentificacionKeyPressed

    private void campoNumeroIdentificacionKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_campoNumeroIdentificacionKeyReleased
        Boolean flag = false;
        String campo = campoNumeroIdentificacion.getText();

        flag = AdministradorValidaciones.getInstancia().validarCampoSoloNumerosEnteros(campo);

        if (!flag) {
            this.advertencia.setText("Esta Ingresando Caracteres");
        } else {
            this.advertencia.setText(" ");
        }

    }// GEN-LAST:event_campoNumeroIdentificacionKeyReleased
     // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JLabel advertencia;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    public javax.swing.JTextField campoApellido;
    public javax.swing.JTextField campoEmail;
    public javax.swing.JTextField campoNombre;
    public javax.swing.JTextField campoNumeroIdentificacion;
    public javax.swing.JTextField campoTelefono;
    public javax.swing.JComboBox comboTipoIdentificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JPanel panelDarAltaPersona;
    // End of variables declaration//GEN-END:variables
}
