/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.pagos;

import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.gui.presupuestos.BuscarPresupuesto;
import javax.swing.JMenuItem;

/**
 *
 * @author matias
 */
public class Pagos extends javax.swing.JInternalFrame
{

    private static Pagos instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem menuPagos = new JMenuItem("Modulo Pagos");

    /**
     * Creates new form Pagos
     */
    private Pagos() {
        initComponents();
    }

    public static Pagos getInstancia() {
        if (instancia == null)
        {
            instancia = new Pagos();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);

        }
        return instancia;
    }

    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario) {
        Pagos.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getMenuPagos() {
        return menuPagos;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegistrarPago = new javax.swing.JButton();
        botonConsultarPagos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Módulo Pagos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonRegistrarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/pagos/registrarPagos.png"))); // NOI18N
        botonRegistrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarPagoActionPerformed(evt);
            }
        });

        botonConsultarPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/pagos/consultarPagos.png"))); // NOI18N
        botonConsultarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarPagosActionPerformed(evt);
            }
        });

        jLabel1.setText("Registrar Pago");

        jLabel2.setText("Consultar Pagos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonRegistrarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonConsultarPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(382, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonConsultarPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRegistrarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(290, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(menuPagos);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonRegistrarPagoActionPerformed
    {//GEN-HEADEREND:event_botonRegistrarPagoActionPerformed
        BuscarPresupuesto formBuscarPresupuesto = new BuscarPresupuesto();
        formBuscarPresupuesto.setFormularioInvocador(ConstantesGui.REGISTRAR_PAGO);
        Principal.cargarFormulario(formBuscarPresupuesto);
        Principal.setVentanasActivas(BuscarPresupuesto.getVentanaBuscarPresupuesto());
    }//GEN-LAST:event_botonRegistrarPagoActionPerformed

    private void botonConsultarPagosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonConsultarPagosActionPerformed
    {//GEN-HEADEREND:event_botonConsultarPagosActionPerformed
        BuscarPresupuesto formBuscarPresupuesto = new BuscarPresupuesto();
        formBuscarPresupuesto.setFormularioInvocador(ConstantesGui.CONSULTAR_PAGOS);
        Principal.cargarFormulario(formBuscarPresupuesto);
        Principal.setVentanasActivas(BuscarPresupuesto.getVentanaBuscarPresupuesto());
    }//GEN-LAST:event_botonConsultarPagosActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultarPagos;
    private javax.swing.JButton botonRegistrarPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
