/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.presupuestos;

import com.licensis.notaire.api.client.RestMapper;
import com.licensis.notaire.dto.DtoPersona;
import com.licensis.notaire.dto.DtoTipoIdentificacion;
import com.licensis.notaire.dto.GenericDto;
import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.servicios.AdministradorJpa;
import com.licensis.notaire.servicios.GenericRestClient;
import java.io.IOException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Tefi
 */
public class ListaPersonasPresupuesto extends javax.swing.JInternalFrame {

    private static JMenuItem ventanaListaPresupuesto = new JMenuItem("Ventana Lista Presupuestos");
    private static ListaPersonasPresupuesto instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static String formularioInvocador = null;
    private static ModificarPresupuesto modificarPresupuesto = null;
    private final GenericRestClient personaClient = AdministradorJpa.getInstancia().getPersonaJpa();

    /**
     * Creates new form ListaPersonasPresupuesto
     */
    private ListaPersonasPresupuesto() {
        initComponents();
        estadoFormulario = Boolean.TRUE;
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioGrandeVertical);
        grillaPersonas.setAutoCreateRowSorter(true);
    }

    public static ListaPersonasPresupuesto getInstancia() {
        if (instancia == null) {
            instancia = new ListaPersonasPresupuesto();
        }
        return instancia;
    }

    public static void setFormModificarPresupuesto(ModificarPresupuesto formulario) {
        modificarPresupuesto = formulario;
    }

    public static void setFormularioInvocador(String nombreFormulario) {
        formularioInvocador = nombreFormulario;
    }

    public Boolean cargarGrillaPersonas(ArrayList<DtoPersona> miListaDtoPersonas) {
        boolean flag = false;

        if (miListaDtoPersonas != null) {
            DtoPersona miDtoPersona = null;

            for (int i = 0; i < miListaDtoPersonas.size(); i++) {

                flag = true;
                miDtoPersona = miListaDtoPersonas.get(i);

                String nomTipo = (miDtoPersona.getDtoTipoIdentificacion() != null)
                        ? miDtoPersona.getDtoTipoIdentificacion().getNombre() : "";
                Object[] datos = {
                        miDtoPersona.getNombre(),
                        miDtoPersona.getApellido(),
                        nomTipo,
                        miDtoPersona.getNumeroIdentificacion(),
                        miDtoPersona.getEsCliente()
                };
                ((DefaultTableModel) grillaPersonas.getModel()).addRow(datos);

            }
        }

        if (!flag) {
            JOptionPane.showMessageDialog(this, "No existen Coincidencias en la Busqueda de Personas");

        } else {
            Principal.cargarFormulario(this);
        }
        return flag;

    }

    public void limpiarJtable() {
        int i = ((DefaultTableModel) grillaPersonas.getModel()).getRowCount() - 1;

        while (((DefaultTableModel) grillaPersonas.getModel()).getRowCount() > 0) {
            ((DefaultTableModel) grillaPersonas.getModel()).removeRow(i);
            i--;
        }
    }

    public static JMenuItem getVentanaListaPresupuesto() {
        return ventanaListaPresupuesto;
    }

    public static void setVentanaListaPresupuesto(JMenuItem ventanaListaPresupuesto) {
        ListaPersonasPresupuesto.ventanaListaPresupuesto = ventanaListaPresupuesto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNuevo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        botonCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grillaPersonas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ventana Lista Presupuestos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }

            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelTitulo.setText("Lista Personas");

        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar.png"))); // NOI18N
        botonCerrar.setText("Cerrar");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        grillaPersonas.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Nombre", "Apellido", "Identificación", "Número", "Cliente"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        grillaPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grillaPersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grillaPersonas);

        javax.swing.GroupLayout panelNuevoLayout = new javax.swing.GroupLayout(panelNuevo);
        panelNuevo.setLayout(panelNuevoLayout);
        panelNuevoLayout.setHorizontalGroup(
                panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelNuevoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelNuevoLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelNuevoLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelNuevoLayout.createSequentialGroup()
                                                .addComponent(labelTitulo)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 821,
                                                Short.MAX_VALUE))
                                .addContainerGap()));
        panelNuevoLayout.setVerticalGroup(
                panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelNuevoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelNuevo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelNuevo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonCerrarActionPerformed
        this.limpiarJtable();
        this.dispose();
    }// GEN-LAST:event_botonCerrarActionPerformed

    private void grillaPersonasMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_grillaPersonasMouseClicked
        TableModel miGrilla = grillaPersonas.getModel();
        int filaSeleccionada = grillaPersonas.getSelectedRow();
        filaSeleccionada = grillaPersonas.convertRowIndexToModel(filaSeleccionada);
        if (filaSeleccionada < 0) return;

        int filas = miGrilla.getRowCount();
        final String nombreTipo = miGrilla.getValueAt(filaSeleccionada, 2) != null
                ? miGrilla.getValueAt(filaSeleccionada, 2).toString() : "";
        final String numeroIdent = miGrilla.getValueAt(filaSeleccionada, 3) != null
                ? miGrilla.getValueAt(filaSeleccionada, 3).toString() : "";
        final String invocador = ListaPersonasPresupuesto.formularioInvocador;
        final ModificarPresupuesto formModificar = modificarPresupuesto;

        new SwingWorker<DtoPersona, Void>() {
            @Override
            protected DtoPersona doInBackground() throws IOException {
                int idTipo = RestMapper.asociarFkTipoIdentificacion(nombreTipo);
                String path = "buscar?numeroIdentificacion=" + URLEncoder.encode(numeroIdent, StandardCharsets.UTF_8);
                if (idTipo > 0) path += "&idTipoIdentificacion=" + idTipo;
                List<GenericDto> raw = personaClient.findAllByPath(path);
                if (raw != null && !raw.isEmpty()) {
                    return RestMapper.toDtoPersona(raw.get(0));
                }
                return null;
            }
            @Override
            protected void done() {
                try {
                    DtoPersona miDtoPersona = get();
                    if (miDtoPersona == null) {
                        JOptionPane.showMessageDialog(ListaPersonasPresupuesto.this,
                                "No se encontró la persona seleccionada.", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    switch (invocador) {
                        case ConstantesGui.MODIFICAR_PRESUPUESTO: {
                            ListaPresupuestosCliente presupuestosForm = new ListaPresupuestosCliente();
                            presupuestosForm.setFormModificarPresupuesto(formModificar);
                            presupuestosForm.setFormulario(invocador);
                            presupuestosForm.setPersona(miDtoPersona);
                            try {
                                presupuestosForm.cargarGrillaPresupuestos();
                            } catch (Exception ex) {
                                Logger.getLogger(ListaPersonasPresupuesto.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            Principal.cargarFormulario(presupuestosForm);
                            Principal.setVentanasActivas(ListaPresupuestosCliente.getVentanaListaPresupuestosCliente());
                            limpiarJtable();
                            dispose();
                            break;
                        }
                        case ConstantesGui.CREAR_PRESUPUESTO: {
                            CrearPresupuesto formCrearPresupuesto = CrearPresupuesto.getInstancia();
                            formCrearPresupuesto.limpiarFormulario();
                            formCrearPresupuesto.cargarFormulario(miDtoPersona);
                            Principal.cargarFormulario(formCrearPresupuesto);
                            Principal.setVentanasActivas(CrearPresupuesto.getVentanaCrearPresupuesto());
                            limpiarJtable();
                            dispose();
                            break;
                        }
                        case ConstantesGui.BUSCAR_PRESUPUESTO: {
                            ListaPresupuestosCliente presupuestoForm = new ListaPresupuestosCliente();
                            presupuestoForm.setFormulario(ConstantesGui.BUSCAR_PRESUPUESTO);
                            presupuestoForm.setPersona(miDtoPersona);
                            try {
                                presupuestoForm.cargarGrillaPresupuestos();
                            } catch (Exception ex) {
                                Logger.getLogger(ListaPersonasPresupuesto.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            Principal.cargarFormulario(presupuestoForm);
                            Principal.setVentanasActivas(ListaPresupuestosCliente.getVentanaListaPresupuestosCliente());
                            limpiarJtable();
                            dispose();
                            break;
                        }
                        case ConstantesGui.INICIAR_GESTION: {
                            if (miDtoPersona.getEsCliente()) {
                                ListaPresupuestosClientesSinGestion presupuestosForm = new ListaPresupuestosClientesSinGestion();
                                presupuestosForm.setFormularioInvocador(ConstantesGui.INICIAR_GESTION);
                                presupuestosForm.setClienteSeleccionado(miDtoPersona);
                                Principal.cargarFormulario(presupuestosForm);
                                Principal.setVentanasActivas(
                                        ListaPresupuestosClientesSinGestion.getVentanaListaPresupuestoClienteSinGestion());
                            } else {
                                JOptionPane.showMessageDialog(ListaPersonasPresupuesto.this,
                                        "La persona seleccionada aun no ha sido registrada como cliente", "Advertencia",
                                        JOptionPane.WARNING_MESSAGE);
                            }
                            limpiarJtable();
                            dispose();
                            break;
                        }
                        default:
                            break;
                    }
                } catch (Exception ex) {
                    Logger.getLogger(ListaPersonasPresupuesto.class.getName()).log(Level.WARNING, "Error al cargar persona", ex);
                    JOptionPane.showMessageDialog(ListaPersonasPresupuesto.this, "Error al cargar persona: " + ex.getMessage(),
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }.execute();
    }// GEN-LAST:event_grillaPersonasMouseClicked

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {// GEN-FIRST:event_formInternalFrameClosed
        Principal.removeVentanaActivas(ventanaListaPresupuesto);
        Principal.eliminarFormulario(this);
    }// GEN-LAST:event_formInternalFrameClosed
     // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JButton botonCerrar;
    private javax.swing.JTable grillaPersonas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelNuevo;
    // End of variables declaration//GEN-END:variables
}
