/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui;

import com.licensis.notaire.dto.DtoUsuario;
import com.licensis.notaire.servicios.AdministradorJpa;
import com.licensis.notaire.servicios.AdministradorSesion;
import com.licensis.notaire.servicios.AdministradorValidaciones;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.SwingWorker;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 *
 * @author matias
 */
public class Login extends javax.swing.JFrame
{
//    private BarraProgreso barraProgreso;

    private JPanel panel;
    private Task task;
    private static final long serialVersionUID = 1L;
    private Principal formPrincipal = null;
    protected static Log log = LogFactory.getLog(Login.class);

    /**
     * Creates new form login
     */
    public Login()
    {

        log.debug("Iniciando el sistema!");
        initComponents();

        AdministradorJpa.getInstancia();
        grupo.setBorder(BorderFactory.createTitledBorder("Login"));

        this.centrarFormulario();

        this.setMinimumSize(new Dimension(400, 450));
        this.setMaximumSize(new Dimension(400, 450));

//        barraProgreso.cerraBarraProgreso();
        //Permite activar los botones en los formularios, para ser 
        //navegados con tab
        ActivarBotonformulario listener = ActivarBotonformulario.install();

        this.getRootPane().setDefaultButton(botonAceptar);

    }

    private void centrarFormulario()
    {
        this.setLocationRelativeTo(null);
    }

    private void salir()
    {
        //this.dispose();
        log.debug("Cerrando la aplicación");
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLongin = new javax.swing.JPanel();
        botonImagen = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        grupo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoContrasenia = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLongin.setVerifyInputWhenFocusTarget(false);
        panelLongin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelLonginKeyPressed(evt);
            }
        });

        botonImagen.setBackground(new java.awt.Color(0, 51, 102));
        botonImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logoRojoPalabra.png"))); // NOI18N
        botonImagen.setBorder(null);
        botonImagen.setBorderPainted(false);
        botonImagen.setContentAreaFilled(false);
        botonImagen.setFocusPainted(false);
        botonImagen.setFocusable(false);

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        botonAceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonAceptarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                botonAceptarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                botonAceptarKeyTyped(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        grupo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jLabel2.setText("Usuario:");

        jLabel3.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña:");

        javax.swing.GroupLayout grupoLayout = new javax.swing.GroupLayout(grupo);
        grupo.setLayout(grupoLayout);
        grupoLayout.setHorizontalGroup(
            grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(grupoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        grupoLayout.setVerticalGroup(
            grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelLonginLayout = new javax.swing.GroupLayout(panelLongin);
        panelLongin.setLayout(panelLonginLayout);
        panelLonginLayout.setHorizontalGroup(
            panelLonginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLonginLayout.createSequentialGroup()
                .addGroup(panelLonginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLonginLayout.createSequentialGroup()
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLonginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLonginLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLonginLayout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(botonImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelLonginLayout.setVerticalGroup(
            panelLonginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLonginLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(botonImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(panelLonginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLongin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLongin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAceptarActionPerformed
    {//GEN-HEADEREND:event_botonAceptarActionPerformed

        DtoUsuario usuarioLogin = new DtoUsuario();
        usuarioLogin = validarLoginGui(usuarioLogin);

        if (usuarioLogin.isValido() == Boolean.TRUE)
        {
            AdministradorSesion.getInstancia().setSesionUsuario(usuarioLogin);

            if (AdministradorValidaciones.getInstancia().validarUsuario(usuarioLogin) == Boolean.TRUE)
            {
                formPrincipal = Principal.getInstancia();
                formPrincipal.setVisible(true);
                this.dispose();

            } else
            {
                JOptionPane.showMessageDialog(this, "El usuario indicado no es valido!", "Error de Login", JOptionPane.ERROR_MESSAGE);

            }
        } else
        {
            JOptionPane.showMessageDialog(this, "Alguno de los datos ingresados no es valido", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
        salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonAceptarKeyPressed
        InputMap im = botonAceptar.getInputMap();
        im.put(KeyStroke.getKeyStroke("ENTER"), "pressed");
        im.put(KeyStroke.getKeyStroke("released ENTER"), "released");
    }//GEN-LAST:event_botonAceptarKeyPressed

    private void botonAceptarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonAceptarKeyReleased
    }//GEN-LAST:event_botonAceptarKeyReleased

    private void botonAceptarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonAceptarKeyTyped
    }//GEN-LAST:event_botonAceptarKeyTyped

    private void panelLonginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelLonginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            botonAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_panelLonginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and
         * feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Login().setVisible(true);
            }
        });
    }

    public DtoUsuario validarLoginGui(DtoUsuario dtoUsuario)
    {

        dtoUsuario.setNombre(campoUsuario.getText());
        dtoUsuario.setContrasenia(campoContrasenia.getText());

        //Esta puesto a mano - cambiar con la logica de validacion del usuario!!!        
        dtoUsuario.setNombre("root");
        dtoUsuario.setContrasenia("admin");

        dtoUsuario = AdministradorSesion.getInstancia().validarUsuario(dtoUsuario);
        if (dtoUsuario.isValido())
        {
            String nombreUsuario = dtoUsuario.getPersonas().getNombre() + " " + dtoUsuario.getPersonas().getApellido();
            Principal.getInstancia().cargarVentanaUsuario(dtoUsuario);
            Principal.getInstancia().itemUsuario.setText(nombreUsuario);
        }

        return dtoUsuario;
    }

    class Task extends SwingWorker<Void, Void>
    {
        /*
         * Main task. Executed in background thread.
         */

        @Override
        public Void doInBackground()
        {

            int progress = 0;
            //Initialize progress property.
            setProgress(0);
            while (progress < 100)
            {
                //Sleep for up to one second.
                try
                {
                    Thread.sleep(100);
                }
                catch (InterruptedException ignore)
                {
                }
                //Make random progress.
                progress++;
                setProgress(progress);
            }
            return null;
        }

        /*
         * Executed in event dispatching thread
         */
        @Override
        public void done()
        {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonImagen;
    private javax.swing.JPasswordField campoContrasenia;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JPanel grupo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelLongin;
    // End of variables declaration//GEN-END:variables
}
