@startuml cu38
!theme plain
title CU38 — Eliminar tipo de documento

actor "Escribano" as Actor
participant "Sistema Notaire" as Sistema

Actor -> Actor : El Escribano decide eliminar un tipo de documento.
Sistema -> Sistema : Escribano
Actor -> Actor : Muestra una lista de todos los tipos de documento disponibles.
Sistema -> Sistema : Sistema
Actor -> Actor : El Escribano selecciona uno y confirma su eliminación.
Sistema -> Sistema : Escribano
Actor -> Actor : Elimina el documento seleccionado.
Sistema -> Sistema : Sistema

@enduml