/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.tramites;

import com.licensis.notaire.dto.DtoTipoDeDocumento;
import com.licensis.notaire.dto.DtoTipoDeTramite;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.jpa.exceptions.ClassEliminatedException;
import com.licensis.notaire.jpa.exceptions.ClassModifiedException;
import com.licensis.notaire.jpa.exceptions.IllegalOrphanException;
import com.licensis.notaire.jpa.exceptions.NonexistentEntityException;
import com.licensis.notaire.jpa.exceptions.PreexistingEntityException;
import com.licensis.notaire.negocio.ControllerNegocio;
import com.licensis.notaire.servicios.AdministradorValidaciones;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Tefi
 */
public class IngresarTipoTramite extends javax.swing.JInternalFrame
{

    private static JMenuItem ventanaIngresarTipoTramite = new JMenuItem("Ventana Ingresar Tipo de Tramites");
    private ControllerNegocio miController = ControllerNegocio.getInstancia();
    private ArrayList<DtoTipoDeDocumento> documentosDisponibles = null;
    private Boolean valido = Boolean.TRUE;

    /**
     * Creates new form IngresarTipoTramite
     */
    public IngresarTipoTramite() {
        initComponents();
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioGrandeVertical);
        inicializarFormulario();
    }

    private void salir() {
        this.dispose();
    }

    public static JMenuItem getVentanaIngresarTipoTramite() {
        return ventanaIngresarTipoTramite;
    }

    public void limpiarGrilla() {
        int i = ((DefaultTableModel) grillaDocumentosNecesarios.getModel()).getRowCount() - 1;

        while (((DefaultTableModel) grillaDocumentosNecesarios.getModel()).getRowCount() > 0)
        {
            ((DefaultTableModel) grillaDocumentosNecesarios.getModel()).removeRow(i);
            i--;
        }
    }

    private void inicializarFormulario() {
        limpiarGrilla();
        documentosDisponibles = miController.buscarTiposDeDocumentoDisponibles();

        if (documentosDisponibles != null && !documentosDisponibles.isEmpty())
        {
            DtoTipoDeDocumento miDtoTipoDeDocumento;
            String nombreDocumento;

            for (int i = 0; i < documentosDisponibles.size(); i++)
            {

                miDtoTipoDeDocumento = documentosDisponibles.get(i);

                nombreDocumento = miDtoTipoDeDocumento.getNombre();

                Object[] datos =
                {
                    nombreDocumento,
                    Boolean.FALSE
                };

                ((DefaultTableModel) grillaDocumentosNecesarios.getModel()).addRow(datos);
            }

            campoNombreTramite.setText("");
            checkBoxInmueble.setSelected(false);
            checkBoxSeArchiva.setSelected(false);
            checkRequiereInscripcion.setSelected(false);
            campoObservaciones.setText("");
        }
        else
        {
            grillaDocumentosNecesarios.setEnabled(false);
            JOptionPane.showMessageDialog(this, "No existen Tipos de Documento para asociar al Tipo de  Tramite.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            salir();
        }
    }

    private void limpiarFormulario() {

        campoNombreTramite.setText("");
        checkBoxInmueble.setSelected(false);
        checkBoxSeArchiva.setSelected(false);
        checkRequiereInscripcion.setSelected(false);
        campoObservaciones.setText("");
        
        inicializarFormulario();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        panelIngresarTipoTramite = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        checkRequiereInscripcion = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        campoNombreTramite = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoObservaciones = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        grillaDocumentosNecesarios = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botonAceptar = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        checkBoxSeArchiva = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        checkBoxInmueble = new javax.swing.JCheckBox();
        labelAdvertenciaNombre = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Ingresar Tipo de Trámites");
        setPreferredSize(new java.awt.Dimension(750, 639));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Ingresar Tipo de Tramite");

        jLabel2.setText("Nombre Trámite");

        jLabel3.setText("Requiere Inscripción");

        checkRequiereInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRequiereInscripcionActionPerformed(evt);
            }
        });

        jLabel4.setText("Observaciones");

        campoNombreTramite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoNombreTramiteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoNombreTramiteKeyReleased(evt);
            }
        });

        campoObservaciones.setColumns(20);
        campoObservaciones.setRows(5);
        jScrollPane1.setViewportView(campoObservaciones);

        grillaDocumentosNecesarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Documento", "Seleccionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(grillaDocumentosNecesarios);

        jLabel5.setText("Documentos Necesarios:");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCerrar.setText("Cancelar");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        jLabel6.setText("Se archiva");

        jLabel7.setText("Se asocia con Inmueble");

        labelAdvertenciaNombre.setForeground(new java.awt.Color(255, 0, 0));
        labelAdvertenciaNombre.setToolTipText("");

        javax.swing.GroupLayout panelIngresarTipoTramiteLayout = new javax.swing.GroupLayout(panelIngresarTipoTramite);
        panelIngresarTipoTramite.setLayout(panelIngresarTipoTramiteLayout);
        panelIngresarTipoTramiteLayout.setHorizontalGroup(
            panelIngresarTipoTramiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarTipoTramiteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngresarTipoTramiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIngresarTipoTramiteLayout.createSequentialGroup()
                        .addGroup(panelIngresarTipoTramiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelIngresarTipoTramiteLayout.createSequentialGroup()
                        .addGroup(panelIngresarTipoTramiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelIngresarTipoTramiteLayout.createSequentialGroup()
                                .addGroup(panelIngresarTipoTramiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelIngresarTipoTramiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelIngresarTipoTramiteLayout.createSequentialGroup()
                                        .addGroup(panelIngresarTipoTramiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkRequiereInscripcion)
                                            .addComponent(checkBoxSeArchiva)
                                            .addComponent(checkBoxInmueble))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panelIngresarTipoTramiteLayout.createSequentialGroup()
                                        .addGroup(panelIngresarTipoTramiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jScrollPane1)
                                            .addComponent(campoNombreTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(4, 4, 4))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelIngresarTipoTramiteLayout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelIngresarTipoTramiteLayout.createSequentialGroup()
                                .addGroup(panelIngresarTipoTramiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(labelAdvertenciaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresarTipoTramiteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelIngresarTipoTramiteLayout.setVerticalGroup(
            panelIngresarTipoTramiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarTipoTramiteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelIngresarTipoTramiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombreTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAdvertenciaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresarTipoTramiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkRequiereInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresarTipoTramiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxSeArchiva)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarTipoTramiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(checkBoxInmueble))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngresarTipoTramiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 116, Short.MAX_VALUE)
                .addGroup(panelIngresarTipoTramiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane3.setViewportView(panelIngresarTipoTramite);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkRequiereInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRequiereInscripcionActionPerformed
    }//GEN-LAST:event_checkRequiereInscripcionActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed

        Boolean vacio = AdministradorValidaciones.getInstancia().validarCampoVacio(campoNombreTramite.getText());

        if (vacio)
        {
            JOptionPane.showMessageDialog(this, "Complete el nombre del nuevo Tipo de Tramite.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            DtoTipoDeTramite miDtoTipoDeTramite = new DtoTipoDeTramite();

            miDtoTipoDeTramite.setNombre(campoNombreTramite.getText());

            if (checkRequiereInscripcion.isSelected())
            {
                miDtoTipoDeTramite.setSeInscribe(true);
            }
            else
            {
                miDtoTipoDeTramite.setSeInscribe(false);
            }

            if (checkBoxSeArchiva.isSelected())
            {
                miDtoTipoDeTramite.setSeArchiva(true);
            }
            else
            {
                miDtoTipoDeTramite.setSeArchiva(false);
            }

            if (checkBoxInmueble.isSelected())
            {
                miDtoTipoDeTramite.setAsociaInmuebles(true);
            }
            else
            {
                miDtoTipoDeTramite.setAsociaInmuebles(false);
            }

            if (!campoObservaciones.getText().isEmpty())
            {
                miDtoTipoDeTramite.setObservaciones(campoObservaciones.getText());
            }

            ArrayList<DtoTipoDeDocumento> documentos = null;

            if (documentosDisponibles != null && !documentosDisponibles.isEmpty())
            {
                documentos = obtenerDocumentosSeleccionados();
            }

            miDtoTipoDeTramite.setHabilitado(true);

            Boolean creado = false;

            if (!documentos.isEmpty())
            {
                try
                {
                    creado = miController.darAltaTipoDeTramite(miDtoTipoDeTramite, documentos);

                    if (creado)
                    {
                        JOptionPane.showMessageDialog(this, "Se ha dado de alta el tipo de tramite.", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
                        limpiarFormulario();
                    }
                }
                catch (PreexistingEntityException ex)
                {
                    JOptionPane.showMessageDialog(this, "El tipo de tramite ya se encuentra registrado", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);                    
                    this.inicializarFormulario();
                }
                catch (ClassModifiedException ex)
                {
                    JOptionPane.showMessageDialog(this, "<HTML>El tipo de tramite ya existe, <BR>y ha sido recientemente modificado por otro usuario.</HTML>", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                    this.inicializarFormulario();
                }
                catch (ClassEliminatedException ex)
                {
                    JOptionPane.showMessageDialog(this, "<HTML>El tipo de tramite ya existe, <BR>y ha sido recientemente eliminado por otro usuario.</HTML>", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                    this.inicializarFormulario();
                }
                catch (IllegalOrphanException ex)
                {
                    JOptionPane.showMessageDialog(this, "Error grave, Accion cancelada", "Error", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(IngresarTipoTramite.class.getName()).log(Level.SEVERE, null, ex);
                    this.salir();
                }
                catch (NonexistentEntityException ex)
                {
                    JOptionPane.showMessageDialog(this, "Error grave, Accion cancelada", "Error", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(IngresarTipoTramite.class.getName()).log(Level.SEVERE, null, ex);
                    this.salir();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un Documento a presentar.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        }

    }//GEN-LAST:event_botonAceptarActionPerformed
    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        salir();
    }//GEN-LAST:event_botonCerrarActionPerformed

    private ArrayList<DtoTipoDeDocumento> obtenerDocumentosSeleccionados() {
        TableModel miGrilla = grillaDocumentosNecesarios.getModel();
        int filas = miGrilla.getRowCount();
        int columnas = miGrilla.getColumnCount();
        Boolean flag = true;
        ArrayList<DtoTipoDeDocumento> documentosSeleccionados = new ArrayList<>();

        for (int i = 0; i < filas; i++)
        {
            flag = (Boolean) miGrilla.getValueAt(i, 1);

            if (flag == true)
            {
                for (int j = 0; j < documentosDisponibles.size(); j++)
                {
                    DtoTipoDeDocumento dtoTipoDeDocumento = documentosDisponibles.get(j);

                    if (((String) miGrilla.getValueAt(i, 0)).equals(dtoTipoDeDocumento.getNombre()))
                    {
                        documentosSeleccionados.add(dtoTipoDeDocumento);
                    }
                }
            }
        }

        return documentosSeleccionados;
    }

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        Principal.removeVentanaActivas(ventanaIngresarTipoTramite);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void campoNombreTramiteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreTramiteKeyPressed
        // TODO add your handling code here:
        int tecla = evt.getKeyCode();

        if ((tecla != KeyEvent.VK_ENTER) && (tecla != KeyEvent.VK_BACK_SPACE))
        {

            Boolean validoLetras = AdministradorValidaciones.getInstancia().validarCampoLetrasYNumeros(campoNombreTramite.getText());

            if (!validoLetras)
            {
                this.labelAdvertenciaNombre.setText("Solo letras y numeros.");
            }
            else
            {
                this.labelAdvertenciaNombre.setText("");
            }
        }
    }//GEN-LAST:event_campoNombreTramiteKeyPressed

    private void campoNombreTramiteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreTramiteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreTramiteKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCerrar;
    public javax.swing.JTextField campoNombreTramite;
    public javax.swing.JTextArea campoObservaciones;
    public javax.swing.JCheckBox checkBoxInmueble;
    public javax.swing.JCheckBox checkBoxSeArchiva;
    public javax.swing.JCheckBox checkRequiereInscripcion;
    public javax.swing.JTable grillaDocumentosNecesarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAdvertenciaNombre;
    private javax.swing.JPanel panelIngresarTipoTramite;
    // End of variables declaration//GEN-END:variables
}
