/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.folios;

import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import java.awt.Dimension;
import javax.swing.JMenuItem;

/**
 *
 * @author matias
 */
public class Folios extends javax.swing.JInternalFrame
{

    private static Folios instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem submenuFolios = new JMenuItem("Sub-Modulo Administrar Folios");

    /**
     * Creates new form Folios
     */
    private Folios() {
        initComponents();
    }

    public static Folios getInstancia() {
        if (instancia == null)
        {
            instancia = new Folios();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
            instancia.setMinimumSize(new Dimension(Principal.tamanioMinimoHorizontal, Principal.tamanioMinimoVertical));
        }
        return instancia;
    }

    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario) {
        Folios.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getSubmenuFolios() {
        return submenuFolios;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonIngresarTipoDeFolio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonModificarTipoDeFolio = new javax.swing.JButton();
        botonEliminarTipoDeFolio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Sub-Modulo Administrar Folios");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonIngresarTipoDeFolio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/administracion/folios/ingresarTipoDeFolio.png"))); // NOI18N
        botonIngresarTipoDeFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarTipoDeFolioActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingresar Tipo de Folio");

        botonModificarTipoDeFolio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/administracion/folios/modificarTipoDeFolio.png"))); // NOI18N
        botonModificarTipoDeFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarTipoDeFolioActionPerformed(evt);
            }
        });

        botonEliminarTipoDeFolio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/licensis/notaire/gui/iconos/administracion/folios/eliminarTipoDeFolio.png"))); // NOI18N
        botonEliminarTipoDeFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarTipoDeFolioActionPerformed(evt);
            }
        });

        jLabel2.setText("Modificar Tipo de Folio");

        jLabel3.setText("Eliminar Tipo de Folio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonIngresarTipoDeFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonModificarTipoDeFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(botonEliminarTipoDeFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonIngresarTipoDeFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonModificarTipoDeFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminarTipoDeFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(submenuFolios);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonIngresarTipoDeFolioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonIngresarTipoDeFolioActionPerformed
    {//GEN-HEADEREND:event_botonIngresarTipoDeFolioActionPerformed
        Principal.cargarFormulario(new IngresarTipoDeFolio(this));
        Principal.setVentanasActivas(IngresarTipoDeFolio.getVentanaIngresarTipoDeFolio());
    }//GEN-LAST:event_botonIngresarTipoDeFolioActionPerformed

    private void botonModificarTipoDeFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarTipoDeFolioActionPerformed
        ModificarEliminarFolio formListaTiposFolio = new ModificarEliminarFolio();
        formListaTiposFolio.setFormularioInvocador(ConstantesGui.MODIFICAR_TIPO_FOLIO);
        Principal.cargarFormulario(formListaTiposFolio);
        Principal.setVentanasActivas(ModificarEliminarFolio.getVentanaAdministrarTiposDeFolios());
    }//GEN-LAST:event_botonModificarTipoDeFolioActionPerformed

    private void botonEliminarTipoDeFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarTipoDeFolioActionPerformed
        ModificarEliminarFolio formListaTiposFolio = new ModificarEliminarFolio();
        formListaTiposFolio.setFormularioInvocador(ConstantesGui.ELIMINAR_TIPO_FOLIO);
        Principal.cargarFormulario(formListaTiposFolio);
        Principal.setVentanasActivas(ModificarEliminarFolio.getVentanaAdministrarTiposDeFolios());
    }//GEN-LAST:event_botonEliminarTipoDeFolioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarTipoDeFolio;
    private javax.swing.JButton botonIngresarTipoDeFolio;
    private javax.swing.JButton botonModificarTipoDeFolio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
