#!/bin/bash

# DevSecOps Report Generator
# Aggregates findings from various tools into a single report.
# Now includes monitoring infrastructure status.

REPORT_DIR="infra/reports"
DATE=$(date +"%Y-%m-%d_%H-%M-%S")
MD_REPORT="$REPORT_DIR/security_report_$DATE.md"
HTML_REPORT="$REPORT_DIR/security_report_$DATE.html"

mkdir -p "$REPORT_DIR"

echo "# 🛡️ Notaire DevSecOps & Monitoring Report" > "$MD_REPORT"
echo "Generated on: $(date)" >> "$MD_REPORT"
echo "" >> "$MD_REPORT"

echo "## 🏗️ Infrastructure Status (Application + Monitoring)" >> "$MD_REPORT"
bash infra/scripts/check-infra.sh >> "$MD_REPORT" 2>&1
echo "" >> "$MD_REPORT"

echo "## 📊 Monitoring Metrics Summary" >> "$MD_REPORT"
echo "" >> "$MD_REPORT"
echo "### Prometheus Targets" >> "$MD_REPORT"
echo '```' >> "$MD_REPORT"
curl -s http://localhost:9090/api/v1/targets 2>/dev/null | python3 -m json.tool 2>/dev/null || echo "Prometheus not reachable" >> "$MD_REPORT"
echo '```' >> "$MD_REPORT"
echo "" >> "$MD_REPORT"

echo "### Grafana Health" >> "$MD_REPORT"
echo '```' >> "$MD_REPORT"
curl -s http://localhost:3001/api/health 2>/dev/null || echo "Grafana not reachable" >> "$MD_REPORT"
echo '```' >> "$MD_REPORT"
echo "" >> "$MD_REPORT"

echo "### Loki Readiness" >> "$MD_REPORT"
echo '```' >> "$MD_REPORT"
curl -s http://localhost:3100/ready 2>/dev/null || echo "Loki not reachable" >> "$MD_REPORT"
echo '```' >> "$MD_REPORT"
echo "" >> "$MD_REPORT"

echo "### PostgreSQL Exporter Metrics (sample)" >> "$MD_REPORT"
echo '```' >> "$MD_REPORT"
curl -s http://localhost:9187/metrics 2>/dev/null | head -30 || echo "PostgreSQL Exporter not reachable" >> "$MD_REPORT"
echo '```' >> "$MD_REPORT"
echo "" >> "$MD_REPORT"

echo "### Notaire Backend Health" >> "$MD_REPORT"
echo '```' >> "$MD_REPORT"
curl -s http://localhost:8080/actuator/health 2>/dev/null | python3 -m json.tool 2>/dev/null || echo "Backend not reachable" >> "$MD_REPORT"
echo '```' >> "$MD_REPORT"
echo "" >> "$MD_REPORT"

echo "## 📦 Container Vulnerability Scan (Trivy)" >> "$MD_REPORT"
echo "Running scan on 'notary-backend' and 'notary-postgres'..."
if command -v trivy &> /dev/null; then
    echo "### Backend Image" >> "$MD_REPORT"
    trivy image --severity HIGH,CRITICAL --format table notary-backend:latest >> "$MD_REPORT" 2>&1
    echo "" >> "$MD_REPORT"
    echo "### PostgreSQL Image" >> "$MD_REPORT"
    trivy image --severity HIGH,CRITICAL --format table postgres:16 >> "$MD_REPORT" 2>&1
else
    echo "Trivy not found. Please run: 'docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image notary-backend:latest'" >> "$MD_REPORT"
fi
echo "" >> "$MD_REPORT"

echo "## 🔍 Static Analysis (SonarQube Summary)" >> "$MD_REPORT"
echo "Visit [SonarQube Dashboard](http://localhost:9000) for full details." >> "$MD_REPORT"
echo "Metrics included: Bugs, Vulnerabilities, Security Hotspots, Code Smells." >> "$MD_REPORT"
echo "" >> "$MD_REPORT"

echo "## 📚 Third-Party Libraries (SCA)" >> "$MD_REPORT"
echo "Visit [Dependency-Track](http://localhost:8085) to view SBOM and license compliance." >> "$MD_REPORT"
echo "" >> "$MD_REPORT"

echo "## 📈 Monitoring Dashboards" >> "$MD_REPORT"
echo "- **Backend API Dashboard**: [Grafana - notaire-backend](http://localhost:3001/d/notaire-backend)" >> "$MD_REPORT"
echo "- **PostgreSQL Dashboard**: [Grafana - notaire-postgres](http://localhost:3001/d/notaire-postgres)" >> "$MD_REPORT"
echo "- **Prometheus Targets**: [Prometheus](http://localhost:9090/targets)" >> "$MD_REPORT"
echo "- **Grafana Explore (Logs)**: [Grafana Explore](http://localhost:3001/explore)" >> "$MD_REPORT"
echo "" >> "$MD_REPORT"

echo "---" >> "$MD_REPORT"
echo "Report generated by Notaire DevSecOps & Monitoring Hub." >> "$MD_REPORT"
echo "Credentials: admin/admin for all services" >> "$MD_REPORT"

# Convert to HTML
echo "<html><body style='font-family: sans-serif; padding: 40px;'>" > "$HTML_REPORT"
if command -v pandoc &> /dev/null; then
    pandoc "$MD_REPORT" -o "$HTML_REPORT"
else
    echo "<h1>Notaire DevSecOps & Monitoring Report</h1>" >> "$HTML_REPORT"
    echo "<p>Generated on: $(date)</p>" >> "$HTML_REPORT"
    echo "<p><strong>Credentials:</strong> admin/admin for all services</p>" >> "$HTML_REPORT"
    echo "<pre>" >> "$HTML_REPORT"
    cat "$MD_REPORT" >> "$HTML_REPORT"
    echo "</pre>" >> "$HTML_REPORT"
fi
echo "</body></html>" >> "$HTML_REPORT"

echo "✅ Report generated: $MD_REPORT"
echo "✅ HTML view: $HTML_REPORT"
echo ""
echo "🔐 Credentials: admin/admin for all services"
