#!/bin/bash

# DevSecOps Report Generator
# Aggregates findings from various tools into a single report.

REPORT_DIR="infra/reports"
DATE=$(date +"%Y-%m-%d_%H-%M-%S")
MD_REPORT="$REPORT_DIR/security_report_$DATE.md"
HTML_REPORT="$REPORT_DIR/security_report_$DATE.html"

mkdir -p "$REPORT_DIR"

echo "# 🛡️ Notaire DevSecOps Security Report" > "$MD_REPORT"
echo "Generated on: $(date)" >> "$MD_REPORT"
echo "" >> "$MD_REPORT"

echo "## 🏗️ Infrastructure Status" >> "$MD_REPORT"
bash infra/scripts/check-infra.sh >> "$MD_REPORT" 2>&1
echo "" >> "$MD_REPORT"

echo "## 📦 Container Vulnerability Scan (Trivy)" >> "$MD_REPORT"
echo "Running scan on 'notary-backend'..."
# Assuming trivy is installed or running via docker
if command -v trivy &> /dev/null; then
    trivy image --severity HIGH,CRITICAL --format table notary-backend:latest >> "$MD_REPORT" 2>&1
else
    echo "Trivy not found. Please run: 'docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image notary-backend:latest'" >> "$MD_REPORT"
fi
echo "" >> "$MD_REPORT"

echo "## 🔍 Static Analysis (SonarQube Summary)" >> "$MD_REPORT"
echo "Visit [SonarQube Dashboard](http://localhost:9000) for full details." >> "$MD_REPORT"
echo "Metrics included: Bugs, Vulnerabilities, Security Hotspots, Code Smells." >> "$MD_REPORT"
echo "" >> "$MD_REPORT"

echo "## 📚 Third-Party Libraries (SCA)" >> "$MD_REPORT"
echo "Visit [Dependency-Track](http://localhost:8085) to view SBOM and license compliance." >> "$MD_REPORT"
echo "" >> "$MD_REPORT"

echo "---" >> "$MD_REPORT"
echo "Report generated by Notaire DevSecOps Hub." >> "$MD_REPORT"

# Simple conversion to HTML (very basic)
echo "<html><body style='font-family: sans-serif; padding: 40px;'>" > "$HTML_REPORT"
# Using a simple perl regex or just cat for now. 
# In a real scenario, we'd use 'pandoc' if available.
if command -v pandoc &> /dev/null; then
    pandoc "$MD_REPORT" -o "$HTML_REPORT"
else
    echo "<h1>Notaire DevSecOps Security Report</h1>" >> "$HTML_REPORT"
    echo "<p>Generated on: $(date)</p>" >> "$HTML_REPORT"
    echo "<pre>" >> "$HTML_REPORT"
    cat "$MD_REPORT" >> "$HTML_REPORT"
    echo "</pre>" >> "$HTML_REPORT"
fi
echo "</body></html>" >> "$HTML_REPORT"

echo "✅ Report generated: $MD_REPORT"
echo "✅ HTML view: $HTML_REPORT"
