/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.presupuestos;

import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import javax.swing.JMenuItem;

/**
 *
 * @author Tefi
 */
public class Presupuestos extends javax.swing.JInternalFrame
{

    private static Presupuestos instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem menuPresupuestos = new JMenuItem("Modulo Presupuestos");

    /**
     * Creates new form Presupuestos
     */
    private Presupuestos() {
        initComponents();
    }

    public static Presupuestos getInstancia() {
        if (instancia == null)
        {
            instancia = new Presupuestos();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        }

        return instancia;
    }

    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario) {
        Presupuestos.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getMenuPresupuestos() {
        return menuPresupuestos;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonCrearPresupuesto = new javax.swing.JButton();
        botonModificarPresupuesto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonBuscarPresupuesto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Modulo Presupuestos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonCrearPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/presupuestos/crearPresupuesto.png"))); // NOI18N
        botonCrearPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearPresupuestoActionPerformed(evt);
            }
        });

        botonModificarPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/presupuestos/modificarPresupuesto.png"))); // NOI18N
        botonModificarPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarPresupuestoActionPerformed(evt);
            }
        });

        jLabel1.setText("Crear Presupuesto");

        jLabel2.setText("Buscar Presupuesto");

        botonBuscarPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/presupuestos/buscarPresupuesto.png"))); // NOI18N
        botonBuscarPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarPresupuestoActionPerformed(evt);
            }
        });

        jLabel3.setText("Modificar Presupuesto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCrearPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonModificarPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBuscarPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonModificarPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBuscarPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonCrearPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(309, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(menuPresupuestos);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonCrearPresupuestoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCrearPresupuestoActionPerformed
    {//GEN-HEADEREND:event_botonCrearPresupuestoActionPerformed
        CrearPresupuesto.getInstancia().limpiarFormulario();
        Principal.cargarFormulario(CrearPresupuesto.getInstancia());
        Principal.setVentanasActivas(CrearPresupuesto.getVentanaCrearPresupuesto());
    }//GEN-LAST:event_botonCrearPresupuestoActionPerformed

    private void botonModificarPresupuestoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonModificarPresupuestoActionPerformed
    {//GEN-HEADEREND:event_botonModificarPresupuestoActionPerformed
        Principal.cargarFormulario(new ModificarPresupuesto());
        Principal.setVentanasActivas(ModificarPresupuesto.getVentanaModificarPresupuesto());
    }//GEN-LAST:event_botonModificarPresupuestoActionPerformed

    private void botonBuscarPresupuestoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonBuscarPresupuestoActionPerformed
    {//GEN-HEADEREND:event_botonBuscarPresupuestoActionPerformed
        BuscarPresupuesto buscarPresupuesto = new BuscarPresupuesto();
        buscarPresupuesto.setFormularioInvocador(ConstantesGui.BUSCAR_PRESUPUESTO);
        Principal.cargarFormulario(buscarPresupuesto);
        Principal.setVentanasActivas(BuscarPresupuesto.getVentanaBuscarPresupuesto());
    }//GEN-LAST:event_botonBuscarPresupuestoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarPresupuesto;
    private javax.swing.JButton botonCrearPresupuesto;
    private javax.swing.JButton botonModificarPresupuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
