package com.licensis.notaire.dto;
// Generated 19/04/2012 16:59:26 by Hibernate Tools 3.2.1.GA

import com.licensis.notaire.dto.interfaces.DtoValido;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * DtoPresupuesto generated by hbm2java
 */
public class DtoBudget implements DtoValido {

    private Integer idBudget;
    private Integer number;
    private Date date;
    private String encabezado;
    private String status;
    private Float propertyAmount;
    private String notes;
    private Integer version = 0;
    private DtoPerson person;
    private List<DtoProcedure> listaProcedures = new ArrayList<>();
    private List<DtoItem> items = new ArrayList<>();

    public DtoBudget() {
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Integer getIdBudget() {
        return this.idBudget;
    }

    public void setIdBudget(Integer idBudget) {
        this.idBudget = idBudget;
    }

    public Integer getNumber() {
        return this.number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getEncabezado() {
        return this.encabezado;
    }

    public void setEncabezado(String encabezado) {
        this.encabezado = encabezado;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Float getPropertyAmount() {
        return this.propertyAmount;
    }

    public void setPropertyAmount(Float propertyAmount) {
        this.propertyAmount = propertyAmount;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public DtoPerson getPerson() {
        return this.person;
    }

    public void setPerson(DtoPerson persons) {
        this.person = persons;
    }

    public List<DtoProcedure> getListaProcedures() {
        return this.listaProcedures;
    }

    public void setListaProcedures(List<DtoProcedure> procedures) {
        this.listaProcedures = procedures;
    }

    public List<DtoItem> getItems() {
        return this.items;
    }

    public void setItems(List<DtoItem> items) {
        this.items = items;
    }

    @Deprecated
    public Float getSaldo() {
        return null;
    }

    @Deprecated
    public void setSaldo(Float saldo) {
    }

    @Deprecated
    public Float getTotal() {
        return propertyAmount;
    }

    @Deprecated
    public void setTotal(Float total) {
    }

    @Override
    public Boolean isValido() {
        return number != null && date != null && encabezado != null && status != null;
    }
}
