package com.licensis.notaire.dto;
// Generated 19/04/2012 16:59:26 by Hibernate Tools 3.2.1.GA

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.licensis.notaire.dto.interfaces.DtoValido;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DtoPersona generated by hbm2java
 */
public class DtoPerson implements DtoValido {

    private Integer idPerson;
    private String name;
    private String lastName;
    private String nationality;
    private String taxId;
    private String sex;
    private Date birthDate;
    private String maritalStatus;
    private Integer marriageCount;
    private String occupation;
    private String address;
    private String phone;
    private Integer notaryRegistrationNumber;
    private boolean isClient;
    private String numeroidentificacion;
    private String email;
    private DtoIdentificationType dtoIdentificationType = null;
    private Integer version;
    private ArrayList<DtoDeedManagement> listDtoManagementDeEscriturasNotary = new ArrayList<DtoDeedManagement>();
    private ArrayList<DtoDeedManagement> listaDtoManagementDeEscriturasPerson = new ArrayList<DtoDeedManagement>();
    private ArrayList<DtoProcedure> listaProceduresPerson = new ArrayList<DtoProcedure>();
    /*
     * Quitar luego los que nos necesarios
     */
    private Set usuarioses = new HashSet(0);
    private Set copiases = new HashSet(0);
    private Set suplenciasesForFkIdSubstitute = new HashSet(0);
    private Set suplenciasesForFkIdSubstituted = new HashSet(0);
    private Set presupuestoses = new HashSet(0);
    private Set identificacioneses = new HashSet(0);
    private Set folioses = new HashSet(0); /*
                                            * -----------------------------------
                                            */

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public DtoPerson() {
    }

    public DtoPerson(String name, String lastName, boolean isClient) {
        this.name = name;
        this.lastName = lastName;
        this.isClient = isClient;
    }

    public DtoPerson(String name, String lastName, String nationality, String taxId, String sex,
            Date birthDate, String maritalStatus, Integer marriageCount, String occupation, String address,
            String phone, Integer Email, Integer notaryRegistrationNumber, boolean isClient, Set usuarioses,
            Set tramiteses, Set copiases, Set suplenciasesForFkIdSubstitute, Set suplenciasesForFkIdSubstituted,
            Set presupuestoses, Set identificacioneses, Set folioses, Set gestionesDeEscriturases) {
        this.name = name;
        this.lastName = lastName;
        this.nationality = nationality;
        this.taxId = taxId;
        this.sex = sex;
        this.birthDate = birthDate;
        this.maritalStatus = maritalStatus;
        this.marriageCount = marriageCount;
        this.occupation = occupation;
        this.address = address;
        this.phone = phone;
        this.notaryRegistrationNumber = notaryRegistrationNumber;
        this.isClient = isClient;
        this.usuarioses = usuarioses;
        this.copiases = copiases;
        this.suplenciasesForFkIdSubstitute = suplenciasesForFkIdSubstitute;
        this.suplenciasesForFkIdSubstituted = suplenciasesForFkIdSubstituted;
        this.presupuestoses = presupuestoses;
        this.identificacioneses = identificacioneses;
        this.folioses = folioses;
    }

    public Integer getId() {
        return this.idPerson;
    }

    public void setId(Integer idPerson) {
        this.idPerson = idPerson;
    }

    public String getFirstName() {
        return this.name;
    }

    public void setFirstName(String name) {
        this.name = name;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getNationality() {
        return this.nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public String getTaxId() {
        return this.taxId;
    }

    public void setTaxId(String taxId) {
        this.taxId = taxId;
    }

    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public Date getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    public String getMaritalStatus() {
        return this.maritalStatus;
    }

    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    public Integer getMarriageCount() {
        return this.marriageCount;
    }

    public void setMarriageCount(Integer marriageCount) {
        this.marriageCount = marriageCount;
    }

    public String getOccupation() {
        return this.occupation;
    }

    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Integer getNotaryRegistrationNumber() {
        return this.notaryRegistrationNumber;
    }

    public void setNotaryRegistrationNumber(Integer notaryRegistrationNumber) {
        this.notaryRegistrationNumber = notaryRegistrationNumber;
    }

    public boolean getIsClient() {
        return this.isClient;
    }

    public void setIsClient(boolean isClient) {
        this.isClient = isClient;
    }

    public boolean isClient() {
        return this.isClient;
    }

    public Set getUsuarioses() {
        return this.usuarioses;
    }

    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }

    public Set getCopiases() {
        return this.copiases;
    }

    public void setCopiases(Set copiases) {
        this.copiases = copiases;
    }

    public Set getSuplenciasesForFkIdSubstitute() {
        return this.suplenciasesForFkIdSubstitute;
    }

    public void setSuplenciasesForFkIdSubstitute(Set suplenciasesForFkIdSubstitute) {
        this.suplenciasesForFkIdSubstitute = suplenciasesForFkIdSubstitute;
    }

    public Set getSuplenciasesForFkIdSubstituted() {
        return this.suplenciasesForFkIdSubstituted;
    }

    public void setSuplenciasesForFkIdSubstituted(Set suplenciasesForFkIdSubstituted) {
        this.suplenciasesForFkIdSubstituted = suplenciasesForFkIdSubstituted;
    }

    public Set getPresupuestoses() {
        return this.presupuestoses;
    }

    public void setPresupuestoses(Set presupuestoses) {
        this.presupuestoses = presupuestoses;
    }

    public Set getIdentificacioneses() {
        return this.identificacioneses;
    }

    public void setIdentificacioneses(Set identificacioneses) {
        this.identificacioneses = identificacioneses;
    }

    public Set getFolioses() {
        return this.folioses;
    }

    public void setFolioses(Set folioses) {
        this.folioses = folioses;
    }

    public void setIdentificationNumber(String identificationNumber) {
        this.numeroidentificacion = identificationNumber;
    }

    public String getIdentificationNumber() {
        return this.numeroidentificacion;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmail() {
        return this.email;
    }

    public DtoIdentificationType getDtoIdentificationType() {
        return dtoIdentificationType;
    }

    public void setDtoIdentificationType(DtoIdentificationType dtoIdentificationType) {
        this.dtoIdentificationType = dtoIdentificationType;
    }

    @JsonIgnore
    @Override
    public Boolean isValido() {
        // Simplified validation without backend dependencies
        if (this.getId() == null || this.getId() == ID_DTO_INICIALIZADO) {
            return false;
        }
        return true;
    }

    /*
     * Retorna las escrituras de un escribano, no la de la persona
     */
    public ArrayList<DtoDeedManagement> getListDtoManagementDeEscriturasDeNotary() {
        return listDtoManagementDeEscriturasNotary;
    }

    public ArrayList<DtoProcedure> getListaProceduresPerson() {
        return listaProceduresPerson;
    }

    public void setListaProceduresPerson(ArrayList<DtoProcedure> listaProceduresPerson) {
        this.listaProceduresPerson = listaProceduresPerson;
    }

    public void setListDtoManagementDeEscriturasDeNotary(ArrayList<DtoDeedManagement> listDtoManagementDeEscrituras) {
        this.listDtoManagementDeEscriturasNotary = listDtoManagementDeEscrituras;
    }

    public ArrayList<DtoDeedManagement> getListaDtoManagementDeEscriturasPerson() {
        return listaDtoManagementDeEscriturasPerson;
    }

    public void setListaDtoManagementDeEscriturasPerson(
            ArrayList<DtoDeedManagement> listaDtoManagementDeEscriturasPerson) {
        this.listaDtoManagementDeEscriturasPerson = listaDtoManagementDeEscriturasPerson;
    }
}
