package com.licensis.notaire.dto;
// Generated 19/04/2012 16:59:26 by Hibernate Tools 3.2.1.GA

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.licensis.notaire.dto.interfaces.DtoValido;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DtoPersona generated by hbm2java
 */
public class DtoPerson implements DtoValido {

    private Integer idPersona;
    private String nombre;
    private String apellido;
    private String nacionalidad;
    private String cuit;
    private String sexo;
    private Date fechaNacimiento;
    private String estadoCivil;
    private Integer numeroNupcias;
    private String ocupacion;
    private String domicilio;
    private String telefono;
    private Integer registroEscribano;
    private boolean esCliente;
    private String numeroidentificacion;
    private String eMail;
    private DtoTipoIdentificacion dtoTipoIdentificacion = null;
    private Integer version;
    private ArrayList<DtoGestionDeEscritura> listDtoGestionDeEscriturasEscribano = new ArrayList<DtoGestionDeEscritura>();
    private ArrayList<DtoGestionDeEscritura> listaDtoGestionDeEscriturasPersona = new ArrayList<DtoGestionDeEscritura>();
    private ArrayList<DtoTramite> listaTramitesPersona = new ArrayList<DtoTramite>();
    /*
     * Quitar luego los que nos necesarios
     */
    private Set usuarioses = new HashSet(0);
    private Set copiases = new HashSet(0);
    private Set suplenciasesForFkIdSuplente = new HashSet(0);
    private Set suplenciasesForFkIdSuplantado = new HashSet(0);
    private Set presupuestoses = new HashSet(0);
    private Set identificacioneses = new HashSet(0);
    private Set folioses = new HashSet(0); /*
                                            * -----------------------------------
                                            */

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public DtoPerson() {
    }

    public DtoPerson(String nombre, String apellido, boolean esCliente) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.esCliente = esCliente;
    }

    public DtoPerson(String nombre, String apellido, String nacionalidad, String cuit, String sexo,
            Date fechaNacimiento, String estadoCivil, Integer numeroNupcias, String ocupacion, String domicilio,
            String telefono, Integer EMail, Integer registroEscribano, boolean esCliente, Set usuarioses,
            Set tramiteses, Set copiases, Set suplenciasesForFkIdSuplente, Set suplenciasesForFkIdSuplantado,
            Set presupuestoses, Set identificacioneses, Set folioses, Set gestionesDeEscriturases) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.nacionalidad = nacionalidad;
        this.cuit = cuit;
        this.sexo = sexo;
        this.fechaNacimiento = fechaNacimiento;
        this.estadoCivil = estadoCivil;
        this.numeroNupcias = numeroNupcias;
        this.ocupacion = ocupacion;
        this.domicilio = domicilio;
        this.telefono = telefono;
        this.registroEscribano = registroEscribano;
        this.esCliente = esCliente;
        this.usuarioses = usuarioses;
        this.copiases = copiases;
        this.suplenciasesForFkIdSuplente = suplenciasesForFkIdSuplente;
        this.suplenciasesForFkIdSuplantado = suplenciasesForFkIdSuplantado;
        this.presupuestoses = presupuestoses;
        this.identificacioneses = identificacioneses;
        this.folioses = folioses;
    }

    public Integer getId() {
        return this.idPersona;
    }

    public void setId(Integer idPersona) {
        this.idPersona = idPersona;
    }

    public String getFirstName() {
        return this.nombre;
    }

    public void setFirstName(String nombre) {
        this.nombre = nombre;
    }

    public String getLastName() {
        return this.apellido;
    }

    public void setLastName(String apellido) {
        this.apellido = apellido;
    }

    public String getNationality() {
        return this.nacionalidad;
    }

    public void setNationality(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    public String getTaxId() {
        return this.cuit;
    }

    public void setTaxId(String cuit) {
        this.cuit = cuit;
    }

    public String getSex() {
        return this.sexo;
    }

    public void setSex(String sexo) {
        this.sexo = sexo;
    }

    public Date getBirthDate() {
        return this.fechaNacimiento;
    }

    public void setBirthDate(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public String getMaritalStatus() {
        return this.estadoCivil;
    }

    public void setMaritalStatus(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    public Integer getMarriageCount() {
        return this.numeroNupcias;
    }

    public void setMarriageCount(Integer numeroNupcias) {
        this.numeroNupcias = numeroNupcias;
    }

    public String getOccupation() {
        return this.ocupacion;
    }

    public void setOccupation(String ocupacion) {
        this.ocupacion = ocupacion;
    }

    public String getAddress() {
        return this.domicilio;
    }

    public void setAddress(String domicilio) {
        this.domicilio = domicilio;
    }

    public String getPhone() {
        return this.telefono;
    }

    public void setPhone(String telefono) {
        this.telefono = telefono;
    }

    public Integer getNotaryRegistrationNumber() {
        return this.registroEscribano;
    }

    public void setNotaryRegistrationNumber(Integer registroEscribano) {
        this.registroEscribano = registroEscribano;
    }

    public boolean getIsClient() {
        return this.esCliente;
    }

    public void setIsClient(boolean esCliente) {
        this.esCliente = esCliente;
    }

    public boolean isClient() {
        return this.esCliente;
    }

    public Set getUsuarioses() {
        return this.usuarioses;
    }

    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }

    public Set getCopiases() {
        return this.copiases;
    }

    public void setCopiases(Set copiases) {
        this.copiases = copiases;
    }

    public Set getSuplenciasesForFkIdSuplente() {
        return this.suplenciasesForFkIdSuplente;
    }

    public void setSuplenciasesForFkIdSuplente(Set suplenciasesForFkIdSuplente) {
        this.suplenciasesForFkIdSuplente = suplenciasesForFkIdSuplente;
    }

    public Set getSuplenciasesForFkIdSuplantado() {
        return this.suplenciasesForFkIdSuplantado;
    }

    public void setSuplenciasesForFkIdSuplantado(Set suplenciasesForFkIdSuplantado) {
        this.suplenciasesForFkIdSuplantado = suplenciasesForFkIdSuplantado;
    }

    public Set getPresupuestoses() {
        return this.presupuestoses;
    }

    public void setPresupuestoses(Set presupuestoses) {
        this.presupuestoses = presupuestoses;
    }

    public Set getIdentificacioneses() {
        return this.identificacioneses;
    }

    public void setIdentificacioneses(Set identificacioneses) {
        this.identificacioneses = identificacioneses;
    }

    public Set getFolioses() {
        return this.folioses;
    }

    public void setFolioses(Set folioses) {
        this.folioses = folioses;
    }

    public void setIdentificationNumber(String numeroIdentificacion) {
        this.numeroidentificacion = numeroIdentificacion;
    }

    public String getIdentificationNumber() {
        return this.numeroidentificacion;
    }

    public void setEmail(String eMail) {
        this.eMail = eMail;
    }

    public String getEmail() {
        return this.eMail;
    }

    public DtoTipoIdentificacion getDtoTipoIdentificacion() {
        return dtoTipoIdentificacion;
    }

    public void setDtoTipoIdentificacion(DtoTipoIdentificacion dtoTipoIdentificacion) {
        this.dtoTipoIdentificacion = dtoTipoIdentificacion;
    }

    @JsonIgnore
    @Override
    public Boolean isValido() {
        // Simplified validation without backend dependencies
        if (this.getId() == null || this.getId() == ID_DTO_INICIALIZADO) {
            return false;
        }
        return true;
    }

    /*
     * Retorna las escrituras de un escribano, no la de la persona
     */
    public ArrayList<DtoGestionDeEscritura> getListDtoGestionDeEscriturasDeEscribano() {
        return listDtoGestionDeEscriturasEscribano;
    }

    public ArrayList<DtoTramite> getListaTramitesPersona() {
        return listaTramitesPersona;
    }

    public void setListaTramitesPersona(ArrayList<DtoTramite> listaTramitesPersona) {
        this.listaTramitesPersona = listaTramitesPersona;
    }

    public void setListDtoGestionDeEscriturasDeEscribano(ArrayList<DtoGestionDeEscritura> listDtoGestionDeEscrituras) {
        this.listDtoGestionDeEscriturasEscribano = listDtoGestionDeEscrituras;
    }

    public ArrayList<DtoGestionDeEscritura> getListaDtoGestionDeEscriturasPersona() {
        return listaDtoGestionDeEscriturasPersona;
    }

    public void setListaDtoGestionDeEscriturasPersona(
            ArrayList<DtoGestionDeEscritura> listaDtoGestionDeEscriturasPersona) {
        this.listaDtoGestionDeEscriturasPersona = listaDtoGestionDeEscriturasPersona;
    }
}
