package com.licensis.notaire.dto;
// Generated 19/04/2012 16:59:26 by Hibernate Tools 3.2.1.GA

import com.licensis.notaire.dto.interfaces.DtoValido;
import java.util.ArrayList;
import java.util.List;

/**
 * DtoTipoDeTramite generated by hbm2java
 */
public class DtoProcedureType extends GenericDto implements DtoValido {

    private Integer idProcedureType;
    private String name;
    private Boolean isArchived;
    private Boolean isRegistered;
    private Boolean associatesProperties;
    private String notes;
    private Boolean enabled;
    private Integer version;
    private List<DtoProcedureTemplate> templateProcedures = new ArrayList<>();
    private Integer workflowDefinitionId;
    private String workflowDefinitionName;

    public DtoProcedureType() {
    }

    public DtoProcedureType(String name, Boolean isArchived, Boolean isRegistered, Boolean associatesProperties) {
        this.name = name;
        this.isArchived = isArchived;
        this.isRegistered = isRegistered;
        this.associatesProperties = associatesProperties;
    }

    public Integer getIdProcedureType() {
        return this.idProcedureType;
    }

    public void setIdProcedureType(Integer idProcedureType) {
        this.idProcedureType = idProcedureType;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.notes;
    }

    public void setDescription(String description) {
        this.notes = description;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Boolean getIsArchived() {
        return this.isArchived;
    }

    public Boolean isIsArchived() {
        return this.isArchived;
    }

    public void setIsArchived(Boolean isArchived) {
        this.isArchived = isArchived;
    }

    public Boolean getIsRegistered() {
        return this.isRegistered;
    }

    public Boolean isIsRegistered() {
        return this.isRegistered;
    }

    public void setIsRegistered(Boolean isRegistered) {
        this.isRegistered = isRegistered;
    }

    public Boolean getAssociatesProperties() {
        return this.associatesProperties;
    }

    public void setAssociatesProperties(Boolean associatesProperties) {
        this.associatesProperties = associatesProperties;
    }

    public Boolean isAssociatesProperties() {
        return this.associatesProperties;
    }

    public Boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public List<DtoProcedureTemplate> getTemplateProcedures() {
        return this.templateProcedures;
    }

    public void setTemplateProcedures(List<DtoProcedureTemplate> templateProcedures) {
        this.templateProcedures = templateProcedures;
    }

    // Backend-only method - kept for compatibility
    public List<DtoBudgetTemplate> getTemplatePresupuestos() {
        return new ArrayList<>();
    }

    public void setTemplatePresupuestos(List<DtoBudgetTemplate> templatePresupuestos) {
        // Backend-only, ignored in shared module
    }

    public Integer getWorkflowDefinitionId() {
        return workflowDefinitionId;
    }

    public void setWorkflowDefinitionId(Integer workflowDefinitionId) {
        this.workflowDefinitionId = workflowDefinitionId;
    }

    public String getWorkflowDefinitionName() {
        return workflowDefinitionName;
    }

    public void setWorkflowDefinitionName(String workflowDefinitionName) {
        this.workflowDefinitionName = workflowDefinitionName;
    }

    @Override
    public Boolean isValido() {
        // TODO: implementar.
        return true;
    }
}
