package com.licensis.notaire.dto;
// Generated 19/04/2012 16:59:26 by Hibernate Tools 3.2.1.GA

import com.licensis.notaire.dto.interfaces.DtoValido;
import java.util.Date;

/**
 * DtoDocumentoPresentado generated by hbm2java
 */
public class DtoSubmittedDocument implements DtoValido
{

    private int version;
    private Integer idSubmittedDocument;
    private DtoProcedure fkProcedure;
    private DtoDocumentType fkDocumentType;
    private String name;
    private Integer cardNumber;
    private Date dateEntry;
    private Date dateExit;
    private boolean prepared;
    private boolean expires;
    private Date dateDue;
    private Integer dueDays;
    private Float amountToPay;
    private Date datePayment;
    private boolean released;
    private Date dateReleased;
    private boolean flagged;
    private String notes;
    private boolean reentered;
    private String deliveredBy;
    private boolean delivered;

    public String getDeliveredBy()
    {
        return deliveredBy;
    }

    public void setDeliveredBy(String deliveredBy)
    {
        this.deliveredBy = deliveredBy;
    }

    public boolean isReentered()
    {
        return reentered;
    }

    public void setReentered(boolean reentered)
    {
        this.reentered = reentered;
    }

    public boolean isDelivered()
    {
        return delivered;
    }

    public void setDelivered(boolean delivered)
    {
        this.delivered = delivered;
    }

    public int getVersion()
    {
        return version;
    }

    public void setVersion(int version)
    {
        this.version = version;
    }

    public DtoSubmittedDocument()
    {
    }
    /*
     * public DtoDocumentoPresentado(DtoTramite tramites, String nombre, Date fechaIngreso, boolean
     * preparado, boolean vence, boolean liberado, boolean observado) {
     * this.fkTramite = tramites;
     * this.nombre = nombre;
     * this.fechaIngreso = fechaIngreso;
     * this.preparado = preparado;
     * this.vence = vence;
     * this.liberado = liberado;
     * this.observado = observado;
     * }
     *
     * public DtoDocumentoPresentado(DtoTramite tramites, String nombre, Integer numeroCarton, Date
     * fechaIngreso, Date fechaSalida, boolean preparado, boolean vence, Date fechaVencimiento,
     * Integer diasVencimiento, Float importeAPagar, Date fechaPago, boolean liberado, Date
     * fechaLiberado, boolean observado, String observaciones) {
     * this.fkTramite = tramites;
     * this.nombre = nombre;
     * this.numeroCarton = numeroCarton;
     * this.fechaIngreso = fechaIngreso;
     * this.fechaSalida = fechaSalida;
     * this.preparado = preparado;
     * this.vence = vence;
     * this.fechaVencimiento = fechaVencimiento;
     * this.diasVencimiento = diasVencimiento;
     * this.importeAPagar = importeAPagar;
     * this.fechaPago = fechaPago;
     * this.liberado = liberado;
     * this.fechaLiberado = fechaLiberado;
     * this.observado = observado;
     * this.observaciones = observaciones;
     * }
     */

    public Integer getIdSubmittedDocument()
    {
        return this.idSubmittedDocument;
    }

    public void setIdSubmittedDocument(Integer idSubmittedDocument)
    {
        this.idSubmittedDocument = idSubmittedDocument;
    }

    public DtoProcedure getFkProcedure()
    {
        return this.fkProcedure;
    }

    public void setFkProcedure(DtoProcedure procedures)
    {
        this.fkProcedure = procedures;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public Integer getCardNumber()
    {
        return this.cardNumber;
    }

    public void setCardNumber(Integer cardNumber)
    {
        this.cardNumber = cardNumber;
    }

    public Date getDateEntry()
    {
        return this.dateEntry;
    }

    public void setDateEntry(Date dateEntry)
    {
        this.dateEntry = dateEntry;
    }

    public Date getDateExit()
    {
        return this.dateExit;
    }

    public void setDateExit(Date dateExit)
    {
        this.dateExit = dateExit;
    }

    public boolean isPrepared()
    {
        return this.prepared;
    }

    public void setPrepared(boolean prepared)
    {
        this.prepared = prepared;
    }

    public boolean isExpires()
    {
        return this.expires;
    }

    public void setExpires(boolean expires)
    {
        this.expires = expires;
    }

    public Date getDateDue()
    {
        return this.dateDue;
    }

    public void setDateDue(Date dateDue)
    {
        this.dateDue = dateDue;
    }

    public Integer getDueDays()
    {
        return this.dueDays;
    }

    public void setDueDays(Integer dueDays)
    {
        this.dueDays = dueDays;
    }

    public Float getAmountToPay()
    {
        return this.amountToPay;
    }

    public void setAmountApagar(Float amountToPay)
    {
        this.amountToPay = amountToPay;
    }

    public Date getDatePayment()
    {
        return this.datePayment;
    }

    public void setDatePayment(Date datePayment)
    {
        this.datePayment = datePayment;
    }

    public boolean isReleased()
    {
        return this.released;
    }

    public void setReleased(boolean released)
    {
        this.released = released;
    }

    public Date getDateReleased()
    {
        return this.dateReleased;
    }

    public void setDateReleased(Date dateReleased)
    {
        this.dateReleased = dateReleased;
    }

    public boolean isFlagged()
    {
        return this.flagged;
    }

    public void setFlagged(boolean flagged)
    {
        this.flagged = flagged;
    }

    public String getNotes()
    {
        return this.notes;
    }

    public void setNotes(String notes)
    {
        this.notes = notes;
    }

    @Override
    public Boolean isValido()
    {
        //  TODO: Implementar
        return true;
    }
}
