package com.licensis.notaire.dto;
// Generated 19/04/2012 16:59:26 by Hibernate Tools 3.2.1.GA

import com.licensis.notaire.dto.interfaces.DtoValido;
import java.util.ArrayList;
import java.util.List;

/**
 * DtoTestimonio generated by hbm2java
 */
public class DtoTestimony implements DtoValido
{

    private Integer idTestimony;
    private DtoDeed deed;
    private int number;
    private boolean flagged;
    private boolean verified;
    private String notes;
    private int version = 0;
    private List<DtoCopy> copies = new ArrayList();
    private List<DtoTestimonyMovement> movimientosTestimonios = new ArrayList();

    public DtoTestimony()
    {
    }

    public int getVersion()
    {
        return version;
    }

    public void setVersion(int version)
    {
        this.version = version;
    }

    public Integer getIdTestimony()
    {
        return this.idTestimony;
    }

    public void setIdTestimony(Integer idTestimony)
    {
        this.idTestimony = idTestimony;
    }

    public DtoDeed getDeed()
    {
        return this.deed;
    }

    public void setDeed(DtoDeed deed)
    {
        this.deed = deed;
    }

    public int getNumber()
    {
        return this.number;
    }

    public void setNumber(int number)
    {
        this.number = number;
    }

    public boolean isFlagged()
    {
        return this.flagged;
    }

    public void setFlagged(boolean flagged)
    {
        this.flagged = flagged;
    }

    public boolean isVerified()
    {
        return this.verified;
    }

    public void setVerified(boolean verified)
    {
        this.verified = verified;
    }

    public String getNotes()
    {
        return this.notes;
    }

    public void setNotes(String notes)
    {
        this.notes = notes;
    }

    public List<DtoCopy> getCopies()
    {
        return this.copies;
    }

    public void setCopies(List<DtoCopy> misCopies)
    {
        this.copies = misCopies;
    }

    public List<DtoTestimonyMovement> getMovimientosTestimonios()
    {
        return this.movimientosTestimonios;
    }

    public void setMovimientosTestimonios(List<DtoTestimonyMovement> movimientosTestimonios)
    {
        this.movimientosTestimonios = movimientosTestimonios;
    }

    @Override
    public Boolean isValido()
    {
        //  TODO: implementar.
        return true;
    }
}
