/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.gestiones.gestion;

import com.licensis.notaire.api.client.RestMapper;
import com.licensis.notaire.dto.GenericDto;
import com.licensis.notaire.dto.DtoGestionDeEscritura;
import com.licensis.notaire.dto.exceptions.DtoInvalidoException;
import com.licensis.notaire.gui.Principal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import com.licensis.notaire.jpa.exceptions.ClassModifiedException;
import com.licensis.notaire.jpa.exceptions.NonexistentJpaException;
import com.licensis.notaire.negocio.ConstantesNegocio;
import com.licensis.notaire.servicios.AdministradorJpa;

/**
 *
 * @author matias
 */
public class ArchivarGestion extends javax.swing.JInternalFrame {

    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem ventanaArchivarGestion = new JMenuItem("Ventana Archivar Gestion");
    private static ArchivarGestion instancia = null;
    private final AdministradorJpa adminJpa = AdministradorJpa.getInstancia();

    /**
     * Creates new form ArchivarGestion
     */
    private ArchivarGestion() {
        initComponents();
        estadoFormulario = Boolean.TRUE;
        this.setSize(Principal.tamanioGrandeHorizontal, Principal.tamanioGrandeVertical);
    }

    public static ArchivarGestion getInstancia() {
        if (instancia == null) {
            instancia = new ArchivarGestion();
        }
        return instancia;
    }

    private void salir() {
        this.dispose();
    }

    public static JMenuItem getVentanaArchivarGestion() {
        return ventanaArchivarGestion;
    }

    public Boolean cargarGrillaGestiones() {
        Boolean flag = false;
        List<DtoGestionDeEscritura> listaDtoGestionDeEscrituras = new ArrayList<>();

        this.limpiarJtable();
        this.activarGrilla();

        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

        try {
            java.util.List<GenericDto> rawGestiones = adminJpa.getGestionJpa().findAll();
            for (GenericDto raw : rawGestiones) {
                DtoGestionDeEscritura dto = RestMapper.toDtoGestion(raw);
                if (dto.getEstado() == null || dto.getEstado().getNombre() == null
                        || !ConstantesNegocio.GESTION_ARCHIVADA.equalsIgnoreCase(dto.getEstado().getNombre())) {
                    listaDtoGestionDeEscrituras.add(dto);
                }
            }

            if (!listaDtoGestionDeEscrituras.isEmpty()) {
                DtoGestionDeEscritura miDtoGestion = null;
                for (int i = 0; i < listaDtoGestionDeEscrituras.size(); i++) {
                    flag = true;
                    miDtoGestion = listaDtoGestionDeEscrituras.get(i);

                    Object[] datos = {
                            miDtoGestion.getNumero(),
                            miDtoGestion.getEncabezado(),
                            formatter.format(miDtoGestion.getFechaInicio()),
                            miDtoGestion.getEstado().getNombre(),
                            miDtoGestion.getNumeroBibliorato(),
                            miDtoGestion.getObservaciones(),
                            miDtoGestion
                    };

                    ((DefaultTableModel) grillaGestiones.getModel()).addRow(datos);

                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ArchivarGestion.class.getName()).log(Level.SEVERE, null, ex);
        }
        return flag;
    }

    public void activarGrilla() {
        this.grillaGestiones.setEnabled(true);

    }

    public void desactivarGrilla() {
        this.grillaGestiones.setEnabled(false);
        this.limpiarJtable();
    }

    public void limpiarJtable() {
        int i = ((DefaultTableModel) grillaGestiones.getModel()).getRowCount() - 1;

        while (((DefaultTableModel) grillaGestiones.getModel()).getRowCount() > 0) {
            ((DefaultTableModel) grillaGestiones.getModel()).removeRow(i);
            i--;
        }
        this.botonAceptar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelArchivarGestion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grillaGestiones = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Archivar Gestión");
        setPreferredSize(new java.awt.Dimension(1000, 584));
        setRequestFocusEnabled(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }

            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }

            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelArchivarGestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelArchivarGestionMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Archivar Gestión");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        grillaGestiones.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Nro Gestión", "Encabezado", "Fecha Inicio", "Estado", "Nro. Bibliorato", "Observaciones",
                        "DtoGestion", "Archivada"
                }) {
            Class[] types = new Class[] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        grillaGestiones.getColumnModel().getColumn(6).setMaxWidth(0);
        grillaGestiones.getColumnModel().getColumn(6).setMinWidth(0);
        grillaGestiones.getColumnModel().getColumn(6).setMaxWidth(0);
        grillaGestiones.getColumnModel().getColumn(6).setMinWidth(0);
        grillaGestiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grillaGestionesMouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                grillaGestionesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(grillaGestiones);

        javax.swing.GroupLayout panelArchivarGestionLayout = new javax.swing.GroupLayout(panelArchivarGestion);
        panelArchivarGestion.setLayout(panelArchivarGestionLayout);
        panelArchivarGestionLayout.setHorizontalGroup(
                panelArchivarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelArchivarGestionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelArchivarGestionLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArchivarGestionLayout
                                                .createSequentialGroup()
                                                .addGap(0, 447, Short.MAX_VALUE)
                                                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelArchivarGestionLayout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 976,
                                                Short.MAX_VALUE))
                                .addContainerGap()));
        panelArchivarGestionLayout.setVerticalGroup(
                panelArchivarGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelArchivarGestionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                                .addGap(11, 11, 11)
                                .addGroup(panelArchivarGestionLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelArchivarGestion, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelArchivarGestion, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_botonAceptarActionPerformed
    {// GEN-HEADEREND:event_botonAceptarActionPerformed

        int i = JOptionPane.showConfirmDialog(this, "¿Realmente Desea Archivar la Gestiones Indicadas?",
                "Confirmar Salida", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            try {
                ArrayList<DtoGestionDeEscritura> listGestionesArchivadas = (ArrayList<DtoGestionDeEscritura>) this
                        .archivarGestion();

                if ((listGestionesArchivadas != null) && (!listGestionesArchivadas.isEmpty())) {
                    this.cargarGrillaGestiones();
                    for (int j = 0; j < listGestionesArchivadas.size(); j++) {
                        int nroArchivo = listGestionesArchivadas.get(j).getIdGestion();
                        int nroBibliorato = listGestionesArchivadas.get(j).getNumeroBibliorato();
                        JOptionPane.showMessageDialog(this, "Numero de Archivo : " + nroArchivo
                                + " Para la Gestion del Bibliorato Nro: " + nroBibliorato);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No se ha ingreso el/los numero de biblioratos", "Advertencia",
                            JOptionPane.WARNING_MESSAGE);
                }

            } catch (Exception ex) {
                if (ex instanceof ClassModifiedException) {
                    String mensaje = "Gestion modificada con anterioridad - Accion Cancelada";
                    JOptionPane.showMessageDialog(this, mensaje, "Advertencia", JOptionPane.WARNING_MESSAGE);
                    this.cargarGrillaGestiones();
                    this.updateUI();
                    this.salir();
                } else if (ex instanceof DtoInvalidoException) {
                    JOptionPane.showMessageDialog(this, "Error grave, accion cancelada: " + ex.getMessage(), "Error",
                            JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(ArchivarGestion.class.getName()).log(Level.SEVERE, null, ex);
                    this.salir();
                } else {
                    JOptionPane.showMessageDialog(this, "Error grave, accion cancelada: " + ex.getMessage(), "Error",
                            JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(ArchivarGestion.class.getName()).log(Level.SEVERE, null, ex);
                    this.salir();
                }
            }

        } else {
            this.toFront();
        }

    }// GEN-LAST:event_botonAceptarActionPerformed

    public List<DtoGestionDeEscritura> archivarGestion()
            throws NonexistentJpaException, DtoInvalidoException, ClassModifiedException {

        TableModel miGrilla = this.grillaGestiones.getModel();
        int filas = miGrilla.getRowCount();

        List<DtoGestionDeEscritura> listaDtoGestionesArchivadas = new ArrayList<>();

        try {
            for (int i = 0; i < filas; i++) {
                if (miGrilla.getValueAt(i, 7) != null) {
                    boolean flag = Boolean.TRUE.equals(miGrilla.getValueAt(i, 7));
                    if (flag) {
                        DtoGestionDeEscritura dtoGestionEscritura = (DtoGestionDeEscritura) grillaGestiones.getValueAt(i, 6);
                        dtoGestionEscritura.setNumeroBibliorato(objToInt(grillaGestiones.getValueAt(i, 4)));
                        dtoGestionEscritura.setObservaciones(String.valueOf(grillaGestiones.getValueAt(i, 5)));
                        listaDtoGestionesArchivadas.add(dtoGestionEscritura);
                    }
                }
            }

            Integer idEstadoArchivada = resolverIdEstadoArchivada();
            if (idEstadoArchivada == null) {
                return null;
            }

            for (DtoGestionDeEscritura dto : listaDtoGestionesArchivadas) {
                GenericDto payload = new GenericDto();
                payload.put("idGestion", dto.getIdGestion());
                payload.put("numero", dto.getNumero());
                payload.put("fechaInicio", dto.getFechaInicio());
                payload.put("encabezado", dto.getEncabezado());
                payload.put("observaciones", dto.getObservaciones());
                payload.put("numeroBibliorato", dto.getNumeroBibliorato());
                payload.put("fkIdEstadoDeGestion", estadoRef(idEstadoArchivada));
                if (dto.getPersonaEscribano() != null && dto.getPersonaEscribano().getIdPersona() != null) {
                    payload.put("fkIdPersonaEscribano", personaRef(dto.getPersonaEscribano().getIdPersona()));
                }
                adminJpa.getGestionJpa().edit(payload);
            }
            return listaDtoGestionesArchivadas;
        } catch (Exception ex) {
            Logger.getLogger(ArchivarGestion.class.getName()).log(Level.SEVERE, "Error archivando gestion", ex);
            return null;
        }
    }

    private Integer resolverIdEstadoArchivada() throws java.io.IOException {
        for (GenericDto e : adminJpa.getEstadoDeGestionJpa().findAll()) {
            if (ConstantesNegocio.GESTION_ARCHIVADA.equalsIgnoreCase(e.getString("nombre"))) {
                return e.getInt("idEstadoGestion");
            }
        }
        return null;
    }

    private static GenericDto estadoRef(int id) {
        GenericDto ref = new GenericDto();
        ref.put("idEstadoGestion", id);
        return ref;
    }

    private static GenericDto personaRef(int id) {
        GenericDto ref = new GenericDto();
        ref.put("idPersona", id);
        return ref;
    }

    private static int objToInt(Object o) {
        if (o == null) return 0;
        if (o instanceof Number n) return n.intValue();
        return o.hashCode();
    }

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_botonCancelarActionPerformed
    {// GEN-HEADEREND:event_botonCancelarActionPerformed
        salir();
    }// GEN-LAST:event_botonCancelarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)// GEN-FIRST:event_formInternalFrameClosed
    {// GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(ventanaArchivarGestion);
        Principal.eliminarFormulario(this);
    }// GEN-LAST:event_formInternalFrameClosed

    private void grillaGestionesMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_grillaGestionesMouseClicked
        botonAceptar.setEnabled(true);

    }// GEN-LAST:event_grillaGestionesMouseClicked

    private void grillaGestionesMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_grillaGestionesMousePressed
        botonAceptar.enable(true);
    }// GEN-LAST:event_grillaGestionesMousePressed

    private void panelArchivarGestionMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_panelArchivarGestionMouseClicked
    }// GEN-LAST:event_panelArchivarGestionMouseClicked
     // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTable grillaGestiones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelArchivarGestion;
    // End of variables declaration//GEN-END:variables
}
