/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.estadosGestion;

import com.licensis.notaire.dto.GenericDto;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.servicios.AdministradorJpa;
import com.licensis.notaire.servicios.GenericRestClient;
import java.io.IOException;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author matias
 */
public class ModificarEstadoGestion extends javax.swing.JInternalFrame
{

    private static JMenuItem ventanaModificarEstadoDeGestion = new JMenuItem("Ventana Modificar Estado de Gestion");
    private List<DtoEstadoDeGestion> miListaEstadosDeGestion = null;
    private DtoEstadoDeGestion dtoSeleccionado = null;

    /**
     * Creates new form ModificarEstadoGestion
     */
    public ModificarEstadoGestion()
    {
        initComponents();
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        estadoGestionClient = AdministradorJpa.getInstancia().getEstadoDeGestionJpa();
        cargarListaEstadosDeGestion();
    }

    private void salir()
    {
        this.dispose();
    }

    public static JMenuItem getVentanaModificarEstadoDeGestion()
    {
        return ventanaModificarEstadoDeGestion;
    }

    private void limpiarFormulario()
    {
        this.campoNombreEstadoGestion.setText("");
        this.campoObservacionesEstadoGestion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        panelModificarEstadoGestion = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoObservacionesEstadoGestion = new javax.swing.JTextArea();
        campoNombreEstadoGestion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaEstadosDisponibles = new javax.swing.JList();
        botonSeleccionar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setMaximizable(true);
        setTitle("Modificar Estado para Gestion");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Modificar Estado Gestión");

        campoObservacionesEstadoGestion.setColumns(20);
        campoObservacionesEstadoGestion.setRows(5);
        jScrollPane1.setViewportView(campoObservacionesEstadoGestion);

        campoNombreEstadoGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreEstadoGestionActionPerformed(evt);
            }
        });

        jLabel3.setText("Observaciones:");

        jLabel2.setText("Nombre:");

        jLabel6.setText("Lista de Estados Disponibles:");

        listaEstadosDisponibles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(listaEstadosDisponibles);

        botonSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/aceptar.png"))); // NOI18N
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelModificarEstadoGestionLayout = new javax.swing.GroupLayout(panelModificarEstadoGestion);
        panelModificarEstadoGestion.setLayout(panelModificarEstadoGestionLayout);
        panelModificarEstadoGestionLayout.setHorizontalGroup(
            panelModificarEstadoGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarEstadoGestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarEstadoGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarEstadoGestionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelModificarEstadoGestionLayout.createSequentialGroup()
                        .addGroup(panelModificarEstadoGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(panelModificarEstadoGestionLayout.createSequentialGroup()
                                .addGroup(panelModificarEstadoGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelModificarEstadoGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNombreEstadoGestion)
                                    .addComponent(jScrollPane1)))
                            .addComponent(jSeparator1)
                            .addComponent(botonSeleccionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 61, Short.MAX_VALUE))))
        );
        panelModificarEstadoGestionLayout.setVerticalGroup(
            panelModificarEstadoGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarEstadoGestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelModificarEstadoGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombreEstadoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelModificarEstadoGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(panelModificarEstadoGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(panelModificarEstadoGestion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreEstadoGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreEstadoGestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreEstadoGestionActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAceptarActionPerformed
    {//GEN-HEADEREND:event_botonAceptarActionPerformed

        dtoSeleccionado.put("nombre", campoNombreEstadoGestion.getText());
        dtoSeleccionado.put("observaciones", campoObservacionesEstadoGestion.getText());

        try
        {
            estadoGestionClient.edit(dtoSeleccionado);
            JOptionPane.showMessageDialog(this, "Se ha modificado el estado de gestion.", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            salir();
        }
        catch (IOException ex)
        {
            JOptionPane.showMessageDialog(this, "Error al comunicarse con el servidor: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "Error al modificar estado de gestión", ex);
            this.cargarListaEstadosDeGestion();
            this.limpiarFormulario();
        }

        limpiarFormulario();

    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
        salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        Principal.removeVentanaActivas(ventanaModificarEstadoDeGestion);
        Principal.eliminarFormulario(this);

    }//GEN-LAST:event_formInternalFrameClosed

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonSeleccionarActionPerformed
    {//GEN-HEADEREND:event_botonSeleccionarActionPerformed
        this.limpiarFormulario();
        try
        {
            String nombreEstado = listaEstadosDisponibles.getSelectedValue().toString();

            for (Iterator<GenericDto> it = miListaEstadosDeGestion.iterator(); it.hasNext();)
            {
                GenericDto dtoEstadoDeGestion = it.next();

                if (nombreEstado.equals(dtoEstadoDeGestion.getString("nombre")))
                {
                    cargarEstado(dtoEstadoDeGestion);
                    break;
                }
            }
        }
        catch (NullPointerException ex)
        {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun elemento", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    private void cargarListaEstadosDeGestion()
    {
        try
        {
            miListaEstadosDeGestion = estadoGestionClient.findAll();

            if (miListaEstadosDeGestion != null && !miListaEstadosDeGestion.isEmpty())
            {
                //  limpiar lista de estados antes de cargar la nueva.
                listaEstadosDisponibles.removeAll();

                DefaultListModel lista = new DefaultListModel();

                for (Iterator<GenericDto> it = miListaEstadosDeGestion.iterator(); it.hasNext();)
                {
                    GenericDto dtoEstadoDeGestion = it.next();
                    String nombre = dtoEstadoDeGestion.getString("nombre");
                    if (nombre != null)
                    {
                        lista.addElement(nombre);
                    }
                }

                this.listaEstadosDisponibles.setModel(lista);
            } else
            {
                JOptionPane.showMessageDialog(this, "No existen estado para modificar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        }
        catch (IOException ex)
        {
            JOptionPane.showMessageDialog(this, "Error al cargar estados de gestión: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "Error al cargar estados de gestión", ex);
        }
    }

    private void cargarEstado(GenericDto unDto)
    {
        dtoSeleccionado = unDto;

        this.campoNombreEstadoGestion.setText(unDto.getString("nombre"));
        this.campoObservacionesEstadoGestion.setText(unDto.getString("observaciones"));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JTextField campoNombreEstadoGestion;
    private javax.swing.JTextArea campoObservacionesEstadoGestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList listaEstadosDisponibles;
    private javax.swing.JPanel panelModificarEstadoGestion;
    // End of variables declaration//GEN-END:variables
}
