/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.protocolo;

import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.gui.protocolo.folios.IngresarFolios;
import com.licensis.notaire.gui.protocolo.folios.ModificarFolio;
import javax.swing.JMenuItem;

/**
 *
 * @author matias
 */
public class Folios extends javax.swing.JInternalFrame
{

    private static Folios instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem subModuloAdministrarFolios = new JMenuItem("Sub-Modulo Administrar Folios");

    /**
     * Creates new form Folios
     */
    private Folios() {
        initComponents();
    }

    public static Folios getInstancia() {
        if (instancia == null)
        {
            instancia = new Folios();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        }
        return instancia;
    }

    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario) {
        Folios.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getSubModuloAdministrarFolios() {
        return subModuloAdministrarFolios;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonIngresarFolios = new javax.swing.JButton();
        botonModificarFolio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Sub-Modulo Administrar Folios");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonIngresarFolios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/protocolo/folios/ingresarFolios.png"))); // NOI18N
        botonIngresarFolios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarFoliosActionPerformed(evt);
            }
        });

        botonModificarFolio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/protocolo/folios/modificarFolio.png"))); // NOI18N
        botonModificarFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarFolioActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingresar Folios");

        jLabel2.setText("Modificar Folio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonIngresarFolios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(botonModificarFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonModificarFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonIngresarFolios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(288, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(subModuloAdministrarFolios);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonIngresarFoliosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonIngresarFoliosActionPerformed
    {//GEN-HEADEREND:event_botonIngresarFoliosActionPerformed
        Principal.cargarFormulario(new IngresarFolios());
        Principal.setVentanasActivas(IngresarFolios.getVentanaIngresarFolios());
    }//GEN-LAST:event_botonIngresarFoliosActionPerformed

    private void botonModificarFolioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonModificarFolioActionPerformed
    {//GEN-HEADEREND:event_botonModificarFolioActionPerformed
        Principal.cargarFormulario(new ModificarFolio());
        Principal.setVentanasActivas(ModificarFolio.getVentanaModificarFolio());
    }//GEN-LAST:event_botonModificarFolioActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresarFolios;
    private javax.swing.JButton botonModificarFolio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
