/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.protocolo;

import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.gui.CartelConstruccion;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author matias
 */
public class Protocolo extends javax.swing.JInternalFrame
{

    private static Protocolo instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem menuProtocolos = new JMenuItem("Modulo Protocolos");

    /**
     * Creates new form Protocolo
     */
    private Protocolo() {
        initComponents();
    }

    public static Protocolo getInstancia() {
        if (instancia == null)
        {
            instancia = new Protocolo();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        }
        return instancia;
    }

    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario) {
        Protocolo.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getMenuProtocolos() {
        return menuProtocolos;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAdministrarFolios = new javax.swing.JButton();
        botonDDJJ = new javax.swing.JButton();
        botonIndices = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Modulo Protocolo");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonAdministrarFolios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/protocolo/folios.png"))); // NOI18N
        botonAdministrarFolios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministrarFoliosActionPerformed(evt);
            }
        });

        botonDDJJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/protocolo/generarDDJJ.png"))); // NOI18N
        botonDDJJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDDJJActionPerformed(evt);
            }
        });

        botonIndices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/protocolo/generarIndices.png"))); // NOI18N
        botonIndices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIndicesActionPerformed(evt);
            }
        });

        jLabel1.setText("Folios");

        jLabel2.setText("Generar DDJJ");

        jLabel3.setText("Generar Indices");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAdministrarFolios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonDDJJ, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(botonIndices, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonIndices, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDDJJ, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAdministrarFolios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(308, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(menuProtocolos);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonAdministrarFoliosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAdministrarFoliosActionPerformed
    {//GEN-HEADEREND:event_botonAdministrarFoliosActionPerformed

        if (Folios.getEstadoFormulario() == Boolean.FALSE)
        {
            Principal.cargarFormulario(Folios.getInstancia());
            Principal.setVentanasActivas(Folios.getSubModuloAdministrarFolios());
        }
        else
        {
            for (int i = 0; i < Principal.AreaTrabajo.getAllFrames().length; i++)
            {
                if (Principal.AreaTrabajo.getAllFrames()[i].equals(Folios.getInstancia()))
                {
                    Principal.cargarFormulario(Folios.getInstancia());
                }
            }
        }
    }//GEN-LAST:event_botonAdministrarFoliosActionPerformed

    private void botonDDJJActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonDDJJActionPerformed
    {//GEN-HEADEREND:event_botonDDJJActionPerformed
        CartelConstruccion miConstruccion = new CartelConstruccion();
        Principal.cargarFormulario(miConstruccion);
        /*
         * Principal.cargarFormulario(new GenerarDDJJ());
         * Principal.setVentanasActivas(GenerarDDJJ.getVentanaGenerarDDJJ());
         */
    }//GEN-LAST:event_botonDDJJActionPerformed

    private void botonIndicesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonIndicesActionPerformed
    {//GEN-HEADEREND:event_botonIndicesActionPerformed
        CartelConstruccion miConstruccion = new CartelConstruccion();
        Principal.cargarFormulario(miConstruccion);
        /*
         * Principal.cargarFormulario(new GenerarIndices());
         * Principal.setVentanasActivas(GenerarIndices.getVentanaGenerarIndice());
         */
    }//GEN-LAST:event_botonIndicesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdministrarFolios;
    private javax.swing.JButton botonDDJJ;
    private javax.swing.JButton botonIndices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
