/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.gestiones.testimonios;

import com.licensis.notaire.dto.DtoCopia;
import com.licensis.notaire.dto.DtoEscritura;
import com.licensis.notaire.dto.DtoMovimientoTestimonio;
import com.licensis.notaire.dto.DtoTestimonio;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.negocio.ControllerNegocio;
import com.licensis.notaire.servicios.AdministradorValidaciones;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author matias
 */
public class GenerarTestimonio extends javax.swing.JInternalFrame
{

    private static JMenuItem ventanaGenerarTestimonio = new JMenuItem("Ventana Generar Testimonios");
    private static Integer cantidadCopias = new Integer(0);
    private DtoEscritura miEscritura = null;
    private ControllerNegocio miController = ControllerNegocio.getInstancia();
    private int numeroTestimonio = 1;

    /**
     * Creates new form DetalleTestimonio
     */
    public GenerarTestimonio()
    {
        initComponents();
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioGrandeVertical);
    }

    private void salir()
    {
        this.dispose();
    }

    public static JMenuItem getVentanaGenerarTestimonio()
    {
        return ventanaGenerarTestimonio;
    }

    public Boolean cargarFormulario(DtoEscritura miDtoEscritura)
    {
        miEscritura = miDtoEscritura;
        Boolean cargada = true;
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

        if (miDtoEscritura.getFechaInscripcion() == null)
        {
            List<DtoTestimonio> testimoniosEscritura = miController.obtenerTestimoniosEscritura(miDtoEscritura);

            if (testimoniosEscritura != null && !testimoniosEscritura.isEmpty())
            {
                List<DtoMovimientoTestimonio> movimientoTestimonios = miController.obtenerMovimientosTestimonio(testimoniosEscritura.get(testimoniosEscritura.size() - 1));

                if (movimientoTestimonios == null)
                {
                    numeroTestimonio = testimoniosEscritura.get(testimoniosEscritura.size() - 1).getNumero();
                    Integer valor = numeroTestimonio + 1;
                    labelTestimonio.setText(valor.toString());
                    labelInformacion.setText("La escritura tiene generados testimonios: " + numeroTestimonio);
                } else
                {
                    JOptionPane.showMessageDialog(this, "<HTML>No se puede generar el testimonio <BR> ya que la Escritura ya tiene uno asociado <BR>y ha sido ingresado para inscribir.</HTML>", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                    cargada = false;
                }
            } else
            {
                labelTestimonio.setText(new Integer(1).toString());
            }

            labelTestimonio.setEnabled(false);
            campoNumeroEscritura.setText(new Integer(miDtoEscritura.getNumero()).toString());
            campoFechaEscritura.setText(formatter.format(miDtoEscritura.getFechaEscrituracion()).toString());
            campoFolioDesde.setText(new Integer(miDtoEscritura.getFolios().get(0).getNumero()).toString());
            campoFolioHasta.setText(new Integer(miDtoEscritura.getFolios().get(miDtoEscritura.getFolios().size() - 1).getNumero()).toString());
        } else
        {
            JOptionPane.showMessageDialog(this, "<HTML>No se puede generar el testimonio <BR>ya que la Escritura ha sido Inscripta.</HTML>", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            cargada = false;
        }

        return cargada;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoNumeroEscritura = new javax.swing.JTextField();
        campoFolioDesde = new javax.swing.JTextField();
        campoFolioHasta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        selectorFechaGeneracion = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        campoFechaEscritura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        selectorCantidadCopias = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoObservaciones = new javax.swing.JTextArea();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        labelValidacion = new javax.swing.JLabel();
        labelInformacion = new javax.swing.JLabel();
        labelTestimonio = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Generar Testimonios");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel2.setText("Número de Escritura:");

        jLabel10.setText("Desde:");

        jLabel3.setText("Fecha:");

        jLabel4.setText("Folios Utilizados:");

        jLabel5.setText("Hasta:");

        jLabel6.setText("Inclusive");

        campoNumeroEscritura.setEditable(false);

        campoFolioDesde.setEditable(false);
        campoFolioDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFolioDesdeActionPerformed(evt);
            }
        });

        campoFolioHasta.setEditable(false);

        jLabel7.setText("Testimonio:");

        jLabel8.setText("Fecha Generación:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Registrar Testimonio");

        campoFechaEscritura.setEditable(false);

        jLabel1.setText("Cantidad de copias:");

        jLabel9.setText("(Primer Testimonio:1, Segundo:2, etc.)");

        selectorCantidadCopias.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        selectorCantidadCopias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectorCantidadCopiasMouseClicked(evt);
            }
        });
        selectorCantidadCopias.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                selectorCantidadCopiasStateChanged(evt);
            }
        });
        selectorCantidadCopias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                selectorCantidadCopiasKeyPressed(evt);
            }
        });

        jLabel11.setText("Observaciones:");

        campoObservaciones.setColumns(20);
        campoObservaciones.setRows(5);
        jScrollPane1.setViewportView(campoObservaciones);

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        labelValidacion.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel11))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(selectorCantidadCopias, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(labelTestimonio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(campoNumeroEscritura, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoFolioDesde, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel5))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(17, 17, 17)
                                                        .addComponent(campoFolioHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel6))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(campoFechaEscritura))))
                                            .addComponent(jLabel9)))
                                    .addComponent(selectorFechaGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelValidacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 186, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNumeroEscritura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(campoFechaEscritura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoFolioDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(campoFolioHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTestimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(selectorFechaGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(selectorCantidadCopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(labelValidacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        Principal.removeVentanaActivas(ventanaGenerarTestimonio);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void limpiarFormulario()
    {
        miEscritura = null;
        labelInformacion.setText("");
        labelValidacion.setText("");
        campoFechaEscritura.setText("");
        campoFolioDesde.setText("");
        campoFolioHasta.setText("");
        campoNumeroEscritura.setText("");
        campoObservaciones.setText("");
        selectorCantidadCopias.setValue(0);
        selectorFechaGeneracion.setDate(null);
        labelTestimonio.setText(new Integer(0).toString());
    }

    private void campoFolioDesdeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_campoFolioDesdeActionPerformed
    {//GEN-HEADEREND:event_campoFolioDesdeActionPerformed
    }//GEN-LAST:event_campoFolioDesdeActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed

        AdministradorValidaciones admin = AdministradorValidaciones.getInstancia();

        if (selectorFechaGeneracion.getDate() != null)
        {
            if (!admin.validarCampoVacio(selectorFechaGeneracion.getDate().toString()))
            {

                DtoTestimonio miDtoTestimonio = new DtoTestimonio();
                DtoCopia miDtoCopia = null;
                List<DtoCopia> misCopias = new ArrayList<>();

                miDtoTestimonio.setEscritura(miEscritura);
                miDtoTestimonio.setNumero(Integer.parseInt(labelTestimonio.getText()));
                miDtoTestimonio.setObservaciones(campoObservaciones.getText());
                miDtoTestimonio.setObservado(false);

                for (int i = 0; i < ((Integer) selectorCantidadCopias.getValue()).intValue(); i++)
                {
                    miDtoCopia = new DtoCopia();
                    miDtoCopia.setNumero(i + 1);
                    miDtoCopia.setFechaImpresion(selectorFechaGeneracion.getDate());
                    miDtoCopia.setPersona(null);
                    misCopias.add(miDtoCopia);
                }

                Boolean creado = miController.crearTestimonio(miDtoTestimonio, misCopias);

                if (creado)
                {
                    JOptionPane.showMessageDialog(this, "Se ha registrado el Testimonio.", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                    limpiarFormulario();
                    salir();
                }

            } else
            {
                JOptionPane.showMessageDialog(this, "Debe completar la fecha de generacion.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }

        } else
        {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void selectorCantidadCopiasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_selectorCantidadCopiasKeyPressed
    }//GEN-LAST:event_selectorCantidadCopiasKeyPressed

    private void selectorCantidadCopiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectorCantidadCopiasMouseClicked
    }//GEN-LAST:event_selectorCantidadCopiasMouseClicked

    private void selectorCantidadCopiasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_selectorCantidadCopiasStateChanged
        /*
         * Integer valorCopias = (Integer) selectorNumeroTestimonio.getValue();
         *
         * if (valorCopias.intValue() <= 0) { labelValidacion.setText("La cantidad de copias debe
         * ser mayor a 0."); flag = false; } else { labelValidacion.setText(""); flag = true; }
         */
    }//GEN-LAST:event_selectorCantidadCopiasStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoFechaEscritura;
    private javax.swing.JTextField campoFolioDesde;
    private javax.swing.JTextField campoFolioHasta;
    private javax.swing.JTextField campoNumeroEscritura;
    private javax.swing.JTextArea campoObservaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelInformacion;
    private javax.swing.JLabel labelTestimonio;
    private javax.swing.JLabel labelValidacion;
    private javax.swing.JSpinner selectorCantidadCopias;
    private com.toedter.calendar.JDateChooser selectorFechaGeneracion;
    // End of variables declaration//GEN-END:variables
}
