/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.conceptos;

import com.licensis.notaire.gui.Principal;
import java.awt.Dimension;
import javax.swing.JMenuItem;

/**
 *
 * @author matias
 */
public class Conceptos extends javax.swing.JInternalFrame
{

    private static Conceptos instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem submenuConceptos = new JMenuItem("Sub-Modulo Conceptos");

    /**
     * Creates new form Conceptos
     */
    private Conceptos() {
        initComponents();
    }

    public static Conceptos getInstancia() {
        if (instancia == null)
        {
            instancia = new Conceptos();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
            instancia.setMinimumSize(new Dimension(Principal.tamanioMinimoHorizontal, Principal.tamanioMinimoVertical));
        }
        return instancia;
    }

    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario) {
        Conceptos.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getSubmenuConceptos() {
        return submenuConceptos;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonIngresarConcepto = new javax.swing.JButton();
        botonModificarConcepto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonEliminarConcepto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Sub-Modulo Conceptos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonIngresarConcepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/administracion/conceptos/nuevoConcepto.png"))); // NOI18N
        botonIngresarConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarConceptoActionPerformed(evt);
            }
        });

        botonModificarConcepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/administracion/conceptos/modificarConcepto.png"))); // NOI18N
        botonModificarConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarConceptoActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingresar Concepto");

        jLabel2.setText("Modificar Concepto");

        botonEliminarConcepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/administracion/conceptos/eliminarConcepto.png"))); // NOI18N
        botonEliminarConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarConceptoActionPerformed(evt);
            }
        });

        jLabel3.setText("Eliminar Concepto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonIngresarConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonModificarConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(botonEliminarConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEliminarConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonModificarConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonIngresarConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addContainerGap(308, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonModificarConceptoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonModificarConceptoActionPerformed
    {//GEN-HEADEREND:event_botonModificarConceptoActionPerformed

        Principal.cargarFormulario(new ModificarConcepto());
        Principal.setVentanasActivas(ModificarConcepto.getVentanaModificarConceptos());
    }//GEN-LAST:event_botonModificarConceptoActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(submenuConceptos);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonIngresarConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarConceptoActionPerformed

        Principal.cargarFormulario(new IngresarConcepto());
        Principal.setVentanasActivas(IngresarConcepto.getVentanaIngresarConceptos());
    }//GEN-LAST:event_botonIngresarConceptoActionPerformed

    private void botonEliminarConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarConceptoActionPerformed

        Principal.cargarFormulario(new EliminarConcepto());
        Principal.setVentanasActivas(EliminarConcepto.getVentanaEliminarConceptos());
    }//GEN-LAST:event_botonEliminarConceptoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarConcepto;
    private javax.swing.JButton botonIngresarConcepto;
    private javax.swing.JButton botonModificarConcepto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
