/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.conceptos;

import com.licensis.notaire.dto.DtoConcepto;
import com.licensis.notaire.gui.Principal;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import com.licensis.notaire.jpa.exceptions.ClassEliminatedException;
import com.licensis.notaire.jpa.exceptions.ClassModifiedException;
import com.licensis.notaire.jpa.exceptions.IllegalOrphanException;
import com.licensis.notaire.jpa.exceptions.NonexistentEntityException;
import com.licensis.notaire.jpa.exceptions.PreexistingEntityException;
import com.licensis.notaire.negocio.ControllerNegocio;
import com.licensis.notaire.servicios.AdministradorValidaciones;

/**
 *
 * @author Tefi
 */
public class ModificarConcepto extends javax.swing.JInternalFrame
{

    private static JMenuItem ventanaModificarConceptos = new JMenuItem("Ventana Modificar Conceptos");
    private ControllerNegocio miControllerNegocio = null;
    private List<DtoConcepto> miListaConceptos = null;
    private DtoConcepto dtoConceptoSeleccionado = null;

    /**
     * Creates new form ModificarConcepto
     */
    public ModificarConcepto() {

        initComponents();
        this.limpiarFormulario();
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        miControllerNegocio = ControllerNegocio.getInstancia();
        this.cargarListaConceptos();
    }

    private void salir() {
        this.dispose();
    }

    public static JMenuItem getVentanaModificarConceptos() {
        return ventanaModificarConceptos;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelModificarConcepto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaConceptosDisponibles = new javax.swing.JList();
        botonSeleccionar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        selectorNuevoPorcentaje = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoNuevoNombre = new javax.swing.JTextField();
        campoNuevoValor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        labelAdvertencia = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        checkBoxFijo = new javax.swing.JCheckBox();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Modificar Conceptos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Modificar Concepto");

        jLabel6.setText("Conceptos:");

        jScrollPane3.setViewportView(listaConceptosDisponibles);

        botonSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/aceptar.png"))); // NOI18N
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        jLabel5.setText("%");

        selectorNuevoPorcentaje.setEnabled(false);
        selectorNuevoPorcentaje.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                selectorNuevoPorcentajeStateChanged(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Valor:");

        campoNuevoNombre.setEditable(false);
        campoNuevoNombre.setEnabled(false);
        campoNuevoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNuevoNombreActionPerformed(evt);
            }
        });

        campoNuevoValor.setEnabled(false);
        campoNuevoValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoNuevoValorKeyReleased(evt);
            }
        });

        jLabel4.setText("Porcentaje:");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        labelAdvertencia.setForeground(new java.awt.Color(237, 18, 18));

        jLabel7.setText("Valor fijo:");

        javax.swing.GroupLayout panelModificarConceptoLayout = new javax.swing.GroupLayout(panelModificarConcepto);
        panelModificarConcepto.setLayout(panelModificarConceptoLayout);
        panelModificarConceptoLayout.setHorizontalGroup(
            panelModificarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarConceptoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarConceptoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelModificarConceptoLayout.createSequentialGroup()
                        .addGroup(panelModificarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(botonSeleccionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jSeparator1)
                            .addGroup(panelModificarConceptoLayout.createSequentialGroup()
                                .addGroup(panelModificarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(panelModificarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNuevoNombre)
                                    .addComponent(checkBoxFijo)
                                    .addGroup(panelModificarConceptoLayout.createSequentialGroup()
                                        .addComponent(selectorNuevoPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(campoNuevoValor))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelModificarConceptoLayout.setVerticalGroup(
            panelModificarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarConceptoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelModificarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAdvertencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelModificarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(campoNuevoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelModificarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(selectorNuevoPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(panelModificarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxFijo)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelModificarConceptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModificarConcepto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModificarConcepto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNuevoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNuevoNombreActionPerformed
    }//GEN-LAST:event_campoNuevoNombreActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAceptarActionPerformed
    {//GEN-HEADEREND:event_botonAceptarActionPerformed

        String msj = AdministradorValidaciones.getInstancia().validarModificarConcepto(this);

        if ("".equals(msj))
        {

            //dtoConceptoSeleccionado.setNombre(this.campoNuevoNombre.getText());
            dtoConceptoSeleccionado.setValor(Float.valueOf(this.campoNuevoValor.getText()));


            if (checkBoxFijo.isSelected())
            {
                dtoConceptoSeleccionado.setFijo(true);
                dtoConceptoSeleccionado.setPorcentaje(0);
            }
            else
            {
                dtoConceptoSeleccionado.setFijo(false);
                dtoConceptoSeleccionado.setPorcentaje(Integer.valueOf(this.selectorNuevoPorcentaje.getValue().toString()));
            }

            if (dtoConceptoSeleccionado.isValido())
            {
                try
                {
                    Boolean modificado;

                    modificado = miControllerNegocio.modificarConcepto(dtoConceptoSeleccionado);

                    if (modificado == Boolean.TRUE)
                    {
                        JOptionPane.showMessageDialog(this, "Se ha modificado un concepto correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);

                        this.cargarListaConceptos();
                        this.listaConceptosDisponibles.updateUI();
                        this.limpiarFormulario();
                    }
                }
                catch (PreexistingEntityException ex)
                {
                    JOptionPane.showMessageDialog(this, "El nombre del concepto ya se encuentra registrado", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
                catch (ClassEliminatedException ex)
                {
                    JOptionPane.showMessageDialog(this, "El concepto ha sido recientemente eliminado por otro usuario.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                    this.limpiarFormulario();
                    this.cargarListaConceptos();
                }
                catch (ClassModifiedException e)
                {
                    JOptionPane.showMessageDialog(this, "El concepto ha sido recientemente modificado por otro usuario.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                    this.limpiarFormulario();
                    this.cargarListaConceptos();
                }
                catch (NonexistentEntityException | IllegalOrphanException ex)
                {
                    JOptionPane.showMessageDialog(this, "Error grave, Accion cancelada", "Error", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(ModificarConcepto.class.getName()).log(Level.SEVERE, null, ex);
                    this.salir();
                }
                finally
                {
                    limpiarFormulario();
                    cargarListaConceptos();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Alguno de los valores ingresados nos es valido.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }

        }
        else
        {
            JOptionPane.showMessageDialog(this, msj);
        }


    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
        salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        Principal.removeVentanaActivas(ventanaModificarConceptos);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonSeleccionarActionPerformed
    {//GEN-HEADEREND:event_botonSeleccionarActionPerformed

        Integer nroSeleccionado = listaConceptosDisponibles.getAnchorSelectionIndex();

        if (nroSeleccionado == -1)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Concepto", "Advertencia", JOptionPane.WARNING_MESSAGE);
            this.disableCamposConcepto();
        }
        else if (this.listaConceptosDisponibles.getModel().getSize() > 0)
        {
            this.enableCamposConcepto();
            String nombreConcepto = this.listaConceptosDisponibles.getSelectedValue().toString();
            cargarConcepto(nombreConcepto);

        }
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    private void campoNuevoValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNuevoValorKeyReleased
        String valor = this.campoNuevoValor.getText();

        if (AdministradorValidaciones.getInstancia().validarNumeroFloat(valor))
        {
            Float numeroFloat = Float.parseFloat(valor);
            if (numeroFloat < 0)
            {
                labelAdvertencia.setText("El valor no puede ser negativo");
                this.campoNuevoValor.setText("");
            }
            else
            {
                labelAdvertencia.setText("");
            }
        }

    }//GEN-LAST:event_campoNuevoValorKeyReleased

    private void selectorNuevoPorcentajeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_selectorNuevoPorcentajeStateChanged
        int valor = this.selectorNuevoPorcentaje.getValue().hashCode();
        if (valor < 0)
        {
            this.selectorNuevoPorcentaje.setValue(0);
        }
    }//GEN-LAST:event_selectorNuevoPorcentajeStateChanged

    public void enableCamposConcepto() {
        campoNuevoNombre.setEnabled(true);
        campoNuevoValor.setEnabled(true);
        selectorNuevoPorcentaje.setEnabled(true);
    }

    public void disableCamposConcepto() {
        campoNuevoNombre.setEnabled(false);
        campoNuevoValor.setEnabled(false);
        selectorNuevoPorcentaje.setEnabled(false);
    }

    private void cargarListaConceptos() {

        miListaConceptos = new ArrayList<>();
        DefaultListModel lista = new DefaultListModel();
        listaConceptosDisponibles.setModel(lista);

        //  obtengo la lista de conceptos disponibles.
        miListaConceptos = miControllerNegocio.obtenerListaConceptosDisponibles();

        //  si la lista no esta vacia, la cargo en la grilla de conceptos disponibles.
        if (miListaConceptos != null && !miListaConceptos.isEmpty())
        {

            for (Iterator<DtoConcepto> it = miListaConceptos.iterator(); it.hasNext();)
            {
                DtoConcepto dtoConcepto = it.next();

                lista.addElement(dtoConcepto.getNombre());
            }

            this.listaConceptosDisponibles.setModel(lista);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No existen Conceptos registrados.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            salir();
        }

    }

    public void limpiarFormulario() {
        dtoConceptoSeleccionado = null;
        this.campoNuevoNombre.setText("");
        this.campoNuevoValor.setText("");
        this.selectorNuevoPorcentaje.setValue(0);
    }

    private void cargarConcepto(String nombreConcepto) {
        if (!nombreConcepto.isEmpty())
        {
            for (Iterator<DtoConcepto> it = miListaConceptos.iterator(); it.hasNext();)
            {
                DtoConcepto dtoConcepto = it.next();

                if (dtoConcepto.getNombre().equals(nombreConcepto))
                {
                    dtoConceptoSeleccionado = dtoConcepto;

                    this.campoNuevoNombre.setText(dtoConcepto.getNombre());
                    this.campoNuevoValor.setText(dtoConcepto.getValor().toString());
                    this.selectorNuevoPorcentaje.setValue(dtoConcepto.getPorcentaje());

                    if (dtoConceptoSeleccionado.isFijo())
                    {
                        checkBoxFijo.setSelected(true);
                    }
                    else
                    {
                        checkBoxFijo.setSelected(false);
                    }
                    break;
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningun concepto!", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonSeleccionar;
    public javax.swing.JTextField campoNuevoNombre;
    public javax.swing.JTextField campoNuevoValor;
    private javax.swing.JCheckBox checkBoxFijo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAdvertencia;
    private javax.swing.JList listaConceptosDisponibles;
    private javax.swing.JPanel panelModificarConcepto;
    public javax.swing.JSpinner selectorNuevoPorcentaje;
    // End of variables declaration//GEN-END:variables
}
