/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.clientes;

import com.licensis.notaire.dto.DtoPersona;
import com.licensis.notaire.dto.DtoTipoIdentificacion;
import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.gui.administracion.escribanos.DarAltaEscribano;
import com.licensis.notaire.gui.administracion.usuarios.DarAltaUsuario;
import com.licensis.notaire.gui.administracion.usuarios.ListarPersonasUsuario;
import com.licensis.notaire.gui.gestiones.gestion.IniciarGestion;
import com.licensis.notaire.gui.presupuestos.CrearPresupuesto;
import com.licensis.notaire.gui.presupuestos.ListaPersonasPresupuesto;
import java.util.ArrayList;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import com.licensis.notaire.negocio.ControllerNegocio;

/**
 *
 * @author matias
 */
public class BuscarCliente extends javax.swing.JInternalFrame
{

    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem ventanaBuscar = new JMenuItem("Ventana Buscar Persona");
    private static BuscarCliente instancia = null;
    private static String tipoBusqueda = null;

    public Boolean getFlag()
    {
        return flag;
    }

    public void setFlag(Boolean flag)
    {
        this.flag = flag;
    }
    private Boolean flag = false; //Sirve para saber cuando hay que cerrar el form de busqueda

    /**
     * Creates new form BuscarCliente
     */
    public BuscarCliente()
    { //Esta publico para que no tire erro en todos los formulario es temporal
        initComponents();
        estadoFormulario = Boolean.TRUE;
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        grupo_botones.add(buscarTipoIdentificacion);
        grupo_botones.add(buscarNombreApellido);
        this.cargarCombo();

    }

    public static String getTipoBusqueda()
    {
        return tipoBusqueda;
    }

    public static void setTipoBusqueda(String tipoBusqueda)
    {
        BuscarCliente.tipoBusqueda = tipoBusqueda;
    }

    public void setTituloForm(String titulo)
    {
        this.labelTitulo.setText(titulo);
    }

    private void salir()
    {
        this.dispose();
    }

    public static JMenuItem getVentanaBuscarCliente()
    {
        return ventanaBuscar;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_botones = new javax.swing.ButtonGroup();
        panelBuscarCliente = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboTipoIdentificacion = new javax.swing.JComboBox();
        botonCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoApellido = new javax.swing.JTextField();
        labelTitulo = new javax.swing.JLabel();
        campoNumeroIdentificacion = new javax.swing.JTextField();
        buscarNombreApellido = new javax.swing.JRadioButton();
        buscarTipoIdentificacion = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Buscar Persona");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel4.setText("Tipo Ident.:");

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        jLabel5.setText("Número Ident.:");

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar.png"))); // NOI18N
        botonCancelar.setText("Cerrar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido");

        campoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNombreMouseClicked(evt);
            }
        });

        jLabel2.setText("Nombre:");

        campoApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoApellidoMouseClicked(evt);
            }
        });
        campoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidoActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelTitulo.setText("Buscar");

        campoNumeroIdentificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNumeroIdentificacionMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                campoNumeroIdentificacionMouseReleased(evt);
            }
        });

        buscarNombreApellido.setSelected(true);
        buscarNombreApellido.setText("Buscar por Nombre y Apellido:");
        buscarNombreApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNombreApellidoActionPerformed(evt);
            }
        });

        buscarTipoIdentificacion.setText("Buscar por Tipo y Número de Identificación:");

        javax.swing.GroupLayout panelBuscarClienteLayout = new javax.swing.GroupLayout(panelBuscarCliente);
        panelBuscarCliente.setLayout(panelBuscarClienteLayout);
        panelBuscarClienteLayout.setHorizontalGroup(
            panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                        .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo)
                            .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(51, 51, 51)
                                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoApellido)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(32, 32, 32)
                                .addComponent(comboTipoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(campoNumeroIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buscarNombreApellido)
                            .addComponent(buscarTipoIdentificacion)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 122, Short.MAX_VALUE))))
        );
        panelBuscarClienteLayout.setVerticalGroup(
            panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addComponent(buscarNombreApellido)
                .addGap(18, 18, 18)
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarTipoIdentificacion)
                .addGap(18, 18, 18)
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboTipoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoNumeroIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("fallthrough")
    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonBuscarActionPerformed
    {//GEN-HEADEREND:event_botonBuscarActionPerformed

        //Creo dtoPersona
        DtoPersona miDtoPersonaParametros = new DtoPersona();
        DtoTipoIdentificacion dtoTipoIdentificacion = new com.licensis.notaire.dto.DtoTipoIdentificacion();

        //Control de selleccion A
        if (buscarNombreApellido.isSelected() && (!campoNombre.getText().isEmpty() || !campoApellido.getText().isEmpty()))
        {
            ArrayList<DtoPersona> miListaDtoPersonasEncontradas = new ArrayList<DtoPersona>();

            //Set datos de busqueda Nombre y apellido, por aproximacion
            miDtoPersonaParametros.setNombre(campoNombre.getText());
            miDtoPersonaParametros.setApellido(campoApellido.getText());

            //Busco todas las personas que tengan alguna coincidencia ya sea por Nombre o Apellido
            miListaDtoPersonasEncontradas = ControllerNegocio.getInstancia().buscarPersonaNombreApellido(miDtoPersonaParametros);

            if (miListaDtoPersonasEncontradas != null)
            {
                /*
                 * Dependiendo del tipo de busqueda cargo la grilla
                 * correspondiente.
                 *
                 * Cada grilla es encargada de filtrar el tipo de persona que
                 * debe motrar,Cliente, Persona, etc. y cargar el formulario
                 */

                switch (tipoBusqueda)
                {
                    case ConstantesGui.BUSCAR_PERSONA:
                    case ConstantesGui.MODIFICAR_CLIENTE:
                    {
                        ListarPersonas.getInstancia().limpiarJtable();
                        this.flag = ListarPersonas.getInstancia().cargarGrillaClientes(miListaDtoPersonasEncontradas, ConstantesGui.MODIFICAR_CLIENTE);
                        break;
                    }
                    case ConstantesGui.BUSCAR_CLIENTE:
                    {
                        ListarPersonas.getInstancia().limpiarJtable();
                        this.flag = ListarPersonas.getInstancia().cargarGrillaClientes(miListaDtoPersonasEncontradas, ConstantesGui.BUSCAR_CLIENTE);
                        break;
                    }
                    case ConstantesGui.DAR_ALTA_CLIENTE:
                    {
                        ListarPersonas.getInstancia().limpiarJtable();
                        this.flag = ListarPersonas.getInstancia().cargarGrillaPersonas(miListaDtoPersonasEncontradas, ConstantesGui.DAR_ALTA_CLIENTE);
                        break;
                    }
                    case ConstantesGui.MODIFICAR_PERSONA:
                    {
                        ListarPersonas.getInstancia().limpiarJtable();
                        this.flag = ListarPersonas.getInstancia().cargarGrillaPersonasClientes(miListaDtoPersonasEncontradas, ConstantesGui.MODIFICAR_PERSONA);
                        break;
                    }
                    case ConstantesGui.DAR_ALTA_USUARIO:
                    {
                        ListarPersonasUsuario.getInstancia().limpiarJtable();
                        this.flag = ListarPersonasUsuario.getInstancia().cargarGrillaPersonasClientes(miListaDtoPersonasEncontradas);
                        break;
                    }
                    case ConstantesGui.DAR_ALTA_ESCRIBANO:
                    {
                        ListarPersonasUsuario.getInstancia().limpiarJtable();
                        this.flag = ListarPersonasUsuario.getInstancia().cargarPersonasEscribano(miListaDtoPersonasEncontradas, ConstantesGui.DAR_ALTA_ESCRIBANO);
                        break;
                    }
                    case ConstantesGui.MODIFICAR_ESCRIBANO:
                    {
                        ListarPersonasUsuario.getInstancia().limpiarJtable();
                        this.flag = ListarPersonasUsuario.getInstancia().cargarPersonasEscribano(miListaDtoPersonasEncontradas, ConstantesGui.MODIFICAR_ESCRIBANO);
                        break;
                    }
                    case ConstantesGui.CREAR_PRESUPUESTO:
                    {
                        ListaPersonasPresupuesto.getInstancia().limpiarJtable();
                        ListaPersonasPresupuesto.setFormularioInvocador(ConstantesGui.CREAR_PRESUPUESTO);
                        this.flag = ListaPersonasPresupuesto.getInstancia().cargarGrillaPersonas(miListaDtoPersonasEncontradas);

                        Principal.setVentanasActivas(ListaPersonasPresupuesto.getVentanaListaPresupuesto());
                        Principal.cargarFormulario(ListaPersonasPresupuesto.getInstancia());

                        this.salir();
                        break;
                    }
                    case ConstantesGui.INICIAR_GESTION:
                    {
                        ListarPersonas.getInstancia().layout();
                        ListarPersonas formListar = ListarPersonas.getInstancia();
                        formListar.cargarGrillaClientes(miListaDtoPersonasEncontradas, ConstantesGui.INICIAR_GESTION);
                        this.salir();
                        break;
                    }
                    case ConstantesGui.MODIFICAR_GESTION:
                    {
                        ListarPersonas.getInstancia().limpiarJtable();
                        ListarPersonas formListar = ListarPersonas.getInstancia();
                        formListar.cargarGrillaClientes(miListaDtoPersonasEncontradas, ConstantesGui.MODIFICAR_GESTION);
                        this.salir();
                        break;
                    }
                    case ConstantesGui.MODIFICAR_GESTION_AGREGAR_CLIENTE:
                    {
                        ListarPersonas.getInstancia().limpiarJtable();
                        ListarPersonas formListar = ListarPersonas.getInstancia();
                        formListar.cargarGrillaClientes(miListaDtoPersonasEncontradas, ConstantesGui.MODIFICAR_GESTION_AGREGAR_CLIENTE);
                        this.salir();
                        break;
                    }
                }
                this.limpiarFormulario();

            } else
            {
                JOptionPane.showMessageDialog(this, "No se encontraron coincidencias");
                this.limpiarFormulario();
            }

        } //Control de selleccion B
        else if (buscarTipoIdentificacion.isSelected() && !campoNumeroIdentificacion.getText().isEmpty())
        {
            //Set dato de busqueda 
            dtoTipoIdentificacion.setNombre(comboTipoIdentificacion.getSelectedItem().toString());
            miDtoPersonaParametros.setDtoTipoIdentificacion(dtoTipoIdentificacion);
            miDtoPersonaParametros.setNumeroIdentificacion(campoNumeroIdentificacion.getText());
            miDtoPersonaParametros.getDtoTipoIdentificacion().setIdTipoIdentificacion(ControllerNegocio.getInstancia().asociarFkTipoIdentificacion(miDtoPersonaParametros));

            //Busco la persona por Tipo y Numero de documento
            miDtoPersonaParametros = ControllerNegocio.getInstancia().buscarPersonaTipoNumeroIdentificacion(miDtoPersonaParametros);

            if (miDtoPersonaParametros != null)
            {
                /*
                 * Dependiendo del tipo de busqueda cargo el formulario que
                 * corresponda Usuario, AdministrarCliente, etc..
                 */
                switch (tipoBusqueda)
                {

                    case ConstantesGui.MODIFICAR_CLIENTE:
                    case ConstantesGui.MODIFICAR_PERSONA:
                    case ConstantesGui.DAR_ALTA_CLIENTE:
                    case ConstantesGui.BUSCAR_CLIENTE:
                    {
                        this.flag = AdministrarCliente.getInstancia().cargarFormulario(miDtoPersonaParametros, this.getTipoBusqueda());
                        break;
                    }

                    case ConstantesGui.DAR_ALTA_USUARIO:
                    {
                        try
                        {
                            this.flag = DarAltaUsuario.getInstancia().cargarFormulario(miDtoPersonaParametros);
                        }
                        catch (Exception ex)
                        {
                            System.out.println("Exception BuscarCliente - cargarFormulario");
                        }
                        break;
                    }
                    case ConstantesGui.CREAR_PRESUPUESTO:
                    {
                        CrearPresupuesto.getInstancia().cargarFormulario(miDtoPersonaParametros);
                        salir();
                        break;
                    }
                    case ConstantesGui.INICIAR_GESTION:
                    {
                        IniciarGestion miForm = (IniciarGestion) Principal.obtenerFormularioActivo(ConstantesGui.INICIAR_GESTION);
                        miForm.agregarClienteGestion(miDtoPersonaParametros);
                        JOptionPane.showMessageDialog(this, "Se ha agregado un cliente a la gestion.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        this.salir();
                        break;
                    }
                    case ConstantesGui.DAR_ALTA_ESCRIBANO:
                    {
                        if (miDtoPersonaParametros.getRegistroEscribano() == null)
                        {
                            DarAltaEscribano miForm = new DarAltaEscribano();
                            miForm.cargarEscribano(miDtoPersonaParametros, ConstantesGui.DAR_ALTA_ESCRIBANO);
                            Principal.cargarFormulario(miForm);
                            this.salir();
                            break;
                        }
                    }
                    case ConstantesGui.MODIFICAR_ESCRIBANO:
                    {
                        DarAltaEscribano miForm = new DarAltaEscribano();
                        miForm.cargarEscribano(miDtoPersonaParametros, ConstantesGui.MODIFICAR_ESCRIBANO);
                        Principal.cargarFormulario(miForm);
                        this.salir();
                        break;
                    }
                }

            } else
            {
                JOptionPane.showMessageDialog(this, "La persona no esta Registrada", "Advertencia", JOptionPane.WARNING_MESSAGE);

            }
        } else
        {
            JOptionPane.showMessageDialog(this, "Complete los datos de busqueda", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

        if (flag)
        { //Si es verdadera significa que se cargo la persona deseada, cierro busqueda
            this.dispose();
        }

        this.limpiarFormulario();
        this.toFront();

        //this.dispose();
    }//GEN-LAST:event_botonBuscarActionPerformed

    public static BuscarCliente getInstancia()
    {
        if (instancia == null)
        {
            instancia = new BuscarCliente();
        }
        return instancia;
    }

    public void cargarCombo()
    {
        String nombre = null;
        ArrayList<DtoTipoIdentificacion> listaDtoIdentificaciones = new ArrayList<DtoTipoIdentificacion>();
        listaDtoIdentificaciones = ControllerNegocio.getInstancia().listarTiposIdentificacion();

        for (int i = 0; i < listaDtoIdentificaciones.size(); i++)
        {
            nombre = listaDtoIdentificaciones.get(i).getNombre();
            comboTipoIdentificacion.addItem(nombre);

        }

    }

    public void limpiarFormulario()
    {

        campoNombre.setText("");
        campoApellido.setText("");
        campoNumeroIdentificacion.setText("");
        buscarNombreApellido.setSelected(true);
    }

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(ventanaBuscar);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
        this.limpiarFormulario();
        salir();
        Principal.removeVentanaActivas(this.getVentanaBuscarCliente());
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void buscarNombreApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNombreApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarNombreApellidoActionPerformed

    private void campoNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNombreMouseClicked

        BuscarCliente.getInstancia().updateUI();
        this.grupo_botones.setSelected(this.buscarNombreApellido.getModel(), true);
    }//GEN-LAST:event_campoNombreMouseClicked

    private void campoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellidoActionPerformed

    private void campoApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoApellidoMouseClicked

        BuscarCliente.getInstancia().updateUI();
        this.grupo_botones.setSelected(this.buscarNombreApellido.getModel(), true);
    }//GEN-LAST:event_campoApellidoMouseClicked

    private void campoNumeroIdentificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNumeroIdentificacionMouseClicked

        BuscarCliente.getInstancia().updateUI();
        this.grupo_botones.setSelected(this.buscarTipoIdentificacion.getModel(), true);
    }//GEN-LAST:event_campoNumeroIdentificacionMouseClicked

    private void campoNumeroIdentificacionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNumeroIdentificacionMouseReleased
        BuscarCliente.getInstancia().updateUI();
        this.grupo_botones.setSelected(this.buscarTipoIdentificacion.getModel(), true);
    }//GEN-LAST:event_campoNumeroIdentificacionMouseReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JRadioButton buscarNombreApellido;
    private javax.swing.JRadioButton buscarTipoIdentificacion;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoNumeroIdentificacion;
    private javax.swing.JComboBox comboTipoIdentificacion;
    private javax.swing.ButtonGroup grupo_botones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelBuscarCliente;
    // End of variables declaration//GEN-END:variables
}
