/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.pagos;

import com.licensis.notaire.dto.GenericDto;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.servicios.AdministradorJpa;
import com.licensis.notaire.servicios.GenericRestClient;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matias
 */
public class ConsultarPagos extends javax.swing.JInternalFrame
{

    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem ventanaConsultarPagos = new JMenuItem("Ventana Consultar Pagos");
    private GenericRestClient pagoClient;
    private GenericRestClient presupuestoClient;
    private Integer idPresupuestoActual = null;
    private static final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form ConsultarPagos
     */
    public ConsultarPagos()
    {
        initComponents();
        estadoFormulario = Boolean.TRUE;
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        
        pagoClient = AdministradorJpa.getInstancia().getPagoJpa();
        presupuestoClient = AdministradorJpa.getInstancia().getPresupuestoJpa();
        
        limpiarFormulario();
    }
    
    private void limpiarFormulario() {
        campoNumeroGestion.setText("");
        campoEncabezado.setText("");
        campoNumeroPresupuesto.setText("");
        campoTotal.setText("");
        campoSaldo.setText("");
        campoObservaciones.setText("");
        idPresupuestoActual = null;
        
        DefaultTableModel model = (DefaultTableModel) grillaConceptosTramite.getModel();
        model.setRowCount(0);
    }

    private void salir()
    {
        this.dispose();
    }

    public static JMenuItem getVentanaConsultarPagos()
    {
        return ventanaConsultarPagos;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConsultarPagos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grillaConceptosTramite = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoNumeroGestion = new javax.swing.JTextField();
        campoEncabezado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoNumeroPresupuesto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoSaldo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoObservaciones = new javax.swing.JTextArea();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ventana Consultar Pagos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Consultar Pago");

        grillaConceptosTramite.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero de Pago", "Monto Pago", "Fecha de Pago", "Observaciones"
            }
        ));
        jScrollPane1.setViewportView(grillaConceptosTramite);

        jLabel2.setText("Numero de Gestion:");

        jLabel3.setText("Encabezado:");

        campoNumeroGestion.setEditable(false);

        campoEncabezado.setEditable(false);

        jLabel4.setText("Numero de Presupuesto:");

        campoNumeroPresupuesto.setEditable(false);

        jLabel5.setText("Total:");

        campoTotal.setEditable(false);

        jLabel6.setText("Saldo:");

        campoSaldo.setEditable(false);

        jLabel10.setText("Observaciones:");

        campoObservaciones.setColumns(20);
        campoObservaciones.setEditable(false);
        campoObservaciones.setRows(5);
        jScrollPane2.setViewportView(campoObservaciones);

        javax.swing.GroupLayout panelConsultarPagosLayout = new javax.swing.GroupLayout(panelConsultarPagos);
        panelConsultarPagos.setLayout(panelConsultarPagosLayout);
        panelConsultarPagosLayout.setHorizontalGroup(
            panelConsultarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsultarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelConsultarPagosLayout.createSequentialGroup()
                        .addGroup(panelConsultarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConsultarPagosLayout.createSequentialGroup()
                                .addGroup(panelConsultarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelConsultarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNumeroPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelConsultarPagosLayout.createSequentialGroup()
                                        .addComponent(campoNumeroGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addGap(8, 8, 8)
                                        .addComponent(campoEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1)
                            .addGroup(panelConsultarPagosLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelConsultarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelConsultarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(200, Short.MAX_VALUE))))
        );
        panelConsultarPagosLayout.setVerticalGroup(
            panelConsultarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConsultarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNumeroGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(campoEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConsultarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoNumeroPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConsultarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultarPagosLayout.createSequentialGroup()
                        .addGroup(panelConsultarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(campoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelConsultarPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(campoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConsultarPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelConsultarPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAceptarActionPerformed
    {//GEN-HEADEREND:event_botonAceptarActionPerformed
        salir();
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
        salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(ventanaConsultarPagos);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed
    
    public void cargarPresupuesto(Integer idPresupuesto) {
        try {
            GenericDto presupuesto = presupuestoClient.find(idPresupuesto);
            if (presupuesto == null) {
                JOptionPane.showMessageDialog(this, "No se encontró el presupuesto", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            idPresupuestoActual = idPresupuesto;
            campoNumeroPresupuesto.setText(String.valueOf(idPresupuesto));
            
            Object encabezado = presupuesto.get("encabezado");
            if (encabezado != null) {
                campoEncabezado.setText(encabezado.toString());
            }
            
            Object tramite = presupuesto.get("fkIdTramite");
            if (tramite instanceof GenericDto) {
                Object idTramite = ((GenericDto) tramite).get("idTramite");
                if (idTramite != null) {
                    campoNumeroGestion.setText(idTramite.toString());
                }
            }
            
            Object total = presupuesto.get("total");
            if (total != null) {
                campoTotal.setText(total.toString());
            }
            
            cargarPagosPorPresupuesto(idPresupuesto);
            calcularSaldo(idPresupuesto);
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar el presupuesto: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargarPagosPorPresupuesto(Integer idPresupuesto) {
        try {
            List<GenericDto> todosPagos = pagoClient.findAll();
            DefaultTableModel model = (DefaultTableModel) grillaConceptosTramite.getModel();
            model.setRowCount(0);
            
            for (GenericDto pago : todosPagos) {
                Object presupuesto = pago.get("fkIdPresupuesto");
                if (presupuesto instanceof GenericDto) {
                    Object idPres = ((GenericDto) presupuesto).get("idPresupuesto");
                    if (idPres != null && idPres.equals(idPresupuesto)) {
                        Object idPago = pago.get("idPago");
                        Object monto = pago.get("monto");
                        Object fecha = pago.get("fecha");
                        Object obs = pago.get("observaciones");
                        
                        String fechaStr = "";
                        if (fecha != null) {
                            try {
                                fechaStr = DATE_FORMAT.format(fecha);
                            } catch (Exception e) {
                                fechaStr = fecha.toString();
                            }
                        }
                        
                        model.addRow(new Object[]{
                            idPago != null ? idPago.toString() : "",
                            monto != null ? monto.toString() : "",
                            fechaStr,
                            obs != null ? obs.toString() : ""
                        });
                    }
                }
            }
            
            if (model.getRowCount() == 0) {
                campoObservaciones.setText("No se encontraron pagos para este presupuesto");
            }
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar los pagos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void calcularSaldo(Integer idPresupuesto) {
        try {
            float total = Float.parseFloat(campoTotal.getText().isEmpty() ? "0" : campoTotal.getText());
            
            List<GenericDto> pagos = pagoClient.findAll();
            float pagado = 0;
            
            for (GenericDto pago : pagos) {
                Object presupuesto = pago.get("fkIdPresupuesto");
                if (presupuesto instanceof GenericDto) {
                    Object idPres = ((GenericDto) presupuesto).get("idPresupuesto");
                    if (idPres != null && idPres.equals(idPresupuesto)) {
                        Object monto = pago.get("monto");
                        if (monto != null) {
                            pagado += Float.parseFloat(monto.toString());
                        }
                    }
                }
            }
            
            float saldo = total - pagado;
            campoSaldo.setText(String.valueOf(saldo));
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al calcular el saldo: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void buscarPresupuestoPorNumero(String numeroPresupuesto) {
        try {
            if (numeroPresupuesto == null || numeroPresupuesto.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese un número de presupuesto", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            Integer idPresupuesto = Integer.parseInt(numeroPresupuesto.trim());
            cargarPresupuesto(idPresupuesto);
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El número de presupuesto debe ser numérico", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoEncabezado;
    private javax.swing.JTextField campoNumeroGestion;
    private javax.swing.JTextField campoNumeroPresupuesto;
    private javax.swing.JTextArea campoObservaciones;
    private javax.swing.JTextField campoSaldo;
    private javax.swing.JTextField campoTotal;
    private javax.swing.JTable grillaConceptosTramite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelConsultarPagos;
    // End of variables declaration//GEN-END:variables
}
