/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.gestiones;

import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.gui.gestiones.documentacion.Documentacion;
import com.licensis.notaire.gui.gestiones.escrituras.Escrituras;
import com.licensis.notaire.gui.gestiones.gestion.Gestion;
import com.licensis.notaire.gui.gestiones.inscripciones.Inscripciones;
import com.licensis.notaire.gui.gestiones.testimonios.Testimonios;
import javax.swing.JMenuItem;

/**
 *
 * @author matias
 */
public class Gestiones extends javax.swing.JInternalFrame
{

    private static Gestiones instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem menuGestions = new JMenuItem("Modulo Gestiones");

    /**
     * Creates new form Gestiones
     */
    private Gestiones() {
        initComponents();
    }

    public static Gestiones getInstancia() {
        if (instancia == null)
        {
            instancia = new Gestiones();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);

        }
        return instancia;
    }

    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario) {
        Gestiones.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getMenuGestions() {
        return menuGestions;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAdministrarGestion = new javax.swing.JButton();
        botonAdministrarDocumentacion = new javax.swing.JButton();
        botonAdministrarEscrituras = new javax.swing.JButton();
        botonAdministrarTestimonios = new javax.swing.JButton();
        botonAdministrarInscripciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Modulo Gestiones");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonAdministrarGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/gestion.png"))); // NOI18N
        botonAdministrarGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministrarGestionActionPerformed(evt);
            }
        });

        botonAdministrarDocumentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/documentacion.png"))); // NOI18N
        botonAdministrarDocumentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministrarDocumentacionActionPerformed(evt);
            }
        });

        botonAdministrarEscrituras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/escrituras.png"))); // NOI18N
        botonAdministrarEscrituras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministrarEscriturasActionPerformed(evt);
            }
        });

        botonAdministrarTestimonios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/testimonios.png"))); // NOI18N
        botonAdministrarTestimonios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministrarTestimoniosActionPerformed(evt);
            }
        });

        botonAdministrarInscripciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/inscripciones.png"))); // NOI18N
        botonAdministrarInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministrarInscripcionesActionPerformed(evt);
            }
        });

        jLabel1.setText("Gestion");

        jLabel2.setText("Documentación");

        jLabel3.setText("Escrituras");

        jLabel4.setText("Testimonios");

        jLabel5.setText("Inscripciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAdministrarInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAdministrarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAdministrarDocumentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAdministrarEscrituras, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(botonAdministrarTestimonios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAdministrarTestimonios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAdministrarEscrituras, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAdministrarDocumentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAdministrarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(37, 37, 37)
                        .addComponent(botonAdministrarInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAdministrarEscriturasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAdministrarEscriturasActionPerformed
    {//GEN-HEADEREND:event_botonAdministrarEscriturasActionPerformed
        if (Escrituras.getEstadoFormulario() == Boolean.FALSE)
        {
            Principal.cargarFormulario(Escrituras.getInstancia());
            Principal.setVentanasActivas(Escrituras.getSubmenuEscrituras());
        }
        else
        {
            for (int i = 0; i < Principal.AreaTrabajo.getAllFrames().length; i++)
            {
                if (Principal.AreaTrabajo.getAllFrames()[i].equals(Escrituras.getInstancia()))
                {
                    Principal.cargarFormulario(Escrituras.getInstancia());
                    Principal.setVentanasActivas(Escrituras.getSubmenuEscrituras());
                }
            }
        }
    }//GEN-LAST:event_botonAdministrarEscriturasActionPerformed

    private void botonAdministrarTestimoniosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAdministrarTestimoniosActionPerformed
    {//GEN-HEADEREND:event_botonAdministrarTestimoniosActionPerformed
        if (Testimonios.getEstadoFormulario() == Boolean.FALSE)
        {
            Principal.cargarFormulario(Testimonios.getInstancia());
            Principal.setVentanasActivas(Testimonios.getSubmenuTestimonios());
        }
        else
        {
            for (int i = 0; i < Principal.AreaTrabajo.getAllFrames().length; i++)
            {
                if (Principal.AreaTrabajo.getAllFrames()[i].equals(Testimonios.getInstancia()))
                {
                    Principal.cargarFormulario(Testimonios.getInstancia());
                    Principal.setVentanasActivas(Testimonios.getSubmenuTestimonios());
                }
            }
        }
    }//GEN-LAST:event_botonAdministrarTestimoniosActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(menuGestions);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonAdministrarGestionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAdministrarGestionActionPerformed
    {//GEN-HEADEREND:event_botonAdministrarGestionActionPerformed
        if (Gestion.getEstadoFormulario() == Boolean.FALSE)
        {
            Principal.cargarFormulario(Gestion.getInstancia());
            Principal.setVentanasActivas(Gestion.getSubmenuGestion());
        }
        else
        {
            for (int i = 0; i < Principal.AreaTrabajo.getAllFrames().length; i++)
            {
                if (Principal.AreaTrabajo.getAllFrames()[i].equals(Gestion.getInstancia()))
                {
                    Principal.cargarFormulario(Gestion.getInstancia());
                    Principal.setVentanasActivas(Gestion.getSubmenuGestion());
                }
            }
        }
    }//GEN-LAST:event_botonAdministrarGestionActionPerformed

    private void botonAdministrarDocumentacionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAdministrarDocumentacionActionPerformed
    {//GEN-HEADEREND:event_botonAdministrarDocumentacionActionPerformed
        if (Documentacion.getEstadoFormulario() == Boolean.FALSE)
        {
            Principal.cargarFormulario(Documentacion.getInstancia());
            Principal.setVentanasActivas(Documentacion.getSubmenuDocumentacion());
        }
        else
        {
            for (int i = 0; i < Principal.AreaTrabajo.getAllFrames().length; i++)
            {
                if (Principal.AreaTrabajo.getAllFrames()[i].equals(Documentacion.getInstancia()))
                {
                    Principal.cargarFormulario(Documentacion.getInstancia());
                    Principal.setVentanasActivas(Documentacion.getSubmenuDocumentacion());
                }
            }
        }
    }//GEN-LAST:event_botonAdministrarDocumentacionActionPerformed

    private void botonAdministrarInscripcionesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAdministrarInscripcionesActionPerformed
    {//GEN-HEADEREND:event_botonAdministrarInscripcionesActionPerformed
        if (Inscripciones.getEstadoFormulario() == Boolean.FALSE)
        {
            Principal.cargarFormulario(Inscripciones.getInstancia());
            Principal.setVentanasActivas(Inscripciones.getSubmenuInscripciones());
        }
        else
        {
            for (int i = 0; i < Principal.AreaTrabajo.getAllFrames().length; i++)
            {
                if (Principal.AreaTrabajo.getAllFrames()[i].equals(Inscripciones.getInstancia()))
                {
                    Principal.cargarFormulario(Inscripciones.getInstancia());
                    Principal.setVentanasActivas(Inscripciones.getSubmenuInscripciones());
                }
            }
        }
    }//GEN-LAST:event_botonAdministrarInscripcionesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdministrarDocumentacion;
    private javax.swing.JButton botonAdministrarEscrituras;
    private javax.swing.JButton botonAdministrarGestion;
    private javax.swing.JButton botonAdministrarInscripciones;
    private javax.swing.JButton botonAdministrarTestimonios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
