#!/usr/bin/env python3
"""
Generate docs/wiki/cicd-reports/e2e-coverage-<date>.md from the actual
Playwright JSON reporter output (frontend/test-results/results.json) and
Bruno CLI JSON reporter output (backend-api/api-test/bruno-results.json),
instead of a static hardcoded template (issue #587).
"""
import glob
import json
import os
import sys


def _iter_specs(suite):
    for spec in suite.get("specs", []):
        yield spec
    for child in suite.get("suites", []):
        yield from _iter_specs(child)


def _find_file(root, filename):
    matches = glob.glob(os.path.join(root, "**", filename), recursive=True)
    return matches[0] if matches else None


def _load_json(path):
    if not path or not os.path.isfile(path):
        return None
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return None


def _playwright_section(pw_data):
    if pw_data is None:
        return "No Playwright results found — the E2E test run may not have completed.", []

    stats = pw_data.get("stats", {})
    expected = stats.get("expected", 0)
    unexpected = stats.get("unexpected", 0)
    skipped = stats.get("skipped", 0)
    flaky = stats.get("flaky", 0)
    total = expected + unexpected + skipped + flaky

    failing = []
    for suite in pw_data.get("suites", []):
        for spec in _iter_specs(suite):
            if spec.get("ok") is False:
                failing.append((spec.get("title", "unknown test"), spec.get("file", "unknown file")))

    lines = [
        f"- **Total:** {total}",
        f"- **Passed:** {expected}",
        f"- **Failed:** {unexpected}",
        f"- **Skipped:** {skipped}",
        f"- **Flaky:** {flaky}",
    ]
    return "\n".join(lines), failing


def _bruno_section(bruno_data):
    if bruno_data is None:
        return "No Bruno API test results found — the Bruno run may not have completed."

    summary = bruno_data.get("summary")
    if not summary:
        return "Bruno results file present but its summary format was not recognized."

    total = summary.get("totalRequests", "?")
    passed = summary.get("passedRequests", "?")
    failed = summary.get("failedRequests", "?")
    return (
        f"- **Total requests:** {total}\n"
        f"- **Passed:** {passed}\n"
        f"- **Failed:** {failed}"
    )


def build_report(pw_data, bruno_data, report_date, trigger):
    pw_summary, failing_specs = _playwright_section(pw_data)
    bruno_summary = _bruno_section(bruno_data)

    if failing_specs:
        action_items = "\n".join(f"- `{file}` — {title}" for title, file in failing_specs)
    else:
        action_items = "No action items — all executed tests passed."

    return f"""---
title: E2E Coverage Report - {report_date}
---

# E2E Coverage Report

**Date:** {report_date}
**Trigger:** {trigger}

## Playwright E2E Results

{pw_summary}

## Bruno API Test Results

{bruno_summary}

## Action Items

{action_items}

---
*Report generated by Playwright E2E Pipeline from actual test results (issue #587)*
"""


def main():
    output_file = os.environ["OUTPUT_FILE"]
    report_date = os.environ["REPORT_DATE"]
    trigger = os.environ["GHA_EVENT"]
    search_root = os.environ.get("ARTIFACTS_ROOT", ".")

    pw_path = os.environ.get("PW_RESULTS_JSON") or _find_file(search_root, "results.json")
    bruno_path = os.environ.get("BRUNO_RESULTS_JSON") or _find_file(search_root, "bruno-results.json")

    report = build_report(_load_json(pw_path), _load_json(bruno_path), report_date, trigger)

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"Wrote {output_file}")


if __name__ == "__main__":
    sys.exit(main())
