#!/usr/bin/env bash
# ============================================================
# generate-markdown-report.sh
#
# Generates ci-report.md using environment variables.
# Called from GitHub Actions workflow to avoid YAML block-scalar
# issues with "---" at column 0.
#
# Required env vars:
#   OUTPUT_FILE       — path to write the report
#   GHA_BRANCH        — github.ref_name
#   GHA_SHA           — github.sha
#   GHA_BUILD         — needs.build.result
#   GHA_UNIT          — needs.unit-tests.result
#   GHA_INTEGRATION   — needs.integration-tests.result
#   GHA_COVERAGE      — needs.coverage.result
#   GHA_SECURITY      — needs.security.result
#   GHA_DOCKER        — needs.docker-build.result
#   GHA_QUALITY       — needs.quality.result
#   UNIT_TOTAL        — total tests executed
#   UNIT_FAIL         — failed tests
#   SEC_CRITICAL      — critical vulnerabilities
#   SEC_HIGH          — high vulnerabilities
#   COV_PCT           — line coverage percentage
#
# Optional:
#   REPORT_EMOJI      — "yes" to include emoji in headings
#   REPORT_NAV_ORDER  — "yes" to add "nav_order: 1" in frontmatter
#   REPORT_TITLE      — custom title (default: "CI/CD Pipeline Report")
#   REPORT_DATE       — date string (default: current UTC datetime)
# ============================================================
set -euo pipefail

: "${OUTPUT_FILE:?REQUIRED}"
: "${GHA_BRANCH:?REQUIRED}"
: "${GHA_SHA:?REQUIRED}"
: "${GHA_BUILD:?REQUIRED}"
: "${GHA_UNIT:?REQUIRED}"
: "${GHA_INTEGRATION:?REQUIRED}"
: "${GHA_COVERAGE:?REQUIRED}"
: "${GHA_SECURITY:?REQUIRED}"
: "${GHA_DOCKER:?REQUIRED}"
: "${GHA_QUALITY:?REQUIRED}"
# Extracted metrics may be empty if no XML/JSON files were found during
# the workflow run. Default to "0" to avoid script failure.
: "${UNIT_TOTAL:-0}"
: "${UNIT_FAIL:-0}"
: "${SEC_CRITICAL:-0}"
: "${SEC_HIGH:-0}"
: "${COV_PCT:-0}"

DATE="${REPORT_DATE:-$(date -u +"%Y-%m-%d %H:%M:%S")}"
TITLE="${REPORT_TITLE:-CI/CD Pipeline Report}"

# Emoji prefixes (controlled by REPORT_EMOJI)
h1=""
h2=""
h3=""
h4=""
h5=""
if [ "${REPORT_EMOJI:-}" = "yes" ]; then
  h1="📊 "
  h2="📋 "
  h3="🧪 "
  h4="🔒 "
  h5="✅ "
fi

# Write frontmatter (uses echo — "---" at col 0 is safe in .sh files)
{
  echo "---"
  echo "title: ${TITLE}"
  if [ "${REPORT_NAV_ORDER:-}" = "yes" ]; then
    echo "nav_order: 1"
  fi
  echo "---"
  echo ""
} > "${OUTPUT_FILE}"

# Append body (printf with %s for each line avoids heredoc issues)
{
  printf '%s\n' "# ${h1}${TITLE}"
  printf '%s\n' ""
  printf '%s\n' "**Generated:** ${DATE}  "
  printf '%s\n' "**Branch:** ${GHA_BRANCH}  "
  printf '%s\n' "**Commit:** ${GHA_SHA}"
  printf '%s\n' ""
  printf '%s\n' "---"
  printf '%s\n' ""
  printf '%s\n' "## ${h2}Job Summary"
  printf '%s\n' ""
  printf '%s\n' "| Job | Status |"
  printf '%s\n' "|-----|--------|"
  printf '%s\n' "| Build & Compile | ${GHA_BUILD} |"
  printf '%s\n' "| Unit Tests | ${GHA_UNIT} |"
  printf '%s\n' "| Integration Tests | ${GHA_INTEGRATION} |"
  printf '%s\n' "| Code Coverage | ${GHA_COVERAGE} |"
  printf '%s\n' "| Security Scan | ${GHA_SECURITY} |"
  printf '%s\n' "| Docker Build | ${GHA_DOCKER} |"
  printf '%s\n' "| Code Quality | ${GHA_QUALITY} |"
  printf '%s\n' ""
  printf '%s\n' "---"
  printf '%s\n' ""
  printf '%s\n' "## ${h3}Test Results"
  printf '%s\n' ""
  printf '%s\n' "| Metric | Value |"
  printf '%s\n' "|--------|-------|"
  printf '%s\n' "| Tests Executed | ${UNIT_TOTAL} |"
  printf '%s\n' "| Failures | ${UNIT_FAIL} |"
  printf '%s\n' ""
  printf '%s\n' "---"
  printf '%s\n' ""
  printf '%s\n' "## ${h4}Security Scan"
  printf '%s\n' ""
  printf '%s\n' "| Severity | Count |"
  printf '%s\n' "|----------|-------|"
  printf '%s\n' "| Critical | ${SEC_CRITICAL} |"
  printf '%s\n' "| High | ${SEC_HIGH} |"
  printf '%s\n' ""
  printf '%s\n' "---"
  printf '%s\n' ""
  printf '%s\n' "## ${h4}Code Coverage"
  printf '%s\n' ""
  printf '%s\n' "**Line Coverage:** ${COV_PCT}%% (Target: 80%%)"
  printf '%s\n' ""
  printf '%s\n' "---"
  printf '%s\n' ""
  printf '%s\n' "## ${h5}Conclusion"
  printf '%s\n' ""
  printf '%s\n' "Pipeline completed. Review individual job results above."
  printf '%s\n' ""
  printf '%s\n' "*Report generated by CI Pipeline*"
} >> "${OUTPUT_FILE}"

echo "=== Markdown report generated ==="
wc -l "${OUTPUT_FILE}"
