#!/usr/bin/env python3
"""
Generate docs/wiki/cicd-reports/e2e-coverage-<date>.md from the actual
Playwright JSON reporter output (frontend/test-results/results.json) and
Bruno CLI JSON reporter output (backend-api/api-test/bruno-results.json),
instead of a static hardcoded template (issue #587).
"""
import glob
import json
import os
import sys


def _iter_specs(suite):
    for spec in suite.get("specs", []):
        yield spec
    for child in suite.get("suites", []):
        yield from _iter_specs(child)


def _find_file(root, filename):
    matches = glob.glob(os.path.join(root, "**", filename), recursive=True)
    return matches[0] if matches else None


def _load_json(path):
    if not path or not os.path.isfile(path):
        return None
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return None


def _playwright_section(pw_data):
    if pw_data is None:
        return "No Playwright results found — the E2E test run may not have completed.", []

    stats = pw_data.get("stats", {})
    expected = stats.get("expected", 0)
    unexpected = stats.get("unexpected", 0)
    skipped = stats.get("skipped", 0)
    flaky = stats.get("flaky", 0)
    total = expected + unexpected + skipped + flaky

    failing = []
    for suite in pw_data.get("suites", []):
        for spec in _iter_specs(suite):
            if spec.get("ok") is False:
                failing.append((spec.get("title", "unknown test"), spec.get("file", "unknown file")))

    lines = [
        f"- **Total:** {total}",
        f"- **Passed:** {expected}",
        f"- **Failed:** {unexpected}",
        f"- **Skipped:** {skipped}",
        f"- **Flaky:** {flaky}",
    ]
    return "\n".join(lines), failing


def _bruno_summaries(bruno_data):
    """`@usebruno/cli run --reporter-json` writes a LIST of per-iteration
    objects (one per `--iteration-count` run, typically just one), each with
    its own "summary" — not a single top-level object with a "summary" key
    (issue #658, verified against a real CI artifact rather than guessed)."""
    if isinstance(bruno_data, list):
        return [item["summary"] for item in bruno_data if isinstance(item, dict) and item.get("summary")]
    if isinstance(bruno_data, dict) and bruno_data.get("summary"):
        return [bruno_data["summary"]]
    return []


def _bruno_section(bruno_data):
    """Returns (markdown_summary, failed_test_count)."""
    if bruno_data is None:
        return "No Bruno API test results found — the Bruno run may not have completed.", 0

    summaries = _bruno_summaries(bruno_data)
    if not summaries:
        return "Bruno results file present but its summary format was not recognized.", 0

    total_requests = sum(s.get("totalRequests", 0) for s in summaries)
    passed_requests = sum(s.get("passedRequests", 0) for s in summaries)
    failed_requests = sum(s.get("failedRequests", 0) for s in summaries)
    total_tests = sum(s.get("totalTests", 0) for s in summaries)
    passed_tests = sum(s.get("passedTests", 0) for s in summaries)
    failed_tests = sum(s.get("failedTests", 0) for s in summaries)

    summary_md = (
        f"- **Total requests:** {total_requests}\n"
        f"- **Passed requests:** {passed_requests}\n"
        f"- **Failed requests:** {failed_requests}\n"
        f"- **Total tests/assertions:** {total_tests}\n"
        f"- **Passed tests:** {passed_tests}\n"
        f"- **Failed tests:** {failed_tests}"
    )
    return summary_md, failed_tests


def build_report(pw_data, bruno_data, report_date, trigger):
    pw_summary, failing_specs = _playwright_section(pw_data)
    bruno_summary, bruno_failed_tests = _bruno_section(bruno_data)

    items = [f"- `{file}` — {title}" for title, file in failing_specs]
    if bruno_failed_tests:
        items.append(
            f"- Bruno API tests: {bruno_failed_tests} failing assertion(s) — see the "
            f"`bruno-results` artifact for per-request detail."
        )
    action_items = "\n".join(items) if items else "No action items — all executed tests passed."

    return f"""---
title: E2E Coverage Report - {report_date}
---

# E2E Coverage Report

**Date:** {report_date}
**Trigger:** {trigger}

## Playwright E2E Results

{pw_summary}

## Bruno API Test Results

{bruno_summary}

## Action Items

{action_items}

---
*Report generated by Playwright E2E Pipeline from actual test results (issue #587)*
"""


def main():
    output_file = os.environ["OUTPUT_FILE"]
    report_date = os.environ["REPORT_DATE"]
    trigger = os.environ["GHA_EVENT"]
    search_root = os.environ.get("ARTIFACTS_ROOT", ".")

    pw_path = os.environ.get("PW_RESULTS_JSON") or _find_file(search_root, "results.json")
    bruno_path = os.environ.get("BRUNO_RESULTS_JSON") or _find_file(search_root, "bruno-results.json")

    report = build_report(_load_json(pw_path), _load_json(bruno_path), report_date, trigger)

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"Wrote {output_file}")


if __name__ == "__main__":
    sys.exit(main())
