#!/usr/bin/env bash
# ============================================================
# generate-pr-validation-report.sh
#
# Generates a PR validation markdown report using environment
# variables. Called from GitHub Actions workflow to avoid YAML
# block-scalar issues with "---" at column 0.
#
# Required env vars:
#   OUTPUT_FILE       — path to write the report
#   GHA_VALIDATE_PR   — needs.validate-pr.result
#   GHA_QUICK_BUILD   — needs.quick-build.result
#   GHA_DEPENDENCY    — needs.dependency-analysis.result
#   GHA_LINT          — needs.lint.result
#   GHA_BRANCH_PROT   — needs.branch-protection.result
#
# Optional:
#   PR_NUMBER         — github.event.pull_request.number
#   PR_TITLE          — github.event.pull_request.title
#   PR_AUTHOR         — github.event.pull_request.user.login
#   PR_CREATED        — github.event.pull_request.created_at
#   PR_CHANGED_FILES  — github.event.pull_request.changed_files
#   PR_BRANCH         — github.head_ref
#   REPORT_DATE       — date string (default: current UTC datetime)
#   REPORT_EMOJI      — "yes" to include emoji in headings
#   WIKI_MODE         — "yes" for wiki-style frontmatter (title only)
# ============================================================
set -euo pipefail

: "${OUTPUT_FILE:?REQUIRED}"
: "${GHA_VALIDATE_PR:?REQUIRED}"
: "${GHA_QUICK_BUILD:?REQUIRED}"
: "${GHA_DEPENDENCY:?REQUIRED}"
: "${GHA_LINT:?REQUIRED}"
: "${GHA_BRANCH_PROT:?REQUIRED}"

# Optional — default to empty string
PR_NUMBER="${PR_NUMBER:-}"
PR_TITLE="${PR_TITLE:-}"
PR_AUTHOR="${PR_AUTHOR:-}"
PR_CREATED="${PR_CREATED:-}"
PR_CHANGED_FILES="${PR_CHANGED_FILES:-}"
PR_BRANCH="${PR_BRANCH:-}"
DATE="${REPORT_DATE:-$(date -u +"%Y-%m-%d %H:%M:%S")}"

# Emoji prefixes
h1=""
h2=""
h3=""
if [ "${REPORT_EMOJI:-}" = "yes" ]; then
  h1="📋 "
  h2="📝 "
  h3="✅ "
fi

# Write frontmatter
{
  echo "---"
  if [ "${WIKI_MODE:-}" = "yes" ] && [ -n "${PR_NUMBER}" ]; then
    echo "title: PR #${PR_NUMBER} Validation Report"
  else
    echo "title: PR Validation Report"
    echo "nav_order: 1"
  fi
  echo "---"
  echo ""
} > "${OUTPUT_FILE}"

# Write body
{
  printf '%s\n' "# ${h1}PR Validation Report"
  printf '%s\n' ""
  printf '%s\n' "**Generated:** ${DATE}  "
  if [ -n "${PR_NUMBER}" ]; then
    printf '%s\n' "**PR:** #${PR_NUMBER}  "
  fi
  if [ -n "${PR_BRANCH}" ]; then
    printf '%s\n' "**Branch:** ${PR_BRANCH}"
  fi
  printf '%s\n' ""
  printf '%s\n' "---"
  printf '%s\n' ""
  printf '%s\n' "## ${h2}Validation Results"
  printf '%s\n' ""
  printf '%s\n' "| Check | Status |"
  printf '%s\n' "|-------|--------|"
  printf '%s\n' "| PR Title & Description | ${GHA_VALIDATE_PR} |"
  printf '%s\n' "| Quick Build | ${GHA_QUICK_BUILD} |"
  printf '%s\n' "| Dependency Analysis | ${GHA_DEPENDENCY} |"
  printf '%s\n' "| Code Lint | ${GHA_LINT} |"
  printf '%s\n' "| Branch Protection | ${GHA_BRANCH_PROT} |"
  printf '%s\n' ""
  printf '%s\n' "---"
  printf '%s\n' ""

  # Only include PR details when available (artifact report)
  if [ "${WIKI_MODE:-}" != "yes" ] && [ -n "${PR_TITLE}" ]; then
    printf '%s\n' "## PR Details"
    printf '%s\n' ""
    printf '%s\n' "- **Title:** ${PR_TITLE}"
    printf '%s\n' "- **Author:** ${PR_AUTHOR}"
    printf '%s\n' "- **Created:** ${PR_CREATED}"
    if [ -n "${PR_CHANGED_FILES}" ]; then
      printf '%s\n' "- **Changes:** ${PR_CHANGED_FILES} files"
    fi
    printf '%s\n' ""
    printf '%s\n' "---"
    printf '%s\n' ""
  fi

  printf '%s\n' "## ${h3}Conclusion"
  printf '%s\n' ""

  # Determine conclusion based on results
  if [ "${GHA_VALIDATE_PR}" = "success" ] && [ "${GHA_QUICK_BUILD}" = "success" ]; then
    printf '%s\n' "**PR Ready:** Validation passed, ready for CI pipeline"
  else
    printf '%s\n' "**Review Required:** Some checks failed, please review"
  fi
  printf '%s\n' ""
  printf '%s\n' "---"
  printf '%s\n' ""
  printf '%s\n' "*Report generated by PR Validation Pipeline*"
} >> "${OUTPUT_FILE}"

echo "=== PR validation report generated ==="
wc -l "${OUTPUT_FILE}"
