#!/usr/bin/env bash
# ============================================================
# generate-cd-report.sh
#
# Generates a CD (Continuous Deployment) markdown report using
# environment variables. Called from GitHub Actions workflow to
# avoid YAML block-scalar issues with "---" at column 0.
#
# Required env vars:
#   OUTPUT_FILE         — path to write the report
#   GHA_BUILD_PUBLISH   — needs.build-and-publish.result
#   GHA_RELEASE         — needs.release.result
#   GHA_UPDATE_DESC     — needs.update-description.result
#   GHA_BRANCH          — github.ref_name
#   GHA_SHA             — github.sha
# Optional:
#   GHA_REPO            — github.repository (e.g. "owner/name")
#
# Optional:
#   REPORT_DATE         — date string (default: current UTC datetime)
#   REPORT_EMOJI        — "yes" to include emoji in headings
#   WIKI_MODE           — "yes" for wiki-style frontmatter (title only)
# ============================================================
set -euo pipefail

: "${OUTPUT_FILE:?REQUIRED}"
: "${GHA_BUILD_PUBLISH:?REQUIRED}"
: "${GHA_RELEASE:?REQUIRED}"
: "${GHA_UPDATE_DESC:?REQUIRED}"
: "${GHA_BRANCH:?REQUIRED}"
: "${GHA_SHA:?REQUIRED}"

GHA_REPO="${GHA_REPO:-}"
DATE="${REPORT_DATE:-$(date -u +"%Y-%m-%d %H:%M:%S")}"

# Emoji prefixes
h1=""
h2=""
h3=""
if [ "${REPORT_EMOJI:-}" = "yes" ]; then
  h1="🚀 "
  h2="📋 "
  h3="✅ "
fi

# Write frontmatter
{
  echo "---"
  if [ "${WIKI_MODE:-}" = "yes" ]; then
    echo "title: CD Report - ${DATE}"
  else
    echo "title: CD Report"
    echo "nav_order: 1"
  fi
  echo "---"
  echo ""
} > "${OUTPUT_FILE}"

# Write body
{
  printf '%s\n' "# ${h1}CD Pipeline Report"
  printf '%s\n' ""
  printf '%s\n' "**Generated:** ${DATE}  "
  printf '%s\n' "**Branch:** ${GHA_BRANCH}  "
  printf '%s\n' "**Commit:** ${GHA_SHA}"
  printf '%s\n' ""
  printf '%s\n' "---"
  printf '%s\n' ""
  printf '%s\n' "## ${h2}Job Results"
  printf '%s\n' ""
  printf '%s\n' "| Job | Status |"
  printf '%s\n' "|-----|--------|"
  printf '%s\n' "| Build & Publish | ${GHA_BUILD_PUBLISH} |"
  printf '%s\n' "| Create Release | ${GHA_RELEASE} |"
  printf '%s\n' "| Update Description | ${GHA_UPDATE_DESC} |"
  printf '%s\n' ""
  printf '%s\n' "---"
  printf '%s\n' ""
  printf '%s\n' "## Docker Image"
  printf '%s\n' ""
  printf '%s\n' "| Property | Value |"
  printf '%s\n' "|----------|-------|"
  printf '%s\n' "| Registry | ghcr.io |"
  printf '%s\n' "| Repository | ${GHA_REPO}/backend |"
  printf '%s\n' "| Tag | ${GHA_BRANCH} |"
  printf '%s\n' ""
  printf '%s\n' "---"
  printf '%s\n' ""
  printf '%s\n' "## ${h3}Conclusion"
  printf '%s\n' ""

  if [ "${GHA_BUILD_PUBLISH}" = "success" ]; then
    printf '%s\n' "**Pipeline:** SUCCESS - Image built and published successfully"
  else
    printf '%s\n' "**Pipeline:** FAILED - Check the logs for details"
  fi
  printf '%s\n' ""
  printf '%s\n' "---"
  printf '%s\n' ""
  printf '%s\n' "*Report generated by CI/CD Pipeline*"
} >> "${OUTPUT_FILE}"

echo "=== CD report generated ==="
wc -l "${OUTPUT_FILE}"
