/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.presupuestos;

import com.licensis.notaire.dto.DtoPersona;
import com.licensis.notaire.dto.DtoPresupuesto;
import com.licensis.notaire.dto.DtoTipoIdentificacion;
import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.gui.gestiones.gestion.IniciarGestion;
import com.licensis.notaire.gui.pagos.ConsultarPagos;
import com.licensis.notaire.gui.pagos.RegistrarPago;
import com.licensis.notaire.jpa.exceptions.NonexistentJpaException;
import com.licensis.notaire.negocio.ControllerNegocio;
import com.licensis.notaire.servicios.AdministradorReportes;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Tefi
 */
public class BuscarPresupuesto extends javax.swing.JInternalFrame
{

    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem ventanaBuscarPresupuesto = new JMenuItem("Ventana Buscar Presupuestos");
    private String formularioInvocador = new String();
    private ControllerNegocio miController = ControllerNegocio.getInstancia();
    private ModificarPresupuesto modificarPresupuesto = null;
    private Map parameters = new HashMap();

    /**
     * Creates new form BuscarPresupuesto
     */
    public BuscarPresupuesto()
    {
        initComponents();
        this.estadoFormulario = Boolean.TRUE;
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        this.grupoBotones.add(radioBuscarPorPresupuesto);
        this.grupoBotones.add(radioNombreApellido);
        this.grupoBotones.add(radioIdentificacion);
        this.grupoBotones.setSelected(radioBuscarPorPresupuesto.getModel(), true);
        this.cargarCombo();
    }

    public void setFormModificarPresupuesto(ModificarPresupuesto formulario)
    {
        this.modificarPresupuesto = formulario;
    }

    public void setFormularioInvocador(String nombreFormulario)
    {
        this.formularioInvocador = nombreFormulario;
    }

    public void cargarCombo()
    {
        ArrayList<DtoTipoIdentificacion> listaDtoIdentificaciones = ControllerNegocio.getInstancia().listarTiposIdentificacion();

        for (int i = 0; i < listaDtoIdentificaciones.size(); i++)
        {
            String nombre = listaDtoIdentificaciones.get(i).getNombre();
            this.comboTipoIdentificacion.addItem(nombre);
        }
    }

    private void salir()
    {
        this.dispose();
    }

    public static JMenuItem getVentanaBuscarPresupuesto()
    {
        return ventanaBuscarPresupuesto;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        panelBuscarPresupuesto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radioBuscarPorPresupuesto = new javax.swing.JRadioButton();
        campoNumeroPresupuesto = new javax.swing.JTextField();
        radioIdentificacion = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        comboTipoIdentificacion = new javax.swing.JComboBox();
        campoNumeroIdentificacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botonBuscar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        radioNombreApellido = new javax.swing.JRadioButton();
        campoApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Buscar Presupuestos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Buscar Presupuesto");

        jLabel2.setText("Número de Presupuesto:");

        radioBuscarPorPresupuesto.setText("Buscar por Número de Presupuesto:");

        campoNumeroPresupuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNumeroPresupuestoMouseClicked(evt);
            }
        });
        campoNumeroPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroPresupuestoActionPerformed(evt);
            }
        });

        radioIdentificacion.setText("Buscar por Tipo y Número de Identificación de Cliente:");
        radioIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioIdentificacionActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo Ident.:");

        comboTipoIdentificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboTipoIdentificacionMouseClicked(evt);
            }
        });

        campoNumeroIdentificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNumeroIdentificacionMouseClicked(evt);
            }
        });

        jLabel5.setText("Número Ident.:");

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        radioNombreApellido.setText("Buscar por Nombre y Apellido:");

        campoApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoApellidoMouseClicked(evt);
            }
        });

        jLabel3.setText("Nombre:");

        campoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNombreMouseClicked(evt);
            }
        });

        jLabel6.setText("Apellido");

        javax.swing.GroupLayout panelBuscarPresupuestoLayout = new javax.swing.GroupLayout(panelBuscarPresupuesto);
        panelBuscarPresupuesto.setLayout(panelBuscarPresupuestoLayout);
        panelBuscarPresupuestoLayout.setHorizontalGroup(
            panelBuscarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarPresupuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarPresupuestoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBuscarPresupuestoLayout.createSequentialGroup()
                        .addGroup(panelBuscarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBuscarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBuscarPresupuestoLayout.createSequentialGroup()
                                    .addGroup(panelBuscarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(radioBuscarPorPresupuesto, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBuscarPresupuestoLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(campoNumeroPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBuscarPresupuestoLayout.createSequentialGroup()
                                            .addGroup(panelBuscarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel3))
                                            .addGap(18, 18, 18)
                                            .addGroup(panelBuscarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(radioNombreApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(radioIdentificacion, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(33, 33, 33)))
                            .addGroup(panelBuscarPresupuestoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(panelBuscarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboTipoIdentificacion, 0, 150, Short.MAX_VALUE)
                                    .addComponent(campoNumeroIdentificacion))))
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBuscarPresupuestoLayout.setVerticalGroup(
            panelBuscarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarPresupuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(radioBuscarPorPresupuesto)
                .addGap(18, 18, 18)
                .addGroup(panelBuscarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNumeroPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioNombreApellido)
                .addGap(18, 18, 18)
                .addGroup(panelBuscarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBuscarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(radioIdentificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBuscarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboTipoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBuscarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoNumeroIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(panelBuscarPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBuscarPresupuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBuscarPresupuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(ventanaBuscarPresupuesto);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
        salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonBuscarActionPerformed
    {//GEN-HEADEREND:event_botonBuscarActionPerformed
        DtoPersona miDtoPersona = new DtoPersona();
        DtoTipoIdentificacion miDtoIdentificacion = new DtoTipoIdentificacion();
        DtoPresupuesto presupuestoEncontrado = null;

        if (radioBuscarPorPresupuesto.isSelected() && !campoNumeroPresupuesto.getText().isEmpty())
        {

            DtoPresupuesto dtoBuscar = new DtoPresupuesto();

            try
            {
                dtoBuscar.setIdPresupuesto(Integer.parseInt(campoNumeroPresupuesto.getText()));

                presupuestoEncontrado = miController.buscarPresupuestoPorNumero(dtoBuscar);

                if (presupuestoEncontrado != null)
                {
                    switch (this.formularioInvocador)
                    {
                        case ConstantesGui.MODIFICAR_PRESUPUESTO:
                        {
                            modificarPresupuesto.setPresupuesto(presupuestoEncontrado);
                            modificarPresupuesto.setPersona(presupuestoEncontrado.getPersona());
                            modificarPresupuesto.cargarFormulario();

                            Principal.cargarFormulario(modificarPresupuesto);
                            Principal.setVentanasActivas(ModificarPresupuesto.getVentanaModificarPresupuesto());
                            break;
                        }
                        case ConstantesGui.INICIAR_GESTION:
                        {
                            if (presupuestoEncontrado.getPersona().getEsCliente())
                            {

                                IniciarGestion miForm = (IniciarGestion) Principal.obtenerFormularioActivo(ConstantesGui.INICIAR_GESTION);

                                //  Verifico que el presupuesto seleccionado no este asociado a una gestion.
                                if (presupuestoEncontrado.getTramite().getGestion() == null)
                                {
                                    miForm.setPresupuestoSeleccionado(presupuestoEncontrado);
                                    miForm.cargarGrillaTramitesPresupuesto();
                                    salir();
                                } else
                                {
                                    JOptionPane.showMessageDialog(this, "El presupuesto seleccionado ya se encuentra registrado en una gestion", "Error", JOptionPane.ERROR_MESSAGE);
                                }

                            } else
                            {
                                JOptionPane.showMessageDialog(this, "La persona que solicito el presupuesto aun no ha sido registrado como cliente.", "Advertencia", JOptionPane.ERROR_MESSAGE);
                                this.salir();
                            }
                            this.salir();
                            break;
                        }
                        case ConstantesGui.BUSCAR_PRESUPUESTO:
                        {
                            AdministradorReportes reportes = AdministradorReportes.getInstancia();
                        try
                        {
                            reportes.generarReportePresupuesto(presupuestoEncontrado);
                        }
                        catch (IOException ex)
                        {
                            Logger.getLogger(BuscarPresupuesto.class.getName()).log(Level.SEVERE, null, ex);
                        }
                            break;
                        }
                        case ConstantesGui.REGISTRAR_PAGO:
                        {
                            RegistrarPago formPago = new RegistrarPago();
                            Principal.cargarFormulario(formPago);
                            Principal.setVentanasActivas(RegistrarPago.getVentanaRegistrarPagos());
                            break;
                        }
                        case ConstantesGui.CONSULTAR_PAGOS:
                        {
                            ConsultarPagos formConsultarPagos = new ConsultarPagos();

                            Principal.cargarFormulario(formConsultarPagos);
                            Principal.setVentanasActivas(ConsultarPagos.getVentanaConsultarPagos());
                            break;
                        }

                    }
                } else
                {
                    JOptionPane.showMessageDialog(this, "El Presupuesto indicado no existe.", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch (NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(this, "El valor de presupuesto no es valido", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } else if (radioNombreApellido.isSelected() && (!campoNombre.getText().isEmpty() || !campoApellido.getText().isEmpty()))
        {

            ArrayList<DtoPersona> miListaDtoPersonasEncontradas = null;

            //Set datos de busqueda Nombre y apellido, por aproximacion
            miDtoPersona.setNombre(campoNombre.getText());
            miDtoPersona.setApellido(campoApellido.getText());

            //Busco todas las personas que tengan alguna coincidencia ya sea por Nombre o Apellido
            miListaDtoPersonasEncontradas = miController.buscarPersonaNombreApellido(miDtoPersona);

            if (miListaDtoPersonasEncontradas != null && !miListaDtoPersonasEncontradas.isEmpty())
            {
                ListaPersonasPresupuesto.getInstancia().limpiarJtable();
                ListaPersonasPresupuesto.setFormularioInvocador(formularioInvocador);
                ListaPersonasPresupuesto.getInstancia().cargarGrillaPersonas(miListaDtoPersonasEncontradas);

                Principal.cargarFormulario(ListaPersonasPresupuesto.getInstancia());
                Principal.setVentanasActivas(ListaPersonasPresupuesto.getVentanaListaPresupuesto());
            } else
            {
                JOptionPane.showMessageDialog(this, "<HTML>No se han encontrado personas con presupuesto,<BR> que coincidan con los datos indicados.</HTML>", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);

            }
        } else if (radioIdentificacion.isSelected() && !campoNumeroIdentificacion.getText().isEmpty())
        {

            //Set dato de busqueda 
            miDtoIdentificacion.setNombre(comboTipoIdentificacion.getSelectedItem().toString());
            miDtoPersona.setDtoTipoIdentificacion(miDtoIdentificacion);
            miDtoPersona.setNumeroIdentificacion(campoNumeroIdentificacion.getText());
            miDtoPersona.getDtoTipoIdentificacion().setIdTipoIdentificacion(miController.asociarFkTipoIdentificacion(miDtoPersona));

            //Busco la persona por Tipo y Numero de documento
            DtoPersona personaEncontrada = miController.buscarPersonaTipoNumeroIdentificacion(miDtoPersona);

            if (personaEncontrada != null)
            {

                switch (formularioInvocador)
                {
                    case ConstantesGui.MODIFICAR_PRESUPUESTO:
                    {
                        ListaPresupuestosCliente ventanaLista = new ListaPresupuestosCliente();

                        ventanaLista.limpiarGrilla();
                        ventanaLista.setFormModificarPresupuesto(modificarPresupuesto);
                        ventanaLista.setPersona(personaEncontrada);
                        try
                        {
                            ventanaLista.cargarGrillaPresupuestos();
                        }
                        catch (NonexistentJpaException ex)
                        {
                            Logger.getLogger(BuscarPresupuesto.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        ventanaLista.setFormulario(formularioInvocador);

                        Principal.cargarFormulario(ventanaLista);
                        break;
                    }
                    case ConstantesGui.BUSCAR_PRESUPUESTO:
                    {
                        ListaPresupuestosCliente ventanaLista = new ListaPresupuestosCliente();

                        ventanaLista.limpiarGrilla();
                        ventanaLista.setPersona(personaEncontrada);
                        try
                        {
                            ventanaLista.cargarGrillaPresupuestos();
                        }
                        catch (NonexistentJpaException ex)
                        {
                            Logger.getLogger(BuscarPresupuesto.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        ventanaLista.setFormulario(formularioInvocador);

                        Principal.cargarFormulario(ventanaLista);
                        break;
                    }
                    case ConstantesGui.INICIAR_GESTION:
                    {
                        if (personaEncontrada.getEsCliente())
                        {
                            ListaPresupuestosClientesSinGestion presupuestosForm = new ListaPresupuestosClientesSinGestion();
                            presupuestosForm.setFormularioInvocador(ConstantesGui.INICIAR_GESTION);
                            presupuestosForm.setClienteSeleccionado(personaEncontrada);

                            Principal.cargarFormulario(presupuestosForm);
                            Principal.setVentanasActivas(ListaPresupuestosClientesSinGestion.getVentanaListaPresupuestoClienteSinGestion());
                        } else
                        {
                            JOptionPane.showMessageDialog(this, "La persona seleccionada aun no ha sido registrada como cliente", "Advertencia", JOptionPane.WARNING_MESSAGE);
                        }
                        salir();
                        break;
                    }
                }

            } else
            {
                JOptionPane.showMessageDialog(this, "La persona indicada no tiene presupuestos asociados.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else
        {
            JOptionPane.showMessageDialog(this, "Debe completar los datos a buscar.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void radioIdentificacionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radioIdentificacionActionPerformed
    {//GEN-HEADEREND:event_radioIdentificacionActionPerformed
    }//GEN-LAST:event_radioIdentificacionActionPerformed

    private void campoNumeroPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroPresupuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroPresupuestoActionPerformed

    private void campoNumeroPresupuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNumeroPresupuestoMouseClicked
        // TODO add your handling code here:
        radioBuscarPorPresupuesto.setSelected(true);
        radioIdentificacion.setSelected(false);
        radioNombreApellido.setSelected(false);
    }//GEN-LAST:event_campoNumeroPresupuestoMouseClicked

    private void campoNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNombreMouseClicked
        // TODO add your handling code here:
        radioBuscarPorPresupuesto.setSelected(false);
        radioIdentificacion.setSelected(false);
        radioNombreApellido.setSelected(true);
    }//GEN-LAST:event_campoNombreMouseClicked

    private void campoApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoApellidoMouseClicked
        // TODO add your handling code here:
        radioBuscarPorPresupuesto.setSelected(false);
        radioIdentificacion.setSelected(false);
        radioNombreApellido.setSelected(true);
    }//GEN-LAST:event_campoApellidoMouseClicked

    private void comboTipoIdentificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTipoIdentificacionMouseClicked
        // TODO add your handling code here:
        radioBuscarPorPresupuesto.setSelected(false);
        radioIdentificacion.setSelected(true);
        radioNombreApellido.setSelected(false);
    }//GEN-LAST:event_comboTipoIdentificacionMouseClicked

    private void campoNumeroIdentificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNumeroIdentificacionMouseClicked
        // TODO add your handling code here:
        radioBuscarPorPresupuesto.setSelected(false);
        radioIdentificacion.setSelected(true);
        radioNombreApellido.setSelected(false);
    }//GEN-LAST:event_campoNumeroIdentificacionMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoNumeroIdentificacion;
    private javax.swing.JTextField campoNumeroPresupuesto;
    private javax.swing.JComboBox comboTipoIdentificacion;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelBuscarPresupuesto;
    private javax.swing.JRadioButton radioBuscarPorPresupuesto;
    private javax.swing.JRadioButton radioIdentificacion;
    private javax.swing.JRadioButton radioNombreApellido;
    // End of variables declaration//GEN-END:variables
}
