/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion;

import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.gui.administracion.conceptos.Conceptos;
import com.licensis.notaire.gui.administracion.documentos.Documentos;
import com.licensis.notaire.gui.administracion.escribanos.Escribanos;
import com.licensis.notaire.gui.administracion.estadosGestion.EstadosDeGestion;
import com.licensis.notaire.gui.administracion.folios.Folios;
import com.licensis.notaire.gui.administracion.plantillasPresupuesto.PlantillasPresupuesto;
import com.licensis.notaire.gui.administracion.tramites.Tramites;
import com.licensis.notaire.gui.administracion.usuarios.Usuarios;
import javax.swing.JMenuItem;

/**
 *
 * @author matias
 */
public class Administracion extends javax.swing.JInternalFrame
{

    private static Administracion instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem menuAdministracion = new JMenuItem("Modulo Administracion");

    /**
     * Creates new form Administracion
     */
    private Administracion() {
        initComponents();
    }

    public static Administracion getInstancia() {
        if (instancia == null)
        {
            instancia = new Administracion();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        }
        return instancia;

    }

    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario) {
        Administracion.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getMenuAdministracion() {
        return menuAdministracion;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAdministrarUsuarios = new javax.swing.JButton();
        botonAdministrarEscribanos = new javax.swing.JButton();
        botonAdministrarTramites = new javax.swing.JButton();
        botonAdministrarDocumentos = new javax.swing.JButton();
        botonAdministrarConceptos = new javax.swing.JButton();
        botonAdministrarEstadosGestion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonAdministrarFolios = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        botonPlantillaPresupuesto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Modulo Administracion");
        setToolTipText("Módulo Administración");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonAdministrarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/administracion/usuarios.png"))); // NOI18N
        botonAdministrarUsuarios.setIconTextGap(0);
        botonAdministrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministrarUsuariosActionPerformed(evt);
            }
        });

        botonAdministrarEscribanos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/administracion/escribanos.png"))); // NOI18N
        botonAdministrarEscribanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministrarEscribanosActionPerformed(evt);
            }
        });

        botonAdministrarTramites.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/administracion/tramites.png"))); // NOI18N
        botonAdministrarTramites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministrarTramitesActionPerformed(evt);
            }
        });

        botonAdministrarDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/administracion/documentos.png"))); // NOI18N
        botonAdministrarDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministrarDocumentosActionPerformed(evt);
            }
        });

        botonAdministrarConceptos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/administracion/conceptos.png"))); // NOI18N
        botonAdministrarConceptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministrarConceptosActionPerformed(evt);
            }
        });

        botonAdministrarEstadosGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/administracion/estadosGestion.png"))); // NOI18N
        botonAdministrarEstadosGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministrarEstadosGestionActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuarios");

        jLabel2.setText("Escribanos");

        jLabel3.setText("Trámites");

        jLabel4.setText("Documentos");

        jLabel5.setText("Conceptos");

        jLabel6.setText("Estados de Gestión");

        botonAdministrarFolios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/administracion/folios/tiposDeFolio.png"))); // NOI18N
        botonAdministrarFolios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministrarFoliosActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipos de Folio");

        botonPlantillaPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/administracion/plantillaPresupuesto.png"))); // NOI18N
        botonPlantillaPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPlantillaPresupuestoActionPerformed(evt);
            }
        });

        jLabel8.setText("Plantillas Presupuesto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAdministrarConceptos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(botonAdministrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAdministrarEscribanos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(botonAdministrarTramites, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAdministrarDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAdministrarEstadosGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAdministrarFolios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(botonPlantillaPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAdministrarDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAdministrarEscribanos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAdministrarTramites, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAdministrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonAdministrarEstadosGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAdministrarFolios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAdministrarConceptos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonPlantillaPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(menuAdministracion);
        instancia = null;
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonAdministrarUsuariosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAdministrarUsuariosActionPerformed
    {//GEN-HEADEREND:event_botonAdministrarUsuariosActionPerformed
        if (Usuarios.getEstadoFormulario() == Boolean.FALSE)
        {
            Principal.cargarFormulario(Usuarios.getInstancia());
            Principal.setVentanasActivas(Usuarios.getSubmenuUsuarios());
        }
        else
        {
            for (int i = 0; i < Principal.AreaTrabajo.getAllFrames().length; i++)
            {
                if (Principal.AreaTrabajo.getAllFrames()[i].equals(Usuarios.getInstancia()))
                {
                    Principal.cargarFormulario(Usuarios.getInstancia());
                    Principal.setVentanasActivas(Usuarios.getSubmenuUsuarios());
                }
            }
        }
    }//GEN-LAST:event_botonAdministrarUsuariosActionPerformed

    private void botonAdministrarEscribanosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAdministrarEscribanosActionPerformed
    {//GEN-HEADEREND:event_botonAdministrarEscribanosActionPerformed
        if (Escribanos.getEstadoFormulario() == Boolean.FALSE)
        {
            Principal.cargarFormulario(Escribanos.getInstancia());
            Principal.setVentanasActivas(Escribanos.getSubmenuEscribanos());
        }
        else
        {
            for (int i = 0; i < Principal.AreaTrabajo.getAllFrames().length; i++)
            {
                if (Principal.AreaTrabajo.getAllFrames()[i].equals(Escribanos.getInstancia()))
                {
                    Principal.cargarFormulario(Escribanos.getInstancia());
                    Principal.setVentanasActivas(Escribanos.getSubmenuEscribanos());
                }
            }
        }
    }//GEN-LAST:event_botonAdministrarEscribanosActionPerformed

    private void botonAdministrarTramitesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAdministrarTramitesActionPerformed
    {//GEN-HEADEREND:event_botonAdministrarTramitesActionPerformed
        if (Tramites.getEstadoFormulario() == Boolean.FALSE)
        {
            Principal.cargarFormulario(Tramites.getInstancia());
            Principal.setVentanasActivas(Tramites.getSubmenuTramites());
        }
        else
        {
            for (int i = 0; i < Principal.AreaTrabajo.getAllFrames().length; i++)
            {
                if (Principal.AreaTrabajo.getAllFrames()[i].equals(Tramites.getInstancia()))
                {
                    Principal.cargarFormulario(Tramites.getInstancia());
                    Principal.setVentanasActivas(Tramites.getSubmenuTramites());
                }
            }
        }
    }//GEN-LAST:event_botonAdministrarTramitesActionPerformed

    private void botonAdministrarDocumentosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAdministrarDocumentosActionPerformed
    {//GEN-HEADEREND:event_botonAdministrarDocumentosActionPerformed
        if (Documentos.getEstadoFormulario() == Boolean.FALSE)
        {
            Principal.cargarFormulario(Documentos.getInstancia());
            Principal.setVentanasActivas(Documentos.getSubmenuDocumentos());
        }
        else
        {
            for (int i = 0; i < Principal.AreaTrabajo.getAllFrames().length; i++)
            {
                if (Principal.AreaTrabajo.getAllFrames()[i].equals(Documentos.getInstancia()))
                {
                    Principal.cargarFormulario(Documentos.getInstancia());
                    Principal.setVentanasActivas(Documentos.getSubmenuDocumentos());
                }
            }
        }
    }//GEN-LAST:event_botonAdministrarDocumentosActionPerformed

    private void botonAdministrarConceptosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAdministrarConceptosActionPerformed
    {//GEN-HEADEREND:event_botonAdministrarConceptosActionPerformed
        if (Conceptos.getEstadoFormulario() == Boolean.FALSE)
        {
            Principal.cargarFormulario(Conceptos.getInstancia());
            Principal.setVentanasActivas(Conceptos.getSubmenuConceptos());
        }
        else
        {
            for (int i = 0; i < Principal.AreaTrabajo.getAllFrames().length; i++)
            {
                if (Principal.AreaTrabajo.getAllFrames()[i].equals(Conceptos.getInstancia()))
                {
                    Principal.cargarFormulario(Conceptos.getInstancia());
                }
            }
        }
    }//GEN-LAST:event_botonAdministrarConceptosActionPerformed

    private void botonAdministrarEstadosGestionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAdministrarEstadosGestionActionPerformed
    {//GEN-HEADEREND:event_botonAdministrarEstadosGestionActionPerformed
        if (EstadosDeGestion.getEstadoFormulario() == Boolean.FALSE)
        {
            Principal.cargarFormulario(EstadosDeGestion.getInstancia());
            Principal.setVentanasActivas(EstadosDeGestion.getSubmenuEstadosDeGestion());
        }
        else
        {
            for (int i = 0; i < Principal.AreaTrabajo.getAllFrames().length; i++)
            {
                if (Principal.AreaTrabajo.getAllFrames()[i].equals(EstadosDeGestion.getInstancia()))
                {
                    Principal.cargarFormulario(EstadosDeGestion.getInstancia());
                }
            }
        }
    }//GEN-LAST:event_botonAdministrarEstadosGestionActionPerformed

    private void botonAdministrarFoliosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAdministrarFoliosActionPerformed
    {//GEN-HEADEREND:event_botonAdministrarFoliosActionPerformed
        if (Folios.getEstadoFormulario() == Boolean.FALSE)
        {
            Principal.cargarFormulario(Folios.getInstancia());
            Principal.setVentanasActivas(Folios.getSubmenuFolios());
        }
        else
        {
            for (int i = 0; i < Principal.AreaTrabajo.getAllFrames().length; i++)
            {
                if (Principal.AreaTrabajo.getAllFrames()[i].equals(Folios.getInstancia()))
                {
                    Principal.cargarFormulario(Folios.getInstancia());
                }
            }
        }
    }//GEN-LAST:event_botonAdministrarFoliosActionPerformed

    private void botonPlantillaPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPlantillaPresupuestoActionPerformed

        if (PlantillasPresupuesto.getEstadoFormulario() == Boolean.FALSE)
        {
            Principal.cargarFormulario(PlantillasPresupuesto.getInstancia());
            Principal.setVentanasActivas(PlantillasPresupuesto.getSubmenuPlantillaPresupuesto());
        }
        else
        {
            for (int i = 0; i < Principal.AreaTrabajo.getAllFrames().length; i++)
            {
                if (Principal.AreaTrabajo.getAllFrames()[i].equals(PlantillasPresupuesto.getInstancia()))
                {
                    Principal.cargarFormulario(PlantillasPresupuesto.getInstancia());
                    Principal.setVentanasActivas(PlantillasPresupuesto.getSubmenuPlantillaPresupuesto());
                }
            }
        }

    }//GEN-LAST:event_botonPlantillaPresupuestoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdministrarConceptos;
    private javax.swing.JButton botonAdministrarDocumentos;
    private javax.swing.JButton botonAdministrarEscribanos;
    private javax.swing.JButton botonAdministrarEstadosGestion;
    private javax.swing.JButton botonAdministrarFolios;
    private javax.swing.JButton botonAdministrarTramites;
    private javax.swing.JButton botonAdministrarUsuarios;
    private javax.swing.JButton botonPlantillaPresupuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
