/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.protocolo.folios;

import com.licensis.notaire.dto.DtoFolio;
import com.licensis.notaire.dto.DtoPersona;
import com.licensis.notaire.dto.DtoTipoDeFolio;
import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.negocio.ConstantesNegocio;
import com.licensis.notaire.negocio.ControllerNegocio;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author matias
 */
public class IngresarFolios extends javax.swing.JInternalFrame
{

    private static JMenuItem ventanaIngresarFolios = new JMenuItem("Ventana Ingresar Folios");
    private static Boolean estadoFormulario = Boolean.FALSE;
    private ControllerNegocio miController = null;
    private List<DtoPersona> milistaEscribanos = null;

    /**
     * Creates new form IngresarFolios
     */
    public IngresarFolios()
    {
        initComponents();
        IngresarFolios.estadoFormulario = Boolean.TRUE;
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        this.miController = ControllerNegocio.getInstancia();
        this.cargarRegistrosEscribanos();
    }

    private void salir()
    {
        this.dispose();
    }

    public static JMenuItem getVentanaIngresarFolios()
    {
        return ventanaIngresarFolios;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIngresarFolios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        comboRegistroEscribano = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoFolioDesde = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoFolioHasta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        selectorAnio = new com.toedter.calendar.JYearChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoObservaciones = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Ingresar Folios");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Ingresar Folios");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Registro Escribano:");

        jLabel3.setText("Desde:");

        jLabel4.setText("Hasta:");

        jLabel5.setText("Inclusive");

        jLabel6.setText("Año:");

        campoObservaciones.setColumns(20);
        campoObservaciones.setRows(5);
        jScrollPane1.setViewportView(campoObservaciones);

        jLabel7.setText("Observaciones:");

        jLabel8.setText("*Todos los Folios son para el protocolo principal.");

        javax.swing.GroupLayout panelIngresarFoliosLayout = new javax.swing.GroupLayout(panelIngresarFolios);
        panelIngresarFolios.setLayout(panelIngresarFoliosLayout);
        panelIngresarFoliosLayout.setHorizontalGroup(
            panelIngresarFoliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarFoliosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngresarFoliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresarFoliosLayout.createSequentialGroup()
                        .addGap(0, 465, Short.MAX_VALUE)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIngresarFoliosLayout.createSequentialGroup()
                        .addGroup(panelIngresarFoliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(panelIngresarFoliosLayout.createSequentialGroup()
                                .addGroup(panelIngresarFoliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelIngresarFoliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectorAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelIngresarFoliosLayout.createSequentialGroup()
                                        .addGroup(panelIngresarFoliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jScrollPane1)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelIngresarFoliosLayout.createSequentialGroup()
                                                .addComponent(campoFolioDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(campoFolioHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(comboRegistroEscribano, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5))))
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelIngresarFoliosLayout.setVerticalGroup(
            panelIngresarFoliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarFoliosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelIngresarFoliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboRegistroEscribano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarFoliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoFolioDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campoFolioHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(panelIngresarFoliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIngresarFoliosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(90, 90, 90)
                        .addGroup(panelIngresarFoliosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelIngresarFoliosLayout.createSequentialGroup()
                        .addComponent(selectorAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelIngresarFolios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelIngresarFolios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAceptarActionPerformed
    {//GEN-HEADEREND:event_botonAceptarActionPerformed
        try
        {
            List<DtoFolio> nuevaListaFolios = new ArrayList<>();

            int desde = Integer.parseInt(campoFolioDesde.getText());
            int hasta = Integer.parseInt(campoFolioHasta.getText());

            //  verificamos que los numeros de folios sean validos.
            if (desde >= hasta)
            {
                JOptionPane.showMessageDialog(this, "Los valores de los folios no son validos", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else
            {
                Date date = new Date();
                SimpleDateFormat simpleDateformat = new SimpleDateFormat("yyyy");
                int anio = Integer.valueOf(simpleDateformat.format(date));

                if (this.selectorAnio.getYear() < anio)
                {
                    JOptionPane.showMessageDialog(this, "El año ingresado es menos que el actual, favor corregir!", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else
                {
                    DtoPersona personaEscribanoSeleccionado = null;
                    Integer registroEscribano = Integer.parseInt(comboRegistroEscribano.getSelectedItem().toString());
                    for (Iterator<DtoPersona> it = milistaEscribanos.iterator(); it.hasNext();)
                    {
                        DtoPersona dtoPersonaEscribano = it.next();
                        if (dtoPersonaEscribano.getRegistroEscribano().intValue() == registroEscribano.intValue())
                        {
                            personaEscribanoSeleccionado = dtoPersonaEscribano;
                            break;
                        }
                    }

                    // Creamos dos instancia (temporales de DtoFolio desde y hasta para verificar si nos validos.
                    DtoFolio folioDesde = new DtoFolio();
                    folioDesde.setNumero(desde);
                    folioDesde.setPersonaEscribano(personaEscribanoSeleccionado);
                    folioDesde.setAnio(anio);

                    DtoFolio folioHasta = new DtoFolio();
                    folioHasta.setNumero(hasta);
                    folioHasta.setPersonaEscribano(personaEscribanoSeleccionado);
                    folioHasta.setAnio(anio);

                    //  Hay que verificar que esos numeros de folios no esten ya registrados.
                    if (miController.verificarExistenciaFolios(folioDesde, folioHasta) == true)
                    {

                        DtoTipoDeFolio miTipoDeFolio = miController.buscarTipoDeFolio(new DtoTipoDeFolio(ConstantesGui.FOLIO_PROTOCOLO_PRINCIPAL));

                        folioDesde.setEstado(ConstantesNegocio.ESTADO_FOLIO_NUEVOS);
                        folioDesde.setObservaciones(campoObservaciones.getText());
                        folioDesde.setAnio(selectorAnio.getYear());
                        folioDesde.setTiposDeFolio(miTipoDeFolio);
                        folioDesde.setPersonaEscribano(personaEscribanoSeleccionado);

                        folioHasta.setEstado(ConstantesNegocio.ESTADO_FOLIO_NUEVOS);
                        folioHasta.setObservaciones(campoObservaciones.getText());
                        folioHasta.setAnio(selectorAnio.getYear());
                        folioHasta.setTiposDeFolio(miTipoDeFolio);
                        folioHasta.setPersonaEscribano(personaEscribanoSeleccionado);

                        if (miController.registrarIngresoNuevosFolios(folioDesde, folioHasta) == Boolean.TRUE)
                        {
                            JOptionPane.showMessageDialog(this, "Se ha ingresado folios Correctamente");
                            salir();
                        } else
                        {
                            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al registrar nuevos folios", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } else
                    {
                        JOptionPane.showMessageDialog(this, "Los valores de los folios no son validos. Ya se encuentran registrados en el sistema.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    }
                }
            }
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Los valores de los folios no son validos", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
        salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(ventanaIngresarFolios);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    public void cargarRegistrosEscribanos()
    {
        try
        {
            this.setMilistaEscribanos(miController.obtenerListaEscribanosDisponibles());

            if (!this.getMilistaEscribanos().isEmpty())
            {

                for (Iterator<DtoPersona> it = this.getMilistaEscribanos().iterator(); it.hasNext();)
                {
                    DtoPersona dtoPersona = it.next();

                    this.comboRegistroEscribano.addItem(dtoPersona.getRegistroEscribano());
                }
            } else
            {
                JOptionPane.showMessageDialog(this, "No existen escribanos registrados", "Error", JOptionPane.ERROR_MESSAGE);
                this.salir();
            }

        }
        catch (NullPointerException e)
        {
            JOptionPane.showMessageDialog(this, "No existen escribanos registrados", "Error", JOptionPane.ERROR_MESSAGE);
            this.salir();
        }
    }

    public List<DtoPersona> getMilistaEscribanos()
    {
        return milistaEscribanos;
    }

    public void setMilistaEscribanos(List<DtoPersona> milistaEscribanos)
    {
        this.milistaEscribanos = milistaEscribanos;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoFolioDesde;
    private javax.swing.JTextField campoFolioHasta;
    private javax.swing.JTextArea campoObservaciones;
    private javax.swing.JComboBox comboRegistroEscribano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelIngresarFolios;
    private com.toedter.calendar.JYearChooser selectorAnio;
    // End of variables declaration//GEN-END:variables
}
