/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.gestiones.escrituras;

import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import javax.swing.JMenuItem;

/**
 *
 * @author matias
 */
public class Escrituras extends javax.swing.JInternalFrame
{

    private static Escrituras instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem submenuEscrituras = new JMenuItem("Sub-modulo Escrituras");

    /**
     * Creates new form Escrituras
     */
    private Escrituras() {
        initComponents();
    }

    public static Escrituras getInstancia() {
        if (instancia == null)
        {
            instancia = new Escrituras();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);

        }
        return instancia;
    }

    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario) {
        Escrituras.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getSubmenuEscrituras() {
        return submenuEscrituras;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonPrepararEscritura = new javax.swing.JButton();
        botonBuscarEscritura = new javax.swing.JButton();
        botonModificarEscritura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Sub-modulo Escrituras");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonPrepararEscritura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/escrituras/prepararEscritura.png"))); // NOI18N
        botonPrepararEscritura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrepararEscrituraActionPerformed(evt);
            }
        });

        botonBuscarEscritura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/escrituras/buscarEscritura.png"))); // NOI18N
        botonBuscarEscritura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarEscrituraActionPerformed(evt);
            }
        });

        botonModificarEscritura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestiones/escrituras/modificarEscritura.png"))); // NOI18N
        botonModificarEscritura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarEscrituraActionPerformed(evt);
            }
        });

        jLabel1.setText("Preparar Escritura");

        jLabel3.setText("Buscar Escritura");

        jLabel4.setText("Modificar Escritura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonPrepararEscritura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonModificarEscritura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBuscarEscritura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonModificarEscritura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarEscritura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPrepararEscritura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(303, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(submenuEscrituras);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonPrepararEscrituraActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonPrepararEscrituraActionPerformed
    {//GEN-HEADEREND:event_botonPrepararEscrituraActionPerformed
        Principal.cargarFormulario(new PrepararEscritura());
        Principal.setVentanasActivas(PrepararEscritura.getVentanaPrepararEscritura());
    }//GEN-LAST:event_botonPrepararEscrituraActionPerformed

    private void botonModificarEscrituraActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonModificarEscrituraActionPerformed
    {//GEN-HEADEREND:event_botonModificarEscrituraActionPerformed
        BuscarEscritura buscarEscrituraForm = new BuscarEscritura();
        buscarEscrituraForm.setFormularioInvocador(ConstantesGui.MODIFICAR_ESCRITURA);        
        buscarEscrituraForm.cargarFormulario();
        Principal.cargarFormulario(buscarEscrituraForm);
        Principal.setVentanasActivas(BuscarEscritura.getVentanaBuscarEscritura());
    }//GEN-LAST:event_botonModificarEscrituraActionPerformed

    private void botonBuscarEscrituraActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonBuscarEscrituraActionPerformed
    {//GEN-HEADEREND:event_botonBuscarEscrituraActionPerformed
        BuscarEscritura buscarEscrituraForm = new BuscarEscritura();
        buscarEscrituraForm.setFormularioInvocador(ConstantesGui.BUSCAR_ESCRITURA);
        buscarEscrituraForm.cargarFormulario();
        Principal.cargarFormulario(buscarEscrituraForm);
        Principal.setVentanasActivas(BuscarEscritura.getVentanaBuscarEscritura());
    }//GEN-LAST:event_botonBuscarEscrituraActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarEscritura;
    private javax.swing.JButton botonModificarEscritura;
    private javax.swing.JButton botonPrepararEscritura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
