/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.gestiones.escrituras;

import com.licensis.notaire.dto.DtoGestionDeEscritura;
import com.licensis.notaire.dto.DtoPersona;
import com.licensis.notaire.dto.DtoTramite;
import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.gui.gestiones.gestion.BuscarGestion;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;

/**
 *
 * @author matias
 */
public class PrepararEscritura extends javax.swing.JInternalFrame
{

    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem ventanaPrepararEscritura = new JMenuItem("Ventana Preparar Escritura");
    private DtoGestionDeEscritura miGestionDeEscritura = null;

    /**
     * Creates new form PrepararEscritura
     */
    public PrepararEscritura() {
        initComponents();
        estadoFormulario = Boolean.TRUE;
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioGrandeVertical);
    }

    private void salir() {
        this.dispose();
    }

    public static JMenuItem getVentanaPrepararEscritura() {
        return ventanaPrepararEscritura;
    }

    public void cargarFormulario(DtoGestionDeEscritura miDtoGestionDeEscritura) {

        if (miDtoGestionDeEscritura != null)
        {
            miGestionDeEscritura = miDtoGestionDeEscritura;
            Integer numeroGestion = miDtoGestionDeEscritura.getNumero();

            campoNumeroGestion.setText(numeroGestion.toString());
            campoEncabezado.setText(miDtoGestionDeEscritura.getEncabezado());

            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            campoFechaInicio.setText(formatter.format(miDtoGestionDeEscritura.getFechaInicio()).toString());

            campoEscribano.setText(miDtoGestionDeEscritura.getPersonaEscribano().getNombre() + " " + miDtoGestionDeEscritura.getPersonaEscribano().getApellido());

            if (miDtoGestionDeEscritura.getListaTramitesAsociados() != null
                    && !miDtoGestionDeEscritura.getListaTramitesAsociados().isEmpty())
            {

                for (Iterator it = miDtoGestionDeEscritura.getListaTramitesAsociados().iterator(); it.hasNext();)
                {
                    DtoTramite miDtoTramite = (DtoTramite) it.next();

                    if (miDtoTramite.getInmueble() != null)
                    {
                        campoNC.setText(miDtoTramite.getInmueble().getNomenclaturaCatastral());
                        break;
                    }
                    else
                    {
                        labelNC.setVisible(false);
                        campoNC.setVisible(false);
                    }

                }
                DefaultListModel listaTramites = new DefaultListModel();

                for (Iterator it = miDtoGestionDeEscritura.getListaTramitesAsociados().iterator(); it.hasNext();)
                {
                    DtoTramite miDtoTramite = (DtoTramite) it.next();

                    //Si no tiene Escritura asociada, lo muestro, sino no
                    if (miDtoTramite.getEscritura() == null)
                    {
                        listaTramites.addElement(miDtoTramite.getTipoDeTramite().getNombre());
                    }
                }

                listaTramitesAsociados.setModel(listaTramites);
            }

            DefaultListModel listaPersonas = new DefaultListModel();

            if (miDtoGestionDeEscritura.getListaClientesInvolucrados() != null
                    && !miDtoGestionDeEscritura.getListaClientesInvolucrados().isEmpty())
            {
                for (Iterator it = miDtoGestionDeEscritura.getListaClientesInvolucrados().iterator(); it.hasNext();)
                {
                    DtoPersona miDtoPersona = (DtoPersona) it.next();

                    listaPersonas.addElement(miDtoPersona.getNombre() + " " + miDtoPersona.getApellido());
                }

                listaClientesAsociados.setModel(listaPersonas);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelPrepararEscritura = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonBuscarGestion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelNC = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaTramitesAsociados = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaClientesAsociados = new javax.swing.JList();
        campoNumeroGestion = new javax.swing.JTextField();
        campoEncabezado = new javax.swing.JTextField();
        campoFechaInicio = new javax.swing.JTextField();
        campoEscribano = new javax.swing.JTextField();
        campoNC = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Preparar Escritura");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonBuscarGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/main/resources/iconos/buscar.png"))); // NOI18N
        botonBuscarGestion.setText("Buscar");
        botonBuscarGestion.setIconTextGap(10);
        botonBuscarGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarGestionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Preparar Escritura");

        jLabel2.setText("Buscar Gestión");

        jLabel3.setText("Número de Gestión:");

        jLabel4.setText("Encabezado:");

        jLabel5.setText("Fecha de Inicio:");

        jLabel6.setText("Trámites Asociados:");

        jLabel7.setText("Escribano a Cargo:");

        jLabel8.setText("Clientes Involucrados:");

        labelNC.setText("Nomenclatura Catastral:");

        jScrollPane3.setViewportView(listaTramitesAsociados);

        jScrollPane2.setViewportView(listaClientesAsociados);

        campoNumeroGestion.setEditable(false);

        campoEncabezado.setEditable(false);

        campoFechaInicio.setEditable(false);

        campoEscribano.setEditable(false);

        campoNC.setEditable(false);

        javax.swing.GroupLayout panelPrepararEscrituraLayout = new javax.swing.GroupLayout(panelPrepararEscritura);
        panelPrepararEscritura.setLayout(panelPrepararEscrituraLayout);
        panelPrepararEscrituraLayout.setHorizontalGroup(
            panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrepararEscrituraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrepararEscrituraLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrepararEscrituraLayout.createSequentialGroup()
                        .addGroup(panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrepararEscrituraLayout.createSequentialGroup()
                                .addGroup(panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelPrepararEscrituraLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(50, 50, 50)
                                        .addComponent(botonBuscarGestion)))
                                .addGap(28, 28, 28)
                                .addGroup(panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(panelPrepararEscrituraLayout.createSequentialGroup()
                                .addGroup(panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(labelNC)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(campoNumeroGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(campoEscribano, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelPrepararEscrituraLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoNC, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(campoFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPrepararEscrituraLayout.setVerticalGroup(
            panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrepararEscrituraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(botonBuscarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoNumeroGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(campoEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoEscribano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNC)
                    .addComponent(campoNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrepararEscrituraLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(panelPrepararEscrituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPrepararEscrituraLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(panelPrepararEscritura);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonAceptarActionPerformed
    {//GEN-HEADEREND:event_botonAceptarActionPerformed
        DetalleEscritura miDetalleEscrituraForm = new DetalleEscritura();
        Boolean ok = miDetalleEscrituraForm.cargarFormularioCrearEscritura(miGestionDeEscritura);

        if (ok)
        {
            miDetalleEscrituraForm.setFormularioInvocador(ConstantesGui.PREPARAR_ESCRITURA);
            Principal.cargarFormulario(miDetalleEscrituraForm);
            Principal.setVentanasActivas(DetalleEscritura.getVentanaDetalleEscritura());
        }
        salir();
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCancelarActionPerformed
    {//GEN-HEADEREND:event_botonCancelarActionPerformed
        salir();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(ventanaPrepararEscritura);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonBuscarGestionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonBuscarGestionActionPerformed
    {//GEN-HEADEREND:event_botonBuscarGestionActionPerformed
        BuscarGestion buscarGestionForm = new BuscarGestion();
        buscarGestionForm.setTipoBusqueda(ConstantesGui.PREPARAR_ESCRITURA);
        
        Principal.cargarFormulario(buscarGestionForm);
        Principal.setVentanasActivas(BuscarGestion.getVentanaBuscarGestion());
        salir();
    }//GEN-LAST:event_botonBuscarGestionActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonBuscarGestion;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoEncabezado;
    private javax.swing.JTextField campoEscribano;
    private javax.swing.JTextField campoFechaInicio;
    private javax.swing.JTextField campoNC;
    private javax.swing.JTextField campoNumeroGestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelNC;
    private javax.swing.JList listaClientesAsociados;
    private javax.swing.JList listaTramitesAsociados;
    private javax.swing.JPanel panelPrepararEscritura;
    // End of variables declaration//GEN-END:variables
}
