/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.plantillasPresupuesto;

import com.licensis.notaire.gui.Principal;
import java.awt.Dimension;
import javax.swing.JMenuItem;

/**
 *
 * @author User
 */
public class PlantillasPresupuesto extends javax.swing.JInternalFrame
{

    private static PlantillasPresupuesto instancia = null;
    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem submenuPlantillaPresupuesto = new JMenuItem("Sub-Modulo Plantillas Presupuesto");

    /**
     * Creates new form Presupuestos
     */
    public PlantillasPresupuesto() {
        initComponents();
    }

    public static PlantillasPresupuesto getInstancia() {
        if (instancia == null)
        {
            instancia = new PlantillasPresupuesto();
            estadoFormulario = Boolean.TRUE;
            instancia.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
            instancia.setMinimumSize(new Dimension(Principal.tamanioMinimoHorizontal, Principal.tamanioMinimoVertical));
        }
        return instancia;
    }

    public static Boolean getEstadoFormulario() {
        return estadoFormulario;
    }

    public static void setEstadoFormulario(Boolean estadoFormulario) {
        PlantillasPresupuesto.estadoFormulario = estadoFormulario;
    }

    public static JMenuItem getSubmenuPlantillaPresupuesto() {
        return submenuPlantillaPresupuesto;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonCrearPlantillaPresupuesto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonModificarPlantillaPresupuesto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botonEliminarrPlantillaPresupuesto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Sub-Modulo Plantillas Presupuesto");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonCrearPlantillaPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/administracion/presupuestos/crearPlantillaPresupuesto.png"))); // NOI18N
        botonCrearPlantillaPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearPlantillaPresupuestoActionPerformed(evt);
            }
        });

        jLabel1.setText("<HTML>Crear Plantilla<BR>Presupuesto</HTML>");

        botonModificarPlantillaPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/administracion/presupuestos/modificarPlantillaPresupuesto.png"))); // NOI18N
        botonModificarPlantillaPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarPlantillaPresupuestoActionPerformed(evt);
            }
        });

        jLabel2.setText("<HTML>Modificar Plantilla<BR>Presupuesto</HTML>");

        botonEliminarrPlantillaPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/administracion/presupuestos/eliminarPlantillaPresupuesto.png"))); // NOI18N
        botonEliminarrPlantillaPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarrPlantillaPresupuestoActionPerformed(evt);
            }
        });

        jLabel3.setText("<HTML>Eliminar Plantilla<BR>Presupuesto</HTML>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCrearPlantillaPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonModificarPlantillaPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEliminarrPlantillaPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonEliminarrPlantillaPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonModificarPlantillaPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonCrearPlantillaPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(259, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearPlantillaPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearPlantillaPresupuestoActionPerformed

        CrearPlantillaPresupuesto miCrearPlantillaPresupuesto = new CrearPlantillaPresupuesto();
        Boolean cargado = miCrearPlantillaPresupuesto.inicializarFormulario();
        
        if (cargado)
        {
            Principal.cargarFormulario(miCrearPlantillaPresupuesto);
            Principal.setVentanasActivas(CrearPlantillaPresupuesto.getVentanaCrearPlantillaPresupuesto());
        }
    }//GEN-LAST:event_botonCrearPlantillaPresupuestoActionPerformed

    private void botonModificarPlantillaPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarPlantillaPresupuestoActionPerformed

        Principal.cargarFormulario(new ModificarPlantillaPresupuesto());
        Principal.setVentanasActivas(ModificarPlantillaPresupuesto.getVentanaModificarPlantillaPresupuesto());
    }//GEN-LAST:event_botonModificarPlantillaPresupuestoActionPerformed

    private void botonEliminarrPlantillaPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarrPlantillaPresupuestoActionPerformed

        Principal.cargarFormulario(new EliminarPlantillaPresupuesto());
        Principal.setVentanasActivas(EliminarPlantillaPresupuesto.getVentanaElimiarPlantillaPresupuesto());
    }//GEN-LAST:event_botonEliminarrPlantillaPresupuestoActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(submenuPlantillaPresupuesto);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearPlantillaPresupuesto;
    private javax.swing.JButton botonEliminarrPlantillaPresupuesto;
    private javax.swing.JButton botonModificarPlantillaPresupuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
