/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.usuarios;

import com.licensis.notaire.dto.DtoPersona;
import com.licensis.notaire.dto.DtoUsuario;
import com.licensis.notaire.gui.Principal;
import com.licensis.notaire.jpa.exceptions.NonexistentJpaException;
import com.licensis.notaire.negocio.ControllerNegocio;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author matias
 */
public class ActividadUsuario extends javax.swing.JInternalFrame
{

    private static Boolean estadoFormulario = Boolean.FALSE;
    private static JMenuItem ventanaActividadUsuario = new JMenuItem("Ventana Modificar Usuario");
    private static ActividadUsuario instancia = null;
    private DtoUsuario dtoUsuarioActvidad = null;

    /**
     * Creates new form ModificarUsuario
     */
    public ActividadUsuario()
    {
        initComponents();
        estadoFormulario = Boolean.TRUE;
        this.setSize(Principal.tamanioGrandeHorizontal, Principal.tamanioGrandeVertical);
        grillaActividadesUsuarios.setAutoCreateRowSorter(true);
    }

    public static ActividadUsuario getInstancia()
    {

        if (instancia == null)
        {
            instancia = new ActividadUsuario();
        }
        return instancia;
    }

    public DtoUsuario getDtoUsuarioModificado()
    {
        return dtoUsuarioActvidad;
    }

    public void setDtoUsuarioModificado(DtoUsuario dtoUsuarioModificado)
    {
        this.dtoUsuarioActvidad = dtoUsuarioModificado;
    }

    private void salir()
    {
        this.dispose();
    }

    public static JMenuItem getVentanaActividadUsuario()
    {
        return ventanaActividadUsuario;
    }

    public void limpiarFormulario()
    {
        limpiarJtable();
    }

    public void limpiarJtable()
    {
        int i = ((DefaultTableModel) grillaActividadesUsuarios.getModel()).getRowCount() - 1;

        while (((DefaultTableModel) grillaActividadesUsuarios.getModel()).getRowCount() > 0)
        {
            ((DefaultTableModel) grillaActividadesUsuarios.getModel()).removeRow(i);
            i--;
        }

    }

    public void cargarUsuariosDisponibles() throws NonexistentJpaException
    {
        ArrayList<DtoUsuario> miListaUsuarios = null;
        miListaUsuarios = ControllerNegocio.getInstancia().buscarUsuariosDisponibles();

        if (miListaUsuarios != null)
        {
            DtoUsuario miDtoUsuario = null;

            for (int i = 0; i < miListaUsuarios.size(); i++)
            {

                miDtoUsuario = miListaUsuarios.get(i);

                Object[] datos =
                {
                    miDtoUsuario.getNombre(),
                    miDtoUsuario.getPersonas().getNombre() + " " + miDtoUsuario.getPersonas().getApellido(),
                    miDtoUsuario.getTipo(),
                    miDtoUsuario.isEstado(),
                    miDtoUsuario.getIdUsuario(),
                    miDtoUsuario.getPersonas().getIdPersona(),
                };

                ((DefaultTableModel) grillaActividadesUsuarios.getModel()).addRow(datos);
            }

        } else
        {
            JOptionPane.showMessageDialog(this, "No existen Usuarios Registrados");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        panelModificarUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grillaActividadesUsuarios = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Actividades de Usuario");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Actividades de Usuario");

        botonCerrar.setText("Cancelar");
        botonCerrar.setIconTextGap(10);
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Lista de Usuarios Disponibles:");

        grillaActividadesUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Persona", "Tipo", "Estado", "id_usuario", "id_persona"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grillaActividadesUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        grillaActividadesUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grillaActividadesUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grillaActividadesUsuarios);
        grillaActividadesUsuarios.getColumnModel().getColumn(0).setResizable(false);
        grillaActividadesUsuarios.getColumnModel().getColumn(0).setPreferredWidth(125);
        grillaActividadesUsuarios.getColumnModel().getColumn(1).setResizable(false);
        grillaActividadesUsuarios.getColumnModel().getColumn(1).setPreferredWidth(225);
        grillaActividadesUsuarios.getColumnModel().getColumn(2).setResizable(false);
        grillaActividadesUsuarios.getColumnModel().getColumn(2).setPreferredWidth(125);
        grillaActividadesUsuarios.getColumnModel().getColumn(3).setResizable(false);
        grillaActividadesUsuarios.getColumnModel().getColumn(3).setPreferredWidth(75);
        grillaActividadesUsuarios.getColumnModel().getColumn(4).setResizable(false);
        grillaActividadesUsuarios.getColumnModel().getColumn(4).setPreferredWidth(0);
        grillaActividadesUsuarios.getColumnModel().getColumn(5).setResizable(false);

        javax.swing.GroupLayout panelModificarUsuarioLayout = new javax.swing.GroupLayout(panelModificarUsuario);
        panelModificarUsuario.setLayout(panelModificarUsuarioLayout);
        panelModificarUsuarioLayout.setHorizontalGroup(
            panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarUsuarioLayout.createSequentialGroup()
                        .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarUsuarioLayout.createSequentialGroup()
                                .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(botonCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        panelModificarUsuarioLayout.setVerticalGroup(
            panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(panelModificarUsuario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCerrarActionPerformed
    {//GEN-HEADEREND:event_botonCerrarActionPerformed
        Principal.removeVentanaActivas(ActividadUsuario.getInstancia().getVentanaActividadUsuario());
        salir();
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        estadoFormulario = Boolean.FALSE;
        Principal.removeVentanaActivas(ventanaActividadUsuario);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void grillaActividadesUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grillaActividadesUsuariosMouseClicked

        TableModel miGrilla = grillaActividadesUsuarios.getModel();
        int filaSeleccionada = grillaActividadesUsuarios.getSelectedRow();

        int filas = miGrilla.getRowCount();
        int columnas = miGrilla.getColumnCount();

        DtoUsuario miUsuario = new DtoUsuario();
        DtoPersona miPersona = new DtoPersona();
        miUsuario.setPersonas(miPersona);

        //Recorro la grilla completa, buscando el cliente seleccionado
        for (int i = 0; i < filas; i++)
        {
            if (i == filaSeleccionada)
            {
                try
                {
                    miUsuario.getPersonas().setIdPersona(Integer.parseInt(grillaActividadesUsuarios.getValueAt(i, 5).toString()));
                    miUsuario = ControllerNegocio.getInstancia().buscarUsuario(miUsuario);
                    VerRegistroActividadesUsuario.getInstancia().cargarRegistrosUsuario(miUsuario);
                    Principal.cargarFormulario(VerRegistroActividadesUsuario.getInstancia());
                    Principal.setVentanasActivas(VerRegistroActividadesUsuario.getVentanaRegistroActividadesUsuario());

                }
                catch (NonexistentJpaException ex)
                {
                    Logger.getLogger(ActividadUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_grillaActividadesUsuariosMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrar;
    private javax.swing.JTable grillaActividadesUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelModificarUsuario;
    // End of variables declaration//GEN-END:variables
}
