/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.licensis.notaire.gui.administracion.folios;

import com.licensis.notaire.dto.DtoTipoDeFolio;
import com.licensis.notaire.gui.ConstantesGui;
import com.licensis.notaire.gui.Principal;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import com.licensis.notaire.jpa.exceptions.ClassModifiedException;
import com.licensis.notaire.negocio.ControllerNegocio;

/**
 *
 * @author matias
 */
public class ModificarEliminarFolio extends javax.swing.JInternalFrame
{

    private static JMenuItem ventanaAdministrarTiposDeFolios = new JMenuItem("Ventana Lista Tipos de Folios");
    private ControllerNegocio miControllerNegocio = null;
    private List<DtoTipoDeFolio> miListaDtoTipoDeFolios = null;
    private DtoTipoDeFolio dtoSeleccionado = null;
    private Integer registroSeleccionado;
    private String formularioInvocador;

    /**
     * Creates new form ModificarTipoFolio
     */
    public ModificarEliminarFolio()
    {
        initComponents();
        this.setSize(Principal.tamanioNormalHorizontal, Principal.tamanioNormalVertical);
        miControllerNegocio = ControllerNegocio.getInstancia();
        cargarListaTiposDeFolios();
    }

    private void salir()
    {
        this.dispose();
    }

    public static JMenuItem getVentanaAdministrarTiposDeFolios()
    {
        return ventanaAdministrarTiposDeFolios;
    }

    public String getFormularioInvocador()
    {
        return formularioInvocador;
    }

    public void setFormularioInvocador(String formularioInvocador)
    {
        this.formularioInvocador = formularioInvocador;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelModificarTipoFolio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonCerrar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        campoNombreTipoDeFolio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoObservaciones = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonSeleccionar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaTiposDeFolios = new javax.swing.JList();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ventana Lista Tipos de Folios");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Lista Tipo de Folio");

        jLabel2.setText("Tipos de folio:");

        botonCerrar.setText("Cancelar");
        botonCerrar.setIconTextGap(10);
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        campoNombreTipoDeFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreTipoDeFolioActionPerformed(evt);
            }
        });

        campoObservaciones.setColumns(20);
        campoObservaciones.setRows(5);
        jScrollPane2.setViewportView(campoObservaciones);

        jLabel3.setText("Nombre:");

        jLabel4.setText("Observaciones:");

        botonSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/aceptar.png"))); // NOI18N
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(listaTiposDeFolios);

        javax.swing.GroupLayout panelModificarTipoFolioLayout = new javax.swing.GroupLayout(panelModificarTipoFolio);
        panelModificarTipoFolio.setLayout(panelModificarTipoFolioLayout);
        panelModificarTipoFolioLayout.setHorizontalGroup(
            panelModificarTipoFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarTipoFolioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarTipoFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(panelModificarTipoFolioLayout.createSequentialGroup()
                        .addGroup(panelModificarTipoFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(panelModificarTipoFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(campoNombreTipoDeFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelModificarTipoFolioLayout.createSequentialGroup()
                        .addGroup(panelModificarTipoFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(panelModificarTipoFolioLayout.createSequentialGroup()
                                .addGroup(panelModificarTipoFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 407, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarTipoFolioLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panelModificarTipoFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarTipoFolioLayout.createSequentialGroup()
                                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(botonSeleccionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        panelModificarTipoFolioLayout.setVerticalGroup(
            panelModificarTipoFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarTipoFolioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarTipoFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoNombreTipoDeFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelModificarTipoFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(panelModificarTipoFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModificarTipoFolio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModificarTipoFolio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCerrarActionPerformed
    {//GEN-HEADEREND:event_botonCerrarActionPerformed
        salir();
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
    {//GEN-HEADEREND:event_formInternalFrameClosed
        Principal.removeVentanaActivas(ventanaAdministrarTiposDeFolios);
        Principal.eliminarFormulario(this);
    }//GEN-LAST:event_formInternalFrameClosed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed

        dtoSeleccionado.setNombre(this.campoNombreTipoDeFolio.getText());
        dtoSeleccionado.setObservaciones(this.campoObservaciones.getText());

        switch (this.getFormularioInvocador())
        {
            case ConstantesGui.MODIFICAR_TIPO_FOLIO:
            {

                if (dtoSeleccionado.isValido())
                {
                    try
                    {
                        if (miControllerNegocio.modificarTipoDeFolios(dtoSeleccionado) == Boolean.TRUE)
                        {
                            JOptionPane.showMessageDialog(this, "Se ha modificado un tipo de Folio correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                            this.limpiarFormulario();
                            this.cargarListaTiposDeFolios();
                        }
                    }
                    catch (ClassModifiedException ex)
                    {
                        JOptionPane.showMessageDialog(this, "El tipo de folio selecciona ya ha sido modificado por otro usuario", "Advertencia", JOptionPane.WARNING_MESSAGE);
                        this.limpiarFormulario();
                        this.cargarListaTiposDeFolios();
                    }
                } else
                {
                    JOptionPane.showMessageDialog(this, "Algun dato indicado no es valido.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }

                break;
            }
            case ConstantesGui.ELIMINAR_TIPO_FOLIO:
            {
                try
                {
                    if (miControllerNegocio.eliminarTipoDeFolio(dtoSeleccionado) == Boolean.TRUE)
                    {
                        JOptionPane.showMessageDialog(this, "Se ha dado de baja el tipo de folio indicado.", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                        this.limpiarFormulario();
                        this.cargarListaTiposDeFolios();
                    } else
                    {
                        JOptionPane.showMessageDialog(this, "Error al dar de baja un tipo de folio", "Error", JOptionPane.ERROR_MESSAGE);
                        this.limpiarFormulario();
                        this.cargarListaTiposDeFolios();
                    }
                }
                catch (ClassModifiedException ex)
                {
                    JOptionPane.showMessageDialog(this, "El tipo de folio indicado ha sido modificado por otro usuario", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    this.limpiarFormulario();
                    this.cargarListaTiposDeFolios();
                }
                break;
            }
        }

    }//GEN-LAST:event_botonAceptarActionPerformed

    private void campoNombreTipoDeFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreTipoDeFolioActionPerformed
    }//GEN-LAST:event_campoNombreTipoDeFolioActionPerformed

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed

        int seleccionado = listaTiposDeFolios.getAnchorSelectionIndex();

        if (seleccionado == ConstantesGui.ERROR)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de folio", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else
        {
            String tipoDeFolio = listaTiposDeFolios.getSelectedValue().toString();

            for (Iterator<DtoTipoDeFolio> it = miListaDtoTipoDeFolios.iterator(); it.hasNext();)
            {
                DtoTipoDeFolio dtoTipoDeFolio = it.next();

                if (dtoTipoDeFolio.getNombre().contains(tipoDeFolio))
                {
                    this.cargarTipoDeFolio(dtoTipoDeFolio);
                    break;
                }
            }
        }

    }//GEN-LAST:event_botonSeleccionarActionPerformed

    public void cargarListaTiposDeFolios()
    {
        //  limpiamos la grilla

        this.listaTiposDeFolios.removeAll();

        //  cargamosla grilla
        miListaDtoTipoDeFolios = miControllerNegocio.obtenerListaTiposDeFoliosDisponibles();

        if (!miListaDtoTipoDeFolios.isEmpty())
        {
            DefaultListModel lista = new DefaultListModel();
            for (Iterator<DtoTipoDeFolio> it = miListaDtoTipoDeFolios.iterator(); it.hasNext();)
            {
                DtoTipoDeFolio dtoTipoDeFolio = it.next();

                lista.addElement(dtoTipoDeFolio.getNombre());
            }

            this.listaTiposDeFolios.setModel(lista);
        } else
        {
            JOptionPane.showMessageDialog(this, "No existen tipos de folios registrados", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }

    public void cargarTipoDeFolio(DtoTipoDeFolio dtoTipoDeFolio)
    {
        this.limpiarFormulario();
        dtoSeleccionado = dtoTipoDeFolio;
        this.campoNombreTipoDeFolio.setText(dtoTipoDeFolio.getNombre());
        this.campoObservaciones.setText(dtoTipoDeFolio.getObservaciones());
    }

    public void limpiarFormulario()
    {
        this.campoNombreTipoDeFolio.setText("");
        this.campoObservaciones.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JTextField campoNombreTipoDeFolio;
    private javax.swing.JTextArea campoObservaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList listaTiposDeFolios;
    private javax.swing.JPanel panelModificarTipoFolio;
    // End of variables declaration//GEN-END:variables
}
